(function(){
  function mount(){
    var panel=document.getElementById('decisionPanel'); if(!panel||document.getElementById('decision-chain')) return;
    var style=document.createElement('style'); style.id='decision-chain-style'; style.textContent='#decision-chain{border:1px solid #29445f;border-radius:12px;padding:11px;background:linear-gradient(135deg,rgba(53,226,176,.08),rgba(24,204,229,.04));margin:10px 0 12px}.dc-kicker{font-size:8px;letter-spacing:.12em;color:#8ea4b5;font-weight:800;margin-bottom:8px}.dc-flow{display:grid;grid-template-columns:repeat(6,1fr);gap:5px}.dc-node{min-width:0;padding:7px 5px;border:1px solid #29445f;border-radius:8px;background:#0b1621;text-align:center}.dc-node b{display:block;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dc-node span{display:block;font-size:7px;color:#8ea4b5;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dc-node.current{border-color:#5ee7c2;box-shadow:inset 0 0 0 1px #5ee7c222}.dc-node.warn{border-color:#ffc85766}.dc-arrow{display:flex;align-items:center;justify-content:center;color:#5ee7c2;font-size:10px}@media(max-width:700px){.dc-flow{grid-template-columns:repeat(3,1fr)}.dc-arrow{display:none}}'; document.head.appendChild(style);
    var names=['EVIDENCE','SCORE','WHY','DECISION','REVIEW','ACTION']; var box=document.createElement('section'); box.id='decision-chain'; box.innerHTML='<div class="dc-kicker">DECISION PATHWAY · EVIDENCE TO ACTION</div><div class="dc-flow">'+names.map(function(x,i){return (i?'<div class="dc-arrow">→</div>':'')+'<div class="dc-node" data-dc="'+x+'"><b>'+x+'</b><span>Awaiting</span></div>'}).join('')+'</div>';
    panel.insertBefore(box,panel.querySelector('.decision')||panel.firstChild);
    function val(id){var e=document.getElementById(id);return e?e.textContent.trim():''}
    function refresh(){var score=val('score').replace('/ 100','').trim(),why=val('justification'),decision=val('decisionStatus');var gaps=document.querySelectorAll('#gaps .gap').length,actions=document.querySelectorAll('#actions .action').length;var map={EVIDENCE:val('context')?'Evidence linked':'Qualified',SCORE:score&&score!=='—'?score+'/100':'Not scored',WHY:why?why.slice(0,34):'Not returned',DECISION:decision||'Review',REVIEW:gaps?gaps+' gap(s)':'Review checklist',ACTION:actions?actions+' action(s)':'Confirm next step'};box.querySelectorAll('[data-dc]').forEach(function(n){var k=n.getAttribute('data-dc');n.classList.toggle('current',k==='DECISION'&&decision&&decision!=='EVIDENCE UNAVAILABLE');n.classList.toggle('warn',k==='REVIEW'&&gaps>0);n.querySelector('span').textContent=map[k]||'Awaiting'})}
    refresh(); new MutationObserver(refresh).observe(panel,{subtree:true,childList:true,characterData:true});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();