(()=>{
'use strict';
if(window.__URBION_WORKSTATION_V2)return;window.__URBION_WORKSTATION_V2=true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=`#urbion-workstation-v2{position:fixed;left:18px;bottom:18px;z-index:9998;width:min(470px,calc(100vw - 36px));padding:12px;border:1px solid rgba(53,226,176,.28);border-radius:16px;background:rgba(7,19,31,.92);backdrop-filter:blur(16px);box-shadow:0 18px 50px rgba(0,0,0,.30);font:10px Inter,system-ui,sans-serif;color:#eaf5f7}#urbion-workstation-v2 .w2-head{display:flex;align-items:center;justify-content:space-between;gap:8px}#urbion-workstation-v2 .w2-k{font-size:7px;font-weight:900;letter-spacing:.16em;color:#5ee7c2}#urbion-workstation-v2 .w2-title{font:700 14px 'Space Grotesk',Inter,sans-serif;margin-top:2px}#urbion-workstation-v2 .w2-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:9px}#urbion-workstation-v2 .w2-step{border:1px solid #203343;border-radius:8px;padding:7px;background:#0a1722}#urbion-workstation-v2 .w2-step b{display:block;font-size:8px}#urbion-workstation-v2 .w2-step span{display:block;margin-top:3px;font-size:7px;color:#7f98a8}#urbion-workstation-v2 .ok{color:#5ee7c2}#urbion-workstation-v2 .wait{color:#ffd37a}#urbion-workstation-v2 button{border:1px solid #31516a;background:#0b1b28;color:#eaf5f7;border-radius:8px;padding:7px 9px;font:900 8px Inter;cursor:pointer}#urbion-workstation-v2 .w2-metrics{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px;color:#9bb2c0;font-size:8px}#urbion-workstation-v2 .w2-note{margin-top:7px;color:#7890a3;font-size:7px;line-height:1.45}@media(max-width:600px){#urbion-workstation-v2{left:8px;bottom:8px;width:calc(100vw - 16px)}#urbion-workstation-v2 .w2-grid{grid-template-columns:repeat(2,1fr)}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const el=document.createElement('aside');el.id='urbion-workstation-v2';el.innerHTML='<div class="w2-head"><div><div class="w2-k">PHASE-E.8 · PLANNER WORKSTATION</div><div class="w2-title">Decision chain control</div></div><button id="w2-run">RUN ANALYSIS</button></div><div id="w2-grid" class="w2-grid">'+['Assessment','Spatial','What-If','Decision','LCP','KM'].map(x=>'<div class="w2-step"><b>'+x+'</b><span class="wait">READY</span></div>').join('')+'</div><div id="w2-metrics" class="w2-metrics">Awaiting run</div><div class="w2-note">Calculated spatial geometry and source-context evidence are shown separately. URBION does not claim statutory approval.</div>';
document.body.appendChild(el);
function payload(){let raw=sessionStorage.getItem('urbion_assessment_inputs');try{if(raw)return JSON.parse(raw)}catch(e){}return{site_lat:2.285,site_lon:102.196,tod_lat:2.286,tod_lon:102.197,plot_ratio:4.5,precinct:'Terminal Sg. Udang',development_type:'TOD Development / Mixed Use',development_class:'Mixed Use',state:'Melaka',district:'Melaka Tengah',pbt:'Majlis Bandaraya Melaka Bersejarah',lot_no:'11213'}}
async function run(){const button=document.getElementById('w2-run');button.disabled=true;button.textContent='RUNNING…';try{const p=payload();const body={assessment_inputs:p,variants:[{id:'LOWER_DENSITY',name:'Lower density',plot_ratio:Math.max(.5,(p.plot_ratio||4.5)-.5)},{id:'HIGHER_DENSITY',name:'Higher density',plot_ratio:(p.plot_ratio||4.5)+.5}],constraints:{flood:false,ksas:false}};const r=await fetch('/workstation/analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.detail?.message||data.detail||r.status);document.getElementById('w2-grid').innerHTML=data.workflow.steps.map(x=>'<div class="w2-step"><b>'+esc(x.label)+'</b><span class="'+(x.status==='COMPLETE'?'ok':'wait')+'">'+esc(x.status)+'</span></div>').join('');const d=data.spatial.tod;document.getElementById('w2-metrics').innerHTML='<b>'+esc(d?.classification||'NO TOD')+'</b> · '+esc(d?.distance_m??'—')+' m · '+data.workflow.completed+'/'+data.workflow.total+' stages complete';try{const di=await fetch('/intelligence/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const intel=await di.json();if(di.ok&&window.urbionDecisionIntelligence)window.urbionDecisionIntelligence(intel);}catch(intelErr){console.warn('Decision intelligence unavailable',intelErr)}}catch(e){document.getElementById('w2-metrics').innerHTML='<span class="wait">RUN FAILED · '+esc(e.message)+'</span>'}finally{button.disabled=false;button.textContent='RUN ANALYSIS'}}
document.getElementById('w2-run').onclick=run;
})();
