(()=>{
'use strict';
if(window.__URBION_POLICY_UI)return; window.__URBION_POLICY_UI=true;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const val=id=>String($('fcc-'+id)?.value||'').trim();
const payload=()=>({
 site_lat:Number(val('lat')),site_lon:Number(val('lon')),state:val('state')||'Melaka',district:val('district')||'Melaka Tengah',pbt:val('pbt')||'Majlis Bandaraya Melaka Bersejarah',lot_no:val('lot'),project_reference:val('project_reference'),project_name:val('project_name'),land_use:val('landuse'),development_class:val('category'),activity:val('activity'),development_type:val('development'),plot_ratio:Number(val('ratio')||4.5),tod_lat:Number(val('todlat')),tod_lon:Number(val('todlon'))
});
const css=`<style id="fcc-policy-ui">#fcc-policy-panel{grid-column:1/-1;margin:0 16px 18px;padding:18px;border:1px solid rgba(94,231,194,.18);border-radius:14px;background:linear-gradient(135deg,rgba(8,19,29,.94),rgba(10,27,39,.82));box-shadow:0 18px 50px rgba(0,0,0,.18)}#fcc-policy-panel .p-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.fcc-policy-grid{display:grid;grid-template-columns:1.15fr 1fr 1fr;gap:12px;margin-top:12px}.fcc-policy-card{border:1px solid rgba(119,147,163,.18);border-radius:11px;padding:13px;background:rgba(255,255,255,.025)}.fcc-policy-card h4{margin:0 0 8px;font:800 11px Inter;letter-spacing:.08em;text-transform:uppercase}.fcc-policy-card p,.fcc-policy-card li{font:500 12px/1.5 Inter;color:#9eb3be}.fcc-policy-card ul{margin:0;padding-left:16px}.fcc-policy-pill{display:inline-flex;padding:5px 8px;margin:3px;border-radius:999px;border:1px solid rgba(73,200,232,.2);font:700 10px Inter;color:#d9edf1;background:rgba(73,200,232,.05)}.fcc-policy-status{font:800 10px Inter;color:#5ee7c2;letter-spacing:.06em}.fcc-policy-gap{color:#f2c45c!important}.fcc-policy-disclaimer{margin-top:10px!important;font-size:10px!important;color:#718995!important}@media(max-width:900px){.fcc-policy-grid{grid-template-columns:1fr}}body.fcc-light #fcc-policy-panel{background:linear-gradient(135deg,#fff,#eef6f8);border-color:#d6e5e9}body.fcc-light .fcc-policy-card{background:rgba(255,255,255,.75);border-color:#d9e5e9}body.fcc-light .fcc-policy-card p,body.fcc-light .fcc-policy-card li{color:#4d6672}body.fcc-light .fcc-policy-pill{color:#17313e}</style>`;
function render(data){
 const root=document.getElementById('urbion-final-command-centre');if(!root)return;
 let panel=$('fcc-policy-panel');if(!panel){panel=document.createElement('section');panel.id='fcc-policy-panel';root.appendChild(panel);}
 const g=data?.guideline_intelligence||{};const pg=data?.policy_graph||{};const rec=data?.recommendations||{};const km=data?.km_readiness||null;const agencies=data?.agency_intelligence?.agencies||[];
 const guidelines=g.guidelines||[];const links=pg.nodes?.links||[];const gaps=[...(g.review_gaps||[]),...(pg.review_gaps||[]),...(rec.review_gaps||[])];
 const frameworks=['Town and Country Planning Act 1976 (Act 172)','National Land Code 1965 (Act 828)','National Physical Plan (RFN)','State Structure Plan (RSN)','Local Plan / RTD / adopted local controls','OSC 3.0 Plus development-control workflow'];
 panel.innerHTML=`${css}<div class="p-head"><div><span class="fcc-kicker">POLICY · GUIDELINE · COMPLIANCE</span><h3 style="margin:4px 0;font:800 20px 'Space Grotesk',Inter">Policy & Guideline Intelligence</h3><p style="margin:0;font:500 12px Inter;color:#8ea7b5">Traceable planning references are surfaced as review support — never as automatic statutory approval.</p></div><span class="fcc-policy-status">${esc(g.candidate_count||0)} GP CANDIDATES · ${esc(links.length)} POLICY EDGES</span></div><div class="fcc-policy-grid"><article class="fcc-policy-card"><h4>Planning policy framework</h4><div>${frameworks.map(x=>`<span class="fcc-policy-pill">${esc(x)}</span>`).join('')}</div><p class="fcc-policy-disclaimer">Framework context is not a project-specific control. Confirm the adopted plan, current edition, jurisdiction and applicable clauses with the responsible PBT/state authority.</p></article><article class="fcc-policy-card"><h4>Garis Panduan Perancangan</h4>${guidelines.length?`<ul>${guidelines.slice(0,6).map(x=>`<li><b>${esc(x.title)}</b><br><small>${esc(x.status||'SOURCE_CONTEXT')} · ${esc((x.topics||[]).join(', '))}</small></li>`).join('')}</ul>`:'<p class="fcc-policy-gap">No matched guideline candidate returned for this case. Review the source catalogue manually.</p>'}<p class="fcc-policy-disclaimer">Candidate applicability only. Confirm adopted status, local applicability, edition and project-specific conditions.</p></article><article class="fcc-policy-card"><h4>Policy → recommendation → authority</h4>${links.length?`<ul>${links.slice(0,5).map(x=>`<li><b>${esc(x.issue||x.impact||x.domain||'Planning issue')}</b><br>${esc(x.reference)}${x.clause?' · '+esc(x.clause):''}${x.sdg?' · '+esc(x.sdg):''}</li>`).join('')}</ul>`:`<p class="fcc-policy-gap">No traceable policy edge supplied by the case yet. Recommendations remain review-required.</p>`}<p class="fcc-policy-disclaimer">Technical/agency context: ${esc(agencies.length)} agencies screened. ${km?'KM readiness module available.':'Kebenaran Merancang readiness details require KM inputs/documents.'}</p></article></div>${gaps.length?`<p class="fcc-policy-disclaimer">Evidence/review gaps disclosed: ${esc(gaps.slice(0,6).join(' · '))}</p>`:''}`;
}
async function load(){
 const root=document.getElementById('urbion-final-command-centre');if(!root)return;
 const status=$('fcc-case-status');
 try{
  const res=await fetch('/lcp/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assessment:payload(),development_inputs:{development_type:val('development'),source_context:window.__URBION_FINAL_CONTEXT||null},spatial_inputs:{source_context:window.__URBION_FINAL_CONTEXT||null},environment_context:null,guideline_topics:[val('activity'),val('landuse'),val('development')].filter(Boolean)})});
  if(!res.ok)throw new Error('LCP intelligence '+res.status);
  const data=await res.json();window.__URBION_LCP_INTELLIGENCE=data;render(data);window.dispatchEvent(new CustomEvent('urbion:lcp-intelligence',{detail:data}));
 }catch(e){render({guideline_intelligence:{review_gaps:['LCP_INTELLIGENCE_UNAVAILABLE: '+e.message]}});}
}
function boot(){const root=document.getElementById('urbion-final-command-centre');if(!root)return;if(!document.getElementById('fcc-policy-ui'))document.head.insertAdjacentHTML('beforeend',css);document.addEventListener('urbion:analysis',()=>setTimeout(load,20));document.addEventListener('urbion:final-language',()=>{const p=$('fcc-policy-panel');if(p)p.dataset.refresh='1';});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,30));else setTimeout(boot,30);
})();