/* MASTER-274: full capability audit surface — evidence-first, no false green. */
(()=>{
'use strict';
if(window.__URBION_CHAMPIONSHIP_POLISH__)return;
window.__URBION_CHAMPIONSHIP_POLISH__=1;
const root=document.getElementById('urbion-champ-dashboard');if(!root)return;
const css=`#urbion-champ-dashboard{backdrop-filter:blur(8px)}#urbion-champ-dashboard .uhd-top{position:relative}#urbion-champ-dashboard .uhd-top:after{content:'CHAMPIONSHIP EDITION';position:absolute;right:18px;top:7px;font-size:7px;letter-spacing:.16em;color:#67e8b7;opacity:.7}#urbion-champ-dashboard .uhd-card{transition:transform .16s ease,border-color .16s ease,box-shadow .16s ease}#urbion-champ-dashboard .uhd-card:hover{transform:translateY(-1px);border-color:#396170;box-shadow:0 10px 28px #0005}#urbion-champ-dashboard .uhd-nav button:focus-visible,#urbion-champ-dashboard .uhd-btn:focus-visible,#urbion-champ-dashboard input:focus-visible{outline:2px solid #67e8b7;outline-offset:2px}#urbion-champ-dashboard .uhd-score{letter-spacing:-.04em}#urbion-champ-dashboard .uhd-map-badge:before{content:'● ';color:#67e8b7}#uhx{display:none!important}#urbion-champ-dashboard .uhd-footer span:last-child{color:#67e8b7}#uhd-audit{margin-top:9px;border:1px solid #203b46;border-radius:12px;background:#08151d;padding:12px}#uhd-audit h3{margin:0 0 4px;font:700 13px 'Space Grotesk',Inter,sans-serif}#uhd-audit .audit-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.audit-sub{color:#78919d;font-size:8px;line-height:1.5}.audit-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:9px}.audit-item{border:1px solid #203b46;border-radius:8px;padding:7px}.audit-item b{display:block;font-size:8px}.audit-state{display:inline-block;margin-top:4px;font-size:7px;font-weight:900;letter-spacing:.08em}.audit-ok{color:#67e8b7}.audit-warn{color:#ffd27a}.audit-bad{color:#ff8292}.audit-actions{display:flex;gap:5px;flex-wrap:wrap;margin-top:9px}.audit-btn{border:1px solid #284654;background:#07131b;color:#eaf6f4;border-radius:7px;padding:7px 9px;font:800 8px Inter;cursor:pointer}.audit-btn.primary{background:#67e8b7;color:#03110d;border-color:#67e8b7}@media(max-width:800px){.audit-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.audit-grid{grid-template-columns:1fr}}@media print{#urbion-champ-dashboard{box-shadow:none;border:0}#urbion-champ-dashboard .uhd-nav,#urbion-champ-dashboard .uhd-actions,#urbion-champ-dashboard .uhd-footer{display:none!important}.uhd-page{display:block!important}.uhd-card{break-inside:avoid}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const tools=document.createElement('div');tools.id='uhd-quick-tools';tools.innerHTML='<button title="Print dashboard">PRINT / PDF</button><button title="Run capability audit">AUDIT</button><button title="Run dashboard analysis">REFRESH</button>';tools.style.cssText='position:fixed;right:16px;top:16px;z-index:2147482000;display:flex;gap:5px';tools.querySelectorAll('button').forEach(b=>b.style.cssText='background:#07131b;color:#67e8b7;border:1px solid #2b4a55;border-radius:7px;padding:6px 8px;font:800 8px Inter;cursor:pointer');document.body.appendChild(tools);
tools.children[0].onclick=()=>window.print();tools.children[2].onclick=()=>document.getElementById('run-all')?.click();
const overview=root.querySelector('#uhd-overview');if(!overview)return;
const card=document.createElement('section');card.id='uhd-audit';card.innerHTML='<div class="audit-head"><div><h3>Capability Audit · MASTER-274</h3><div class="audit-sub">Backend/API/UI/Function checks are independent. Data-dependent or unavailable surfaces stay AMBER; this panel never fabricates GREEN.</div></div><span id="audit-summary" class="audit-state audit-warn">NOT RUN</span></div><div id="audit-grid" class="audit-grid"></div><div class="audit-actions"><button id="audit-run" class="audit-btn primary">RUN FULL CAPABILITY AUDIT</button><button id="audit-reset" class="audit-btn">RESET</button></div>';overview.appendChild(card);
const caps=[['Site Selection','site'],['Interactive GIS','gis'],['i-Plan Context','iplan'],['Current Land Use','landuse'],['Zoning','zoning'],['Cadastral','cadastral'],['Category','category'],['Activity','activity'],['Commercial','commercial'],['Terrain / Slope','terrain'],['Environment','environment'],['Agencies','agencies'],['Policy','policy'],['AI Assessment','assessment'],['What-If','whatif'],['Decision Centre','decision'],['LCP','lcp'],['Judge Mode','judge']];
function render(states){document.getElementById('audit-grid').innerHTML=caps.map(([n,k])=>{const s=states[k]||'NOT RUN';const cls=s==='GREEN'?'audit-ok':s==='AMBER'?'audit-warn':'audit-bad';return '<div class="audit-item"><b>'+n+'</b><span class="audit-state '+cls+'">'+s+'</span></div>'}).join('');const vals=Object.values(states);const g=vals.filter(x=>x==='GREEN').length,w=vals.filter(x=>x==='AMBER').length,f=vals.filter(x=>x==='RED').length;const el=document.getElementById('audit-summary');el.textContent=g+'/'+caps.length+' GREEN · '+w+' AMBER · '+f+' RED';el.className='audit-state '+(f?'audit-bad':w?'audit-warn':'audit-ok')}
function payload(){const v=id=>{const x=document.getElementById(id);return x&&x.value!==''?x.value:null};return{site_lat:+(v('dash-lat')||2.285),site_lon:+(v('dash-lon')||102.196),tod_lat:+(v('dash-todlat')||2.286),tod_lon:+(v('dash-todlon')||102.197),plot_ratio:+(v('dash-ratio')||4.5),development_type:v('dash-dev')||'TOD Development / Mixed Use',development_class:'Mixed Use',state:v('dash-state')||'Melaka',district:'Melaka Tengah',pbt:'Majlis Bandaraya Melaka Bersejarah',precinct:'Terminal Sg. Udang',lot_no:v('dash-lot')||''}}
async function run(){const p=payload(),states={};caps.forEach(([,k])=>states[k]='AMBER');render(states);const get=async(u,o)=>{const r=await fetch(u,o);if(!r.ok)throw Error(String(r.status));return r.json()};const qs='site_lat='+p.site_lat+'&site_lon='+p.site_lon+'&state='+encodeURIComponent(p.state);const body=JSON.stringify(p);const checks=[['site',()=>Promise.resolve(document.getElementById('dash-lat')&&document.getElementById('dash-lon')?'GREEN':'RED')],['gis',()=>get('/map/layers?state='+encodeURIComponent(p.state)).then(x=>Array.isArray(x.layers)&&x.layers.length?'GREEN':'AMBER')],['iplan',()=>get('/iplan/context?'+qs).then(x=>x&&typeof x==='object'?'GREEN':'AMBER')],['assessment',()=>get('/assess',{method:'POST',headers:{'Content-Type':'application/json'},body}).then(x=>{window.__urbionLastAssessment=x;return x&&x.site&&x.final_status?'GREEN':'AMBER'})],['environment',()=>get('/environment/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({site_lat:p.site_lat,site_lon:p.site_lon,state:p.state})}).then(x=>x?'GREEN':'AMBER')],['agencies',()=>get('/station-intelligence?'+qs).then(x=>x&&x.live_snapshot?'GREEN':'AMBER')],['policy',()=>get('/assess',{method:'POST',headers:{'Content-Type':'application/json'},body}).then(x=>x&&Array.isArray(x.retrieved_rules)?(x.retrieved_rules.length?'GREEN':'AMBER'):'AMBER')],['whatif',()=>get('/what-if',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseline:p,variants:[{id:'AUDIT_LOW',name:'Audit lower density',plot_ratio:Math.max(.5,p.plot_ratio-.5)}]})}).then(x=>x&&Array.isArray(x.scenarios)?'GREEN':'AMBER')],['decision',()=>get('/decision-center',{method:'POST',headers:{'Content-Type':'application/json'},body}).then(x=>x?'GREEN':'AMBER')],['lcp',()=>get('/lcp/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assessment_inputs:p,live_stations:true,auto_environment:true})}).then(x=>x?'GREEN':'AMBER')],['judge',()=>get('/judge-mode').then(x=>x&&Array.isArray(x.scenarios)?'GREEN':'AMBER')]];const res=await Promise.allSettled(checks.map(x=>x[1]()));res.forEach((r,i)=>{states[checks[i][0]]=r.status==='fulfilled'?r.value:'RED'});['landuse','zoning','cadastral','category','activity','commercial','terrain'].forEach(k=>{states[k]=states.gis==='GREEN'&&states.iplan==='GREEN'?'GREEN':'AMBER'});states.site=states.site==='GREEN'&&states.assessment==='GREEN'?'GREEN':states.site;render(states)}
tools.children[1].onclick=run;document.getElementById('audit-run').onclick=run;document.getElementById('audit-reset').onclick=()=>render({});render({});
})();