/* URBION shared UI controller: bilingual labels + resilient light/dark/system theme. */
(function(){
  const KEY_LANG='urbion-lang',KEY_THEME='urbion-theme';
  const dict={en:{language:'Language',dark:'Dark mode',light:'Light mode',system:'System',layers:'Map layers',basemap:'Basemap',planning:'Planning',cadastre:'Cadastre',terrain:'Terrain',geology:'Geology',environment:'Environment',source:'Source context',verify:'Planner verification required',current:'Current land use',zoning:'Zoning',committed:'Committed land use',lot:'Cadastral lot',contour:'5m contours'},ms:{language:'Bahasa',dark:'Mod gelap',light:'Mod cerah',system:'Sistem',layers:'Lapisan peta',basemap:'Peta asas',planning:'Perancangan',cadastre:'Kadaster',terrain:'Bentuk muka bumi',geology:'Geologi',environment:'Alam sekitar',source:'Konteks sumber',verify:'Pengesahan perancang diperlukan',current:'Guna tanah semasa',zoning:'Zon guna tanah',committed:'Guna tanah komited',lot:'Lot kadaster',contour:'Kontur 5m'}};
  function lang(){return localStorage.getItem(KEY_LANG)||'en'}
  function theme(){return localStorage.getItem(KEY_THEME)||'system'}
  function apply(){const l=lang(),t=theme();document.documentElement.dataset.lang=l;document.documentElement.dataset.theme=t;document.documentElement.style.colorScheme=t==='system'?'light dark':t;document.dispatchEvent(new CustomEvent('urbion-ui',{detail:{lang:l,theme:t,t:dict[l]}}))}
  function controls(){if(document.getElementById('urbion-ui-controls'))return;const box=document.createElement('div');box.id='urbion-ui-controls';box.setAttribute('aria-label','URBION language and theme controls');box.innerHTML='<label>Language <select id="urbion-lang"><option value="en">English</option><option value="ms">Bahasa Melayu</option></select></label><label>Theme <select id="urbion-theme"><option value="system">System</option><option value="dark">Dark</option><option value="light">Light</option></select></label>';const s=document.createElement('style');s.textContent='#urbion-ui-controls{position:fixed;right:14px;bottom:14px;z-index:99999;display:flex;gap:7px;padding:8px;border:1px solid #203343;border-radius:12px;background:#07121ced;color:#eff8ff;font:10px Inter,system-ui,sans-serif;backdrop-filter:blur(12px);box-shadow:0 10px 30px #0006}#urbion-ui-controls label{display:flex;align-items:center;gap:5px}#urbion-ui-controls select{width:auto;min-width:86px;padding:5px 7px;border:1px solid #203343;border-radius:7px;background:#07121c;color:inherit}@media(max-width:600px){#urbion-ui-controls{left:10px;right:10px;bottom:10px;justify-content:space-between}}';document.head.appendChild(s);document.body.appendChild(box);document.getElementById('urbion-lang').value=lang();document.getElementById('urbion-theme').value=theme();document.getElementById('urbion-lang').onchange=e=>setLang(e.target.value);document.getElementById('urbion-theme').onchange=e=>setTheme(e.target.value)}
  function setLang(v){localStorage.setItem(KEY_LANG,v==='en'?'en':'ms');apply();sync()}
  function setTheme(v){localStorage.setItem(KEY_THEME,['dark','light','system'].includes(v)?v:'system');apply();sync()}
  function sync(){const a=document.getElementById('urbion-lang'),b=document.getElementById('urbion-theme');if(a)a.value=lang();if(b)b.value=theme()}
  window.URBION_UI={dict,get lang(){return lang()},get theme(){return theme()},t(k){return dict[lang()][k]||k},setLang,setTheme,apply};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',controls);else controls();
  apply();
})();