/* MASTER-279: reliability bridge for the primary championship workspace. */
(()=>{
'use strict';
if(window.__URBION_CHAMPIONSHIP_V279__)return;
window.__URBION_CHAMPIONSHIP_V279__=1;
const ROOT='#urbion-champ-dashboard';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,opt)=>{const r=await fetch(path,opt);if(!r.ok)throw Error(path+' · '+r.status);return r.json()};
const payload=()=>({site_lat:+($('dash-lat')?.value||2.285),site_lon:+($('dash-lon')?.value||102.196),tod_lat:+($('dash-todlat')?.value||2.286),tod_lon:+($('dash-todlon')?.value||102.197),plot_ratio:+($('dash-ratio')?.value||4.5),development_type:$('dash-dev')?.value||'TOD Development / Mixed Use',development_class:'Mixed Use',state:$('dash-state')?.value||'Melaka',district:'Melaka Tengah',pbt:'Majlis Bandaraya Melaka Bersejarah',precinct:'Terminal Sg. Udang',lot_no:$('dash-lot')?.value||''});
const LAYERS={current:{label:'Current Land Use · i-PLAN',url:'https://scharms.planmalaysia.gov.my/arcgis/rest/services/iPLAN/GTsemasa_04/MapServer',op:.62},zoning:{label:'Planning Zoning · i-PLAN',url:'https://scharms.planmalaysia.gov.my/arcgis/rest/services/iPLAN/GTzoning_04/MapServer',op:.55},cadastral:{label:'Cadastral Lots · i-PLAN',url:'https://scharms.planmalaysia.gov.my/arcgis/rest/services/iPLAN/LOT_04/MapServer',op:.8},contour:{label:'5m Contours · i-PLAN',url:'https://scharms.planmalaysia.gov.my/arcgis/rest/services/iPLAN/KONTUR5M_04/MapServer',op:.55}};
function css(){const st=document.createElement('style');st.textContent=`#urbion-champ-dashboard .v276-card{transition:transform .16s ease,border-color .16s ease,box-shadow .16s ease}#urbion-champ-dashboard .v276-card:hover{transform:translateY(-1px);border-color:#396170;box-shadow:0 10px 28px #0005}#urbion-champ-dashboard .v276-nav button:focus-visible,#urbion-champ-dashboard .v276-btn:focus-visible,#urbion-champ-dashboard input:focus-visible,#urbion-champ-dashboard select:focus-visible{outline:2px solid #67e8b7;outline-offset:2px}#urbion-champ-dashboard .v276-map-badge:before{content:'● ';color:#67e8b7}#urbion-champ-dashboard .v276-top{position:relative}#urbion-champ-dashboard .v276-top:after{content:'CHAMPIONSHIP EDITION';position:absolute;right:22px;top:7px;font-size:7px;letter-spacing:.16em;color:#67e8b7;opacity:.75}#urbion-champ-dashboard .v276-footer span:last-child{color:#67e8b7}.v279-sourcebar{display:flex;gap:6px;flex-wrap:wrap;padding:7px 18px;background:#061018;border-bottom:1px solid #19313b;font-size:7px;color:#78919d;letter-spacing:.06em}.v279-sourcebar b{color:#67e8b7}.v279-live{margin-left:auto;color:#67e8b7}.v279-error{color:#ff8292!important}.v279-warn{color:#ffd27a!important}.v279-ok{color:#67e8b7!important}@media print{#urbion-champ-dashboard .v276-nav,#urbion-champ-dashboard .v276-actions,#urbion-champ-dashboard .v276-footer,#uhd-quick-tools,#vf-sticky{display:none!important}#urbion-champ-dashboard .v276-page{display:block!important;break-inside:auto}#urbion-champ-dashboard .v276-card{break-inside:avoid;box-shadow:none!important;transform:none!important}.v279-sourcebar{display:flex!important}}@media(max-width:560px){#urbion-champ-dashboard .v276-top:after{display:none}.v279-live{margin-left:0}}`;document.head.appendChild(st)}
function sourceBar(){const top=document.querySelector(ROOT+' .v276-top');if(!top||$('v279-sourcebar'))return;const bar=document.createElement('div');bar.id='v279-sourcebar';bar.className='v279-sourcebar';bar.innerHTML='<span><b>LIVE SOURCES</b></span><span>PLANMalaysia i-PLAN</span><span>i-Plan ArcGIS REST</span><span>DPFDN environment</span><span>Planner support only</span><span class="v279-live">● BUILD LINKED</span>';top.insertAdjacentElement('afterend',bar)}
function nav(page){const b=[...document.querySelectorAll(ROOT+' .v276-nav button')].find(x=>x.dataset.page===page);if(b)b.click()}
function layerUrl(s,b){const q=new URLSearchParams({bbox:[b.getWest(),b.getSouth(),b.getEast(),b.getNorth()].join(','),bboxSR:'4326',imageSR:'4326',size:'1400,900',format:'png32',transparent:'true',f:'image'});return s.url+'/export?'+q}
let map=null,over={};
function hookMap(){map=window.__URBION_V277_MAP__||map;if(!map||map.__v279)return false;map.__v279=1;map.on('moveend',()=>Object.keys(over).forEach(k=>{try{const b=map.getBounds();over[k].setUrl(layerUrl(LAYERS[k],b))}catch(_){}}));return true}
function layerButtons(){const host=$('dash-layers');if(!host)return;host.querySelectorAll('[data-vf-layer]').forEach(b=>{if(b.__v279)return;b.__v279=1;b.onclick=()=>toggleLayer(b.dataset.vfLayer,b)});}
function toggleLayer(k,b){hookMap();const s=LAYERS[k];if(!s){b.textContent='UNKNOWN';return}if(!map){b.textContent='MAP NOT READY';b.classList.add('v279-warn');setTimeout(()=>{hookMap();if(map)b.textContent='OFF'},900);return}if(over[k]){map.removeLayer(over[k]);delete over[k];b.textContent='OFF';b.classList.remove('vp');b.classList.remove('v279-error');return}const bounds=map.getBounds();const ov=L.imageOverlay(layerUrl(s,bounds),bounds,{opacity:s.op,interactive:false,crossOrigin:true});ov.on('load',()=>{b.textContent='ON';b.classList.add('vp');b.classList.remove('v279-error')});ov.on('error',()=>{b.textContent='ERROR';b.classList.remove('vp');b.classList.add('v279-error');if(over[k]){try{map.removeLayer(over[k])}catch(_){}}delete over[k]});over[k]=ov;ov.addTo(map);b.textContent='LOADING…'}
function repairGate(){const b=$('gate'),out=$('gate-result');if(!b||b.__v279)return;b.__v279=1;b.onclick=async()=>{b.disabled=true;b.textContent='CHECKING…';if(out)out.innerHTML='<span class="v276-warn">Evaluating championship gate…</span>';try{const d=await api('/championship-gate');if(out)out.innerHTML='<pre class="vjson">'+esc(JSON.stringify(d,null,2))+'</pre>'}catch(e){if(out)out.innerHTML='<span class="v276-bad">Gate check failed · '+esc(e.message)+'</span>'}finally{b.disabled=false;b.textContent='CHECK GATE'}}}
async function runScenario(ratio,label){const x=payload(),out=$('scenario-results');if(out)out.innerHTML='<span class="v276-warn">RUNNING '+esc(label)+'…</span>';try{const d=await api('/what-if',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseline:x,variants:[{id:'BASELINE',name:'Baseline',plot_ratio:x.plot_ratio},{id:label.toUpperCase().replace(/\\s+/g,'_'),name:label,plot_ratio:ratio}]})});if(out)out.innerHTML='<pre class="vjson">'+esc(JSON.stringify(d,null,2))+'</pre>';return d}catch(e){if(out)out.innerHTML='<span class="v276-bad">What-If failed · '+esc(e.message)+'</span>';return null}}
function wireScenarios(){const a=$('run-a'),b=$('run-b');if(a&&!a.__v279){a.__v279=1;a.onclick=()=>runScenario(+$('sc-a').value||3.5,'Lower Density')}if(b&&!b.__v279){b.__v279=1;b.onclick=()=>runScenario(+$('sc-b').value||5.5,'Higher Density')}}
function hardenRun(){const b=$('run-all');if(!b||b.__v279)return;b.__v279=1;b.addEventListener('click',()=>{setTimeout(()=>{if($('ov-health')&&/RUNNING/.test($('ov-health').textContent))$('ov-health').innerHTML='<span class="v276-warn">CHAMPIONSHIP SUITE IS RUNNING IN PARALLEL…</span>'},30)})}
function inspectFallback(){const b=$('vf-inspect');if(!b||b.__v279)return;b.__v279=1;b.addEventListener('click',()=>setTimeout(()=>{hookMap();if(map){const x=payload();map.setView([x.site_lat,x.site_lon],17)}},180))}
function boot(){const root=document.querySelector(ROOT);if(!root){setTimeout(boot,80);return}css();sourceBar();layerButtons();repairGate();wireScenarios();hardenRun();inspectFallback();hookMap();setTimeout(()=>{layerButtons();repairGate();wireScenarios();hookMap()},900);setTimeout(()=>{if($('vf-sticky'))$('vf-sticky').style.top='auto'},1000)}
boot();
})();