/* URBION HORIZON — P4 live evidence story owner.
   Presentation-only view over canonical evidence. No inference, scoring, or statutory claims. */
(()=>{'use strict';
if(window.__URBION_LIVE_EVIDENCE_OWNER_V1__)return;
window.__URBION_LIVE_EVIDENCE_OWNER_V1__=true;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]||m));
function packet(){return window.URBION_LAST?.canonical_evidence_packet||window.URBION_LAST?.copilot?.canonical_evidence_packet||window.URBION_LAST?.deterministic_packet?.canonical_evidence_packet||null}
function sources(p){const s=p?.evidence?.stations||{};const env=p?.evidence?.environment||{};const out=[];for(const [label,key] of [['JPS rainfall','jps_rainfall'],['MyEQMS water','eqmp_water'],['Air quality','air_quality'],['MyGEMS lithology','mygems_lithology']]){const b=s[key]||env[key]||p?.live_station_evidence?.[key];if(!b)continue;const items=Array.isArray(b?.stations)?b.stations:Array.isArray(b?.features)?b.features:[];out.push({label,key,state:String(b.evidence_state||b.status||'SOURCE_CONTEXT').toUpperCase(),updated:b.last_updated||b.observed_at||b.last_updated_rainfall||b.query_time||b.timestamp||'timestamp not supplied',count:items.length,source:b.source||b.source_url||b.source_registry||'canonical evidence packet'})}return out}
function stateClass(s){return s==='VERIFIED'?'ok':s==='UNVERIFIED'||s.includes('ERROR')?'bad':'warn'}
function render(){const root=document.querySelector('.right');if(!root)return;let card=$('urbionLiveEvidenceCard');if(!card){card=document.createElement('section');card.id='urbionLiveEvidenceCard';card.className='card';root.appendChild(card)}const p=packet();if(!p){card.innerHTML='<div class="cardhead"><h3>LIVE EVIDENCE STORY</h3><span class="tiny">WAITING</span></div><div class="tiny">Run the canonical analysis to populate source-backed observation context.</div>';return}const rows=sources(p);const html=rows.length?rows.map(x=>`<div class="le-row"><div><b>${esc(x.label)}</b><span>${esc(x.source)}</span></div><div class="le-meta"><em class="tag ${stateClass(x.state)}">${esc(x.state)}</em><small>${x.count?esc(x.count+' record(s)'):'identity / query context'} · ${esc(x.updated)}</small></div></div>`).join(''):'<div class="tiny">No live source block was returned in the canonical packet.</div>';card.innerHTML=`<div class="cardhead"><h3>LIVE EVIDENCE STORY</h3><span class="tiny">SOURCE-BACKED · READ-ONLY</span></div><div class="tiny">What the connected source actually supports — without upgrading source context into statutory verification.</div><div class="le-list">${html}</div><div class="le-note"><b>BOUNDARY</b> · Live source context supports observation/identity only. It does not by itself prove adopted-plan applicability, parcel authority, or statutory approval.</div>`}
function css(){if($('urbionLiveEvidenceStyle'))return;const s=document.createElement('style');s.id='urbionLiveEvidenceStyle';s.textContent='.le-list{margin-top:7px}.le-row{display:flex;justify-content:space-between;gap:8px;padding:7px 0;border-bottom:1px solid rgba(45,85,100,.15)}.le-row b{display:block;font-size:6.8px}.le-row span,.le-row small{display:block;font-size:5.7px;color:var(--muted);line-height:1.35}.le-meta{text-align:right;min-width:120px}.le-meta small{margin-top:2px}.le-note{margin-top:7px;padding:7px 8px;border-left:2px solid var(--cyan);background:rgba(47,225,233,.035);font-size:5.9px;line-height:1.45;color:#b9ccd3}.light .le-note{color:#5d727d}';document.head.appendChild(s)}
function boot(){css();render();window.addEventListener('urbion:analysis-ready',render,{passive:true});setInterval(()=>{if(packet())render()},750)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();