/* URBION HORIZON — canonical V2 map/layer + compact accordion repair */
(()=>{
'use strict';
if(window.__URBION_LAYER_RUNTIME_V2__) return;
window.__URBION_LAYER_RUNTIME_V2__=true;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function getMap(){try{return (typeof map!=='undefined'&&map)||window.__URBION_MAP__||window.URBION_FCC_MAP||null}catch(_){return null}}
function state(){return String($('state')?.value||'Melaka').trim()||'Melaka'}
const CODES={'Johor':'01','Kedah':'02','Kelantan':'03','Melaka':'04','Negeri Sembilan':'05','Pahang':'06','Pulau Pinang':'07','Perak':'08','Perlis':'09','Selangor':'10','Terengganu':'11','Sabah':'12','Sarawak':'13','Wilayah Persekutuan':'14','Labuan':'15','Putrajaya':'16'};
function addCss(){if($('urbion-v2-ui'))return;const s=document.createElement('style');s.id='urbion-v2-ui';s.textContent=`
.leftscroll>.sec:not(:first-of-type){border-radius:11px}.leftscroll>.sec:not(:first-of-type) .sechead{min-height:42px;cursor:pointer}.leftscroll>.sec:not(:first-of-type) .sechead button{display:flex;align-items:center;justify-content:space-between}.leftscroll>.sec:not(:first-of-type) .sechead button:after{content:'⌄';color:var(--muted);font-size:11px;transition:transform .18s ease}.leftscroll>.sec.collapsed .sechead button:after{transform:rotate(-90deg)}.layer-group{border:1px solid rgba(63,129,149,.18);border-radius:9px;overflow:hidden;margin:5px 0}.layer-group-head{width:100%;border:0;background:rgba(7,29,41,.55);color:var(--text);display:flex;align-items:center;justify-content:space-between;padding:8px 9px;font-size:7.5px;font-weight:800;letter-spacing:.06em;text-align:left}.layer-group-head:after{content:'⌄';color:var(--muted)}.layer-group.closed .layer-group-head:after{transform:rotate(-90deg)}.layer-group.closed .layer-group-body{display:none}.layer-group-body{padding:4px 7px 6px}.layerrow{align-items:center}.layerrow span{line-height:1.25}.layerstate[data-state='loading']{color:var(--warn)}.layerstate[data-state='ok']{color:var(--good)}.layerstate[data-state='error']{color:var(--bad)}#layers{max-height:78%;padding:8px}.layer-tools{display:flex;gap:5px;margin-bottom:7px}.layer-tools button{flex:1;background:#061923;border:1px solid var(--line);border-radius:7px;padding:6px;font-size:6.8px;color:var(--muted)}.layer-tools button:hover{color:var(--text);border-color:rgba(47,225,233,.4)}
`;document.head.appendChild(s)}
function compactCaseSections(){const secs=[...document.querySelectorAll('.leftscroll>.sec')];secs.forEach((s,i)=>{if(i>0&&!s.dataset.v2Init){s.dataset.v2Init='1';s.classList.add('collapsed')}})}
function setState(id,text,type){const e=document.querySelector(`[data-layer-state="${CSS.escape(id)}"]`);if(!e)return;e.textContent=text;if(type)e.dataset.state=type}
function wmBounds(x,y,z){const n=2**z,s=40075016.68557849/n,minx=x*s-20037508.342789244,maxx=(x+1)*s-20037508.342789244,maxy=20037508.342789244-y*s,miny=20037508.342789244-(y+1)*s;return [minx,miny,maxx,maxy]}
function arcgis(info){const Layer=L.GridLayer.extend({createTile(c,done){const t=document.createElement('img');t.width=256;t.height=256;t.alt='';t.crossOrigin='anonymous';const b=wmBounds(c.x,c.y,c.z),lid=Number(info.layerId??0);const url=String(info.url).replace(/\/$/,'')+`/export?bbox=${b.join(',')}&bboxSR=3857&imageSR=3857&size=256,256&imageDisplay=256,256,96&dpi=96&format=png32&transparent=true&f=image&layers=show:${lid}`;t.onload=()=>done(null,t);t.onerror=e=>done(e,t);t.src=url;return t}});return new Layer({tileSize:256,opacity:.82,updateWhenIdle:false,keepBuffer:2})}
function makeLayer(info){const type=String(info.type||'').toUpperCase();if(type==='GEOSERVER_WMS'){if(!info.url||!info.layers)throw Error('WMS endpoint/layer missing');const l=L.tileLayer.wms(info.url,{layers:info.layers,styles:'',format:'image/png',transparent:true,version:'1.1.1',crs:L.CRS.EPSG3857,opacity:.78,tiled:true});l.on('tileloadstart',()=>setState(info.id,'LOADING · WMS','loading'));l.on('tileload',()=>setState(info.id,'ON · RENDERED','ok'));l.on('tileerror',()=>setState(info.id,'ERROR · TILE','error'));return l}if(type==='ARCGIS_MAP'){const l=arcgis(info);l.on('loading',()=>setState(info.id,'LOADING · ARCGIS','loading'));l.on('load',()=>setState(info.id,'ON · RENDERED','ok'));return l}if(type==='TILE'){const l=L.tileLayer(info.url,{maxZoom:19,opacity:.78,attribution:info.name||info.source||'Source'});l.on('tileloadstart',()=>setState(info.id,'LOADING · TILE','loading'));l.on('tileload',()=>setState(info.id,'ON · RENDERED','ok'));l.on('tileerror',()=>setState(info.id,'ERROR · TILE','error'));return l}return null}
function cadastral(code){return {id:'iplan-cadastral',name:'i-Plan · Cadastral Lots',name_ms:'i-Plan · Lot Kadaster',group:'CADASTRAL',type:'ARCGIS_MAP',url:`https://scharms.planmalaysia.gov.my/arcgis/rest/services/iPLAN/LOT_${code}/MapServer`,layerId:0,source:'iplan',evidence:'SOURCE_CONTEXT',access_note:'Live public ArcGIS parcel geometry anchor; JUPEM remains the cadastral verification authority.'}}
function normalise(layers){const code=CODES[state()]||'04',all=[cadastral(code),...(Array.isArray(layers)?layers:[])].filter(x=>x&&x.id!=='osm');const seen=new Set();return all.filter(x=>{if(seen.has(x.id))return false;seen.add(x.id);return true})}
function clearOverlays(){const m=getMap(),store=window.__URBION_LIVE_LAYERS__||{};Object.values(store).forEach(l=>{try{if(m&&m.hasLayer(l))m.removeLayer(l)}catch(_){}});window.__URBION_LIVE_LAYERS__={}}
async function catalog(){const r=await fetch(location.origin+'/map/layers?state='+encodeURIComponent(state())+'&_='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return normalise((await r.json()).layers)}
function draw(layers){const list=$('layerList');if(!list)return;list.innerHTML='';const groups={};layers.forEach(x=>(groups[x.group||'OTHER']??=[]).push(x));const order=['PLANNING','CADASTRAL','HAZARD','ENVIRONMENT','ECOLOGY','HERITAGE','HOUSING','TERRAIN','GEOLOGY','GEOHAZARD','GEOHERITAGE'];const keys=[...order.filter(k=>groups[k]),...Object.keys(groups).filter(k=>!order.includes(k))];keys.forEach((g,idx)=>{const wrap=document.createElement('div');wrap.className='layer-group'+(idx?' closed':'');const h=document.createElement('button');h.type='button';h.className='layer-group-head';h.textContent=g.replaceAll('_',' ');h.onclick=()=>wrap.classList.toggle('closed');const b=document.createElement('div');b.className='layer-group-body';groups[g].forEach(x=>{const r=document.createElement('div');r.innerHTML=`<div class="layerrow"><input type="checkbox" data-v2-layer="${esc(x.id)}"><span>${esc(x.name||x.id)}</span><small>${esc(x.source||x.type||'')}</small></div><div class="layerstate" data-layer-state="${esc(x.id)}" data-state="off">OFF · ${esc(x.type||'SOURCE')}</div>`;b.appendChild(r.firstElementChild);b.appendChild(r.lastElementChild)});wrap.append(h,b);list.appendChild(wrap)});layers.forEach(x=>list.querySelector(`[data-v2-layer="${CSS.escape(x.id)}"]`)?.addEventListener('change',e=>toggle(x,e.target.checked))) }
async function refresh(){const m=getMap();if(!m||typeof L==='undefined')return false;try{draw(await catalog());if(window.URBION_FINAL)window.URBION_FINAL.loadLayers=refresh;return true}catch(e){if($('layerList'))$('layerList').innerHTML=`<div class="tiny" style="color:var(--bad)">Live catalogue error · ${esc(e.message)}</div>`;return false}}
function toggle(info,on){const m=getMap();if(!m||typeof L==='undefined')return;window.__URBION_LIVE_LAYERS__=window.__URBION_LIVE_LAYERS__||{};const old=window.__URBION_LIVE_LAYERS__[info.id];if(!on){if(old&&m.hasLayer(old))m.removeLayer(old);delete window.__URBION_LIVE_LAYERS__[info.id];setState(info.id,'OFF · '+String(info.type||'SOURCE'),'off');return}if(old&&m.hasLayer(old)){setState(info.id,'ON · RENDERED','ok');return}try{setState(info.id,'LOADING · SOURCE','loading');const layer=makeLayer(info);if(!layer){setState(info.id,'PORTAL · SOURCE','off');return}layer.__urbionSource=info.source||'official';layer.__urbionLayerId=info.id;layer.addTo(m);window.__URBION_LIVE_LAYERS__[info.id]=layer;setTimeout(()=>{if(m.hasLayer(layer)&&document.querySelector(`[data-layer-state="${CSS.escape(info.id)}"]`)?.dataset.state==='loading')setState(info.id,'ON · RENDERED','ok')},3500)}catch(e){setState(info.id,'ERROR · '+e.message,'error');console.error('URBION V2 layer failure',info,e)}}
async function boot(){addCss();compactCaseSections();for(let i=0;i<120;i++){const m=getMap();if(m&&typeof L!=='undefined'&&$('layerList')){await refresh();if(window.URBION_FINAL)window.URBION_FINAL.loadLayers=refresh;const btn=$('layerBtn');if(btn&&!btn.dataset.v2LayerBound){btn.dataset.v2LayerBound='1';btn.addEventListener('click',e=>{e.stopImmediatePropagation();$('layers')?.classList.toggle('open');void refresh()},true)}$('state')?.addEventListener('change',()=>{clearOverlays();void refresh()});return}await sleep(250)}}
window.URBION_LAYER_V2={refresh,toggle,clearOverlays};void boot();
})();