/* URBION HORIZON — authoritative V5 GIS layer manager + About guard. */
(()=>{'use strict';
if(window.__URBION_LAYER_MANAGER__)return; window.__URBION_LAYER_MANAGER__=true;
const $=id=>document.getElementById(id), sleep=ms=>new Promise(r=>setTimeout(r,ms));
const CODES={Johor:'01',Kedah:'02',Kelantan:'03',Melaka:'04','Negeri Sembilan':'05',Pahang:'06','Pulau Pinang':'07',Perak:'08',Perlis:'09',Selangor:'10',Terengganu:'11',Sabah:'12',Sarawak:'13','Wilayah Persekutuan':'14',Labuan:'15',Putrajaya:'16','W.P. Kuala Lumpur':'14','W.P. Labuan':'15','W.P. Putrajaya':'16'};
const CORE=new Set(['iplan-current','iplan-zoning','iplan-committed','iplan-rfn','iplan-rsn','iplan-flood','iplan-disaster-risk','iplan-ksas','iplan-cfs','iplan-ecology','iplan-heritage','iplan-affordable-housing','iplan-topography','iplan-hutan','iplan-coastal-erosion','iplan-rmm','iplan-contours','mygems-faults','mygems-quarries','mygems-groundwater','mygems-geowarisan','mygems-lithology','mygems-seismic','mygems-mineral']);
function mapObj(){try{const m=(typeof map!=='undefined'&&map)||window.__URBION_MAP__||window.URBION_FCC_MAP||null;return m&&typeof m.addLayer==='function'&&typeof m.hasLayer==='function'?m:null}catch(_){return null}}
function state(){return String($('state')?.value||$('cs-state')?.value||'Melaka').trim()||'Melaka'}
function panel(){return $('layerList')||$('cs-layer-drawer')||document.querySelector('.layers')}
function safeId(id){return String(id).replace(/[^a-zA-Z0-9_-]/g,'_')}
function setState(id,text,type){const e=document.querySelector(`[data-layer-state="${CSS.escape(id)}"]`);if(e){e.textContent=text;e.dataset.state=type}}
function addCss(){if($('urbion-layer-manager-css'))return;const s=document.createElement('style');s.id='urbion-layer-manager-css';s.textContent='.urbion-layer-tools{display:flex;gap:6px;margin-bottom:8px}.urbion-layer-tools button{flex:1;background:#061923;border:1px solid var(--line);border-radius:7px;padding:7px;font-size:7px;color:var(--text)}.urbion-layer-group{border:1px solid rgba(63,129,149,.18);border-radius:8px;overflow:hidden;margin:5px 0}.urbion-layer-head{width:100%;border:0;background:rgba(7,29,41,.65);color:var(--text);display:flex;justify-content:space-between;padding:8px;font-size:7px;font-weight:800;text-align:left}.urbion-layer-head:after{content:"⌄";color:var(--muted)}.urbion-layer-group.closed .urbion-layer-head:after{transform:rotate(-90deg)}.urbion-layer-body{padding:2px 7px 5px}.urbion-layer-group.closed .urbion-layer-body{display:none}.urbion-layer-row{display:grid;grid-template-columns:16px 1fr;gap:6px;padding:7px 1px;border-bottom:1px solid rgba(45,85,100,.18);font-size:7.5px}.urbion-layer-row:last-child{border-bottom:0}.urbion-layer-row input{accent-color:var(--cyan);margin-top:2px}.urbion-layer-name{display:block}.urbion-layer-source{display:block;color:var(--muted);font-size:6px;margin-top:2px}.urbion-layer-state{grid-column:2;font-size:6px;color:var(--muted);padding-bottom:5px}.urbion-layer-state[data-state=loading]{color:var(--warn)}.urbion-layer-state[data-state=ok]{color:var(--good)}.urbion-layer-state[data-state=error]{color:var(--bad)}';document.head.appendChild(s)}
function normalizeEnglishLabels(){const replacements=new Map([['GUNA TANAH & ZONING','LAND USE & ZONING'],['GUNA TANAH 1','LAND USE LEVEL 1'],['GUNA TANAH 2','LAND USE LEVEL 2'],['GUNA TANAH 3','LAND USE LEVEL 3'],['AKTIVITI','ACTIVITY'],['PEMBANGUNAN & CADANGAN','DEVELOPMENT PROPOSAL'],['PEMBANGUNAN INTENSITI','DEVELOPMENT INTENSITY'],['KEMUDAHAN & UTILITI','INFRASTRUCTURE & UTILITIES'],['ALAM SEKITAR & RISIKO','ENVIRONMENT & RISK'],['SOKONGAN EVIDENCE','SUPPORTING EVIDENCE'],['PILIHAN ANALISIS AI','AI ANALYSIS OPTIONS'],['JANA / EKSPORT','GENERATE / EXPORT'],['KETERANGAN','DESCRIPTION'],['KELAS PEMBANGUNAN','DEVELOPMENT CLASS'],['JENIS PEMBANGUNAN','DEVELOPMENT TYPE'],['GUNA TANAH','LAND USE'],['DAERAH','DISTRICT'],['PIHAK BERKUASA TEMPATAN','LOCAL AUTHORITY'],['KELUASAN TAPAK','SITE AREA'],['GARIS PANDUAN','GUIDELINES']]);const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];let n;while(n=walker.nextNode())nodes.push(n);nodes.forEach(node=>{const raw=node.nodeValue||'',trimmed=raw.trim();if(!trimmed)return;const replacement=replacements.get(trimmed.toUpperCase());if(replacement)node.nodeValue=raw.replace(trimmed,replacement)});document.documentElement.lang='en'}
function aboutGuard(){document.addEventListener('click',e=>{const el=e.target?.closest?.('button,a,[role="button"]');if(!el)return;if(el.closest('#urbionUtilityTools'))return;if((el.textContent||'').trim().toUpperCase()!=='ABOUT')return;e.preventDefault();e.stopImmediatePropagation();window.location.assign('/about')},true)}
function mercatorBounds(x,y,z){const n=2**z,s=40075016.68557849/n;return[x*s-20037508.342789244,20037508.342789244-(y+1)*s,((x+1)*s)-20037508.342789244,20037508.342789244-y*s]}
function arcgis(info){const Base=L.GridLayer.extend({createTile(c,done){const t=document.createElement('img');t.width=256;t.height=256;t.alt='';t.crossOrigin='anonymous';const b=mercatorBounds(c.x,c.y,c.z),service=String(info.url).replace(/\/$/,''),lid=info.layerId??info.layer_id,q=lid==null?'':`&layers=show:${encodeURIComponent(lid)}`;t.src=location.origin+'/map/arcgis?service='+encodeURIComponent(service)+`&bbox=${b.join(',')}&bboxSR=3857&imagesr=3857&size=256,256&imagedisplay=256,256,96&dpi=96&format=png32&transparent=true&f=image${q}`;t.onload=()=>done(null,t);t.onerror=e=>done(e,t);return t}});return new Base({tileSize:256,opacity:Number(info.opacity??.82),updateWhenIdle:false,keepBuffer:2})}
function bindTiles(layer,info,label){let loaded=0,errored=0,timer=null;const success=()=>{loaded+=1;if(timer){clearTimeout(timer);timer=null}setState(info.id,'ON · RENDERED','ok');normalizeEnglishLabels()};layer.on('tileloadstart',()=>setState(info.id,'LOADING · '+label,'loading'));layer.on('tileload',success);layer.on('load',success);layer.on('tileerror',()=>{errored+=1;if(!loaded&&errored>=1)setState(info.id,'ERROR · '+label,'error')});timer=setTimeout(()=>{if(!loaded)setState(info.id,'ERROR · TIMEOUT','error')},35000)}
function makeLayer(info){const type=String(info.type||'').toUpperCase();if(type==='GEOSERVER_WMS'){if(!info.layers)throw Error('WMS layer identifier missing');const l=L.tileLayer.wms(location.origin+'/map/wms',{layers:info.layers,styles:'',format:'image/png',transparent:true,version:'1.1.1',opacity:Number(info.opacity??.78),tiled:true});bindTiles(l,info,'SOURCE');return l}if(type==='ARCGIS_MAP'||type==='INFO_SCREENING'){if(!info.url)throw Error('ArcGIS service URL missing');const l=arcgis(info);bindTiles(l,info,'ARCGIS');return l}if(type==='TILE'){const l=L.tileLayer(info.url,{maxZoom:19,opacity:Number(info.opacity??.78),attribution:info.name||info.source||'Source'});bindTiles(l,info,'TILE');return l}return null}
function cadastral(){const code=CODES[state()]||'04';return{id:'iplan-cadastral',name:'i-Plan · Cadastral Lots',group:'CADASTRAL',type:'ARCGIS_MAP',url:`https://scharms.planmalaysia.gov.my/arcgis/rest/services/iPLAN/LOT_${code}/MapServer`,layerId:0,source:'iplan',evidence:'SOURCE_CONTEXT',access_note:'Live i-Plan parcel geometry anchor; JUPEM MyLot remains the cadastral verification reference.'}}
async function catalog(){const r=await fetch(location.origin+'/map/layers?state='+encodeURIComponent(state())+'&_='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json(),incoming=Array.isArray(d.layers)?d.layers:[];const out=[cadastral(),...incoming.filter(x=>x&&CORE.has(x.id))];const seen=new Set();return out.filter(x=>!seen.has(x.id)&&(seen.add(x.id),true))}
function clearLive(){const m=mapObj(),store=window.__URBION_LIVE_LAYERS__||{};Object.values(store).forEach(l=>{try{if(m&&m.hasLayer(l))m.removeLayer(l)}catch(_){}});window.__URBION_LIVE_LAYERS__={}}
function groupOrder(groups){const order=['PLANNING','CADASTRAL','HAZARD','ENVIRONMENT','ECOLOGY','GEOLOGY','GEOHAZARD','GEOHERITAGE','HERITAGE','HOUSING','TERRAIN','HYDROLOGY','TRANSPORT'];return[...order.filter(k=>groups[k]),...Object.keys(groups).filter(k=>!order.includes(k))]}
function row(body,x){const wrap=document.createElement('div'),id=safeId(x.id);wrap.className='urbion-layer-row';const cb=document.createElement('input');cb.type='checkbox';cb.dataset.urbionLayer=x.id;cb.dataset.layer=x.id;cb.id='urbion-layer-'+id;const label=document.createElement('label');label.htmlFor=cb.id;label.className='urbion-layer-name';label.textContent=x.name||x.id;const src=document.createElement('span');src.className='urbion-layer-source';src.textContent=x.source||x.type||'';label.appendChild(src);const st=document.createElement('div');st.className='urbion-layer-state';st.dataset.layerState=x.id;st.dataset.state='off';st.textContent='OFF · '+String(x.type||'SOURCE');wrap.append(cb,label,st);body.appendChild(wrap);cb.addEventListener('change',()=>toggle(x,cb.checked));return cb}
function draw(layers){const host=panel();if(!host)return false;host.replaceChildren();const tools=document.createElement('div');tools.className='urbion-layer-tools';const clear=document.createElement('button');clear.type='button';clear.textContent='CLEAR MAP';const refresh=document.createElement('button');refresh.type='button';refresh.textContent='REFRESH';tools.append(clear,refresh);host.appendChild(tools);const groups={};layers.forEach(x=>(groups[x.group||'OTHER']??=[]).push(x));groupOrder(groups).forEach((g,i)=>{const wrap=document.createElement('div');wrap.className='urbion-layer-group'+(i?' closed':'');const head=document.createElement('button');head.type='button';head.className='urbion-layer-head';head.textContent=g.replaceAll('_',' ');head.onclick=()=>wrap.classList.toggle('closed');const body=document.createElement('div');body.className='urbion-layer-body';groups[g].forEach(x=>row(body,x));wrap.append(head,body);host.appendChild(wrap)});clear.onclick=()=>{clearLive();host.querySelectorAll('input[data-urbion-layer]').forEach(x=>{x.checked=false});layers.forEach(x=>setState(x.id,'OFF · '+String(x.type||'SOURCE'),'off'))};refresh.onclick=()=>void refreshLayers();normalizeEnglishLabels();return true}
function toggle(info,on){const m=mapObj();if(!m)return;window.__URBION_LIVE_LAYERS__=window.__URBION_LIVE_LAYERS__||{};const old=window.__URBION_LIVE_LAYERS__[info.id];if(!on){if(old&&m.hasLayer(old))m.removeLayer(old);delete window.__URBION_LIVE_LAYERS__[info.id];setState(info.id,'OFF · '+String(info.type||'SOURCE'),'off');return}if(old&&m.hasLayer(old)){setState(info.id,'ON · RENDERED','ok');return}try{setState(info.id,'LOADING · '+(String(info.type||'SOURCE').toUpperCase()==='ARCGIS_MAP'?'ARCGIS':'SOURCE'),'loading');const layer=makeLayer(info);if(!layer)throw Error('Unsupported layer type');layer.addTo(m);window.__URBION_LIVE_LAYERS__[info.id]=layer}catch(e){setState(info.id,'ERROR · '+String(e.message||e),'error');console.error('URBION layer failure',info,e)}}
async function refreshLayers(){const m=mapObj();if(!m||typeof L==='undefined'||!panel())return false;try{const layers=await catalog();draw(layers);window.__URBION_LAYER_CATALOG__=layers;normalizeEnglishLabels();return true}catch(e){const host=panel();if(host)host.innerHTML=`<div style="padding:10px;color:var(--bad);font-size:7px">LIVE GIS CATALOGUE ERROR · ${String(e.message||e)}</div>`;return false}}
async function boot(){addCss();aboutGuard();normalizeEnglishLabels();for(let i=0;i<160;i++){if(mapObj()&&typeof L!=='undefined'&&panel()){await refreshLayers();return}await sleep(250)}console.warn('URBION GIS manager: map/panel not ready')}
window.URBION_LAYER_MANAGER={refresh:refreshLayers,toggle,clearLive};void boot();
})();
