(()=>{
'use strict';
if(window.__URBION_PREMIUM_V6__)return;
window.__URBION_PREMIUM_V6__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const root=()=>$('#urbion-championship-shell');
const lang=()=>localStorage.getItem('urbion-lang')==='bm'?'bm':'en';
const copy={en:{case:'PLANNING CASE',caseSub:'Define the site, governance, land use and proposal before analysis.',layers:'MAP LAYERS',layersSub:'Turn planning evidence on or off directly on the map.',about:'ABOUT URBION',sources:'DATA SOURCES',status:'SYSTEM STATUS',run:'RUN ANALYSIS',newCase:'NEW CASE',active:'ACTIVE',visible:'VISIBLE',source:'SOURCE',development:'Development / Proposal',selectDevelopment:'Select development / proposal',sourceBound:'SOURCE-BOUND',browser:'Browser map connection'},bm:{case:'KES PERANCANGAN',caseSub:'Takrif tapak, tadbir urus, guna tanah dan cadangan sebelum analisis.',layers:'LAPISAN PETA',layersSub:'Hidup atau matikan bukti perancangan terus pada peta.',about:'TENTANG URBION',sources:'SUMBER DATA',status:'STATUS SISTEM',run:'JALANKAN ANALISIS',newCase:'KES BAHARU',active:'AKTIF',visible:'DIPAPARKAN',source:'SUMBER',development:'Pembangunan / Cadangan',selectDevelopment:'Pilih pembangunan / cadangan',sourceBound:'TERIKAT SUMBER',browser:'Sambungan peta pelayar'}};
const t=()=>copy[lang()];
const developmentOptions=['New Development','Redevelopment','Extension / Addition','Change of Use','Subdivision','Land Consolidation','Mixed-Use Development','Temporary Use'];
function installStyles(){if($('#urbion-premium-v6-style'))return;const s=document.createElement('style');s.id='urbion-premium-v6-style';s.textContent=`
:root{--u-bg:#061019;--u-panel:#0a1823;--u-panel2:#0d202d;--u-line:rgba(116,218,211,.18);--u-text:#e8f4f6;--u-muted:#7894a1;--u-cyan:#57dff2;--u-mint:#63e4c2;--u-blue:#67a9ff;--u-amber:#ffbd72;--u-purple:#c99aff}
#urbion-championship-shell{position:relative;isolation:isolate;min-height:100vh;background:radial-gradient(900px 500px at 83% 0%,rgba(43,200,239,.13),transparent 60%),radial-gradient(700px 500px at 10% 90%,rgba(55,225,181,.08),transparent 62%),linear-gradient(180deg,#061019 0%,#07121c 52%,#061019 100%);color:var(--u-text)!important;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}
#urbion-championship-shell:before{content:"";position:absolute;inset:0;z-index:-1;pointer-events:none;opacity:.24;background-image:radial-gradient(circle at 1px 1px,rgba(117,225,220,.32) 1px,transparent 1.4px),linear-gradient(rgba(101,180,209,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(101,180,209,.035) 1px,transparent 1px);background-size:24px 24px,48px 48px,48px 48px;mask-image:linear-gradient(to bottom,#000 0%,rgba(0,0,0,.75) 65%,transparent 100%)}
#urbion-championship-shell:after{content:"";position:absolute;inset:0;z-index:-1;pointer-events:none;background:linear-gradient(90deg,transparent 0%,rgba(87,223,242,.035) 50%,transparent 100%);mix-blend-mode:screen}
#urbion-championship-shell *{box-sizing:border-box}
.cs-head{position:sticky!important;top:0;z-index:60;height:72px!important;padding:0 28px!important;background:rgba(4,12,18,.9)!important;border-bottom:1px solid rgba(107,222,218,.16)!important;backdrop-filter:blur(18px) saturate(130%);box-shadow:0 10px 35px rgba(0,0,0,.18)}
.brand img{filter:drop-shadow(0 0 14px rgba(67,224,225,.16));transition:transform .18s ease}.brand img:hover{transform:translateY(-1px)}
.online{display:inline-flex;align-items:center;gap:7px;padding:7px 9px;border:1px solid rgba(88,227,193,.18);border-radius:999px;background:rgba(62,219,192,.05);color:#70e7ca!important}
.online:before{content:"";width:6px;height:6px;border-radius:50%;background:#65e5c5;box-shadow:0 0 12px #65e5c5}
.head-actions button{min-width:52px!important;height:34px!important;border-radius:10px!important;background:linear-gradient(180deg,#10222d,#091721)!important;border:1px solid rgba(102,180,204,.28)!important;color:#c3d5db!important;font-weight:900!important;letter-spacing:.06em;box-shadow:inset 0 1px 0 rgba(255,255,255,.04),0 8px 18px rgba(0,0,0,.12)}
.head-actions button:hover{border-color:rgba(99,228,201,.62)!important;color:#83ebd2!important;transform:translateY(-1px)}
.head-actions .premium-lang-control{min-width:64px!important}.head-actions .premium-icon-control{min-width:70px!important}
.cs-hero{max-width:1560px!important;padding:32px 30px 22px!important}.cs-hero h1{max-width:980px;font-size:clamp(34px,4vw,54px)!important;line-height:1.03!important;letter-spacing:-.045em!important}.cs-hero p{font-size:12px!important;color:#8ea9b6!important}.hero-actions .primary,.hero-actions .secondary{min-height:38px!important;padding:0 15px!important}
.premium-run-control{background:linear-gradient(180deg,#6ee8ca,#52d9bd)!important;color:#03201b!important;border:1px solid rgba(151,255,232,.62)!important;box-shadow:0 10px 24px rgba(51,214,181,.16),inset 0 1px 0 rgba(255,255,255,.32)!important}.premium-run-control:not(:disabled):hover{transform:translateY(-1px);box-shadow:0 14px 28px rgba(51,214,181,.22),inset 0 1px 0 rgba(255,255,255,.34)!important}.premium-secondary-control{background:#0a1924!important;border-color:#2a4d5a!important}
.cs-grid{max-width:1560px!important;grid-template-columns:minmax(0,1fr) 380px!important;gap:16px!important;padding:0 30px 20px!important}
.map-panel{border-radius:18px!important;border-color:rgba(112,219,215,.2)!important;background:linear-gradient(145deg,rgba(10,28,39,.97),rgba(4,13,21,.99))!important;box-shadow:0 25px 60px rgba(0,0,0,.2)!important;display:grid!important;grid-template-columns:minmax(0,1fr) 290px;grid-template-rows:auto minmax(530px,1fr)!important;overflow:hidden!important}
.panel-head{grid-column:1/-1!important;padding:12px 14px!important;border-bottom:1px solid rgba(105,211,215,.12);background:linear-gradient(180deg,rgba(9,25,35,.9),rgba(7,19,28,.78))}.panel-head>b{font-size:15px!important}.panel-head small{color:#708d9a!important}
.map-actions{align-items:center!important;flex-wrap:wrap}.map-actions button{padding:8px 11px!important;border-radius:9px!important;background:#0b1d28!important;border:1px solid #2a4b58!important;color:#90a9b4!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.03)}.map-actions button:hover,.map-actions button.active{color:#d9fffa!important;border-color:#63ddcd!important;background:rgba(65,215,193,.11)!important;box-shadow:0 0 0 1px rgba(99,221,205,.08),0 8px 18px rgba(43,204,182,.1)}
#cs-map{grid-column:1!important;grid-row:2!important;height:100%!important;min-height:530px!important;background:#071018!important}.leaflet-container{font:inherit}.leaflet-control-zoom a{background:#0a1b26!important;color:#d8eef0!important;border-color:#294957!important}.leaflet-control-attribution{background:rgba(4,13,19,.74)!important;color:#708891!important}.leaflet-control-attribution a{color:#91cfd0!important}
.persistent-layers{grid-column:2!important;grid-row:2!important;position:static!important;width:auto!important;max-height:none!important;overflow:auto!important;display:flex!important;flex-direction:column!important;padding:10px!important;border:0!important;border-left:1px solid rgba(105,211,215,.12)!important;border-radius:0!important;background:linear-gradient(180deg,rgba(6,17,25,.98),rgba(7,20,29,.96))!important;gap:3px!important}
.persistent-layers .premium-layer-head{display:flex;justify-content:space-between;align-items:start;gap:8px;padding:5px 6px 10px;margin-bottom:3px;border-bottom:1px solid rgba(112,218,212,.13)}.premium-layer-head b{display:block;color:#cfe4e7;font-size:10px;letter-spacing:.12em}.premium-layer-head small{display:block;max-width:210px;margin-top:4px;color:#6f8b97;font-size:8px;line-height:1.45}.premium-layer-head strong{min-width:28px;text-align:center;padding:4px 6px;border:1px solid rgba(99,226,201,.24);border-radius:8px;color:#6fe5cb;background:rgba(99,226,201,.06);font-size:10px}
.fcc-layer-row{position:relative;display:grid!important;grid-template-columns:22px 1fr!important;align-items:center;gap:8px!important;padding:8px 8px!important;border:1px solid transparent!important;border-radius:9px!important;background:rgba(255,255,255,.012)!important;color:#9db2bb!important;cursor:pointer;transition:background .15s ease,border-color .15s ease,transform .15s ease}.fcc-layer-row:before{content:"";position:absolute;left:0;top:8px;bottom:8px;width:2px;border-radius:5px;background:var(--layer-accent,#63deda);opacity:.18}.fcc-layer-row:hover,.fcc-layer-row.hover{background:rgba(76,213,196,.06)!important;border-color:rgba(93,216,201,.14)!important;transform:translateX(1px)}.fcc-layer-row.is-on{background:rgba(72,214,191,.08)!important;border-color:rgba(98,228,206,.2)!important}.fcc-layer-row.is-on:before{opacity:1;box-shadow:0 0 12px var(--layer-accent,#63deda)}.fcc-layer-row input{appearance:none;width:16px!important;height:16px!important;margin:0!important;border-radius:5px!important;border:1px solid #3c5a65!important;background:#091820!important;display:grid!important;place-items:center;cursor:pointer}.fcc-layer-row input:checked{background:var(--layer-accent,#63deda)!important;border-color:var(--layer-accent,#63deda)!important;box-shadow:0 0 12px rgba(89,226,207,.18)}.fcc-layer-row input:checked:after{content:"✓";font-size:10px;font-weight:900;color:#06201c}.fcc-layer-row span{display:block!important;font-size:9px!important;font-weight:800!important;line-height:1.15}.fcc-layer-row small{display:block!important;margin-top:3px!important;color:#667f8b!important;font-size:7px!important;letter-spacing:.1em!important}
.premium-layer-foot{margin-top:auto;padding:9px 7px 2px;border-top:1px solid rgba(109,211,210,.12);display:flex;align-items:center;gap:6px}.premium-layer-foot span{color:#61dfc7;font-size:11px}.premium-layer-foot small{color:#647f8b;font-size:7px;line-height:1.4}
.intelligence{position:sticky!important;top:86px!important;align-self:start!important;max-height:calc(100vh - 104px);overflow:auto;padding-right:2px;scrollbar-width:thin}.intelligence::-webkit-scrollbar{width:6px}.intelligence::-webkit-scrollbar-thumb{background:#1c3743;border-radius:99px}.card{border-color:rgba(105,211,210,.17)!important;background:linear-gradient(145deg,rgba(11,28,39,.96),rgba(6,17,25,.98))!important;box-shadow:0 16px 34px rgba(0,0,0,.18)!important}.card:hover{border-color:rgba(105,222,211,.28)!important}.readiness{background:linear-gradient(145deg,rgba(14,43,45,.96),rgba(8,23,30,.98))!important}.bar{height:6px!important;background:#102630!important}.bar i{background:linear-gradient(90deg,#5fe5c6,#55ccec)!important}
.persistent-case{position:static!important;width:auto!important;max-height:none!important;overflow:visible!important;padding:0!important;margin:0!important;border:1px solid rgba(105,211,210,.2)!important;border-radius:16px!important;background:linear-gradient(145deg,rgba(10,25,35,.97),rgba(6,16,24,.98))!important;box-shadow:0 18px 36px rgba(0,0,0,.16)!important;transform:none!important;border-left:1px solid rgba(105,211,210,.2)!important}.persistent-case .drawer-head{padding:14px 14px 8px}.persistent-case .drawer-head h2{margin:4px 0 4px!important;font-size:20px!important}.persistent-case .drawer-head:after{content:'Required inputs → analysis';display:block;color:#67838f;font-size:8px;letter-spacing:.04em}.persistent-case #cs-close{display:none!important}.persistent-case .form-grid{padding:0 14px 4px;gap:8px!important}.persistent-case .form-grid label{font-size:8px!important;color:#83a0ac!important}.persistent-case .form-grid input,.persistent-case .form-grid select{height:36px!important;padding:9px 10px!important;border-radius:9px!important;background:#07141d!important;border:1px solid #244351!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.02)}.persistent-case .form-grid input:focus,.persistent-case .form-grid select:focus{outline:none!important;border-color:#58dbc9!important;box-shadow:0 0 0 3px rgba(88,219,201,.09)!important}.persistent-case .two{gap:7px}.persistent-case .full{margin:10px 14px 0!important;width:calc(100% - 28px)!important}.persistent-case .history{margin:14px 14px 16px!important;padding-top:12px!important}.persistent-case .history-item{background:#091922!important;border-color:#1c3946!important}.persistent-case .history-item:hover{border-color:#4bdcc7!important;background:rgba(66,210,194,.07)!important}
.tool-grid button{border-radius:9px!important;background:#0b1d29!important;border-color:#294a57!important}.tool-grid button:hover{border-color:#63dfce!important;box-shadow:0 8px 18px rgba(45,208,186,.1)}.tool-result{border-color:#23404d!important;background:rgba(255,255,255,.012)!important}
.analysis{max-width:1560px!important;padding:0 30px 22px!important}.tabs{gap:4px!important;padding:5px!important;border-radius:13px!important;background:rgba(7,20,29,.88)!important;border-color:rgba(110,205,210,.16)!important;box-shadow:0 14px 28px rgba(0,0,0,.12)}.tabs button{min-width:88px!important;padding:10px 13px!important;border:1px solid transparent!important;border-radius:9px!important;color:#7d97a3!important;transition:all .15s ease}.tabs button:hover{color:#d9eef0!important;background:rgba(255,255,255,.04)!important;border-color:rgba(115,215,210,.1)!important;transform:translateY(-1px)}.tabs button.active{background:linear-gradient(180deg,rgba(82,211,197,.18),rgba(55,168,171,.08))!important;color:#91f1dc!important;border-color:rgba(100,229,208,.34)!important;box-shadow:0 8px 18px rgba(45,214,192,.11),inset 0 1px 0 rgba(255,255,255,.06)}.tabs button:nth-child(2).active{color:#8ad9ff!important;border-color:rgba(96,190,255,.35)!important}.tabs button:nth-child(3).active{color:#ffcf8f!important;border-color:rgba(255,189,111,.34)!important}.tabs button:nth-child(4).active{color:#d9b1ff!important;border-color:rgba(202,155,255,.34)!important}.tabs button:nth-child(5).active{color:#9fd0ff!important;border-color:rgba(110,169,255,.34)!important}
.premium-info-strip{max-width:1560px;margin:0 auto;padding:0 30px 28px;display:grid;grid-template-columns:1fr 1.3fr 1fr;gap:10px}.premium-info-strip article{padding:13px 14px;border:1px solid rgba(108,207,210,.13);border-radius:13px;background:linear-gradient(145deg,rgba(9,25,35,.72),rgba(6,17,25,.82));box-shadow:inset 0 1px 0 rgba(255,255,255,.025)}.premium-info-strip span{display:block;color:#61d9c5;font-size:8px;font-weight:900;letter-spacing:.14em}.premium-info-strip b{display:block;margin-top:6px;color:#d8eaed;font-size:10px}.premium-info-strip small{display:block;margin-top:4px;color:#708a96;font-size:8px;line-height:1.5}.status-dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:#63e3c1;box-shadow:0 0 10px rgba(99,227,193,.6);margin-right:5px}
.cs-foot{max-width:1560px!important;padding:0 30px 22px!important;color:#5d7682!important;font-size:8px!important;letter-spacing:.04em!important;border-top:1px solid rgba(112,205,209,.09);padding-top:12px!important}
.cs-light #urbion-championship-shell{--u-bg:#f7fbfc;--u-panel:#fff;--u-panel2:#eff8fa;--u-line:#d7e6ea;--u-text:#17303c;--u-muted:#63808a;background:radial-gradient(800px 420px at 80% 0%,rgba(28,181,220,.10),transparent 60%),radial-gradient(600px 420px at 10% 90%,rgba(57,193,155,.09),transparent 62%),linear-gradient(180deg,#f8fcfd,#edf6f8 55%,#fff)!important;color:#17303c!important}.cs-light .cs-head{background:rgba(250,253,254,.92)!important;border-bottom-color:#d9e7ea!important}.cs-light .map-panel,.cs-light .card,.cs-light .persistent-case{background:linear-gradient(145deg,#fff,#f2f8fa)!important;border-color:#d5e4e8!important;color:#17303c!important}.cs-light .panel-head{background:linear-gradient(180deg,#fff,#f4f9fa)}.cs-light .persistent-layers{background:linear-gradient(180deg,#f7fbfc,#eef6f8)!important;border-left-color:#d9e7ea!important}.cs-light .fcc-layer-row{background:rgba(20,80,94,.015)!important;color:#415d67!important}.cs-light .fcc-layer-row input{background:#fff!important;border-color:#b9cfd6!important}.cs-light .persistent-case .form-grid input,.cs-light .persistent-case .form-grid select{background:#fff!important;color:#17303c!important;border-color:#bfd4da!important}.cs-light .tabs{background:rgba(246,251,252,.9)!important;border-color:#d6e5e9!important}.cs-light .tabs button{color:#5a737d!important}.cs-light .tabs button.active{background:#e9f8f6!important}.cs-light .premium-info-strip article{background:rgba(255,255,255,.86);border-color:#d7e6ea}.cs-light .premium-info-strip b{color:#17303c}.cs-light .premium-info-strip small{color:#607a85}.cs-light .online{background:#e9fbf7;color:#11856e!important}.cs-light .head-actions button{background:#fff!important;color:#36515c!important;border-color:#cbdde1!important}
@media(max-width:1250px){.cs-grid{grid-template-columns:minmax(0,1fr) 350px!important}.map-panel{grid-template-columns:minmax(0,1fr) 250px}}@media(max-width:1020px){.cs-grid{grid-template-columns:1fr!important}.intelligence{position:static!important;max-height:none!important;overflow:visible!important}.map-panel{grid-template-columns:1fr!important;grid-template-rows:auto 520px auto!important}.persistent-layers{grid-column:1!important;grid-row:3!important;border-left:0!important;border-top:1px solid rgba(105,211,210,.12)!important;max-height:270px!important}.premium-info-strip{grid-template-columns:1fr!important}.analysis{padding-left:16px!important;padding-right:16px!important}.cs-hero,.cs-grid{padding-left:16px!important;padding-right:16px!important}}@media(max-width:720px){.cs-head{padding:0 12px!important}.brand img{width:146px!important}.online{display:none!important}.head-actions button{min-width:48px!important}.cs-hero h1{font-size:34px!important}.hero-actions{flex-wrap:wrap}.map-panel{grid-template-rows:auto 430px auto!important}.panel-head{align-items:flex-start;flex-direction:column}.map-actions{justify-content:flex-start}.map-actions button{padding:7px 9px!important}.persistent-layers{max-height:310px!important}.two{grid-template-columns:1fr!important}.tabs{width:100%!important;overflow:auto}.tabs button{min-width:82px!important}.premium-info-strip{padding-left:16px;padding-right:16px}.cs-foot{padding-left:16px!important;padding-right:16px!important}}
@media(prefers-reduced-motion:reduce){#urbion-championship-shell *{scroll-behavior:auto!important;transition:none!important;animation:none!important;transform:none!important}}
`;document.head.appendChild(s)}
function syncTheme(){const light=document.body.classList.contains('cs-light');document.body.classList.toggle('fcc-light',light);const b=$('#cs-theme');if(b){b.textContent=light?'DARK':'LIGHT';b.title=light?'Switch to dark mode':'Switch to light mode';b.setAttribute('aria-label',b.title)}}
function syncLanguageButton(){const b=$('#cs-lang');if(!b)return;b.textContent=lang()==='bm'?'EN':'BM';b.title=lang()==='bm'?'Switch to English':'Tukar ke Bahasa Melayu';b.setAttribute('aria-label',b.title)}
function populateDevelopment(){const e=$('#cs-development');if(!e||e.dataset.v6dev)return;e.dataset.v6dev='1';const old=e.value;e.innerHTML='<option value="">'+t().selectDevelopment+'</option>'+developmentOptions.map(v=>`<option value="${v}">${v}</option>`).join('');if(old)e.value=old;const label=$$('#urbion-championship-shell label').find(x=>(x.childNodes[0]?.textContent||'').trim().startsWith('Development / Proposal'));if(label&&label.childNodes[0])label.childNodes[0].textContent=t().development+' ';e.addEventListener('change',()=>window.__URBION_PREMIUM_V6_SYNC__?.());}
function moveCaseBuilder(){const r=root(),d=$('#cs-drawer'),i=$('.intelligence',r);if(!r||!d||!i)return;if(d.parentElement!==i)i.appendChild(d);d.classList.add('persistent-case');$('#cs-close')?.setAttribute('aria-hidden','true');$('#cs-close')?.setAttribute('tabindex','-1');setTimeout(()=>window.__URBION_FCC_MAP__?.invalidateSize?.(),100)}
function decorateLayerRail(){const d=$('#cs-layer-drawer');if(!d||d.dataset.premiumV6)return;d.dataset.premiumV6='1';d.classList.add('persistent-layers');const labels=$$('label',d);labels.forEach((row,idx)=>{row.classList.add('fcc-layer-row');const input=$('input',row);const small=$('small',row);const txt=(small?.textContent||'').trim()||'MAP';row.dataset.group=txt;row.dataset.index=idx+1;row.dataset.layerId=input?.dataset.layer||'';input?.setAttribute('aria-label',(row.textContent||'').trim())});const head=document.createElement('div');head.className='premium-layer-head';head.innerHTML=`<div><b>${t().layers}</b><small>${t().layersSub}</small></div><strong id="premium-layer-count">0</strong>`;d.prepend(head);const foot=document.createElement('div');foot.className='premium-layer-foot';foot.innerHTML='<span>●</span><small>i-Plan WMS · Source-labeled evidence</small>';d.appendChild(foot);updateLayerCount()}
function updateLayerCount(){const d=$('#cs-layer-drawer'),c=$('#premium-layer-count');if(!d||!c)return;c.textContent=$$('input[data-layer]:checked',d).length}
function addInfoStrip(){const r=root();if(!r||$('#premium-info-strip'))return;const tabs=$('.analysis',r)||$('#cs-analysis',r);if(!tabs)return;const strip=document.createElement('section');strip.id='premium-info-strip';strip.className='premium-info-strip';strip.innerHTML=`<article><span>${t().about}</span><b>URBION HORIZON</b><small>Planner decision-support workspace connecting spatial context, evidence and explainable decisions.</small></article><article><span>${t().sources}</span><b>i-Plan · JUPEM · JPS · MyEQMS · MyGEMS</b><small>Live availability varies by configured service and source response.</small></article><article><span>${t().status}</span><b><i class="status-dot"></i> RUNTIME ONLINE</b><small>${t().sourceBound} · ${t().browser}</small></article>`;tabs.insertAdjacentElement('afterend',strip)}
function styleLayerCategories(){const d=$('#cs-layer-drawer');if(!d)return;$$('.fcc-layer-row',d).forEach(row=>{const g=(row.dataset.group||'').toLowerCase();row.style.setProperty('--layer-accent',g.includes('risk')?'#ffb86b':g.includes('ecology')?'#6fe3b5':g.includes('heritage')?'#d19af8':g.includes('housing')?'#6dc9ff':g.includes('terrain')?'#b0c1cc':'#63deda')})}
function setupBaseMap(){const m=window.__URBION_FCC_MAP__;if(!m||!window.L||m.__premiumV6Base)return;m.__premiumV6Base=true;window.__URBION_PREMIUM_BASES__=window.__URBION_PREMIUM_BASES__||{};const B=window.__URBION_PREMIUM_BASES__;B.street=B.street||L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'});B.light=B.light||L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:20,attribution:'© OpenStreetMap © CARTO'});B.dark=B.dark||L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:20,attribution:'© OpenStreetMap © CARTO'});B.sat=B.sat||L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'© Esri'});B.terrain=B.terrain||L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'});const set=k=>{Object.values(B).forEach(x=>{if(m.hasLayer(x))m.removeLayer(x)});B[k].addTo(m);$$('[data-base]',r()).forEach(x=>x.classList.toggle('active',x.dataset.base===k));window.__URBION_FCC_BASE_TILE__=B[k];m.invalidateSize()};$$('[data-base]',r()).forEach(b=>{if(b.dataset.boundV6)return;b.dataset.boundV6='1';b.onclick=e=>set(e.currentTarget.dataset.base)});B.street.addTo(m);set('street')}
function mapLayerDirect(id,on){const m=window.__URBION_FCC_MAP__;if(!m||!window.L)return;window.__URBION_WMS__=window.__URBION_WMS__||{};const code=({Johor:'01',Kedah:'02',Kelantan:'03',Melaka:'04','Negeri Sembilan':'05',Pahang:'06','Pulau Pinang':'07',Perak:'08',Perlis:'09',Selangor:'10',Terengganu:'11',Sabah:'12',Sarawak:'13','Wilayah Persekutuan':'14',Labuan:'15',Putrajaya:'16'}[$('#cs-state')?.value]||'04');const names={'iplan-current':`iplan:gunatanah_semasa_${code}`,'iplan-zoning':`iplan:gunatanah_zoning_${code}`,'iplan-committed':`iplan:gunatanah_komited_${code}`,'iplan-rfn':'iplan:rfn','iplan-flood':'iplan:banjir','iplan-disaster-risk':'iplan:risiko_bencana','iplan-ksas':'iplan:ksas','iplan-cfs':'iplan:cfs','iplan-ecology':'iplan:rangkaian_ekologi','iplan-heritage':'iplan:warisan','iplan-affordable-housing':'iplan:rumah_mampu_milik','iplan-topography':'iplan:topo'};const old=window.__URBION_WMS__[id];if(old&&m.hasLayer(old))m.removeLayer(old);if(!on){delete window.__URBION_WMS__[id];updateLayerCount();return}const name=names[id];if(!name)return;const layer=L.tileLayer.wms('https://iplan.planmalaysia.gov.my/geoserver/iplan/wms',{layers:name,format:'image/png',transparent:true,version:'1.1.1',opacity:id==='iplan-current'?.72:.66,attribution:'PLANMalaysia · i-Plan'});layer.addTo(m);window.__URBION_WMS__[id]=layer;updateLayerCount()}
function bindLayers(){const d=$('#cs-layer-drawer');if(!d||d.dataset.v6change)return;d.dataset.v6change='1';d.addEventListener('change',e=>{const i=e.target;if(!(i instanceof HTMLInputElement)||!i.matches('[data-layer]'))return;mapLayerDirect(i.dataset.layer,i.checked);i.closest('.fcc-layer-row')?.classList.toggle('is-on',i.checked);updateLayerCount()})}
function normalizeLayerMarkup(){const d=$('#cs-layer-drawer');if(!d)return;$$('label',d).forEach(row=>{const i=$('input',row);if(!i||!i.dataset.layer)return;row.classList.add('fcc-layer-row');row.dataset.layerId=i.dataset.layer});styleLayerCategories()}
function enhanceTabs(){const r=root(),bar=$('.tabs',r);if(!bar)return;bar.classList.add('premium-tabs');$$('button',bar).forEach((b,i)=>{b.dataset.tabIndex=i+1;b.title=(b.textContent||'').trim();b.setAttribute('aria-label',b.title)})}
function polishControls(){const r=root();if(!r)return;$$('button',r).forEach(b=>{if(!b.title&&(b.textContent||'').trim())b.title=(b.textContent||'').trim()});$('#cs-theme')?.classList.add('premium-icon-control');$('#cs-lang')?.classList.add('premium-lang-control');$('#cs-run')?.classList.add('premium-run-control');$('#cs-next')?.classList.add('premium-run-control');$('#cs-reset')?.classList.add('premium-secondary-control');$('#cs-save')?.classList.add('premium-run-control')}
function keepCaseVisible(){const d=$('#cs-drawer');if(d&&!d.classList.contains('persistent-case'))d.classList.add('persistent-case')}
function sync(){window.__URBION_PREMIUM_V6_SYNC__=()=>{try{const ids=['project_name','lat','lon','state','pbt','district','landuse','category','activity','development','ratio'];const n=ids.filter(id=>String($('#cs-'+id)?.value||'').trim()).length;const pct=Math.round(n/ids.length*100)+'%';const e=$('#cs-ready');if(e)e.textContent=pct}catch{}};window.__URBION_PREMIUM_V6_SYNC__()}
function refresh(){installStyles();moveCaseBuilder();normalizeLayerMarkup();decorateLayerRail();bindLayers();enhanceTabs();polishControls();syncTheme();syncLanguageButton();populateDevelopment();addInfoStrip();setupBaseMap();keepCaseVisible();window.__URBION_PREMIUM_V6_SYNC__?.();setTimeout(()=>{window.__URBION_FCC_MAP__?.invalidateSize?.();updateLayerCount()},150)}
function observe(){const r=root();if(!r||r.__v6obs)return;r.__v6obs=true;const mo=new MutationObserver(()=>{moveCaseBuilder();normalizeLayerMarkup();styleLayerCategories();keepCaseVisible();syncTheme();updateLayerCount()});mo.observe(r,{childList:true,subtree:true})}
function boot(){const r=root();if(!r)return setTimeout(boot,120);refresh();observe();setTimeout(refresh,500);setTimeout(refresh,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
