/* URBION HORIZON — Road Access Intelligence UI owner.
   One isolated drawer; consumes the canonical /road-intelligence contract only.
   No second map engine, no second planning engine, no fabricated road/centre data. */
(()=>{
'use strict';
if(window.__URBION_ROAD_INTELLIGENCE_OWNER_V1__) return;
window.__URBION_ROAD_INTELLIGENCE_OWNER_V1__=true;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function style(){if($('urbionRoadStyle'))return;const s=document.createElement('style');s.id='urbionRoadStyle';s.textContent='.urbion-road-launch{width:100%;margin-top:6px;border:1px solid rgba(47,225,233,.22);background:rgba(47,225,233,.05);border-radius:8px;padding:8px 9px;text-align:left;font-size:7px}.urbion-road-launch:hover{border-color:rgba(47,225,233,.55)}.urbion-road-drawer{position:fixed;top:70px;right:0;width:min(430px,94vw);height:calc(100vh - 70px);z-index:1700;transform:translateX(105%);transition:transform .2s ease;border-left:1px solid var(--line);background:#061820;box-shadow:-20px 0 60px rgba(0,0,0,.35);overflow:auto;padding:14px}.urbion-road-drawer.open{transform:translateX(0)}.light .urbion-road-drawer{background:#fbfeff}.urbion-road-drawer .rh{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:10px}.urbion-road-drawer h2{margin:0;font:700 16px Space Grotesk,system-ui,sans-serif}.urbion-road-close{border:1px solid var(--line);background:transparent;border-radius:8px;padding:6px 8px;font-size:8px}.urbion-road-section{border:1px solid var(--line);border-radius:9px;padding:9px;margin-bottom:8px}.urbion-road-title{font-size:7px;letter-spacing:.08em;color:var(--cyan);margin-bottom:7px}.urbion-road-row{display:flex;justify-content:space-between;gap:10px;padding:5px 0;border-bottom:1px solid rgba(45,85,100,.18);font-size:7px}.urbion-road-row:last-child{border-bottom:0}.urbion-road-row span:last-child{text-align:right}.urbion-road-muted{color:var(--muted)}.urbion-road-pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:3px 6px;font-size:6px}.urbion-road-rings{display:grid;grid-template-columns:repeat(5,1fr);gap:4px}.urbion-road-ring{border:1px solid var(--line);border-radius:7px;padding:7px 4px;text-align:center;font-size:7px}.urbion-road-note{font-size:6.4px;line-height:1.5;color:var(--muted);margin-top:6px}.urbion-road-spinner{font-size:7px;color:var(--muted);padding:8px 0}.urbion-road-error{font-size:7px;color:var(--bad);padding:8px 0}';document.head.appendChild(s)}
function mount(){style();if($('urbionRoadDrawer'))return;const d=document.createElement('aside');d.id='urbionRoadDrawer';d.className='urbion-road-drawer';d.innerHTML='<div class="rh"><h2>ROAD ACCESS</h2><button type="button" class="urbion-road-close" id="urbionRoadClose">CLOSE</button></div><div id="urbionRoadBody"></div>';document.body.appendChild(d);$('urbionRoadClose')?.addEventListener('click',close);}
function coords(){const pairs=[['site_lat','site_lon'],['cs-lat','cs-lon'],['cs_lat','cs_lon']];for(const [a,b] of pairs){const lat=Number($(a)?.value),lon=Number($(b)?.value);if(Number.isFinite(lat)&&Number.isFinite(lon))return{lat,lon}}const p=window.URBION_LAST?.canonical_evidence_packet?.site||window.URBION_LAST?.site||{};const lat=Number(p.latitude),lon=Number(p.longitude);return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon}:null}
function value(v){return v===null||v===undefined||v===''?'—':esc(v)}
function mergeCanonical(data){const last=window.URBION_LAST;const packet=last?.canonical_evidence_packet;if(!packet)return false;packet.evidence=packet.evidence||{};packet.evidence.mobility=packet.evidence.mobility||{};packet.evidence.mobility.road_intelligence=data;packet.mobility=packet.mobility||{};packet.mobility.road_intelligence=data;last.road_intelligence=data;try{window.dispatchEvent(new CustomEvent('urbion:road-ready',{detail:{data}}))}catch(_){ }return true}
function render(data){const body=$('urbionRoadBody');if(!body)return;const ra=data?.road_access?.nearest_road||{};const cp=Array.isArray(data?.centre_proximity)?data.centre_proximity:[];const rings=Array.isArray(data?.radius_analysis)?data.radius_analysis:[];const roadState=ra.evidence_status||'UNVERIFIED';const roadHtml='<div class="urbion-road-section"><div class="urbion-road-title">NEAREST ROAD</div><div class="urbion-road-row"><span>Road</span><span>'+value(ra.name)+'</span></div><div class="urbion-road-row"><span>Distance</span><span>'+value(ra.distance_km!==null&&ra.distance_km!==undefined?ra.distance_km+' km':null)+'</span></div><div class="urbion-road-row"><span>Hierarchy</span><span>'+value(ra.hierarchy)+'</span></div><div class="urbion-road-row"><span>Evidence</span><span class="urbion-road-pill">'+esc(roadState)+'</span></div></div>';const centresHtml='<div class="urbion-road-section"><div class="urbion-road-title">CENTRE PROXIMITY</div>'+(cp.length?cp.map(x=>'<div class="urbion-road-row"><span>'+value(x.name)+'</span><span>'+value(x.distance_km!==null&&x.distance_km!==undefined?x.distance_km+' km':null)+'</span></div>').join(''):'<div class="urbion-road-muted" style="font-size:7px">No source-backed centres supplied.</div>')+'</div>';const ringsHtml='<div class="urbion-road-section"><div class="urbion-road-title">RADIUS ANALYSIS</div><div class="urbion-road-rings">'+rings.map(x=>'<div class="urbion-road-ring"><b>'+value(x.radius_km)+' km</b><div style="font-size:5.8px;color:var(--muted);margin-top:3px">'+(Array.isArray(x.centres_inside)?x.centres_inside.length:0)+' centres</div></div>').join('')+'</div><div class="urbion-road-note">Radius analysis is a spatial proximity screen. It is not a statutory accessibility threshold.</div></div>';const chain=Array.isArray(data?.road_access?.hierarchy_chain)?data.road_access.hierarchy_chain:[];const chainHtml='<div class="urbion-road-section"><div class="urbion-road-title">NETWORK CONTEXT</div><div style="font-size:7px">'+(chain.length?chain.map(x=>'<span class="urbion-road-pill">'+esc(x)+'</span>').join(' <span style="color:var(--muted)">→</span> '):'<span class="urbion-road-muted">Hierarchy chain unavailable.</span>')+'</div><div class="urbion-road-note">'+value(data?.evidence_boundary)+'</div></div>';body.innerHTML=roadHtml+centresHtml+ringsHtml+chainHtml}
async function open(){mount();const d=$('urbionRoadDrawer');d?.classList.add('open');const body=$('urbionRoadBody');if(!body)return;body.innerHTML='<div class="urbion-road-spinner">Analysing road & centre context…</div>';try{const c=coords();if(!c)throw Error('Valid site coordinates are required');const r=await fetch('/road-intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({site_lat:c.lat,site_lon:c.lon})});const data=await r.json();if(!r.ok)throw Error(data?.message||data?.detail?.message||data?.detail||'Road intelligence unavailable');mergeCanonical(data);window.URBION_ROAD_LAST=data;render(data)}catch(e){body.innerHTML='<div class="urbion-road-error">'+esc(e.message||e)+'</div>'}}
window.URBION_ROAD_OPEN=open;
window.URBION_ROAD_COORDS=coords;
function close(){$('urbionRoadDrawer')?.classList.remove('open')}
function bind(){mount();const host=document.querySelector('.right');if(!host)return;if(!$('urbionRoadOpen')){const card=document.createElement('div');card.className='card';card.id='urbionRoadLaunch';card.innerHTML='<div class="cardhead"><h3>ROAD ACCESS</h3><span class="tiny">SPATIAL CONTEXT</span></div><div class="tiny">Road hierarchy · nearest road · centres · radius rings</div><button type="button" class="urbion-road-launch" id="urbionRoadOpen">OPEN ROAD ACCESS ANALYSIS</button>';host.prepend(card);$('urbionRoadOpen')?.addEventListener('click',open)}}
function boot(){let n=0;const t=setInterval(()=>{bind();if(++n>=120)clearInterval(t)},100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();