/* MASTER-281: public-source evidence workspace — linked public GIS and environmental source surface. */
(()=>{
'use strict';
if(window.__URBION_PUBLIC_SOURCE_BRIDGE_V281__)return;
window.__URBION_PUBLIC_SOURCE_BRIDGE_V281__=1;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(u,o)=>{const r=await fetch(u,o);if(!r.ok)throw Error(u+' · '+r.status);return r.json()};
const p=()=>({site_lat:+($('dash-lat')?.value||2.285),site_lon:+($('dash-lon')?.value||102.196),state:$('dash-state')?.value||'Melaka',district:'Melaka Tengah'});
const style=document.createElement('style');style.textContent=`.v281-source{border:1px solid #244452;border-radius:12px;background:#08161e;padding:14px;margin-top:10px}.v281-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.v281-card{border:1px solid #203b46;border-radius:10px;padding:10px;background:#07131b}.v281-card b{display:block;color:#67e8b7;font-size:11px}.v281-card small{display:block;color:#78919d;line-height:1.45;margin-top:5px}.v281-state{display:inline-block;margin-top:7px;font-size:8px;font-weight:900;letter-spacing:.08em}.v281-good{color:#67e8b7}.v281-warn{color:#ffd27a}.v281-bad{color:#ff8292}.v281-btn{display:inline-block;border:1px solid #284654;background:#07131b;color:#edf7f5;border-radius:8px;padding:8px 10px;font:800 9px Inter;cursor:pointer;margin:5px 5px 0 0;text-decoration:none}.v281-table{width:100%;border-collapse:collapse;font-size:9px;margin-top:8px}.v281-table th,.v281-table td{padding:7px;border-bottom:1px solid #19313b;text-align:left;vertical-align:top}.v281-table th{color:#67e8b7}@media(max-width:1000px){.v281-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.v281-grid{grid-template-columns:1fr}}`;
document.head.appendChild(style);
function add(){const gis=document.querySelector('#uhd-gis .v276-grid');if(!gis||$('v281-sources'))return;const card=document.createElement('div');card.id='v281-sources';card.className='v276-card full v281-source';card.innerHTML=`<h3>PUBLIC-SOURCE INTELLIGENCE</h3><div class="v276-muted">Live public-source evidence is connected to the active site. A successful response means the source contract returned data; it is not statutory approval.</div><div class="v281-grid"><div class="v281-card"><b>PLANMalaysia · i-PLAN</b><small>Current land use, zoning, cadastral, contour and planning context.</small><span id="v281-iplan" class="v281-state v281-warn">CHECKING</span></div><div class="v281-card"><b>JPS · Public Infobanjir</b><small>Water level, rainfall, station status, trends and forecast pages.</small><span id="v281-jps" class="v281-state v281-warn">CHECKING</span></div><div class="v281-card"><b>JMG · MyGEMS</b><small>Lithology, faults, geophysics, groundwater, minerals and marine geology.</small><span id="v281-jmg" class="v281-state v281-warn">CHECKING</span></div><div class="v281-card"><b>MYGEOS / MyGDI</b><small>National geospatial sharing and UPI context.</small><span id="v281-mygdi" class="v281-state v281-warn">REFERENCE</span></div></div><div><button id="v281-check" class="v281-btn">RUN PUBLIC SOURCE CHECK</button><button id="v281-evidence" class="v281-btn">BUILD LINKED EVIDENCE</button><button id="v281-mapcheck" class="v281-btn">CHECK MAP SOURCES</button></div><div id="v281-out" class="v281-card" style="margin-top:8px">Ready.</div><div class="v276-muted" style="margin-top:8px">Official source links: i-PLAN · SCHARMS ArcGIS REST · Public Infobanjir · MyGEMS · MyGeoportal.</div></div>`;gis.appendChild(card);$('v281-check').onclick=check;$('v281-evidence').onclick=evidence;$('v281-mapcheck').onclick=mapCheck;check()}
async function check(){const o=$('v281-out');if(!o)return;const q=p();o.textContent='Checking public source availability…';const jobs=[['i-PLAN',()=>api('/iplan/context?site_lat='+q.site_lat+'&site_lon='+q.site_lon+'&state='+encodeURIComponent(q.state))],['JPS environment',()=>api('/environment/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(q)})],['JMG MyGEMS',()=>api('/public-sources/mygems?lat='+q.site_lat+'&lon='+q.site_lon)],['JPS Public Infobanjir',()=>api('/public-sources/infobanjir?state='+encodeURIComponent(q.state))],['MyGeoportal',()=>api('/public-sources/mygdi')]];const rs=await Promise.allSettled(jobs.map(x=>x[1]()));$('v281-iplan').textContent=rs[0].status==='fulfilled'?'LIVE / DATA':'FAILED';$('v281-jps').textContent=rs[1].status==='fulfilled'?'LIVE / DATA':'FAILED';$('v281-jmg').textContent=rs[2].status==='fulfilled'?'LIVE / DATA':'FAILED';$('v281-mygdi').textContent=rs[4].status==='fulfilled'?'LIVE / DATA':'REFERENCE';o.innerHTML=rs.map((r,i)=>`<div><b>${esc(jobs[i][0])}</b> · <span class="${r.status==='fulfilled'?'v281-good':'v281-bad'}">${r.status==='fulfilled'?'RESPONDED':'FAILED'}</span></div>`).join('')+'<small>Browser UI reads the server-side public-source bridge, avoiding a false claim that cross-domain browser requests are directly available.</small>'}
async function evidence(){const o=$('v281-out');if(!o)return;const q=p();o.textContent='Building site-linked evidence…';try{const x=await api('/public-sources/site-evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(q)});const rows=Object.entries(x.sources||{});o.innerHTML='<table class="v281-table"><thead><tr><th>Source</th><th>Site-linked result</th></tr></thead><tbody>'+rows.map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(JSON.stringify(v).slice(0,1600))}</td></tr>`).join('')+'</tbody></table><small>Chain: site → public sources → evidence → planning assessment. Data freshness and statutory status remain source-dependent.</small>'}catch(e){o.innerHTML='<span class="v281-bad">Evidence build failed · '+esc(e.message)+'</span>'}}
async function mapCheck(){const o=$('v281-out');if(!o)return;o.textContent='Checking configured GIS services…';try{const x=await api('/public-sources/map-services');o.innerHTML='<table class="v281-table"><thead><tr><th>Source</th><th>Service</th><th>Status</th></tr></thead><tbody>'+Object.entries(x.services||{}).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v.url||'')}</td><td class="v281-good">${esc(v.status||'CONFIGURED')}</td></tr>`).join('')+'</tbody></table>'}catch(e){o.innerHTML='<span class="v281-bad">Map source check failed · '+esc(e.message)+'</span>'}}
function links(){const layers=$('dash-layers');if(!layers||layers.dataset.v281)return;layers.dataset.v281='1';const box=document.createElement('div');box.className='v281-source';box.innerHTML='<b>OFFICIAL SOURCE ACCESS</b><small>Open the authoritative service documentation or portal.</small><div><a class="v281-btn" target="_blank" rel="noopener" href="https://iplan.planmalaysia.gov.my/">i-PLAN</a><a class="v281-btn" target="_blank" rel="noopener" href="https://scharms.planmalaysia.gov.my/arcgis/rest/services/iPLAN/GTsemasa_04/MapServer">i-PLAN Current Land Use REST</a><a class="v281-btn" target="_blank" rel="noopener" href="https://publicinfobanjir.water.gov.my/">Public Infobanjir</a><a class="v281-btn" target="_blank" rel="noopener" href="https://mygems.jmg.gov.my/server/rest/services/GeologiAsas/Major_Fault/MapServer">MyGEMS Major Fault</a><a class="v281-btn" target="_blank" rel="noopener" href="https://www.mygeoportal.gov.my/">MyGeoportal</a></div>';layers.parentElement.appendChild(box)}
function load283(){if(window.__URBION_PUBLIC_SPATIAL_LOADER_V283__)return;window.__URBION_PUBLIC_SPATIAL_LOADER_V283__=1;const s=document.createElement('script');s.src='/urbion_public_spatial_v283.js';s.async=false;s.onload=()=>console.info('URBION MASTER-283 spatial intelligence loaded');s.onerror=()=>console.warn('URBION MASTER-283 spatial intelligence unavailable');document.head.appendChild(s)}
function boot(){add();links();load283()}
setTimeout(boot,400);setTimeout(boot,1400);new MutationObserver(boot).observe(document.body,{childList:true,subtree:true});
})();
