(()=>{
  const $=id=>document.getElementById(id);
  const steps=[['01','SITE','Define'],['02','MAP','Context'],['03','ANALYSE','Run'],['04','WHY','Explain'],['05','WHAT-IF','Test'],['06','DECISION','Decide'],['07','ACTION','Next']];
  const targets=['#lat','#spatial-studio','#intel-upgrade','.iu-score','#intel-upgrade','#intel-upgrade','.judge'];
  function style(){if($('urbion-workflow-style'))return;document.head.insertAdjacentHTML('beforeend',`<style id="urbion-workflow-style">#urbion-workflow{margin:0 0 14px;padding:10px 12px;border:1px solid var(--line);border-radius:14px;background:linear-gradient(135deg,#091722,#07131c);position:relative;z-index:2}.uw-track{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.uw-step{position:relative;padding:9px 7px;border:1px solid #17303e;border-radius:9px;background:#07131c;color:#7892a3;text-align:left;cursor:pointer;transition:.18s}.uw-step b{display:block;font-size:7px;letter-spacing:.08em;color:#5f7788}.uw-step strong{display:block;margin-top:3px;font:700 10px 'Space Grotesk';color:#cfe0e8}.uw-step span{display:block;margin-top:2px;font-size:6px}.uw-step.active{border-color:var(--a);background:#5ee7c20b;box-shadow:inset 0 0 0 1px #5ee7c214}.uw-step.active b,.uw-step.active strong{color:var(--a)}.uw-step.done{border-color:#315347}.uw-step.done b{color:#6ee7b7}.uw-status{display:flex;justify-content:space-between;gap:10px;margin-top:7px;color:#8da5b6;font-size:7px}.uw-status b{color:var(--a)}.uw-focus{outline:2px solid var(--a);outline-offset:4px;box-shadow:0 0 0 6px #5ee7c214!important}@media(max-width:760px){.uw-track{grid-template-columns:repeat(4,1fr)}.uw-step:nth-child(n+5){display:none}}@media(max-width:460px){.uw-track{grid-template-columns:repeat(2,1fr)}.uw-step:nth-child(n+3){display:none}}</style>`)}
  function jump(view,i){const btn=document.querySelector(`[data-view="${view}"]`);if(btn)btn.click();setTimeout(()=>focus(i),80)}
  function focus(i){const target=document.querySelector(targets[i]);if(!target)return;document.querySelectorAll('.uw-focus').forEach(el=>el.classList.remove('uw-focus'));target.scrollIntoView({behavior:'smooth',block:'center'});target.classList.add('uw-focus');clearTimeout(window.__urbionWorkflowFocusTimer);window.__urbionWorkflowFocusTimer=setTimeout(()=>target.classList.remove('uw-focus'),1400)}
  function mount(){if($('urbion-workflow'))return;const nav=$('#nav');if(!nav)return;const el=document.createElement('section');el.id='urbion-workflow';el.innerHTML=`<div class="uw-track">${steps.map((s,i)=>`<button class="uw-step ${i===0?'active':''}" data-uw-view="${s[1].toLowerCase()}"><b>${s[0]}</b><strong>${s[1]}</strong><span>${s[2]}</span></button>`).join('')}</div><div class="uw-status"><span>DECISION WORKFLOW</span><b id="uw-current">01 · SITE DEFINITION</b></div>`;nav.parentNode.insertBefore(el,nav);el.querySelectorAll('[data-uw-view]').forEach((b,i)=>b.onclick=()=>jump(['command','command','command','command','scenarios','decision','judge'][i],i));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>activate(b.dataset.view)));activate('command')}
  function activate(view){const map={command:0,evidence:1,scenarios:4,decision:5,judge:6};const i=map[view]??0;document.querySelectorAll('.uw-step').forEach((b,n)=>{b.classList.toggle('active',n===i);b.classList.toggle('done',n<i)});const s=steps[i]||steps[0];const c=$('uw-current');if(c)c.textContent=`${s[0]} · ${s[1]} ${s[2].toUpperCase()}`)}
  function markAnalysed(){document.querySelectorAll('.uw-step').forEach((b,i)=>b.classList.toggle('done',i<4));activate('command')}
  function bind(){window.addEventListener('urbion:analysis',markAnalysed);window.addEventListener('urbion:site-change',()=>{document.querySelectorAll('.uw-step').forEach(b=>b.classList.remove('done'));activate('command')})}
  function boot(){style();mount();bind()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();