/* URBION HORIZON — canonical analysis + judge decision/evidence presentation owner.
   Reuses the deterministic packet; adds no alternative scoring engine. */
(()=>{
'use strict';
if(window.__URBION_ANALYSIS_SUMMARY_OWNER_V5__)return;
window.__URBION_ANALYSIS_SUMMARY_OWNER_V5__=true;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function packet(){return window.URBION_LAST?.canonical_evidence_packet||null}
function host(){return document.querySelector('.right')||document.querySelector('.layout > :last-child')}
function stateChip(state){const s=String(state||'UNVERIFIED').toUpperCase();return `<span class="uas-evidence-chip uas-${esc(s.toLowerCase())}">${esc(s.replaceAll('_',' '))}</span>`}
function stateForIndicator(item,p){if(item?.evidence_state)return item.evidence_state;if(item?.evidence)return item.evidence;if(item?.verified===true)return 'VERIFIED';if(item?.score!=null)return 'CALCULATED';return 'UNVERIFIED'}
function style(){if($('urbionAnalysisSummaryStyleV5'))return;const s=document.createElement('style');s.id='urbionAnalysisSummaryStyleV5';s.textContent=`
.urbion-analysis-summary{border:1px solid rgba(47,225,233,.20);border-radius:10px;padding:10px;margin-bottom:8px;background:linear-gradient(145deg,rgba(7,29,41,.96),rgba(3,15,22,.98))}.light .urbion-analysis-summary{background:#fff}.uas-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.uas-title{font-size:8px;font-weight:900;letter-spacing:.07em}.uas-sub{font-size:6px;color:var(--muted)}.uas-grid{display:grid;grid-template-columns:86px 1fr;gap:10px;align-items:center;margin-top:9px}.uas-donut{width:82px;height:82px;border-radius:50%;display:grid;place-items:center;position:relative;background:#173846}.uas-donut:after{content:'';position:absolute;inset:9px;border-radius:50%;background:#061820}.light .uas-donut:after{background:#fff}.uas-donut b{position:relative;z-index:1;font:800 18px Space Grotesk,system-ui,sans-serif}.uas-bars{display:flex;flex-direction:column;gap:6px}.uas-bar-row{display:grid;grid-template-columns:76px 1fr auto;gap:6px;align-items:center;font-size:6.5px}.uas-bar-track{height:5px;border-radius:99px;background:#12303d;overflow:hidden}.uas-bar-fill{height:100%;background:linear-gradient(90deg,var(--mint),var(--cyan));border-radius:99px}.uas-status{margin-top:8px;font-size:6.5px;color:var(--muted)}.uas-status strong{color:var(--cyan)}.uas-ai{margin-top:9px;padding:9px;border:1px solid rgba(47,225,233,.16);border-radius:9px;background:rgba(47,225,233,.04)}.uas-ai-head{display:flex;justify-content:space-between;gap:8px}.uas-ai-title{font-size:7px;font-weight:900;letter-spacing:.06em}.uas-ai-body{font-size:7px;line-height:1.55;margin-top:6px;color:#c1d4db}.light .uas-ai-body{color:#536b76}.uas-ai-tag{font-size:5.8px;color:var(--muted)}.uas-actions{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:7px}.uas-action{border:1px solid var(--line);border-radius:7px;padding:6px;font-size:6.2px;background:#071923;color:var(--text)}.light .uas-action{background:#f5fafb}.uas-evidence-chip{display:inline-flex;align-items:center;border:1px solid var(--line);border-radius:999px;padding:3px 5px;font-size:4.8px;letter-spacing:.04em;white-space:nowrap}.uas-calculated{color:var(--cyan);border-color:rgba(47,225,233,.28)}.uas-source_context{color:var(--warn);border-color:rgba(255,203,93,.28)}.uas-verified{color:var(--good);border-color:rgba(72,223,170,.28)}.uas-user_provided{color:var(--blue);border-color:rgba(85,167,255,.28)}.uas-unverified{color:var(--muted);border-color:rgba(134,166,181,.24)}
.urbion-story-card{border:1px solid var(--line);border-radius:10px;background:linear-gradient(145deg,rgba(7,29,41,.96),rgba(3,15,22,.98));padding:10px;margin-bottom:8px}.light .urbion-story-card{background:#fff}.usc-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.usc-title{font-size:8px;font-weight:900;letter-spacing:.07em}.usc-sub{font-size:5.8px;color:var(--muted)}.usc-titlebar{margin-top:8px;padding-top:7px;border-top:1px solid rgba(45,85,100,.18);font-size:6px;letter-spacing:.08em;color:var(--cyan);font-weight:900}.usc-row{padding:6px 0;border-bottom:1px solid rgba(45,85,100,.15)}.usc-row b{display:block;font-size:6.8px}.usc-row span,.usc-row small{display:block;font-size:5.8px;color:var(--muted);line-height:1.4}.usc-pill{display:inline-block;padding:3px 6px;border:1px solid var(--line);border-radius:999px;font-size:5.5px;color:var(--muted);margin:2px 3px 0 0}.usc-ok{color:var(--good);border-color:rgba(72,223,170,.3)}.usc-warn{color:var(--warn);border-color:rgba(255,203,93,.3)}.usc-bad{color:var(--bad);border-color:rgba(255,129,117,.3)}.usc-note{margin-top:7px;padding:7px 8px;border-left:2px solid var(--cyan);background:rgba(47,225,233,.035);font-size:5.9px;line-height:1.45;color:#b9ccd3}.light .usc-note{color:#5d727d}
`;
 document.head.appendChild(s)}
function scoreColor(v){return v>=80?'var(--good)':v>=65?'var(--cyan)':'var(--warn)'}
async function refreshAi(){const input=typeof getInputs==='function'?getInputs():null;if(!input)return;try{const r=await fetch('/copilot/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assessment:input})});const d=await r.json();if(!r.ok)throw Error(d?.detail?.message||d?.detail||'AI unavailable');const ex=d.explanation||{};window.URBION_AI_LAST={provider:ex.provider||'LLM',status:ex.status||'READY',text:ex.text||String(ex),evidence_ledger:d.evidence_ledger||{},source:'bounded_copilot_explain'};render()}catch(e){const t=$('toast');if(t){t.textContent='AI answer unavailable; deterministic site analysis preserved';t.style.display='block';t.style.color='var(--bad)';setTimeout(()=>t.style.display='none',2400)}}}
function render(){const root=host();const p=packet();if(!root||!p?.site_analysis)return false;style();let card=$("urbionAnalysisSummary");if(!card){card=document.createElement('section');card.id='urbionAnalysisSummary';card.className='urbion-analysis-summary';card.dataset.owner='canonical';root.prepend(card)}const sa=p.site_analysis,score=Number(sa.score);const indicators=Array.isArray(sa.indicators)?sa.indicators:[];const pct=Number.isFinite(score)?Math.max(0,Math.min(100,score)):0;const degree=pct*3.6;const bars=indicators.slice(0,5).map(x=>{const v=x.score==null?null:Math.max(0,Math.min(100,Number(x.score)));return `<div class="uas-bar-row"><span>${esc(x.name)}</span><div class="uas-bar-track"><div class="uas-bar-fill" style="width:${v==null?0:v}%"></div></div><b>${v==null?'—':v}</b>${stateChip(stateForIndicator(x,p))}</div>`}).join('');const rec=sa.recommendation?.headline||sa.band||'REQUIRES FURTHER STUDY';const ai=window.URBION_AI_LAST;let aiText=ai?.text||'';if(!aiText)aiText='Run the canonical analysis to generate a planner-facing evidence summary.';const scoreState=(p.evidence_states||{}).site_analysis_score||'CALCULATED';const next=`<div class="uas-head"><span class="uas-title">SITE ANALYSIS · DECISION SNAPSHOT</span><span class="uas-sub">PRELIMINARY · NOT STATUTORY APPROVAL</span></div><div class="uas-grid"><div class="uas-donut" style="background:conic-gradient(${scoreColor(pct)} 0 ${degree}deg,#173846 ${degree}deg 360deg)"><b>${Number.isFinite(score)?score:'—'}%</b></div><div><div style="font-size:6.5px;color:var(--muted);margin-bottom:6px">SITE SUITABILITY ${stateChip(scoreState)}</div><div style="font:800 11px Space Grotesk;color:${scoreColor(pct)}">${esc(rec)}</div><div class="uas-status"><strong>${sa.score_coverage?.assessed_dimensions||0}/${sa.score_coverage?.total_dimensions||indicators.length}</strong> dimensions assessed · unverified dimensions excluded</div></div></div><div style="margin-top:9px" class="uas-bars">${bars}</div><div class="uas-ai"><div class="uas-ai-head"><span class="uas-ai-title">AI PLANNING ANSWER</span><span class="uas-ai-tag">${esc(ai?.provider||'BOUNDED COPILOT')}</span></div><div class="uas-ai-body">${esc(aiText)}</div><div class="uas-actions"><button class="uas-action" id="uasRefreshAi" type="button">REFRESH AI ANSWER</button><button class="uas-action" id="uasExplainEvidence" type="button">VIEW EVIDENCE TRACE</button></div></div>`;if(card.innerHTML!==next)card.innerHTML=next;const refresh=$('uasRefreshAi');if(refresh&&!refresh.dataset.bound){refresh.dataset.bound='1';refresh.addEventListener('click',()=>void refreshAi())}const explain=$('uasExplainEvidence');if(explain&&!explain.dataset.bound){explain.dataset.bound='1';explain.addEventListener('click',()=>{if(typeof evidenceModal==='function')evidenceModal()})}return true}
function reviewCount(p){const r=p?.review_gaps??p?.review_required??p?.assessment?.review_gaps??[];if(Array.isArray(r))return r.length;const n=Number(r);return Number.isFinite(n)?n:0}
function decisionRules(p){const a=p?.assessment||{};return Array.isArray(a.compliance_results)&&a.compliance_results.length?a.compliance_results:(Array.isArray(a.retrieved_rules)?a.retrieved_rules:[])}
function decisionScenarios(p){const s=p?.what_if||p?.evidence?.what_if||p?.scenario_intelligence||p?.assessment?.scenario_intelligence||{};const items=Array.isArray(s.ranked_scenarios)&&s.ranked_scenarios.length?s.ranked_scenarios:(Array.isArray(s.scenarios)?s.scenarios:[]);return {items,best:s.best_candidate||s.preferred_scenario||s.recommended_scenario||null}}
function liveSources(p){const e=p?.evidence||{};const out=[];for(const [label,key] of [['JPS rainfall','jps_rainfall'],['MyEQMS water','eqmp_water'],['Air quality','air_quality'],['MyGEMS lithology','mygems_lithology']]){const b=e?.stations?.[key]||e?.environment?.[key]||p?.live_station_evidence?.[key];if(!b)continue;const items=Array.isArray(b.stations)?b.stations:Array.isArray(b.features)?b.features:[];out.push({label,state:String(b.evidence_state||b.status||'SOURCE_CONTEXT').toUpperCase(),count:items.length,updated:b.last_updated||b.observed_at||b.last_updated_rainfall||b.query_time||b.timestamp||'timestamp not supplied',source:b.source||b.source_url||'canonical evidence packet'})}return out}
function klass(status){const s=String(status||'').toUpperCase();return s.includes('NON')||s.includes('FAIL')?'usc-bad':s.includes('REVIEW')||s.includes('VERIFY')||s.includes('UNVERIFIED')?'usc-warn':'usc-ok'}
function renderDecisionStory(){const root=host(),p=packet();if(!root)return false;let card=$("urbionDecisionStoryCard");if(!card){card=document.createElement('section');card.id='urbionDecisionStoryCard';card.className='urbion-story-card';root.appendChild(card)}if(!p){card.innerHTML='<div class="usc-head"><span class="usc-title">DECISION STORY</span><span class="usc-sub">WAITING FOR ANALYSIS</span></div><div class="usc-note">Run the canonical assessment to build the evidence-backed decision story.</div>';window.__URBION_DECISION_STORY_OWNER_V1__=true;return false}const a=p.assessment||{},rules=decisionRules(p).slice(0,4),sc=decisionScenarios(p),gaps=Array.isArray(p.review_gaps)?p.review_gaps:[],live=liveSources(p);const ruleHtml=rules.length?rules.map(r=>`<div class="usc-row"><b>${esc(r.rule_id||r.parameter||r.name||'Planning control')}</b><span>${esc(r.source||r.source_document||'Planning source')} → ${esc(r.proposed_value??r.value??'—')} → <em class="usc-pill ${klass(r.status)}">${esc(r.status||'REQUIRES REVIEW')}</em></span><small>${esc(r.reason||r.why||'Review against applicable planning control.')}</small></div>`).join(''):'<div class="usc-sub">No rule records surfaced in the canonical packet.</div>';const scHtml=sc.items.slice(0,3).map(s=>`<div class="usc-row"><b>${esc(s.name||s.id||'Scenario')}</b><span>${esc(s.status||s.final_status||'REVIEW')} · ${esc(s.decision_delta??'no delta supplied')}</span></div>`).join('')||'<div class="usc-sub">No scenario comparison executed yet.</div>';const liveHtml=live.length?live.map(x=>`<span class="usc-pill ${x.state==='VERIFIED'?'usc-ok':x.state.includes('ERROR')?'usc-bad':'usc-warn'}">${esc(x.label)} · ${esc(x.state)} · ${esc(x.updated)}</span>`).join(''):'<span class="usc-pill usc-warn">LIVE SOURCE CONTEXT · not returned</span>';const handoff=gaps.length?'REVIEW REQUIRED':'READY FOR PLANNER REVIEW';card.innerHTML=`<div class="usc-head"><span class="usc-title">DECISION STORY</span><span class="usc-sub">CANONICAL PACKET · READ-ONLY</span></div><div class="usc-note"><b>${esc(a.final_status||'REQUIRES REVIEW')} · ${esc(a.classification||'PLANNING CASE')}</b><br>Baseline is the canonical assessment. ${sc.best?`Preferred scenario signal: ${esc(typeof sc.best==='object'?(sc.best.name||sc.best.id||'candidate'):sc.best)}.`:'No preferred scenario is claimed yet.'}<br><small>STATUTORY VERIFICATION · ${esc(p.statutory_verification||'NOT_CLAIMED')}</small></div><div class="usc-titlebar">RULE → VALUE → RESULT → WHY</div>${ruleHtml}<div class="usc-titlebar">BASELINE → OPTIONS</div>${scHtml}<div class="usc-titlebar">LIVE EVIDENCE</div><div>${liveHtml}</div><div class="usc-note"><b>${handoff}</b><br>${gaps.length?gaps.slice(0,2).map(esc).join('<br>'):'No disclosed review blockers in the canonical packet.'}<br><small>DECISION AUTHORITY · ${esc(p.decision_authority||'NONE')} · PLANNER REVIEW ONLY</small></div>`;window.__URBION_DECISION_STORY_OWNER_V1__=true;return true}
function renderLiveEvidence(){const root=host(),p=packet();if(!root)return false;let card=$("urbionLiveEvidenceCard");if(!card){card=document.createElement('section');card.id='urbionLiveEvidenceCard';card.className='urbion-story-card';root.appendChild(card)}if(!p){card.innerHTML='<div class="usc-head"><span class="usc-title">LIVE EVIDENCE STORY</span><span class="usc-sub">WAITING</span></div><div class="usc-note">Run canonical analysis to populate source-backed observation context.</div>';window.__URBION_LIVE_EVIDENCE_OWNER_V1__=true;return false}const rows=liveSources(p),html=rows.length?rows.map(x=>`<div class="usc-row"><b>${esc(x.label)}</b><span>${esc(x.source)}</span><small><em class="usc-pill ${x.state==='VERIFIED'?'usc-ok':x.state.includes('ERROR')?'usc-bad':'usc-warn'}">${esc(x.state)}</em> · ${esc(x.count?x.count+' record(s)':'identity / query context')} · ${esc(x.updated)}</small></div>`).join(''):'<div class="usc-sub">No live source block was returned in the canonical packet.</div>';card.innerHTML=`<div class="usc-head"><span class="usc-title">LIVE EVIDENCE STORY</span><span class="usc-sub">SOURCE-BACKED · READ-ONLY</span></div><div class="usc-sub">What each connected source actually supports, without upgrading source context into statutory verification.</div>${html}<div class="usc-note"><b>BOUNDARY</b> · Live source context supports observation/identity only. It does not by itself prove adopted-plan applicability, parcel authority, or statutory approval.</div>`;window.__URBION_LIVE_EVIDENCE_OWNER_V1__=true;return true}
function scheduleRender(){if(window.__URBION_ANALYSIS_SUMMARY_RENDER_SCHEDULED__)return;window.__URBION_ANALYSIS_SUMMARY_RENDER_SCHEDULED__=true;requestAnimationFrame(()=>{window.__URBION_ANALYSIS_SUMMARY_RENDER_SCHEDULED__=false;try{render();renderDecisionStory();renderLiveEvidence()}catch(_){}})}
function boot(){style();let n=0;const t=setInterval(()=>{try{const ok=render();renderDecisionStory();renderLiveEvidence();if(ok||++n>=300)clearInterval(t)}catch(_){if(++n>=300)clearInterval(t)}},100);scheduleRender()}
window.addEventListener('urbion:assessment-ready',boot,{passive:true});window.addEventListener('urbion:analysis-ready',boot,{passive:true});window.addEventListener('urbion:environment-ready',boot,{passive:true});window.addEventListener('urbion:mobility-ready',boot,{passive:true});window.addEventListener('urbion:ai-ready',boot,{passive:true});window.addEventListener('urbion:workspace-ready',boot,{passive:true});window.addEventListener('load',boot,{once:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
