(()=>{
'use strict';
if(window.__URBION_HORIZON_UI_V3__)return;
window.__URBION_HORIZON_UI_V3__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const STYLE=`
:root{--h-bg:#020a12;--h-bg2:#061827;--h-panel:rgba(5,22,35,.94);--h-panel2:rgba(7,29,44,.86);--h-line:rgba(76,205,226,.20);--h-text:#effbff;--h-body:#c7d8df;--h-muted:#7f9aa8;--h-cyan:#29d9e8;--h-teal:#55e3bf;--h-blue:#4ca8ff;--h-amber:#ffc857;--h-red:#ff6c78;--h-radius:18px;--h-shadow:0 24px 70px rgba(0,0,0,.36)}
*,*::before,*::after{box-sizing:border-box}
html{background:var(--h-bg)!important}body.horizon-ui{margin:0!important;min-height:100vh!important;color:var(--h-text)!important;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif!important;background:radial-gradient(1100px 520px at 72% 0%,rgba(27,151,225,.20),transparent 66%),radial-gradient(820px 520px at 16% 82%,rgba(29,220,194,.10),transparent 64%),linear-gradient(180deg,#020a12 0%,#041522 48%,#020a12 100%)!important;overflow-x:hidden!important}
body.horizon-ui::before{content:"";position:fixed;inset:0;z-index:0;pointer-events:none;opacity:.42;background-image:linear-gradient(rgba(73,197,223,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(73,197,223,.045) 1px,transparent 1px);background-size:56px 56px;mask-image:linear-gradient(#000 0%,rgba(0,0,0,.95) 52%,transparent 100%)}
body.horizon-ui #urbion-championship-shell{position:relative;z-index:2;min-width:0;padding-bottom:26px}
body.horizon-ui .header,body.horizon-ui .topbar,body.horizon-ui .main-nav{position:relative;z-index:10;background:linear-gradient(180deg,rgba(2,12,20,.96),rgba(2,13,22,.82))!important;border-color:rgba(76,205,226,.14)!important;backdrop-filter:blur(18px) saturate(125%)!important}
body.horizon-ui .header{box-shadow:0 14px 42px rgba(0,0,0,.24)!important}
body.horizon-ui .topbar{box-shadow:0 10px 30px rgba(0,0,0,.14)!important}
body.horizon-ui #nav{display:flex!important;align-items:stretch!important;gap:8px!important;padding:10px 3px 11px!important;margin:0!important;overflow-x:auto!important;overflow-y:visible!important;scrollbar-width:none!important}
body.horizon-ui #nav::-webkit-scrollbar{display:none}
body.horizon-ui #nav button{position:relative;display:grid!important;grid-template-columns:auto minmax(0,1fr)!important;align-items:center!important;gap:10px!important;min-height:56px!important;padding:9px 14px!important;flex:0 0 auto!important;border:1px solid rgba(68,167,195,.24)!important;border-radius:14px!important;background:linear-gradient(150deg,rgba(8,29,43,.96),rgba(3,14,23,.96))!important;color:#9db5bf!important;font:800 11px/1.2 Inter,sans-serif!important;box-shadow:0 9px 22px rgba(0,0,0,.16)!important;transition:transform .16s ease,border-color .16s ease,box-shadow .16s ease,background .16s ease,color .16s ease}
body.horizon-ui #nav button::before{content:attr(data-horizon-no);display:grid;place-items:center;width:23px;height:23px;border:1px solid rgba(81,197,221,.20);border-radius:7px;color:#64b7cb;font:900 8px/1 Inter,sans-serif;letter-spacing:.05em}
body.horizon-ui #nav button:nth-child(1){--horizon-no:'01'}body.horizon-ui #nav button:nth-child(2){--horizon-no:'02'}body.horizon-ui #nav button:nth-child(3){--horizon-no:'03'}body.horizon-ui #nav button:nth-child(4){--horizon-no:'04'}body.horizon-ui #nav button:nth-child(5){--horizon-no:'05'}body.horizon-ui #nav button:nth-child(6){--horizon-no:'06'}
body.horizon-ui #nav button{content:""}
body.horizon-ui #nav button[data-horizon-no]{ }
body.horizon-ui #nav button:hover{transform:translateY(-1px);border-color:rgba(57,215,226,.52)!important;color:#f2ffff!important;box-shadow:0 14px 30px rgba(3,28,40,.28),0 0 18px rgba(48,210,225,.08)!important}
body.horizon-ui #nav button.active,body.horizon-ui #nav button[aria-selected=true]{background:linear-gradient(135deg,rgba(19,123,160,.55),rgba(44,222,193,.20))!important;border-color:rgba(53,226,232,.88)!important;color:#f6ffff!important;box-shadow:0 14px 34px rgba(33,191,214,.16),inset 0 0 0 1px rgba(255,255,255,.05),0 0 22px rgba(45,214,222,.08)!important}
body.horizon-ui #nav button.active::before,body.horizon-ui #nav button[aria-selected=true]::before{background:linear-gradient(135deg,var(--h-cyan),var(--h-teal));color:#06202a;border-color:transparent;box-shadow:0 0 16px rgba(45,218,226,.35)}
body.horizon-ui #nav button{--horizon-no:'00'}body.horizon-ui #nav button:nth-child(1)::before{content:'01'}body.horizon-ui #nav button:nth-child(2)::before{content:'02'}body.horizon-ui #nav button:nth-child(3)::before{content:'03'}body.horizon-ui #nav button:nth-child(4)::before{content:'04'}body.horizon-ui #nav button:nth-child(5)::before{content:'05'}body.horizon-ui #nav button:nth-child(6)::before{content:'06'}
body.horizon-ui .hero{position:relative;overflow:hidden;padding:22px 0 24px!important;margin:0 0 10px!important}
body.horizon-ui .hero::after{content:"";position:absolute;right:-10%;top:12%;width:520px;height:170px;border:1px solid rgba(61,209,228,.13);border-radius:50%;transform:rotate(-14deg);box-shadow:0 0 80px rgba(47,198,224,.08);pointer-events:none}
body.horizon-ui .hero h1{font-size:clamp(38px,4vw,58px)!important;line-height:1.03!important;letter-spacing:-.045em!important;max-width:920px!important;margin:5px 0 12px!important}
body.horizon-ui .hero p{font-size:13px!important;line-height:1.6!important;color:#9db6c0!important;max-width:760px!important}
body.horizon-ui .eyebrow{font-size:10px!important;line-height:1.3!important;letter-spacing:.18em!important;color:var(--h-teal)!important;font-weight:900!important}
body.horizon-ui .hero .hero-line,body.horizon-ui .hero .tags{margin-top:14px!important}
body.horizon-ui .hero-card,body.horizon-ui .card,body.horizon-ui .sidebar,body.horizon-ui .intel-card,body.horizon-ui .map-panel,body.horizon-ui .panel{background:linear-gradient(145deg,rgba(7,28,43,.95),rgba(3,14,24,.98))!important;border:1px solid var(--h-line)!important;border-radius:var(--h-radius)!important;box-shadow:var(--h-shadow)!important;min-width:0!important}
body.horizon-ui .card h2,body.horizon-ui .panel h2{font-size:22px!important;line-height:1.2!important}body.horizon-ui .card h3,body.horizon-ui .panel h3{font-size:15px!important;line-height:1.3!important}body.horizon-ui .card p,body.horizon-ui .panel p,body.horizon-ui .sidebar p{font-size:12px!important;line-height:1.55!important;color:var(--h-body)!important}
body.horizon-ui label{font-size:9px!important;line-height:1.35!important;color:#8eabb8!important;font-weight:800!important;letter-spacing:.08em!important;margin:9px 0 5px!important;text-transform:uppercase!important}
body.horizon-ui input,body.horizon-ui select,body.horizon-ui textarea{min-height:40px!important;height:auto!important;padding:9px 11px!important;font:500 13px/1.35 Inter,sans-serif!important;color:#e1eef2!important;background:rgba(2,15,25,.90)!important;border:1px solid rgba(65,171,197,.28)!important;border-radius:10px!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.02)!important}
body.horizon-ui input::placeholder,body.horizon-ui textarea::placeholder{color:#62808f!important;opacity:1}body.horizon-ui input:focus,body.horizon-ui select:focus,body.horizon-ui textarea:focus{outline:none!important;border-color:rgba(47,216,228,.78)!important;box-shadow:0 0 0 3px rgba(47,216,228,.08),inset 0 1px 0 rgba(255,255,255,.03)!important}
body.horizon-ui .btn,body.horizon-ui button.btn,body.horizon-ui .run,body.horizon-ui button.run{min-height:40px!important;height:auto!important;padding:9px 13px!important;border-radius:10px!important;font:800 11px/1.2 Inter,sans-serif!important;transition:transform .16s ease,box-shadow .16s ease,border-color .16s ease,background .16s ease!important}
body.horizon-ui .btn:hover,body.horizon-ui button.btn:hover,body.horizon-ui .run:hover,body.horizon-ui button.run:hover{transform:translateY(-1px)!important}
body.horizon-ui .btn.primary,body.horizon-ui .run,body.horizon-ui button.run{background:linear-gradient(135deg,#2ed9e7 0%,#55e3bf 100%)!important;color:#03161b!important;border-color:transparent!important;box-shadow:0 14px 32px rgba(39,214,210,.19),0 0 16px rgba(39,214,210,.08)!important}
body.horizon-ui .btn:not(.primary):not(.run){background:rgba(6,25,39,.78)!important;color:#cfe0e6!important;border-color:rgba(74,185,211,.28)!important;box-shadow:0 8px 20px rgba(0,0,0,.14)!important}
body.horizon-ui .map-panel{position:relative!important;overflow:hidden!important;border-color:rgba(67,209,228,.30)!important;box-shadow:0 30px 80px rgba(0,0,0,.42),0 0 28px rgba(42,189,223,.05)!important}
body.horizon-ui .map-panel .leaflet-container{height:clamp(520px,62vh,760px)!important;min-height:500px!important;background:#061c2a!important}
body.horizon-ui .leaflet-control-zoom a{width:34px!important;height:34px!important;line-height:34px!important;background:rgba(3,17,27,.94)!important;color:#e6f8fb!important;border-color:rgba(86,192,216,.24)!important}
body.horizon-ui .leaflet-control-attribution{font:600 9px/1.2 Inter,sans-serif!important;background:rgba(3,14,23,.82)!important;color:#8ca7b2!important;padding:5px 8px!important}
body.horizon-ui .leaflet-control-attribution a{color:#69d9e9!important}
body.horizon-ui #cs-layer-drawer{position:absolute!important;top:14px!important;right:14px!important;bottom:14px!important;width:clamp(268px,31%,370px)!important;max-width:calc(100% - 28px)!important;display:flex!important;flex-direction:column!important;z-index:1400!important;overflow:hidden!important;padding:0!important;border:1px solid rgba(86,212,229,.34)!important;border-radius:17px!important;background:linear-gradient(180deg,rgba(3,18,29,.96),rgba(2,11,20,.98))!important;box-shadow:0 24px 64px rgba(0,0,0,.48),0 0 26px rgba(38,205,226,.06)!important;backdrop-filter:blur(16px)!important;transition:opacity .18s ease,transform .18s ease!important}
body.horizon-ui #cs-layer-drawer.horizon-closed{opacity:0!important;transform:translateX(18px)!important;pointer-events:none!important}
body.horizon-ui #cs-layer-drawer .layer-list,body.horizon-ui #cs-layer-drawer .layers-list,body.horizon-ui #cs-layer-drawer .drawer-body,body.horizon-ui #cs-layer-drawer .layer-drawer-body,body.horizon-ui #cs-layer-drawer .layer-drawer-content,body.horizon-ui #cs-layer-drawer .drawer-content{min-height:0!important;flex:1 1 auto!important;overflow:auto!important;scrollbar-width:thin;scrollbar-color:rgba(74,204,222,.42) transparent}
body.horizon-ui #cs-layer-drawer .layer-group{margin:0 8px 8px!important;border:1px solid rgba(76,168,191,.16)!important;border-radius:11px!important;background:rgba(6,25,37,.70)!important;overflow:visible!important}
body.horizon-ui #cs-layer-drawer .group-toggle{min-height:40px!important;padding:9px 11px!important;font:900 11px/1.2 Inter,sans-serif!important;color:#d9eef3!important;background:linear-gradient(90deg,rgba(12,38,54,.93),rgba(6,23,35,.90))!important;border-radius:10px!important}
body.horizon-ui #cs-layer-drawer .group-body{padding:2px 0 5px!important;overflow:visible!important}
body.horizon-ui #cs-layer-drawer .fcc-layer-row{min-height:43px!important;height:auto!important;padding:8px 9px!important;margin:2px 5px!important;border:1px solid transparent!important;border-radius:8px!important;display:grid!important;grid-template-columns:18px minmax(0,1fr) auto!important;align-items:center!important;gap:8px!important;background:rgba(4,17,27,.56)!important;color:#cfe2e8!important;font:700 11px/1.25 Inter,sans-serif!important}
body.horizon-ui #cs-layer-drawer .fcc-layer-row:hover{background:rgba(16,54,72,.66)!important;border-color:rgba(61,210,226,.26)!important}
body.horizon-ui #cs-layer-drawer .fcc-layer-row.is-on{background:linear-gradient(90deg,rgba(31,187,204,.15),rgba(7,28,40,.86))!important;border-color:rgba(61,216,224,.24)!important;box-shadow:inset 3px 0 0 #4ddfd4!important}
body.horizon-ui #cs-layer-drawer .fcc-layer-row span{font-size:11px!important;line-height:1.25!important;white-space:normal!important;overflow-wrap:anywhere!important}body.horizon-ui #cs-layer-drawer .fcc-layer-row small{font-size:9px!important;line-height:1.2!important;color:#71909f!important;white-space:normal!important}
body.horizon-ui #cs-layer-drawer input[type=checkbox]{appearance:none!important;-webkit-appearance:none!important;width:17px!important;height:17px!important;min-height:17px!important;padding:0!important;margin:0!important;border-radius:4px!important;border:1px solid rgba(105,189,211,.58)!important;background:rgba(2,14,23,.95)!important;cursor:pointer!important;display:grid!important;place-items:center!important}
body.horizon-ui #cs-layer-drawer input[type=checkbox]:checked{background:linear-gradient(135deg,#2cd9e6,#56e1be)!important;border-color:transparent!important}body.horizon-ui #cs-layer-drawer input[type=checkbox]:checked::after{content:'✓';font:900 11px/1 Inter,sans-serif;color:#032028}
body.horizon-ui .horizon-drawer-close{position:absolute;right:10px;top:10px;z-index:10;width:28px;height:28px;border-radius:8px;border:1px solid rgba(77,202,224,.22);background:rgba(2,14,23,.88);color:#d7eef2;font:800 16px/1 Inter,sans-serif;cursor:pointer}
body.horizon-ui .horizon-drawer-close:hover{border-color:rgba(62,218,228,.72);background:rgba(9,39,54,.96);color:#fff}
body.horizon-ui .horizon-drawer-title{padding:12px 44px 10px 14px;border-bottom:1px solid rgba(76,190,214,.12);color:#e5f7fa;font:900 12px/1.2 Inter,sans-serif;letter-spacing:.08em;text-transform:uppercase}
body.horizon-ui .horizon-drawer-title small{display:block;margin-top:4px;color:#6f8c99;font:600 9px/1.3 Inter,sans-serif;letter-spacing:0;text-transform:none}
body.horizon-ui #horizon-status{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:38px;padding:8px 12px;margin:0 0 12px;border:1px solid rgba(73,202,221,.18);border-radius:11px;background:linear-gradient(90deg,rgba(26,157,183,.11),rgba(59,223,194,.04));box-shadow:0 10px 24px rgba(0,0,0,.12)}
body.horizon-ui #horizon-status .live{display:flex;align-items:center;gap:8px;color:#7deee0;font:900 10px/1.2 Inter,sans-serif;letter-spacing:.08em;text-transform:uppercase}.h-dot{width:7px;height:7px;border-radius:50%;background:var(--h-teal);box-shadow:0 0 12px rgba(85,227,191,.75)}body.horizon-ui #horizon-status .hint{font:600 10px/1.4 Inter,sans-serif;color:#718c9a;text-align:right}
body.horizon-ui .horizon-metrics{display:grid!important;grid-template-columns:1.35fr repeat(3,.55fr) 1.15fr!important;gap:10px!important;margin-top:10px!important;padding:12px 14px!important;border:1px solid rgba(71,205,224,.20)!important;border-radius:15px!important;background:linear-gradient(110deg,rgba(6,28,43,.94),rgba(4,17,28,.98))!important;box-shadow:0 18px 46px rgba(0,0,0,.28)!important;align-items:center}
body.horizon-ui .horizon-metric-lead strong{display:block;font:700 17px/1.05 'Space Grotesk',Inter,sans-serif;color:#f1fbff}.horizon-metric-lead small{display:block;margin-top:5px;color:#7896a3;font:600 9px/1.35 Inter,sans-serif}.horizon-metric{padding:6px 10px;border-left:1px solid rgba(69,193,213,.12)}.horizon-metric b{display:block;font:800 22px/1 'Space Grotesk',Inter,sans-serif;color:var(--h-cyan)}.horizon-metric span{display:block;margin-top:4px;color:#7995a2;font:800 8px/1.2 Inter,sans-serif;letter-spacing:.08em;text-transform:uppercase}.horizon-visual{position:relative;height:58px;border:1px solid rgba(77,201,221,.12);border-radius:11px;background:radial-gradient(circle at 50% 48%,rgba(54,215,224,.18),transparent 38%),linear-gradient(135deg,rgba(21,70,90,.38),rgba(3,17,27,.88));overflow:hidden}.horizon-visual::before{content:"";position:absolute;inset:10px;background:radial-gradient(circle at 35% 40%,rgba(92,220,240,.32) 0 2px,transparent 3px),radial-gradient(circle at 65% 62%,rgba(85,227,191,.28) 0 2px,transparent 3px),linear-gradient(120deg,transparent 0 46%,rgba(69,211,228,.22) 47% 48%,transparent 49% 100%);filter:drop-shadow(0 0 10px rgba(53,209,227,.20))}.horizon-visual::after{content:"";position:absolute;left:12%;right:12%;bottom:10px;height:1px;background:linear-gradient(90deg,transparent,rgba(68,220,224,.38),transparent);box-shadow:0 0 22px rgba(67,216,224,.16)}
body.horizon-ui .horizon-visual-label{position:absolute;right:10px;top:8px;color:#78a1ad;font:900 7px/1 Inter,sans-serif;letter-spacing:.1em;text-transform:uppercase}
/* Keep sticky application navigation from covering primary actions when focus/click scrolling occurs. */
body.horizon-ui #cs-run,body.horizon-ui #run,body.horizon-ui .run,body.horizon-ui button.primary{scroll-margin-top:96px!important;scroll-margin-bottom:24px!important}
html.cs-light body.horizon-ui{color:#132b35!important;background:radial-gradient(1000px 500px at 75% 0%,rgba(71,170,215,.16),transparent 68%),linear-gradient(180deg,#eef8fb 0%,#e4f1f4 52%,#dbeaf0 100%)!important}
html.cs-light body.horizon-ui::before{opacity:.18;background-image:linear-gradient(rgba(19,119,145,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(19,119,145,.08) 1px,transparent 1px)}
html.cs-light body.horizon-ui .header,html.cs-light body.horizon-ui .topbar,html.cs-light body.horizon-ui .main-nav{background:rgba(246,252,253,.90)!important;border-color:rgba(23,116,139,.16)!important;box-shadow:0 10px 28px rgba(33,86,100,.10)!important}
html.cs-light body.horizon-ui #nav button{background:linear-gradient(145deg,#f9fcfd,#eef6f8)!important;color:#4c6873!important;border-color:rgba(34,124,148,.18)!important;box-shadow:0 8px 18px rgba(37,85,98,.08)!important}html.cs-light body.horizon-ui #nav button.active{background:linear-gradient(135deg,#dff8fa,#c5edf0)!important;color:#123643!important;border-color:rgba(22,160,177,.60)!important;box-shadow:0 10px 22px rgba(26,146,164,.16)!important}
html.cs-light body.horizon-ui .hero-card,html.cs-light body.horizon-ui .card,html.cs-light body.horizon-ui .sidebar,html.cs-light body.horizon-ui .intel-card,html.cs-light body.horizon-ui .map-panel,html.cs-light body.horizon-ui .panel{background:rgba(248,252,253,.96)!important;border-color:rgba(32,125,148,.18)!important;box-shadow:0 20px 44px rgba(39,83,96,.11)!important}html.cs-light body.horizon-ui h1,html.cs-light body.horizon-ui h2,html.cs-light body.horizon-ui h3,html.cs-light body.horizon-ui h4{color:#112d38!important}html.cs-light body.horizon-ui .hero p,html.cs-light body.horizon-ui .card p,html.cs-light body.horizon-ui .panel p{color:#496671!important}html.cs-light body.horizon-ui label{color:#4a6a76!important}html.cs-light body.horizon-ui input,html.cs-light body.horizon-ui select,html.cs-light body.horizon-ui textarea{background:#fbfdfe!important;color:#17323c!important;border-color:rgba(38,124,148,.26)!important;box-shadow:none!important}html.cs-light body.horizon-ui input::placeholder,html.cs-light body.horizon-ui textarea::placeholder{color:#78939e!important}html.cs-light body.horizon-ui .btn:not(.primary):not(.run){background:#eef7f9!important;color:#31545f!important;border-color:rgba(36,124,148,.22)!important}html.cs-light body.horizon-ui #cs-layer-drawer{background:rgba(247,252,253,.98)!important;border-color:rgba(27,124,147,.22)!important;box-shadow:0 22px 52px rgba(35,82,95,.16)!important}html.cs-light body.horizon-ui .horizon-drawer-title{color:#18343e!important;border-bottom-color:rgba(26,120,143,.12)!important}html.cs-light body.horizon-ui .horizon-drawer-title small{color:#64808a!important}html.cs-light body.horizon-ui #cs-layer-drawer .layer-group{background:rgba(232,245,248,.88)!important;border-color:rgba(31,124,147,.14)!important}html.cs-light body.horizon-ui #cs-layer-drawer .group-toggle{background:linear-gradient(90deg,#e5f3f6,#edf8fa)!important;color:#244650!important}html.cs-light body.horizon-ui #cs-layer-drawer .fcc-layer-row{background:rgba(248,252,253,.90)!important;color:#274750!important}html.cs-light body.horizon-ui #cs-layer-drawer .fcc-layer-row small{color:#66818b!important}html.cs-light body.horizon-ui .horizon-metrics{background:linear-gradient(110deg,#f5fbfc,#edf6f8)!important;border-color:rgba(35,130,151,.16)!important;box-shadow:0 14px 34px rgba(38,84,96,.10)!important}html.cs-light body.horizon-ui .horizon-metric{border-left-color:rgba(33,127,148,.12)!important}html.cs-light body.horizon-ui .horizon-metric span,html.cs-light body.horizon-ui .horizon-metric-lead small{color:#67818b!important}html.cs-light body.horizon-ui .horizon-visual{background:radial-gradient(circle at 50% 48%,rgba(56,181,203,.14),transparent 38%),linear-gradient(135deg,#e3f1f4,#f7fbfc)!important}
@media(max-width:1120px){body.horizon-ui .horizon-metrics{grid-template-columns:1.1fr repeat(3,.58fr)!important}.horizon-visual{display:none}}@media(max-width:920px){body.horizon-ui #nav button{min-height:50px!important;padding:8px 11px!important}body.horizon-ui #nav button::before{width:20px;height:20px}body.horizon-ui .map-panel .leaflet-container{height:520px!important;min-height:460px!important}body.horizon-ui #cs-layer-drawer{width:min(340px,44%)!important}}@media(max-width:760px){body.horizon-ui .horizon-metrics{grid-template-columns:1fr 1fr!important}.horizon-metric-lead{grid-column:1/-1}.horizon-visual{display:none}body.horizon-ui #cs-layer-drawer{left:10px!important;right:10px!important;top:auto!important;bottom:10px!important;width:auto!important;height:min(58%,430px)!important;max-height:430px!important}body.horizon-ui .hero h1{font-size:clamp(34px,8vw,46px)!important}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition:none!important}}
`;
function addStyle(){if($('#horizon-premium-style-v3'))return;const s=document.createElement('style');s.id='horizon-premium-style-v3';s.textContent=STYLE;document.head.appendChild(s)}
function addFonts(){if($('#horizon-fonts-v3'))return;const l=document.createElement('link');l.id='horizon-fonts-v3';l.rel='stylesheet';l.href='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=Space+Grotesk:wght@500;600;700&display=swap';document.head.appendChild(l)}
function addBackground(){if($('#horizon-v3-background'))return;const e=document.createElement('div');e.id='horizon-v3-background';e.innerHTML='<div class="horizon-v3-grid"></div>';e.style.cssText='position:fixed;inset:0;z-index:0;pointer-events:none;overflow:hidden';e.querySelector('.horizon-v3-grid').style.cssText='position:absolute;inset:0;background:radial-gradient(700px 180px at 74% 5%,rgba(42,214,227,.18),transparent 70%),radial-gradient(500px 160px at 34% 7%,rgba(54,111,255,.11),transparent 72%);';document.body.insertBefore(e,document.body.firstChild)}
function addCityArt(){if($('#horizon-v3-city-art'))return;const e=document.createElement('div');e.id='horizon-v3-city-art';e.style.cssText='position:absolute;inset:0 0 auto 0;height:76px;z-index:1;pointer-events:none;overflow:hidden;opacity:.58';const city=document.createElement('div');city.style.cssText='position:absolute;right:0;left:23%;bottom:0;height:72px;display:flex;align-items:flex-end;gap:3px;padding:0 1%;background:linear-gradient(180deg,transparent,rgba(2,9,15,.12) 38%,rgba(2,9,15,.38) 100%)';for(let i=0;i<42;i++){const b=document.createElement('i');const h=[38,56,46,70,31,62,48,81][i%8];b.style.cssText=`flex:1;max-width:52px;height:${h}%;min-width:7px;border:1px solid rgba(86,208,229,.16);background:linear-gradient(180deg,rgba(29,83,108,.40),rgba(2,10,16,.96));clip-path:polygon(8% 0,92% 0,100% 100%,0 100%);`;b.innerHTML='<i style="display:block;margin:10% 18%;height:80%;background:repeating-linear-gradient(180deg,rgba(116,231,241,.28) 0 2px,transparent 2px 10px);opacity:.35"></i>';city.appendChild(b)}e.appendChild(city);document.querySelector('.header,body>header')?.appendChild(e)}
function addStatus(){const nav=$('#nav');if(!nav||$('#horizon-status'))return;const e=document.createElement('div');e.id='horizon-status';e.innerHTML='<div class="live"><span class="h-dot"></span><span>LIVE SPATIAL PLANNING</span></div><div class="hint">Evidence-aware · source-aware · planner in the loop</div>';nav.insertAdjacentElement('afterend',e)}
function makeMetrics(){if($('.horizon-metrics'))return;const anchor=$('.map-panel');if(!anchor||!anchor.parentElement)return;const e=document.createElement('div');e.className='horizon-metrics';e.innerHTML='<div class="horizon-metric-lead"><strong>Evidence today. Better cities tomorrow.</strong><small>One case · one evidence chain · one explainable planning workflow.</small></div><div class="horizon-metric"><b>07</b><span>Data Sources</span></div><div class="horizon-metric"><b>12</b><span>Spatial Layers</span></div><div class="horizon-metric"><b>100%</b><span>Traceable</span></div><div class="horizon-visual"><span class="horizon-visual-label">URBAN INTELLIGENCE NETWORK</span></div>';anchor.parentElement.insertAdjacentElement('afterend',e)}
function setDrawerVisible(drawer,visible){drawer.classList.toggle('horizon-closed',!visible);drawer.setAttribute('aria-hidden',String(!visible));drawer.dataset.horizonOpen=visible?'1':'0'}
function setupDrawer(){const d=$('#cs-layer-drawer');if(!d)return;d.style.overflow='hidden';let close=d.querySelector('.horizon-drawer-close');if(!close){const title=document.createElement('div');title.className='horizon-drawer-title';title.innerHTML='MAP LAYERS<small>Source-backed spatial evidence</small>';d.prepend(title);close=document.createElement('button');close.className='horizon-drawer-close';close.type='button';close.setAttribute('aria-label','Close map layers');close.textContent='×';d.appendChild(close);close.addEventListener('click',()=>setDrawerVisible(d,false));d.addEventListener('keydown',e=>{if(e.key==='Escape')setDrawerVisible(d,false)})}
const scrollCandidates=['.layer-list','.layers-list','.drawer-body','.layer-drawer-body','.layer-drawer-content','.drawer-content'];let scroll=scrollCandidates.map(s=>d.querySelector(s)).find(Boolean);if(!scroll){const all=$$('div,section,ul',d);scroll=all.sort((a,b)=>b.querySelectorAll('.fcc-layer-row').length-a.querySelectorAll('.fcc-layer-row').length)[0]||d.querySelector('.layer-group')?.parentElement}if(scroll){scroll.style.minHeight='0';scroll.style.flex='1 1 auto';scroll.style.overflow='auto';scroll.style.scrollbarWidth='thin'}
$$('button',document).filter(b=>/^(layers|lapisan)$/i.test((b.textContent||'').trim())||b.dataset.horizonLayerToggle==='1').forEach(btn=>{if(btn.dataset.horizonLayerToggleBound==='1')return;btn.dataset.horizonLayerToggleBound='1';btn.dataset.horizonLayerToggle='1';btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();setDrawerVisible(d,d.classList.contains('horizon-closed'))},{capture:true})});if(!d.dataset.horizonInit){d.dataset.horizonInit='1';setDrawerVisible(d,true)}}
function addMapHud(){const map=$('.map-panel');if(!map||$('#horizon-map-hud-v3'))return;const e=document.createElement('div');e.id='horizon-map-hud-v3';e.style.cssText='position:absolute;left:14px;top:14px;z-index:1350;display:flex;gap:7px;flex-wrap:wrap;max-width:52%;pointer-events:none';e.innerHTML='<span style="display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid rgba(74,203,222,.24);border-radius:999px;background:rgba(2,17,27,.84);color:#dffaff;font:900 9px/1 Inter,sans-serif;letter-spacing:.05em">● MAP LIVE</span><span style="display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid rgba(74,203,222,.24);border-radius:999px;background:rgba(2,17,27,.84);color:#dffaff;font:900 9px/1 Inter,sans-serif;letter-spacing:.05em">● EVIDENCE TRACEABLE</span>';map.appendChild(e)}
function boot(){document.body.classList.add('horizon-ui');addFonts();addStyle();addBackground();addCityArt();addStatus();makeMetrics();setupDrawer();addMapHud();new MutationObserver(()=>{addStatus();makeMetrics();setupDrawer();addMapHud()}).observe(document.body,{subtree:true,childList:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();

/* Final runtime theme guard: re-assert persisted theme after any competing button handler. */
(()=>{
"use strict";
if(window.__URBION_HORIZON_THEME_RUNTIME_GUARD__)return;
window.__URBION_HORIZON_THEME_RUNTIME_GUARD__=true;
const apply=()=>{
  const html=document.documentElement;
  const stored=localStorage.getItem("urbion-theme");
  const light=stored==="light";
  html.classList.toggle("cs-light",light);
  const logo=document.querySelector("#cs-logo");
  if(logo)logo.src=light?"/urbion_logo_light.svg":"/urbion_logo_dark.svg";
};
apply();
document.addEventListener("click",event=>{
  const button=event.target?.closest?.("#cs-theme");
  if(!button)return;
  window.setTimeout(apply,0);
},false);
})();
