/* MASTER-284: unified site intelligence bridge on top of MASTER-283. */
(()=>{
'use strict';
if(window.__URBION_PUBLIC_SPATIAL_V284__)return;
window.__URBION_PUBLIC_SPATIAL_V284__=1;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(u,o)=>{const r=await fetch(u,o);if(!r.ok)throw Error(u+' · '+r.status);return r.json()};
const p=()=>({site_lat:+($('dash-lat')?.value||2.285),site_lon:+($('dash-lon')?.value||102.196),state:$('dash-state')?.value||'Melaka',district:'Melaka Tengah'});
const Q={current:'https://scharms.planmalaysia.gov.my/arcgis/rest/services/iPLAN/GTsemasa_04/MapServer/0/query',zoning:'https://scharms.planmalaysia.gov.my/arcgis/rest/services/iPLAN/GTzoning_04/MapServer/0/query',lot:'https://scharms.planmalaysia.gov.my/arcgis/rest/services/iPLAN/LOT_04/MapServer/0/query'};
const css=document.createElement('style');css.textContent=`.v284-shell{border:1px solid #315363;border-radius:14px;background:linear-gradient(145deg,#08171f,#061018);padding:15px;margin-top:10px}.v284-head{display:flex;justify-content:space-between;gap:12px}.v284-k{font-size:8px;letter-spacing:.16em;color:#67e8b7;font-weight:900}.v284-title{font-size:18px;font-weight:900;margin-top:3px}.v284-muted{font-size:9px;color:#7e99a3;line-height:1.5}.v284-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin-top:10px}.v284-metric{border:1px solid #203c47;border-radius:10px;padding:10px;background:#091a22}.v284-metric b{display:block;font-size:16px;color:#eaf7f4}.v284-metric small{font-size:8px;color:#78919d}.v284-ok{color:#67e8b7}.v284-warn{color:#ffd27a}.v284-bad{color:#ff8292}.v284-btn{border:1px solid #315363;background:#0a1b24;color:#edf7f5;border-radius:8px;padding:8px 11px;font:800 9px Inter;cursor:pointer;margin:7px 6px 0 0}.v284-btn:disabled{opacity:.55}.v284-table{width:100%;border-collapse:collapse;font-size:9px;margin-top:9px}.v284-table th,.v284-table td{padding:7px;border-bottom:1px solid #1b3440;text-align:left;vertical-align:top}.v284-table th{color:#67e8b7}.v284-result{margin-top:9px;max-height:360px;overflow:auto}.v284-note{margin-top:9px;padding:8px;border-left:2px solid #67e8b7;background:#091b23;color:#91aab3;font-size:8px;line-height:1.5}@media(max-width:950px){.v284-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.v284-grid{grid-template-columns:1fr 1fr}.v284-head{display:block}}`;
document.head.appendChild(css);
function arcParams(lat,lon){return new URLSearchParams({where:'1=1',geometry:lon+','+lat,geometryType:'esriGeometryPoint',inSR:'4326',spatialRel:'esriSpatialRelIntersects',distance:'5000',units:'esriSRUnit_Meter',outFields:'*',returnGeometry:'true',outSR:'4326',f:'json'}).toString()}
async function arc(url,q){const r=await fetch(url+'?'+arcParams(q.site_lat,q.site_lon));if(!r.ok)throw Error('HTTP '+r.status);const x=await r.json();if(x.error)throw Error(x.error.message||'ArcGIS error');return x}
async function run(){const o=$('v284-out'),b=$('v284-run');if(!o||!b)return;b.disabled=true;b.textContent='RUNNING…';o.innerHTML='<div class="v284-warn">Running site-linked intelligence in parallel…</div>';const q=p();const jobs=[['i-PLAN Current Land Use',()=>arc(Q.current,q)],['i-PLAN Zoning',()=>arc(Q.zoning,q)],['i-PLAN Cadastral Lot',()=>arc(Q.lot,q)],['JMG Major Fault',()=>arc('https://mygems.jmg.gov.my/server/rest/services/GeologiAsas/Major_Fault/FeatureServer/5/query',q)],['JMG Lithology · Melaka',()=>arc('https://mygems.jmg.gov.my/server/rest/services/Demarcation/Litology_by_Negeri/FeatureServer/22/query',q)],['JPS Station Intelligence',()=>api('/station-intelligence?site_lat='+q.site_lat+'&site_lon='+q.site_lon+'&state='+encodeURIComponent(q.state))],['Championship Health',()=>api('/championship-health?site_lat='+q.site_lat+'&site_lon='+q.site_lon+'&state='+encodeURIComponent(q.state))]];const rs=await Promise.allSettled(jobs.map(x=>x[1]()));let good=0,rows='';rs.forEach((r,i)=>{const name=jobs[i][0],ok=r.status==='fulfilled';if(ok)good++;let n='—';if(ok&&r.value&&Array.isArray(r.value.features))n=r.value.features.length+' feature(s)';else if(ok&&name==='JPS Station Intelligence')n='LIVE CONTEXT';else if(ok&&name==='Championship Health')n='CHAIN READY';rows+='<tr><td>'+esc(name)+'</td><td class="'+(ok?'v284-ok':'v284-bad')+'">'+(ok?'RESPONDED':'FAILED')+'</td><td>'+esc(n)+'</td></tr>'});window.__URBION_SITE_INTELLIGENCE_V284__={site:q,results:Object.fromEntries(rs.map((r,i)=>[jobs[i][0],r.status==='fulfilled'?r.value:null]))};o.innerHTML='<table class="v284-table"><thead><tr><th>Source / Engine</th><th>Status</th><th>Result</th></tr></thead><tbody>'+rows+'</tbody></table><div class="v284-note">Evidence state: SOURCE_CONTEXT / CALCULATED where applicable. Public responses are not statutory approval.</div>';const s=$('v284-score');if(s)s.textContent=good+'/'+jobs.length;b.disabled=false;b.textContent='RUN SITE INTELLIGENCE AGAIN'}
function add(){const host=document.querySelector('#uhd-gis .v276-grid');if(!host||$('v284'))return;const c=document.createElement('section');c.id='v284';c.className='v276-card full v284-shell';c.innerHTML='<div class="v284-head"><div><div class="v284-k">CHAMPIONSHIP SITE INTELLIGENCE</div><div class="v284-title">One Site → One Evidence Chain</div><div class="v284-muted">Combines authoritative public GIS context with URBION planning engines and exposes the returned result count before downstream decisions.</div></div><div class="v284-metric"><b id="v284-score">0/7</b><small>SOURCES RESPONDED</small></div></div><div class="v284-grid"><div class="v284-metric"><b>i-PLAN</b><small>Current Land Use · Zoning · Lot</small></div><div class="v284-metric"><b>JPS</b><small>Station Intelligence</small></div><div class="v284-metric"><b>JMG</b><small>Fault · Lithology</small></div><div class="v284-metric"><b>AI</b><small>Assessment · Policy</small></div><div class="v284-metric"><b>LCP</b><small>Decision Handoff</small></div></div><div><button id="v284-run" class="v284-btn">RUN SITE INTELLIGENCE</button><button id="v284-evidence" class="v284-btn">BUILD EVIDENCE CHAIN</button><button id="v284-decision" class="v284-btn">OPEN DECISION CENTRE</button></div><div id="v284-out" class="v284-card v284-result">Ready. Run the complete site-linked check.</div><div class="v284-note">Architecture: Site → i-PLAN GIS → JPS/JMG context → AI Assessment → What-If → Decision Centre → LCP. Source freshness and statutory verification remain source-dependent.</div></section>';host.appendChild(c);$('v284-run').onclick=run;$('v284-evidence').onclick=evidence;$('v284-decision').onclick=()=>{const q=p();sessionStorage.setItem('urbion_assessment_inputs',JSON.stringify({...q,tod_lat:q.site_lat,tod_lon:q.site_lon,plot_ratio:4.5,development_type:'TOD Development / Mixed Use',development_class:'Mixed Use',district:q.district,pbt:'Majlis Bandaraya Melaka Bersejarah'}));location.href='/decision-center'} }
async function evidence(){const o=$('v284-out');if(!o)return;o.innerHTML='<div class="v284-warn">Building linked evidence…</div>';try{const q=p(),x=await api('/public-sources/site-evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(q)});const rows=Object.entries(x.sources||{}).map(([k,v])=>'<tr><td>'+esc(k)+'</td><td>'+esc(JSON.stringify(v).slice(0,1800))+'</td></tr>').join('');o.innerHTML='<table class="v284-table"><thead><tr><th>Evidence Source</th><th>Site-linked result</th></tr></thead><tbody>'+rows+'</tbody></table><div class="v284-note">Evidence bundle created from the current site coordinates. No statutory approval is inferred.</div>';window.__URBION_EVIDENCE_CHAIN_V284__=x}catch(e){o.innerHTML='<span class="v284-bad">Evidence build failed · '+esc(e.message)+'</span>'}}
function boot(){add()}setTimeout(boot,800);setTimeout(boot,1800);new MutationObserver(boot).observe(document.body,{childList:true,subtree:true});
})();
