(()=>{
'use strict';
if(window.__URBION_CHAMPION_REVIEW)return;window.__URBION_CHAMPION_REVIEW=true;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const css=`<style id="fcc-champion-review-css">
#fcc-champion-review{grid-column:1/-1;margin:0 16px 18px;padding:18px;border:1px solid rgba(53,226,176,.16);border-radius:16px;background:linear-gradient(145deg,rgba(7,19,31,.98),rgba(10,29,40,.92));box-shadow:0 20px 60px rgba(0,0,0,.2)}
.fcr-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.fcr-kicker{font:800 9px Inter;letter-spacing:.14em;color:#5ee7c2}.fcr-head h3{margin:4px 0;font:800 20px 'Space Grotesk',Inter;color:#eaf5f7}.fcr-head p{margin:0;color:#8ea7b5;font:500 11px/1.5 Inter}.fcr-state{font:800 9px Inter;letter-spacing:.08em;color:#5ee7c2;white-space:nowrap}
.fcr-grid{display:grid;grid-template-columns:1.05fr 1.05fr 1fr 1fr;gap:10px;margin-top:14px}.fcr-card{padding:13px;border:1px solid rgba(119,147,163,.16);border-radius:12px;background:rgba(255,255,255,.025);min-height:150px}.fcr-card h4{margin:0 0 9px;font:800 10px Inter;letter-spacing:.08em;text-transform:uppercase;color:#dceff2}.fcr-card p,.fcr-card li{font:500 10px/1.55 Inter;color:#91a8b3}.fcr-card ul{margin:0;padding-left:15px}.fcr-meter{height:6px;background:rgba(255,255,255,.07);border-radius:99px;overflow:hidden;margin:8px 0}.fcr-meter i{display:block;height:100%;width:0;background:linear-gradient(90deg,#18cce5,#35e2b0);transition:width .25s ease}.fcr-row{display:flex;justify-content:space-between;gap:8px;font:700 10px Inter;color:#b9d1d7}.fcr-checks{display:grid;grid-template-columns:1fr 1fr;gap:5px}.fcr-checks label{font:600 9px Inter;color:#8ea7b5}.fcr-checks input{accent-color:#35e2b0;margin-right:5px}.fcr-select{width:100%;margin-top:8px;background:#091a27;color:#dceff2;border:1px solid rgba(119,147,163,.2);border-radius:8px;padding:7px;font:700 9px Inter}.fcr-option{padding:7px 0;border-bottom:1px solid rgba(119,147,163,.1)}.fcr-option:last-child{border-bottom:0}.fcr-tag{display:inline-flex;padding:3px 6px;border-radius:99px;border:1px solid rgba(94,231,194,.2);font:800 8px Inter;color:#9fe9d7;margin:2px}.fcr-note{margin-top:9px!important;font-size:9px!important;color:#708895!important}.fcr-action{display:inline-block;margin-top:8px;padding:6px 8px;border-radius:8px;background:rgba(53,226,176,.08);border:1px solid rgba(53,226,176,.18);color:#bdece2;font:800 9px Inter}.fcr-run{width:100%;margin-top:8px;padding:7px;border-radius:8px;background:rgba(24,204,229,.08);border:1px solid rgba(24,204,229,.2);color:#c8f3f7;font:800 9px Inter;cursor:pointer}.fcr-run:disabled{opacity:.5;cursor:wait}
body.fcc-light #fcc-champion-review{background:linear-gradient(145deg,#fff,#eef6f8);border-color:#d6e5e9}body.fcc-light .fcr-card{background:rgba(255,255,255,.72);border-color:#d9e5e9}body.fcc-light .fcr-card p,body.fcc-light .fcr-card li,body.fcc-light .fcr-checks label{color:#4d6672}body.fcc-light .fcr-select{background:#fff;color:#17313e}
@media(max-width:1050px){.fcr-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.fcr-grid{grid-template-columns:1fr}.fcr-head{display:block}.fcr-state{display:block;margin-top:8px}}
</style>`;
function unifiedCase(){const u=window.__URBION_UNIFIED_STATE||{},c=u.case||u.caseData||u.inputs||{};const pick=(a,b)=>c[a]??u[a]??b;return {lat:Number(pick('lat',$('#fcc-lat')?.value)),lon:Number(pick('lon',$('#fcc-lon')?.value)),state:pick('state',$('#fcc-state')?.value||''),pbt:pick('pbt',$('#fcc-pbt')?.value||''),district:pick('district',$('#fcc-district')?.value||''),lot:pick('lot',$('#fcc-lot')?.value||''),project:pick('project_name',$('#fcc-project_name')?.value||''),landuse:pick('landuse',$('#fcc-landuse')?.value||''),category:pick('category',$('#fcc-category')?.value||''),activity:pick('activity',$('#fcc-activity')?.value||''),development:pick('development',$('#fcc-development')?.value||''),ratio:Number(pick('ratio',$('#fcc-ratio')?.value||0))};}
function derive(data){const s=data?.spatial_intelligence||{},m=Array.isArray(s.metrics)?s.metrics:[],gaps=[...(data?.review_gaps||[]),...(s.review_gaps||[])];const find=needle=>m.find(x=>String(x?.name||x?.metric||x?.label||'').toLowerCase().includes(needle));return {metrics:m,gaps,flood:find('flood'),road:find('road'),elev:find('elevation')};}
function render(data){const root=$('#urbion-final-command-centre');if(!root)return;let p=$('#fcc-champion-review');if(!p){p=document.createElement('section');p.id='fcc-champion-review';root.appendChild(p)}const d=derive(data||window.__urbionAssessment||window.__URBION_LCP_INTELLIGENCE||{}),c=unifiedCase();const docs=['location plan','site plan','development proposal report','layout / masterplan'];let stored=[];try{stored=JSON.parse(localStorage.getItem('urbion-km-docs')||'[]')}catch(e){}const checked=new Set(stored),readiness=Math.round(docs.filter(x=>checked.has(x)).length/docs.length*100),floodTxt=d.flood?.value??d.flood?.status??'SOURCE REVIEW',roadTxt=d.road?.value??d.road?.status??'PROXIMITY / CATCHMENT',gaps=d.gaps.length?d.gaps.slice(0,3):['No surfaced review gap from the current LCP payload'],ratio=c.ratio||4.5,scenarios=[{name:'BASELINE',ratio:ratio,delta:'Current case'},{name:'LOWER INTENSITY',ratio:Math.max(.1,ratio-.5),delta:'−0.5 plot ratio'},{name:'HIGHER INTENSITY',ratio:ratio+.5,delta:'+0.5 plot ratio'}];p.innerHTML=`${css}<div class="fcr-head"><div><span class="fcr-kicker">CHAMPIONSHIP REVIEW LAYER · BATCH 2–7</span><h3>Planner Review & Decision Readiness</h3><p>One compact review surface connecting submission readiness, spatial interpretation, controlled What-If options and the next planner action.</p></div><span class="fcr-state">${esc(c.state||'STATE')} · ${esc(c.pbt||'PBT')}</span></div><div class="fcr-grid">
<article class="fcr-card"><h4>KM / OSC READINESS</h4><div class="fcr-row"><span>Evidence readiness</span><b>${readiness}%</b></div><div class="fcr-meter"><i style="width:${readiness}%"></i></div><div class="fcr-checks">${docs.map(x=>`<label><input type="checkbox" data-km-doc="${esc(x)}" ${checked.has(x)?'checked':''}>${esc(x)}</label>`).join('')}</div><p class="fcr-note">Workflow support only. PBT-specific checklist and statutory status require authority confirmation.</p></article>
<article class="fcr-card"><h4>SPATIAL → PLANNING IMPLICATION</h4><div class="fcr-option"><span class="fcr-tag">FLOOD</span><b>${esc(floodTxt)}</b><p>Use the flood signal as a screening constraint; confirm authoritative hazard mapping and site-specific engineering requirements.</p></div><div class="fcr-option"><span class="fcr-tag">ACCESS</span><b>${esc(roadTxt)}</b><p>Current accessibility is proximity/catchment-based. Do not represent it as pedestrian network travel time.</p></div><p class="fcr-note">The map remains the spatial evidence surface; this card interprets signals without inventing geometry.</p></article>
<article class="fcr-card"><h4>CONTROLLED WHAT-IF</h4><p>Choose an intensity option, then re-run the <b>same /assess engine</b> with the changed ratio. This is a screening experiment, not approval.</p><select id="fcr-scenario" class="fcr-select">${scenarios.map((x,i)=>`<option value="${i}">${x.name} · Plot Ratio ${x.ratio.toFixed(1)}</option>`).join('')}</select><div id="fcr-scenario-detail" class="fcr-option"></div><button id="fcr-scenario-run" class="fcr-run">RUN SELECTED SCENARIO</button><p class="fcr-note">The selected scenario is sent through the canonical assessment path so decision/output state can refresh from the same backend chain.</p></article>
<article class="fcr-card"><h4>NEXT ACTION / DECISION</h4><ul>${gaps.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="fcr-action">${data?.km_readiness?.readiness==='READY_FOR_WORKFLOW_REVIEW'?'Proceed to workflow review':'Resolve evidence / review gaps before workflow progression'}</div><p class="fcr-note">URBION provides decision support; it does not grant or predict statutory approval.</p></article>
</div>`;
const updateScenario=()=>{const x=scenarios[Number($('#fcr-scenario')?.value||0)],delta=x.ratio-ratio;$('#fcr-scenario-detail').innerHTML=`<div class="fcr-row"><span>Baseline</span><b>${ratio.toFixed(1)}</b></div><div class="fcr-row"><span>Selected</span><b>${x.ratio.toFixed(1)}</b></div><p>${delta===0?'No intensity change.':`${delta>0?'+':''}${delta.toFixed(1)} plot ratio. Run the canonical assessment before decision review.`}</p>`};
$('#fcr-scenario')?.addEventListener('change',updateScenario);updateScenario();$('#fcr-scenario-run')?.addEventListener('click',async()=>{const x=scenarios[Number($('#fcr-scenario')?.value||0)],b=$('#fcr-scenario-run');b.disabled=true;b.textContent='RUNNING CANONICAL ASSESSMENT…';try{if(typeof window.URBION_FINAL_RUN==='function'){await window.URBION_FINAL_RUN(x.ratio)}else{throw Error('Canonical assessment runner unavailable')} }finally{b.disabled=false;b.textContent='RUN SELECTED SCENARIO'}});
p.querySelectorAll('[data-km-doc]').forEach(i=>i.addEventListener('change',()=>{const set=new Set(Array.from(p.querySelectorAll('[data-km-doc]:checked')).map(x=>x.dataset.kmDoc));try{localStorage.setItem('urbion-km-docs',JSON.stringify([...set]))}catch(e){}render(window.__urbionAssessment||data)}));}
function boot(){const root=$('#urbion-final-command-centre');if(!root)return;document.addEventListener('urbion:lcp-intelligence',e=>render(e.detail));document.addEventListener('urbion:analysis',e=>{window.__urbionAssessment=e.detail;setTimeout(()=>render(e.detail),40)});document.addEventListener('urbion:unified-state',e=>setTimeout(()=>render(window.__urbionAssessment||e.detail||{}),40));setTimeout(()=>render(window.__urbionAssessment||window.__URBION_LCP_INTELLIGENCE||{}),250);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
