(()=>{'use strict';if(window.__URBION_PBT_CATALOG_V1__)return;window.__URBION_PBT_CATALOG_V1__=true;const P={
Johor:['Majlis Bandaraya Iskandar Puteri','Majlis Bandaraya Johor Bahru','Majlis Bandaraya Pasir Gudang','Majlis Daerah Kota Tinggi','Majlis Daerah Labis','Majlis Daerah Mersing','Majlis Daerah Simpang Renggam','Majlis Daerah Tangkak','Majlis Daerah Yong Peng','Majlis Perbandaran Batu Pahat','Majlis Perbandaran Kluang','Majlis Perbandaran Kulai','Majlis Perbandaran Muar','Majlis Perbandaran Pengerang','Majlis Perbandaran Pontian','Majlis Perbandaran Segamat'],
Kedah:['Majlis Bandaraya Alor Setar','Majlis Perbandaran Kubang Pasu','Majlis Perbandaran Kulim','Majlis Perbandaran Langkawi Bandaraya Pelancongan','Majlis Perbandaran Sungai Petani','Majlis Daerah Baling','Majlis Daerah Bandar Baharu','Majlis Daerah Padang Terap','Majlis Daerah Pendang','Majlis Daerah Sik','Majlis Daerah Yan'],
Kelantan:['Majlis Perbandaran Kota Bharu Bandaraya Islam','Majlis Daerah Bachok','Majlis Daerah Dabong','Majlis Daerah Gua Musang','Majlis Daerah Jeli','Majlis Daerah Ketereh','Majlis Daerah Kuala Krai','Majlis Daerah Machang','Majlis Daerah Pasir Mas','Majlis Daerah Pasir Puteh','Majlis Daerah Tanah Merah','Majlis Daerah Tumpat'],
Melaka:['Majlis Bandaraya Melaka Bersejarah','Majlis Perbandaran Alor Gajah','Majlis Perbandaran Hang Tuah Jaya','Majlis Perbandaran Jasin'],
'Negeri Sembilan':['Majlis Bandaraya Seremban','Majlis Perbandaran Jempol','Majlis Perbandaran Port Dickson','Majlis Daerah Jelebu','Majlis Daerah Kuala Pilah','Majlis Daerah Rembau','Majlis Daerah Tampin'],
Pahang:['Majlis Bandaraya Kuantan','Majlis Perbandaran Bentong','Majlis Perbandaran Pekan','Majlis Perbandaran Temerloh','Majlis Daerah Bera','Majlis Daerah Cameron Highlands','Majlis Daerah Jerantut','Majlis Daerah Lipis','Majlis Daerah Maran','Majlis Daerah Raub','Majlis Daerah Rompin'],
'Pulau Pinang':['Majlis Bandaraya Pulau Pinang','Majlis Bandaraya Seberang Perai'],
Perak:['Majlis Bandaraya Ipoh','Majlis Perbandaran Kuala Kangsar','Majlis Perbandaran Manjung','Majlis Perbandaran Taiping','Majlis Perbandaran Teluk Intan','Majlis Daerah Batu Gajah','Majlis Daerah Gerik','Majlis Daerah Kampar','Majlis Daerah Kerian','Majlis Daerah Lenggong','Majlis Daerah Pengkalan Hulu','Majlis Daerah Perak Tengah','Majlis Daerah Selama','Majlis Daerah Tanjong Malim','Majlis Daerah Tapah'],
Perlis:['Majlis Perbandaran Kangar'],
Selangor:['Majlis Bandaraya Diraja Klang','Majlis Bandaraya Petaling Jaya','Majlis Bandaraya Shah Alam','Majlis Bandaraya Subang Jaya','Majlis Daerah Sabak Bernam','Majlis Perbandaran Ampang Jaya','Majlis Perbandaran Hulu Selangor','Majlis Perbandaran Kajang','Majlis Perbandaran Kuala Langat','Majlis Perbandaran Kuala Selangor','Majlis Perbandaran Selayang','Majlis Perbandaran Sepang'],
Terengganu:['Majlis Bandaraya Kuala Terengganu','Majlis Perbandaran Dungun','Majlis Perbandaran Kemaman','Majlis Daerah Besut','Majlis Daerah Hulu Terengganu','Majlis Daerah Marang','Majlis Daerah Setiu'],
Sabah:['Dewan Bandaraya Kota Kinabalu','Lembaga Bandaran Kudat','Majlis Perbandaran Sandakan','Majlis Perbandaran Tawau','Majlis Daerah Beaufort','Majlis Daerah Beluran','Majlis Daerah Keningau','Majlis Daerah Kinabatangan','Majlis Daerah Kota Belud','Majlis Daerah Kota Marudu','Majlis Daerah Kuala Penyu','Majlis Daerah Kunak','Majlis Daerah Lahad Datu','Majlis Daerah Nabawan','Majlis Daerah Papar','Majlis Daerah Penampang','Majlis Daerah Pitas','Majlis Daerah Putatan','Majlis Daerah Ranau','Majlis Daerah Semporna','Majlis Daerah Sipitang','Majlis Daerah Tambunan','Majlis Daerah Telupid','Majlis Daerah Tenom','Majlis Daerah Tongod','Majlis Daerah Tuaran'],
Sarawak:['Dewan Bandaraya Kuching Utara','Majlis Bandaraya Kuching Selatan','Majlis Bandaraya Miri','Lembaga Kemajuan Bintulu (Perbandaran)','Majlis Daerah Bau','Majlis Daerah Betong','Majlis Daerah Dalat & Mukah','Majlis Daerah Gedong','Majlis Daerah Kanowit','Majlis Daerah Kapit','Majlis Daerah Lawas','Majlis Daerah Limbang','Majlis Daerah Lubok Antu','Majlis Daerah Lundu','Majlis Daerah Maradong & Julau','Majlis Daerah Marudi','Majlis Daerah Matu & Daro','Majlis Daerah Saratok','Majlis Daerah Sarikei','Majlis Daerah Serian','Majlis Daerah Simunjan','Majlis Daerah Sri Aman','Majlis Daerah Subis','Majlis Perbandaran Kota Samarahan','Majlis Perbandaran Padawan','Majlis Perbandaran Sibu'],
'W.P. Kuala Lumpur':['Dewan Bandaraya Kuala Lumpur'],'W.P. Labuan':['Perbadanan Labuan'],'W.P. Putrajaya':['Perbadanan Putrajaya']};
window.__URBION_PBT_CATALOG__=Object.freeze(P);
const esc=s=>String(s??'').replace(/[&<>\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[m]));
const visible=x=>!!x&&!!(x.offsetWidth||x.offsetHeight||x.getClientRects().length);
const rowByLabel=t=>{const n=t.toLowerCase();let fallback=null;for(const r of document.querySelectorAll('.sec .row')){const l=r.querySelector('.lab');if(!l||!l.textContent.trim().toLowerCase().includes(n))continue;fallback=fallback||r;const c=r.querySelector('input,select,textarea');if(visible(c))return r}return fallback};
const get=(id,label)=>{const row=rowByLabel(label);const rowControl=row?.querySelector('input:visible,select:visible,textarea:visible')||row?.querySelector('input,select,textarea');if(rowControl)return rowControl;return [document.getElementById('cs-'+id),document.getElementById(id)].find(Boolean)||null};
function ensureSelect(){let x=get('pbt','local authority');if(!x)return null;if(x.tagName==='SELECT')return x;const prev=String(x.value||'');const s=document.createElement('select');for(const a of ['id','name','class','required','disabled','autocomplete','aria-label'])if(x.hasAttribute(a))s.setAttribute(a,x.getAttribute(a));s.className=x.className||'select';s.dataset.pbtPreviousValue=prev;x.replaceWith(s);return s}
function stateKey(v){return ({'Wilayah Persekutuan':'W.P. Kuala Lumpur','W.Persekutuan':'W.P. Kuala Lumpur','W.P. Kuala Lumpur':'W.P. Kuala Lumpur','W.P. Labuan':'W.P. Labuan','W.P. Putrajaya':'W.P. Putrajaya','N.Sembilan':'Negeri Sembilan'}[v]||v)}
let syncing=false;let boundState=null;let boundPbt=null;function expectedOptions(state){return P[stateKey(state)]||[]}function isExpected(p,items){const vals=[...p.options].slice(1).map(o=>o.value);return vals.length===items.length&&vals.every((v,i)=>v===items[i])}function sync(){if(syncing)return;const s=get('state','state'),p=ensureSelect();if(!s||!p||!visible(s))return;const items=expectedOptions(s.value),prev=String(p.value||p.dataset.pbtPreviousValue||'');if(isExpected(p,items)){p.dataset.pbtCatalogOwner='urbion_workspace_pbt_catalog.js';p.dataset.pbtCount=String(items.length);p.dataset.pbtCanonicalControl='1';p.disabled=items.length===0;return}syncing=true;try{p.innerHTML='<option value="">Select Local Authority</option>'+items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(prev&&items.includes(prev))p.value=prev;p.dataset.pbtCount=String(items.length);p.dataset.pbtCatalogOwner='urbion_workspace_pbt_catalog.js';p.dataset.pbtCanonicalControl='1';p.disabled=items.length===0;p.dispatchEvent(new Event('input',{bubbles:true}))}finally{syncing=false}}
let bodyObserver=null;function tryBind(){const s=get('state','state'),p=ensureSelect();if(!s||!p||!visible(s))return false;if(boundState!==s){boundState=s;if(!s.dataset.urbionPbtBound){s.dataset.urbionPbtBound='1';s.addEventListener('change',sync)}}if(boundPbt!==p){boundPbt=p;p.dataset.pbtCatalogOwner='urbion_workspace_pbt_catalog.js';p.dataset.pbtCanonicalControl='1'}sync();return true}
function boot(){bodyObserver=new MutationObserver(()=>{if(!syncing)tryBind()});bodyObserver.observe(document.body,{childList:true,subtree:true});window.__URBION_PBT_CATALOG_BODY_OBSERVER__=bodyObserver;tryBind();let n=0;const tick=()=>{tryBind();if(n++<300)setTimeout(tick,100)};tick()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();
