(()=>{'use strict';if(window.__URBION_PBT_CATALOG_V2__)return;window.__URBION_PBT_CATALOG_V2__=true;const P={
Johor:['Majlis Bandaraya Iskandar Puteri','Majlis Bandaraya Johor Bahru','Majlis Bandaraya Pasir Gudang','Majlis Daerah Kota Tinggi','Majlis Daerah Labis','Majlis Daerah Mersing','Majlis Daerah Simpang Renggam','Majlis Daerah Tangkak','Majlis Daerah Yong Peng','Majlis Daerah Batu Pahat','Majlis Perbandaran Kluang','Majlis Perbandaran Kulai','Majlis Perbandaran Muar','Majlis Perbandaran Pengerang','Majlis Perbandaran Pontian','Majlis Perbandaran Segamat'],
Kedah:['Majlis Bandaraya Alor Setar','Majlis Perbandaran Kubang Pasu','Majlis Perbandaran Kulim','Majlis Perbandaran Langkawi Bandaraya Pelancongan','Majlis Perbandaran Sungai Petani','Majlis Daerah Baling','Majlis Daerah Bandar Baharu','Majlis Daerah Padang Terap','Majlis Daerah Pendang','Majlis Daerah Sik','Majlis Daerah Yan'],
Kelantan:['Majlis Perbandaran Kota Bharu Bandaraya Islam','Majlis Daerah Bachok','Majlis Daerah Dabong','Majlis Daerah Gua Musang','Majlis Daerah Jeli','Majlis Daerah Ketereh','Majlis Daerah Kuala Krai','Majlis Daerah Machang','Majlis Daerah Pasir Mas','Majlis Daerah Pasir Puteh','Majlis Daerah Tanah Merah','Majlis Daerah Tumpat'],
Melaka:['Majlis Bandaraya Melaka Bersejarah','Majlis Perbandaran Alor Gajah','Majlis Perbandaran Hang Tuah Jaya','Majlis Perbandaran Jasin'],
'Negeri Sembilan':['Majlis Bandaraya Seremban','Majlis Perbandaran Jempol','Majlis Perbandaran Port Dickson','Majlis Daerah Jelebu','Majlis Daerah Kuala Pilah','Majlis Daerah Rembau','Majlis Daerah Tampin'],
Pahang:['Majlis Bandaraya Kuantan','Majlis Perbandaran Bentong','Majlis Perbandaran Pekan','Majlis Perbandaran Temerloh','Majlis Daerah Bera','Majlis Daerah Cameron Highlands','Majlis Daerah Jerantut','Majlis Daerah Lipis','Majlis Daerah Maran','Majlis Daerah Raub','Majlis Daerah Rompin'],
'Pulau Pinang':['Majlis Bandaraya Pulau Pinang','Majlis Bandaraya Seberang Perai'],
Perak:['Majlis Bandaraya Ipoh','Majlis Perbandaran Kuala Kangsar','Majlis Perbandaran Manjung','Majlis Perbandaran Taiping','Majlis Perbandaran Teluk Intan','Majlis Daerah Batu Gajah','Majlis Daerah Gerik','Majlis Daerah Kampar','Majlis Daerah Kerian','Majlis Daerah Lenggong','Majlis Daerah Pengkalan Hulu','Majlis Daerah Perak Tengah','Majlis Daerah Selama','Majlis Daerah Tanjong Malim','Majlis Daerah Tapah'],
Perlis:['Majlis Perbandaran Kangar'],
Selangor:['Majlis Bandaraya Diraja Klang','Majlis Bandaraya Petaling Jaya','Majlis Bandaraya Shah Alam','Majlis Bandaraya Subang Jaya','Majlis Daerah Sabak Bernam','Majlis Perbandaran Ampang Jaya','Majlis Perbandaran Hulu Selangor','Majlis Perbandaran Kajang','Majlis Perbandaran Kuala Langat','Majlis Perbandaran Kuala Selangor','Majlis Perbandaran Selayang','Majlis Perbandaran Sepang'],
Terengganu:['Majlis Bandaraya Kuala Terengganu','Majlis Perbandaran Dungun','Majlis Perbandaran Kemaman','Majlis Daerah Besut','Majlis Daerah Hulu Terengganu','Majlis Daerah Marang','Majlis Daerah Setiu'],
Sabah:['Dewan Bandaraya Kota Kinabalu','Lembaga Bandaran Kudat','Majlis Perbandaran Sandakan','Majlis Perbandaran Tawau','Majlis Daerah Beaufort','Majlis Daerah Beluran','Majlis Daerah Keningau','Majlis Daerah Kinabatangan','Majlis Daerah Kota Belud','Majlis Daerah Kota Marudu','Majlis Daerah Kuala Penyu','Majlis Daerah Kunak','Majlis Daerah Lahad Datu','Majlis Daerah Nabawan','Majlis Daerah Papar','Majlis Daerah Penampang','Majlis Daerah Pitas','Majlis Daerah Putatan','Majlis Daerah Ranau','Majlis Daerah Semporna','Majlis Daerah Sipitang','Majlis Daerah Tambunan','Majlis Daerah Telupid','Majlis Daerah Tenom','Majlis Daerah Tongod','Majlis Daerah Tuaran'],
Sarawak:['Dewan Bandaraya Kuching Utara','Majlis Bandaraya Kuching Selatan','Majlis Bandaraya Miri','Lembaga Kemajuan Bintulu (Perbandaran)','Majlis Daerah Bau','Majlis Daerah Betong','Majlis Daerah Dalat & Mukah','Majlis Daerah Gedong','Majlis Daerah Kanowit','Majlis Daerah Kapit','Majlis Daerah Lawas','Majlis Daerah Limbang','Majlis Daerah Lubok Antu','Majlis Daerah Lundu','Majlis Daerah Maradong & Julau','Majlis Daerah Marudi','Majlis Daerah Matu & Daro','Majlis Daerah Saratok','Majlis Daerah Sarikei','Majlis Daerah Serian','Majlis Daerah Simunjan','Majlis Daerah Sri Aman','Majlis Daerah Subis','Majlis Perbandaran Kota Samarahan','Majlis Perbandaran Padawan','Majlis Perbandaran Sibu'],
'W.P. Kuala Lumpur':['Dewan Bandaraya Kuala Lumpur'],'W.P. Labuan':['Perbadanan Labuan'],'W.P. Putrajaya':['Perbadanan Putrajaya']};
const DISTRICTS={
Johor:['Batu Pahat','Johor Bahru','Kluang','Kota Tinggi','Kulai','Mersing','Muar','Pontian','Segamat','Tangkak'],Kedah:['Baling','Bandar Baharu','Kota Setar','Kubang Pasu','Kulim','Langkawi','Padang Terap','Pendang','Sik','Yan'],Kelantan:['Bachok','Gua Musang','Jeli','Kota Bharu','Kuala Krai','Machang','Pasir Mas','Pasir Puteh','Tanah Merah','Tumpat'],Melaka:['Alor Gajah','Jasin','Melaka Tengah'],'Negeri Sembilan':['Jelebu','Jempol','Kuala Pilah','Port Dickson','Rembau','Seremban','Tampin'],Pahang:['Bera','Bentong','Cameron Highlands','Jerantut','Kuantan','Lipis','Maran','Pekan','Raub','Rompin','Temerloh'],'Pulau Pinang':['Barat Daya','Timur Laut','Seberang Perai Selatan','Seberang Perai Tengah','Seberang Perai Utara'],Perak:['Bagan Datuk','Batang Padang','Hilir Perak','Hulu Perak','Kampar','Kerian','Kinta','Kuala Kangsar','Larut Matang dan Selama','Manjung','Muallim','Perak Tengah'],Perlis:['Perlis'],Selangor:['Gombak','Hulu Langat','Hulu Selangor','Klang','Kuala Langat','Kuala Selangor','Petaling','Sabak Bernam','Sepang'],Terengganu:['Besut','Dungun','Kemaman','Kuala Nerus','Kuala Terengganu','Marang','Setiu','Hulu Terengganu'],Sabah:['Beaufort','Beluran','Kalabakan','Keningau','Kinabatangan','Kota Belud','Kota Kinabalu','Kota Marudu','Kuala Penyu','Kunak','Lahad Datu','Nabawan','Papar','Penampang','Pitas','Putatan','Ranau','Sandakan','Semporna','Sipitang','Tambunan','Tawau','Telupid','Tenom','Tongod','Tuaran'],Sarawak:['Betong','Bintulu','Kapit','Kuching','Limbang','Lawas','Miri','Mukah','Padawan','Samarahan','Saratok','Sarikei','Serian','Sibu','Sri Aman','Marudi'],'W.P. Kuala Lumpur':['Kuala Lumpur'],'W.P. Labuan':['Labuan'],'W.P. Putrajaya':['Putrajaya']};
window.__URBION_PBT_CATALOG__=Object.freeze(P);window.__URBION_DISTRICT_CATALOG__=Object.freeze(DISTRICTS);
const esc=s=>String(s??'').replace(/[&<>\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[m]));
const visible=x=>!!x&&!!(x.offsetWidth||x.offsetHeight||x.getClientRects().length);
const rowByLabel=t=>{const n=t.toLowerCase();let fallback=null;for(const r of document.querySelectorAll('.sec .row')){const l=r.querySelector('.lab');if(!l||!l.textContent.trim().toLowerCase().includes(n))continue;fallback=fallback||r;const c=r.querySelector('input,select,textarea');if(visible(c))return r}return fallback};
const get=(id,label)=>{const row=rowByLabel(label);const candidates=row?[...row.querySelectorAll('input,select,textarea')]:[];const rowControl=candidates.find(visible)||candidates[0]||null;if(rowControl)return rowControl;return [document.getElementById('cs-'+id),document.getElementById(id)].find(Boolean)||null};
function ensureSelect(x){if(!x)return null;if(x.tagName==='SELECT')return x;const prev=String(x.value||'');const s=document.createElement('select');for(const a of ['id','name','class','required','disabled','autocomplete','aria-label'])if(x.hasAttribute(a))s.setAttribute(a,x.getAttribute(a));s.className=x.className||'select';s.dataset.pbtPreviousValue=prev;x.replaceWith(s);return s}
function stateKey(v){return ({'Wilayah Persekutuan':'W.P. Kuala Lumpur','W.Persekutuan':'W.P. Kuala Lumpur','N.Sembilan':'Negeri Sembilan'}[v]||v)}
function options(select){return select?[...select.options].map(o=>String(o.value||o.textContent||'').trim()).filter(Boolean):[]}
let syncing=false;
function expectedOptions(state){return P[stateKey(state)]||[]}
function syncPbt(){if(syncing)return;const s=get('state','state'),p=ensureSelect(get('pbt','local authority'));if(!s||!p||!visible(s))return false;const items=expectedOptions(s.value),prev=String(p.value||p.dataset.pbtPreviousValue||'');if(options(p).slice(1).join('|')===items.join('|')){p.dataset.pbtCatalogOwner='urbion_workspace_pbt_catalog.js';p.dataset.pbtCount=String(items.length);p.dataset.pbtCanonicalControl='1';return true}syncing=true;try{p.innerHTML='<option value="">Select Local Authority</option>'+items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(prev&&items.includes(prev))p.value=prev;p.dataset.pbtCount=String(items.length);p.dataset.pbtCatalogOwner='urbion_workspace_pbt_catalog.js';p.dataset.pbtCanonicalControl='1';p.dispatchEvent(new Event('input',{bubbles:true}))}finally{syncing=false}return true}
function syncDistrictFallback(){if(syncing)return false;const s=ensureSelect(get('state','state')),d=ensureSelect(get('district','district'));if(!s||!d||!visible(s))return false;const items=DISTRICTS[stateKey(s.value)]||[];if(!items.length)return false;const current=options(d).slice(1),prev=String(d.value||d.dataset.geoPreviousValue||'');const same=current.length===items.length&&current.every((v,i)=>v===items[i]);if(same){d.dataset.geoFallback='1';d.dataset.geoFallbackSource='URBION_LOCAL_ADMIN_CATALOG';d.dataset.urbionDistrictOwner='urbion_workspace_pbt_catalog.js';return true}syncing=true;try{d.innerHTML='<option value="">Select District</option>'+items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(prev&&items.includes(prev))d.value=prev;d.dataset.geoFallback='1';d.dataset.geoFallbackSource='URBION_LOCAL_ADMIN_CATALOG';d.dataset.urbionDistrictOwner='urbion_workspace_pbt_catalog.js';d.dispatchEvent(new Event('input',{bubbles:true}));return true}finally{syncing=false}}
function syncAll(){syncPbt();syncDistrictFallback()}
function boot(){const root=document.querySelector('.leftscroll');if(!root)return;const bind=()=>{const s=ensureSelect(get('state','state'));ensureSelect(get('pbt','local authority'));ensureSelect(get('district','district'));if(s&&!s.dataset.urbionPbtBoundV2){s.dataset.urbionPbtBoundV2='1';s.addEventListener('change',()=>{syncAll()},{capture:true});}syncAll()};bind();setTimeout(bind,80);setTimeout(bind,300);setTimeout(bind,700);setTimeout(bind,1200);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();