(()=>{
'use strict';
if(window.__URBION_UNIFIED_WORKSPACE_BRIDGE)return;window.__URBION_UNIFIED_WORKSPACE_BRIDGE=true;
const $=id=>document.getElementById(id);
const state=window.__URBION_UNIFIED_STATE={inputs:{},lot:null,spatial:null,assessment:null,decision:null,whatIf:null,updatedAt:null};
let lotLayer=null;
function map(){const n=$('ss-map');return n?.__urbionMap||(window.__URBION_MAPS||[]).find(x=>x&&x.getContainer&&x.getContainer()===n)||null}
function set(id,value){const e=$(id);if(e&&value!=null)e.textContent=String(value)}
function inputSnapshot(){return window.URBION?.getAssessmentPayload?.()||Object.fromEntries(['lat','lon','todlat','todlon','state','pbt','devtype','devclass','ratio','lot'].map(id=>[id,$(id)?.value||'']))}
function spatialSummary(d){const layers=d?.layers||[];const live=layers.filter(x=>x.status==='LIVE_QUERY');const hits=live.filter(x=>Number(x.feature_count||0)>0);const gaps=layers.filter(x=>['QUERY_ERROR','NOT_CONFIGURED','EVIDENCE_GAP'].includes(String(x.status||'').toUpperCase()));return{total:layers.length,live:live.length,hits:hits.length,gaps:gaps.length}}
function renderLotGeometry(d){const m=map(),g=d?.selected?.geometry;if(!m||!g||!window.L)return;if(lotLayer){try{m.removeLayer(lotLayer)}catch(e){}lotLayer=null}lotLayer=L.geoJSON(g,{style:()=>({color:'#43e5bd',weight:3,opacity:.95,fillOpacity:.06,dashArray:'7 6',interactive:false})});lotLayer.addTo(m)}
function render(){const p=state.spatialSummary||{total:0,live:0,hits:0,gaps:0};const lot=state.lot?.selected?.identity||{};const lotVerified=state.lot?.status==='VERIFIED_CANDIDATE';const analysed=!!state.assessment;const decisionText=state.decision?.decision||state.decision?.status||$('decisionStatus')?.textContent?.trim()||'';set('ux5-site',lot.lot_no?`Lot ${lot.lot_no}`:($('site-name')?.textContent||'Selected planning site'));set('ux5-authority',lotVerified?`${lot.district||$('pbt')?.value||'Local authority'} · lot candidate verified · JUPEM check required`:$('pbt')?.value||'Local authority required');const evidenceState=lotVerified&&p.hits?`LOT + GIS ${p.hits} HIT${p.hits===1?'':'S'}`:p.hits?`GIS ${p.hits} HIT${p.hits===1?'':'S'}`:lotVerified?'LOT CANDIDATE':'WAITING';set('ux5-evidence-state',evidenceState);if(p.live||p.total)set('ux5-source-count',`${p.live}/${p.total}`);if(decisionText&&/approved|reject|review|decision|conditional/i.test(decisionText))set('ux5-next-title','Review decision evidence');else if(state.whatIf)set('ux5-next-title','Compare the What-If delta');else if(analysed)set('ux5-next-title','Review evidence before deciding');else if(lotVerified||p.hits)set('ux5-next-title','Run site analysis');else set('ux5-next-title','Define the planning case');const copy=lotVerified?`Official i-Plan lot candidate linked to the case. JUPEM cadastral verification is still required.`:p.hits?`${p.hits} mapped GIS source${p.hits===1?'':'s'} returned geometry. Review the relationships before testing an option.`:analysed?'Assessment is complete. Inspect evidence, then move to What-If or Decision.':'Complete the case inputs to build the evidence chain.';set('ux5-next-copy',copy);const btn=$('ux5-next-btn');if(btn&&!btn.dataset.unifiedBound){btn.dataset.unifiedBound='1';btn.onclick=()=>{if(state.whatIf)document.querySelector('.nav button[data-view="decision"]')?.click();else if(analysed)document.querySelector('.nav button[data-view="evidence"]')?.click();else $('run')?.click()}};const readiness=$('ux5-readiness-note');if(readiness)readiness.textContent=lotVerified?`Lot identity linked. ${p.hits} live GIS relationship${p.hits===1?'':'s'} available; cadastral authority remains external.`:p.hits?`${p.hits} live GIS relationship${p.hits===1?'':'s'} available from the spatial evidence scan.`:analysed?'Analysis complete. Continue through evidence → What-If → decision.':'Complete the case and run analysis to build the evidence chain.';window.dispatchEvent(new CustomEvent('urbion:unified-workspace',{detail:state}))}
function ingestInputs(e){state.inputs=e?.detail?.inputs||inputSnapshot();state.updatedAt=Date.now();render()}
function ingestLot(e){state.lot=e.detail||null;renderLotGeometry(state.lot);render()}
function ingestSpatial(e){state.spatial=e.detail||null;state.spatialSummary=spatialSummary(state.spatial);render()}
function ingestAssessment(e){state.assessment=e.detail||null;state.updatedAt=Date.now();render()}
function observeDecision(){const panel=$('decisionPanel');if(!panel||panel.__unifiedObserved)return;panel.__unifiedObserved=true;const refresh=()=>{state.decision={status:$('decisionStatus')?.textContent?.trim()||'',score:$('score')?.textContent?.trim()||'',context:$('context')?.textContent?.trim()||''};state.whatIf={visible:!!document.querySelector('#whatif, #what-if, [data-what-if], .what-if')};render()};new MutationObserver(refresh).observe(panel,{subtree:true,childList:true,characterData:true});refresh()}
function boot(){window.addEventListener('urbion:inputs-ready',ingestInputs);window.addEventListener('urbion:inputs-change',ingestInputs);window.addEventListener('urbion:lot-resolved',ingestLot);window.addEventListener('urbion:spatial-context-ready',ingestSpatial);window.addEventListener('urbion:spatial-context',ingestSpatial);window.addEventListener('urbion:analysis',ingestAssessment);window.addEventListener('urbion:unified-refresh',render);ingestInputs();observeDecision();setTimeout(observeDecision,800);setTimeout(observeDecision,1800);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();