(()=>{
'use strict';
if(window.__URBION_VISUAL_OVERHAUL_V2)return;window.__URBION_VISUAL_OVERHAUL_V2=true;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=`
:root{--uo-bg:#06131c;--uo-panel:#0b1c27;--uo-line:#234455;--uo-text:#edf8fb;--uo-muted:#89a5b4;--uo-accent:#43e5bd;--uo-cyan:#18cce5;--uo-warn:#ffc857;--uo-shadow:0 18px 55px rgba(0,0,0,.28)}
body.uo-clean .header{height:76px;padding:0 24px;background:rgba(5,16,25,.96);backdrop-filter:blur(18px)}
body.uo-clean .header .logo{background:none;width:188px;height:52px;border-radius:0;display:block;background-image:url('/urbion_logo_dark.svg');background-size:contain;background-repeat:no-repeat;background-position:left center;color:transparent}
body.urbion-light.uo-clean .header .logo{background-image:url('/urbion_logo_light.svg')}
body.uo-clean .header .brand{gap:0}.uo-brand-sub{display:none}.uo-clean .nav{gap:6px;margin-bottom:12px}.uo-clean .nav button{border-radius:999px;padding:8px 13px;background:#081923}
#urbion-workstation-v2,#urbion-decision-os{display:none!important}
#uo-statusbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0 0 12px;padding:9px 12px;border:1px solid var(--uo-line);border-radius:12px;background:linear-gradient(90deg,rgba(67,229,189,.08),rgba(24,204,229,.04));font-size:8px;color:var(--uo-muted)}
#uo-statusbar .uo-live{display:flex;align-items:center;gap:7px;color:var(--uo-accent);font-weight:900;letter-spacing:.08em}.uo-dot{width:7px;height:7px;border-radius:50%;background:var(--uo-accent);box-shadow:0 0 12px var(--uo-accent)}#uo-statusbar button{border:1px solid var(--uo-line);border-radius:999px;background:#07151e;color:var(--uo-text);padding:6px 9px;font-size:7px;font-weight:900;cursor:pointer}
#spatial-studio{margin-top:12px!important;border-radius:18px!important;border-color:#315467!important;background:linear-gradient(145deg,#081822,#06121a)!important;box-shadow:var(--uo-shadow)!important}#spatial-studio .ss-head{padding:15px 16px!important}.ss-head h2{font-size:20px!important}.ss-actions button{border-radius:999px!important;padding:8px 11px!important}.ss-map{height:560px!important;position:relative}.ss-panel{max-height:560px!important;padding:12px!important}
#uo-map-hud{position:absolute;left:12px;top:12px;z-index:900;display:flex;gap:6px;flex-wrap:wrap;max-width:calc(100% - 24px);pointer-events:none}.uo-hud-chip{padding:7px 9px;border:1px solid rgba(67,229,189,.28);border-radius:999px;background:rgba(5,18,27,.88);backdrop-filter:blur(10px);color:#dff6f2;font:800 7px Inter;letter-spacing:.04em;box-shadow:0 8px 25px rgba(0,0,0,.18)}
#uo-layer-dock{position:absolute;right:12px;top:12px;z-index:901;width:min(318px,calc(100% - 24px));max-height:calc(100% - 24px);border:1px solid rgba(36,68,85,.95);border-radius:14px;background:rgba(5,18,27,.94);backdrop-filter:blur(14px);box-shadow:0 12px 32px rgba(0,0,0,.26);overflow:hidden}.uo-dock-head{padding:10px 11px;border-bottom:1px solid #234455;display:flex;justify-content:space-between;align-items:center}.uo-dock-head b{font-size:8px;letter-spacing:.08em}.uo-dock-head span{font-size:6px;color:#7f9baa}.uo-dock-head button{border:0;background:transparent;color:#89a5b4;font-weight:900;cursor:pointer;font-size:13px}.uo-dock-body{padding:8px;display:grid;gap:7px;max-height:500px;overflow:auto}.uo-group{border:1px solid #1d3848;border-radius:10px;overflow:hidden}.uo-group-head{padding:7px 8px;background:#081923;display:flex;justify-content:space-between;align-items:center}.uo-group-head b{font-size:7px;letter-spacing:.08em}.uo-group-head small{font-size:6px;color:#6f8997}.uo-layer-row{display:grid;grid-template-columns:auto 1fr auto;gap:7px;align-items:center;padding:7px 8px;border-top:1px solid #16303e;background:#07151e;color:#dcecf0;font-size:7px}.uo-layer-row input{accent-color:var(--uo-accent)}.uo-layer-row small{color:#7592a2;text-align:right;font-size:6px}.uo-layer-row.is-active{background:rgba(67,229,189,.07)}.uo-layer-row .uo-source{color:#7592a2;display:block;font-size:6px;margin-top:2px}.uo-empty{padding:8px;color:#718b98;font-size:7px;line-height:1.4}.uo-boundary{padding:8px;border-top:1px solid #1d3848;color:#7894a1;font-size:6px;line-height:1.45}
#uo-legend{display:flex;gap:5px;flex-wrap:wrap;margin:8px 0 0}.uo-legend-chip{padding:5px 7px;border:1px solid #254858;border-radius:999px;background:#071720;color:#a6bbc4;font-size:6px;font-weight:900}.uo-legend-chip b{color:#43e5bd}.uo-ring-label{padding:4px 6px;border:1px solid rgba(67,229,189,.35);border-radius:999px;background:rgba(5,18,27,.9);color:#d9f8f0;font:800 7px Inter;box-shadow:0 5px 15px rgba(0,0,0,.2)}
.leaflet-container .uo-site-pin,.leaflet-container .uo-tod-pin{display:grid;place-items:center;width:34px;height:34px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);border:2px solid #fff;box-shadow:0 5px 16px rgba(0,0,0,.35)}.uo-site-pin i,.uo-tod-pin i{display:block;width:11px;height:11px;border-radius:50%;background:#fff}.uo-site-pin{background:linear-gradient(135deg,#18cce5,#43e5bd)}.uo-tod-pin{background:linear-gradient(135deg,#ffc857,#ff8f5a)}.uo-pin-label{font:900 8px Inter;letter-spacing:.03em}
@media(max-width:900px){#spatial-studio .ss-grid{grid-template-columns:1fr!important}.ss-panel{max-height:none!important}.ss-map{height:470px!important}#uo-layer-dock{width:min(300px,calc(100% - 24px))}}@media(max-width:600px){body.uo-clean .header .logo{width:155px}#uo-layer-dock{top:54px;left:12px;right:12px;width:auto;max-height:calc(100% - 66px)}#uo-map-hud{right:12px}}
`;
const st=document.createElement('style');st.id='urbion-visual-overhaul-v2-style';st.textContent=css;document.head.appendChild(st);
function waitFor(fn,tries=100){if(fn())return;if(tries>0)setTimeout(()=>waitFor(fn,tries-1),100)}
function cleanBrand(){document.body.classList.add('uo-clean')}
function addStatus(){if($('uo-statusbar'))return;const nav=$('nav');if(!nav)return;const el=document.createElement('div');el.id='uo-statusbar';el.innerHTML='<div class="uo-live"><i class="uo-dot"></i> LIVE PLANNING EVIDENCE <span style="opacity:.5">·</span> source-aware map online</div><button id="uo-density">COMPACT UI</button>';nav.insertAdjacentElement('afterend',el);$('uo-density').onclick=()=>document.body.classList.toggle('uo-compact')}
function category(x){const s=((x.name||x.id||'')+' '+(x.group||'')+' '+(x.type||'')).toLowerCase();if(/zoning|land use|guna tanah|committed|planning|housing|heritage/.test(s))return s.includes('heritage')?'HERITAGE':'PLANNING / LAND USE';if(/flood|water|river|drain|hazard|ksas|environment|eco|green|forest/.test(s))return'ENVIRONMENT / HAZARD';if(/road|transport|rail|transit|bus|network|mobility/.test(s))return'MOBILITY';if(/geology|fault|quarry|groundwater|lithology|seismic|mineral|topo|terrain/.test(s))return'TERRAIN / GEOLOGY';return'SPATIAL CONTEXT'}
function sourceStatus(x){return String(x?.status||x?.evidence_status||x?.evidence||x?.source_status||'SOURCE CONTEXT').toUpperCase()}
function addIcon(className){return L.divIcon({className:'',html:`<div class="${className}"><i></i></div>`,iconSize:[34,34],iconAnchor:[17,34],popupAnchor:[0,-30]})}
function makeEvidenceLayer(x,opacity){if(!x||!window.L)return null;if(x.type==='GEOSERVER_WMS'&&x.url&&x.layers)return L.tileLayer.wms(x.url,{layers:x.layers,transparent:true,format:'image/png',version:'1.1.1',opacity,attribution:x.name||'Declared source'});if(x.type==='TILE'&&x.url)return L.tileLayer(x.url,{opacity,attribution:x.name||'Declared source'});if(x.type==='ARCGIS_MAP'&&x.url){const base=x.url.replace(/\/$/,'').replace(/\/MapServer.*$/,'/MapServer');return L.tileLayer(base+'/tile/{z}/{y}/{x}',{opacity,attribution:x.name||'Declared source',maxZoom:19})}return null}
function setupMap(){const mapNode=$('ss-map');if(!mapNode||!window.L||mapNode.__uoV2Ready)return false;const m=mapNode.__urbionMap||(window.__URBION_MAPS||[]).find(x=>x&&x.getContainer&&x.getContainer()===mapNode)||mapNode._leaflet_map_instance||mapNode.__leaflet_map;if(!m)return false;mapNode.__uoV2Ready=true;
const s=()=>({lat:parseFloat($('lat')?.value),lon:parseFloat($('lon')?.value),todlat:parseFloat($('todlat')?.value),todlon:parseFloat($('todlon')?.value)});const hav=(a,b,c,d)=>{const R=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,z=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(z))};
const evidence=new Map();const rings=new Map();
const site=L.marker([s().lat,s().lon],{icon:addIcon('uo-site-pin'),zIndexOffset:1000}).addTo(m).bindTooltip('<span class="uo-pin-label">SCREENING SITE</span>',{direction:'top'});const tod=L.marker([s().todlat,s().todlon],{icon:addIcon('uo-tod-pin'),zIndexOffset:990}).addTo(m).bindTooltip('<span class="uo-pin-label">TOD REFERENCE</span>',{direction:'top'});
const ringSpecs=[[400,'400 m',.055,2],[800,'800 m',.03,2],[1000,'1 km',.016,1],[1500,'1.5 km',.01,1]];ringSpecs.forEach(([r,label,fill,w])=>{const c=L.circle([s().lat,s().lon],{radius:r,color:r<=800?'#43e5bd':'#18cce5',weight:w,opacity:.7,fillOpacity:fill,interactive:false}).addTo(m);rings.set(String(r),c);const lab=L.marker([s().lat,s().lon],{icon:L.divIcon({className:'',html:`<span class="uo-ring-label">${label}</span>`,iconSize:[70,20],iconAnchor:[35,10]}),interactive:false}).addTo(m);rings.set(String(r)+'label',lab)});
const link=L.polyline([[s().lat,s().lon],[s().todlat,s().todlon]],{color:'#ffc857',weight:3,dashArray:'8 7',opacity:.9}).addTo(m);
const hud=document.createElement('div');hud.id='uo-map-hud';hud.innerHTML='<span class="uo-hud-chip">SITE <b>ACTIVE</b></span><span class="uo-hud-chip">TOD DISTANCE <b data-metric="distance">—</b></span><span class="uo-hud-chip">RINGS <b>4</b></span><span class="uo-hud-chip">SOURCE LAYERS <b data-metric="layers">0</b></span>';mapNode.appendChild(hud);
const dock=document.createElement('div');dock.id='uo-layer-dock';dock.innerHTML='<div class="uo-dock-head"><div><b>MAP EVIDENCE</b><span> · LIVE / DECLARED SOURCE CONTEXT</span></div><button type="button" id="uo-dock-toggle">−</button></div><div class="uo-dock-body" id="uo-dock-body"><div id="uo-layer-groups"></div><div class="uo-boundary"><b>EVIDENCE BOUNDARY:</b> calculated rings are deterministic screening geometry. Rendered WMS/ArcGIS layers are source context only; they do not prove parcel applicability, currency or statutory approval.</div></div>';mapNode.appendChild(dock);
$('uo-dock-toggle').onclick=()=>{const body=$('uo-dock-body');body.style.display=body.style.display==='none'?'grid':'none';$('uo-dock-toggle').textContent=body.style.display==='none'?'+':'−'};
function sync(){const v=s();if(![v.lat,v.lon,v.todlat,v.todlon].every(Number.isFinite))return;site.setLatLng([v.lat,v.lon]);tod.setLatLng([v.todlat,v.todlon]);ringSpecs.forEach(([r])=>{rings.get(String(r))?.setLatLng([v.lat,v.lon]);rings.get(String(r)+'label')?.setLatLng([v.lat,v.lon])});link.setLatLngs([[v.lat,v.lon],[v.todlat,v.todlon]]);const d=hav(v.lat,v.lon,v.todlat,v.todlon);const el=hud.querySelector('[data-metric="distance"]');if(el)el.textContent=d<1000?Math.round(d)+' m':(d/1000).toFixed(2)+' km'}
function renderGroups(list){const host=$('uo-layer-groups');if(!host)return;const renderable=list.filter(x=>['GEOSERVER_WMS','TILE','ARCGIS_MAP'].includes(x.type)&&x.id!=='osm');const groups={};renderable.forEach(x=>(groups[category(x)]??=[]).push(x));const order=['PLANNING / LAND USE','ENVIRONMENT / HAZARD','MOBILITY','HERITAGE','TERRAIN / GEOLOGY','SPATIAL CONTEXT'];host.innerHTML=order.filter(k=>groups[k]?.length).map(k=>`<div class="uo-group"><div class="uo-group-head"><b>${k}</b><small>${groups[k].length} SOURCE${groups[k].length===1?'':'S'}</small></div>${groups[k].map(x=>`<label class="uo-layer-row"><input type="checkbox" data-evidence="${esc(x.id)}"><span>${esc(x.name||x.id)}<span class="uo-source">${esc(sourceStatus(x))}</span></span><small>MAP</small></label>`).join('')}</div>`).join('')||'<div class="uo-empty">No declared browser-renderable evidence layers are available for this state.</div>';
renderable.forEach(x=>{const cb=host.querySelector(`input[data-evidence="${CSS.escape(x.id)}"]`);if(!cb)return;cb.onchange=()=>{const row=cb.closest('.uo-layer-row');if(!cb.checked){const old=evidence.get(x.id);if(old)m.removeLayer(old);evidence.delete(x.id);row.classList.remove('is-active')}else{const layer=makeEvidenceLayer(x,.62);if(layer){layer._urbionEvidenceId=x.id;layer.addTo(m);evidence.set(x.id,layer);row.classList.add('is-active')}else{cb.checked=false}};const count=hud.querySelector('[data-metric="layers"]');if(count)count.textContent=evidence.size}});
const defaults=renderable.filter(x=>x.id==='iplan-current');defaults.forEach(x=>{const cb=host.querySelector(`input[data-evidence="${CSS.escape(x.id)}"]`);if(cb){cb.checked=true;cb.dispatchEvent(new Event('change'))}});
}
async function loadSources(){try{const state=encodeURIComponent($('state')?.value||'Melaka');const r=await fetch('/map/layers?state='+state,{cache:'no-store'});if(!r.ok)throw Error(r.status);const data=await r.json();renderGroups(data.layers||[])}catch(e){const host=$('uo-layer-groups');if(host)host.innerHTML='<div class="uo-empty">Source catalogue unavailable. Basemap and calculated screening geometry remain available; no source layer has been fabricated.</div>'}}
sync();m.on('zoomend',sync);window.addEventListener('urbion:site-change',sync);loadSources();return true}
function compactLegacy(){document.querySelectorAll('#spatial-studio .ss-actions button').forEach(b=>{if(b.id==='ss-clear')b.style.display='none'});const layerPanel=document.querySelector('#spatial-studio #ss-layers');if(layerPanel){const section=layerPanel.closest('.ss-section');if(section)section.style.display='none'}}
function run(){cleanBrand();addStatus();compactLegacy();return setupMap()}
waitFor(run);})();