/* URBION shared UI controller: bilingual labels + resilient light/dark/system theme. */
(function(){
  const KEY_LANG='urbion-lang',KEY_THEME='urbion-theme';
  const dict={en:{language:'Language',dark:'Dark mode',light:'Light mode',system:'System',layers:'Map layers',basemap:'Basemap',planning:'Planning',cadastre:'Cadastre',terrain:'Terrain',geology:'Geology',environment:'Environment',source:'Source context',verify:'Planner verification required',current:'Current land use',zoning:'Zoning',committed:'Committed land use',lot:'Cadastral lot',contour:'5m contours',lcp:'LCP Intelligence'},ms:{language:'Bahasa',dark:'Mod gelap',light:'Mod cerah',system:'Sistem',layers:'Lapisan peta',basemap:'Peta asas',planning:'Perancangan',cadastre:'Kadaster',terrain:'Bentuk muka bumi',geology:'Geologi',environment:'Alam sekitar',source:'Konteks sumber',verify:'Pengesahan perancang diperlukan',current:'Guna tanah semasa',zoning:'Zon guna tanah',committed:'Guna tanah komited',lot:'Lot kadaster',contour:'Kontur 5m',lcp:'Inteligens LCP'}};
  function lang(){return localStorage.getItem(KEY_LANG)||'en'}
  function theme(){return localStorage.getItem(KEY_THEME)||'system'}
  function apply(){const l=lang(),t=theme();document.documentElement.dataset.lang=l;document.documentElement.dataset.theme=t;document.documentElement.style.colorScheme=t==='system'?'light dark':t;document.dispatchEvent(new CustomEvent('urbion-ui',{detail:{lang:l,theme:t,t:dict[l]}}))}
  function controls(){if(document.getElementById('urbion-ui-controls'))return;const box=document.createElement('div');box.id='urbion-ui-controls';box.setAttribute('aria-label','URBION language and theme controls');box.innerHTML='<label>Language <select id="urbion-lang"><option value="en">English</option><option value="ms">Bahasa Melayu</option></select></label><label>Theme <select id="urbion-theme"><option value="system">System</option><option value="dark">Dark</option><option value="light">Light</option></select></label>';const s=document.createElement('style');s.textContent='#urbion-ui-controls{--u-bg:#07121ced;--u-fg:#eff8ff;--u-border:#203343;position:fixed;right:14px;bottom:14px;z-index:99999;display:flex;gap:7px;padding:8px;border:1px solid var(--u-border);border-radius:12px;background:var(--u-bg);color:var(--u-fg);font:10px Inter,system-ui,sans-serif;backdrop-filter:blur(12px);box-shadow:0 10px 30px #0006}#urbion-ui-controls label{display:flex;align-items:center;gap:5px}#urbion-ui-controls select{width:auto;min-width:86px;padding:5px 7px;border:1px solid var(--u-border);border-radius:7px;background:#07121c;color:inherit}@media(max-width:600px){#urbion-ui-controls{left:10px;right:10px;bottom:10px;justify-content:space-between}}:root[data-theme="light"] #urbion-ui-controls{--u-bg:#fffffff2;--u-fg:#102334;--u-border:#b8c9d6}:root[data-theme="light"] #urbion-ui-controls select{background:#f5f9fc}:root[data-theme="system"] #urbion-ui-controls{color-scheme:light dark}@media(prefers-color-scheme:light){:root[data-theme="system"] #urbion-ui-controls{--u-bg:#fffffff2;--u-fg:#102334;--u-border:#b8c9d6}:root[data-theme="system"] #urbion-ui-controls select{background:#f5f9fc}}';document.head.appendChild(s);document.body.appendChild(box);document.getElementById('urbion-lang').value=lang();document.getElementById('urbion-theme').value=theme();document.getElementById('urbion-lang').onchange=e=>setLang(e.target.value);document.getElementById('urbion-theme').onchange=e=>setTheme(e.target.value)}
  function dashboard(){if(!document.getElementById('assessment')||document.getElementById('urbion-live-command'))return;const box=document.createElement('section');box.id='urbion-live-command';box.innerHTML='<div><b>URBION PHASE-E.7 · LIVE DECISION COMMAND</b><span>Connected decision tools</span></div><div class="urbion-live-actions"><a href="map-studio.html">MAP STUDIO</a><a href="what-if.html">WHAT-IF</a><a href="decision-center.html">DECISION CENTER</a><a href="lcp-intelligence.html">LCP INTELLIGENCE</a></div><div id="urbion-live-health">Checking engine…</div>';const s=document.createElement('style');s.textContent='#urbion-live-command{margin:0 0 22px;padding:13px 15px;border:1px solid #203343;border-radius:15px;background:#ffffff04;display:grid;grid-template-columns:1.5fr auto auto;gap:12px;align-items:center;font:10px Inter,system-ui,sans-serif}#urbion-live-command b{display:block;letter-spacing:.08em}#urbion-live-command span{display:block;color:#8ea4b5;font-size:9px;margin-top:3px}.urbion-live-actions{display:flex;gap:6px;flex-wrap:wrap}.urbion-live-actions a{padding:8px 10px;border:1px solid #203343;border-radius:8px;color:#eff8ff;text-decoration:none;font-weight:800;font-size:8px}.urbion-live-actions a:hover{border-color:#5ee7c2}.urbion-live-actions a:first-child{background:#5ee7c215}.urbion-live-actions a:nth-child(3){background:#6aa9ff12}.urbion-live-actions a:nth-child(4){background:#b58cff15}#urbion-live-health{font-size:8px;color:#5ee7c2;white-space:nowrap}@media(max-width:900px){#urbion-live-command{grid-template-columns:1fr}.urbion-live-actions{flex-wrap:wrap}}';document.head.appendChild(s);document.getElementById('assessment').parentNode.insertBefore(box,document.getElementById('assessment'));fetch(location.origin+'/health').then(r=>r.json()).then(j=>{document.getElementById('urbion-live-health').textContent=(j.status||'unknown').toUpperCase()+' · '+(j.engine||'ENGINE')}).catch(()=>{document.getElementById('urbion-live-health').textContent='ENGINE STATUS UNAVAILABLE'})}
  function setLang(v){localStorage.setItem(KEY_LANG,v==='en'?'en':'ms');apply();sync()}
  function setTheme(v){localStorage.setItem(KEY_THEME,['dark','light','system'].includes(v)?v:'system');apply();sync()}
  function sync(){const a=document.getElementById('urbion-lang'),b=document.getElementById('urbion-theme');if(a)a.value=lang();if(b)b.value=theme()}
  window.URBION_UI={dict,get lang(){return lang()},get theme(){return theme()},t(k){return dict[lang()][k]||k},setLang,setTheme,apply};
  function boot(){controls();dashboard()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
  apply();
})();