/* URBION HORIZON — canonical LCP-oriented data readiness presentation owner. */
(()=>{
'use strict';
if(window.__URBION_LCP_READINESS_OWNER_V1__)return;
window.__URBION_LCP_READINESS_OWNER_V1__=true;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function root(){return document.querySelector('.right')||document.querySelector('.layout > :last-child')}
function data(){return window.URBION_LAST?.lcp_data_readiness||window.URBION_LAST?.copilot?.lcp_data_readiness||window.URBION_AI_LAST?.lcp_data_readiness||null}
function style(){if($('urbionLcpReadinessStyle'))return;const s=document.createElement('style');s.id='urbionLcpReadinessStyle';s.textContent=`.urbion-lcp-card{border:1px solid rgba(47,225,233,.22);border-radius:10px;padding:10px;margin-bottom:8px;background:linear-gradient(145deg,rgba(7,29,41,.97),rgba(3,15,22,.99))}.light .urbion-lcp-card{background:#fff}.ulcp-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.ulcp-title{font-size:8px;font-weight:900;letter-spacing:.07em}.ulcp-sub{font-size:5.8px;color:var(--muted)}.ulcp-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px}.ulcp-chip{border:1px solid var(--line);border-radius:8px;padding:7px}.ulcp-chip b{display:block;font-size:11px}.ulcp-chip span{display:block;margin-top:2px;font-size:5.5px;color:var(--muted)}.ulcp-section{margin-top:8px;padding-top:7px;border-top:1px solid rgba(45,85,100,.18)}.ulcp-section h4{margin:0 0 5px;font-size:5.8px;letter-spacing:.08em;color:var(--cyan)}.ulcp-row{padding:6px 0;border-bottom:1px solid rgba(45,85,100,.13);font-size:6px;cursor:pointer}.ulcp-row b{display:block;font-size:6.5px}.ulcp-row small{display:block;color:var(--muted);line-height:1.4;margin-top:2px}.ulcp-pill{display:inline-block;padding:3px 5px;border:1px solid var(--line);border-radius:999px;font-size:5px;margin-top:3px}.ulcp-available{color:var(--good);border-color:rgba(72,223,170,.28)}.ulcp-missing{color:var(--warn);border-color:rgba(255,203,93,.28)}.ulcp-note{margin-top:7px;padding:7px 8px;border-left:2px solid var(--cyan);background:rgba(47,225,233,.035);font-size:5.8px;line-height:1.45;color:#b9ccd3}.light .ulcp-note{color:#5d727d}.ulcp-detail{margin-top:5px;padding:6px;border:1px solid var(--line);border-radius:7px;font-size:5.6px;line-height:1.45;display:none}.ulcp-detail.open{display:block}.ulcp-action{margin-top:6px;width:100%;border:1px solid var(--line);border-radius:7px;padding:6px;background:transparent;color:var(--text);font:700 6px Inter,system-ui,sans-serif;text-align:left}.ulcp-action:hover{border-color:rgba(47,225,233,.5)}`;document.head.appendChild(s)}
function render(){const host=root();if(!host)return false;style();let card=$('urbionLcpReadinessCard');if(!card){card=document.createElement('section');card.id='urbionLcpReadinessCard';card.className='urbion-lcp-card';host.insertBefore(card,host.firstChild)}const d=data();if(!d){card.innerHTML='<div class="ulcp-head"><span class="ulcp-title">LCP DATA READINESS</span><span class="ulcp-sub">WAITING</span></div><div class="ulcp-note">Run Site Analysis to build a source-aware LCP-oriented data acquisition checklist. This is workflow support, not a legal declaration of all statutory LCP requirements.</div>';return false}const av=Array.isArray(d.available_fields)?d.available_fields:[],mi=Array.isArray(d.missing_fields)?d.missing_fields:[],actions=Array.isArray(d.acquisition_actions)?d.acquisition_actions:[];const status=String(d.status||'PARTIAL').toUpperCase();const missingRows=mi.slice(0,6).map((x,i)=>`<div class="ulcp-row" data-lcp-index="${i}"><b>${esc(x.label||'Data area')}</b><span class="ulcp-pill ulcp-missing">NEED VERIFICATION / DATA</span><small>${esc(x.source_target||'Source target not supplied')} · ${esc(x.verification||'REVIEW_REQUIRED')}</small><div class="ulcp-detail" data-detail="${i}"><b>NEXT ACTION</b><br>${esc((actions.find(a=>a.field===x.label)||{}).action||'Obtain or verify this data area before relying on it in the LCP evidence base.')}<br><b>SOURCE TARGET</b><br>${esc(x.source_target||'Not specified')}<br><b>EVIDENCE NOTE</b><br>${esc(x.note||'')}</div></div>`).join('');const availableRows=av.slice(0,5).map(x=>`<div class="ulcp-row"><b>${esc(x.label||'Data area')}</b><span class="ulcp-pill ulcp-available">AVAILABLE · ${esc(x.verification||'SOURCE')}</span><small>${esc(x.source_target||'Canonical packet')}</small></div>`).join('');card.innerHTML=`<div class="ulcp-head"><span class="ulcp-title">LCP DATA READINESS</span><span class="ulcp-sub">${esc(status)} · ${esc(d.scope||'LCP_ORIENTED_DATA_READINESS')}</span></div><div class="ulcp-grid"><div class="ulcp-chip"><b>${esc(d.available_count??av.length)}</b><span>AVAILABLE AREAS</span></div><div class="ulcp-chip"><b>${esc(d.missing_count??mi.length)}</b><span>NEED DATA / VERIFICATION</span></div></div><div class="ulcp-section"><h4>NEXT REQUIRED DATA</h4>${missingRows||'<div class="ulcp-note">No missing LCP-oriented data areas are currently surfaced. Continue source verification before relying on the evidence base.</div>'}</div>${availableRows?`<div class="ulcp-section"><h4>ALREADY AVAILABLE</h4>${availableRows}</div>`:''}<div class="ulcp-note"><b>WORKFLOW BOUNDARY</b><br>${esc(d.disclaimer||'Supports LCP preparation/evidence collection; not a legal declaration of all statutory LCP requirements.')}</div>`;card.querySelectorAll('.ulcp-row[data-lcp-index]').forEach(row=>row.addEventListener('click',()=>{const box=row.querySelector('.ulcp-detail');if(box)box.classList.toggle('open')}));return true}
function watch(){let n=0;const tick=()=>{if(render())return; if(n++<60)setTimeout(tick,250)};tick();window.addEventListener('urbion:analysis-ready',()=>render());}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else watch();
setInterval(render,1000);
})();
