(()=>{
'use strict';
if(window.__URBION_SPATIAL_CONTEXT_UPGRADE)return;window.__URBION_SPATIAL_CONTEXT_UPGRADE=true;
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let contextLayers=new Map(), contextData=null;
const DEFAULT_VISIBLE=new Set(['iplan-current','iplan-zoning','iplan-flood','mygems-lithology']);
const palette={PLANNING:'#35e2b0',HAZARD:'#ff7d7d',ENVIRONMENT:'#62d6ff',ECOLOGY:'#7bd88f',HERITAGE:'#f2c66d',GEOLOGY:'#c89bff',GEOHAZARD:'#ff9f68',CADASTRAL:'#d5e3ea'};
function captureMap(){if(!window.L||window.__URBION_SPATIAL_MAP_PATCHED)return;const original=L.map;L.map=function(...args){const m=original.apply(this,args);window.__URBION_SPATIAL_MAP=m;const node=typeof args[0]==='string'?$(args[0]):args[0];if(node)node.__urbionMap=m;return m};window.__URBION_SPATIAL_MAP_PATCHED=true}
captureMap();
function style(){if($('ss-context-style'))return;const s=document.createElement('style');s.id='ss-context-style';s.textContent=`#ss-context{padding:9px;border:1px solid #17303e;border-radius:9px;background:#07131c;margin-top:8px}.sc-head{display:flex;justify-content:space-between;gap:7px;align-items:center}.sc-head b{font-size:7px;letter-spacing:.08em}.sc-actions{display:flex;gap:5px}.sc-actions button{border:1px solid #31516a;border-radius:6px;background:#0b1b28;color:#d8e6ec;padding:5px 7px;font:900 6px Inter;cursor:pointer}.sc-status{margin-top:6px;color:#8299a8;font-size:6px;line-height:1.4}.sc-grid{display:grid;gap:5px;margin-top:7px}.sc-row{display:grid;grid-template-columns:auto 1fr auto;gap:6px;align-items:center;padding:6px;border:1px solid #203343;border-radius:6px}.sc-row input{accent-color:var(--a)}.sc-name{font-size:7px;color:#d8e6ec}.sc-meta{display:block;color:#8299a8;font-size:5.8px;margin-top:2px}.sc-count{font-size:6px;color:#9ec0cc}.sc-signal{margin-top:7px;display:grid;gap:4px}.sc-signal div{padding:6px;border-left:2px solid #31516a;background:#091722;font-size:6.5px;color:#b8cbd5}.sc-signal strong{color:#eaf5f7}.sc-popup{font-size:11px;line-height:1.4}.sc-popup small{color:#5d7280}`;document.head.appendChild(s)}
function map(){return window.__URBION_SPATIAL_MAP||document.querySelector('#ss-map')?.__urbionMap||null}
function state(){return{lat:parseFloat($('lat')?.value),lon:parseFloat($('lon')?.value),state:$('state')?.value||'Melaka'}}
function fmt(v){return v==null?'—':v<1000?`${Math.round(v)} m`:`${(v/1000).toFixed(2)} km`}
function layerStyle(item){const c=palette[item.group]||'#9ec0cc';return{color:c,weight:item.group==='PLANNING'?2:1.5,opacity:.9,fillColor:c,fillOpacity:item.group==='HAZARD'?.22:.11}}
function popup(item,feature){const p=feature.properties||{};const keys=Object.keys(p).slice(0,8);return `<div class="sc-popup"><b>${esc(item.name)}</b><br><small>${esc(item.source||'Public GIS source')} · SOURCE CONTEXT</small>${keys.length?'<hr style="border:0;border-top:1px solid #d7e2e8">'+keys.map(k=>`<div><b>${esc(k)}</b>: ${esc(p[k])}</div>`).join(''):''}</div>`}
function clearRendered(){const m=map();if(!m)return;contextLayers.forEach(x=>m.removeLayer(x));contextLayers.clear()}
function renderLayer(item,on){const m=map();if(!m||!item)return;if(!on){const old=contextLayers.get(item.id);if(old)m.removeLayer(old);contextLayers.delete(item.id);return}const gj=L.geoJSON({type:'FeatureCollection',features:item.features||[]},{style:()=>layerStyle(item),pointToLayer:(_f,ll)=>L.circleMarker(ll,{radius:6,...layerStyle(item),fillOpacity:.75}),onEachFeature:(f,l)=>l.bindPopup(popup(item,f))});gj.addTo(m);contextLayers.set(item.id,gj)}
function renderRows(){const host=$('sc-grid');if(!host||!contextData)return;host.innerHTML=contextData.layers.map(item=>{const active=contextLayers.has(item.id);const checked=active?'checked':'';const status=item.status==='LIVE_QUERY'?'LIVE QUERY':item.status==='NO_FEATURE'?'NO FEATURE':'EVIDENCE GAP';return `<label class="sc-row"><input type="checkbox" data-layer="${esc(item.id)}" ${checked}><span><span class="sc-name">${esc(item.name)}</span><small class="sc-meta">${esc(item.group||'SPATIAL')} · ${esc(status)} · ${esc(item.source||'public GIS')}</small></span><span class="sc-count">${item.feature_count||0}${item.inside_count?` · ${item.inside_count} hit`:''}</span></label>`}).join('');host.querySelectorAll('input[data-layer]').forEach(cb=>cb.onchange=()=>{const item=contextData.layers.find(x=>x.id===cb.dataset.layer);renderLayer(item,cb.checked);renderRows()})}
function renderSignals(){const host=$('sc-signals');if(!host||!contextData)return;const hits=contextData.signals.filter(x=>x.status==='SOURCE_CONTEXT_HIT'&&((x.features||0)>0));host.innerHTML=hits.slice(0,8).map(x=>`<div><strong>${esc(x.label)}</strong> · ${x.features} feature${x.features===1?'':'s'}${x.inside?` · ${x.inside} intersects site point`:''}${x.nearest_distance_m!=null?` · nearest ${fmt(x.nearest_distance_m)}`:''}</div>`).join('')||'<div><strong>No live feature hit</strong> · source query completed without a mapped feature in the screening radius.</div>'}
function inject(){const panel=document.querySelector('#spatial-studio .ss-panel');if(!panel||$('ss-context'))return;style();const sec=document.createElement('div');sec.id='ss-context';sec.className='ss-section';sec.innerHTML='<div class="sc-head"><b>LIVE SITE CONTEXT · GIS QUERY</b><div class="sc-actions"><button id="sc-run">QUERY SITE</button><button id="sc-clear">CLEAR</button></div></div><div class="sc-status" id="sc-status">No live site-context query yet. Query uses public GIS geometry around the screening site; source state remains non-statutory.</div><div id="sc-signals" class="sc-signal"></div><div id="sc-grid" class="sc-grid"></div>';panel.insertBefore(sec,panel.querySelector('.ss-note'));$('sc-run').onclick=query;$('sc-clear').onclick=()=>{clearRendered();contextData=null;$('sc-status').textContent='Context cleared. Existing WMS/base layers are unchanged.';$('sc-signals').innerHTML='';$('sc-grid').innerHTML=''};}
async function query(){const m=map(),s=state();if(!m||![s.lat,s.lon].every(Number.isFinite)){if($('sc-status'))$('sc-status').textContent='Waiting for a valid map/site coordinate.';return}const b=$('sc-run');if(b){b.disabled=true;b.textContent='QUERYING…'}if($('sc-status'))$('sc-status').textContent='Querying public GIS sources in parallel…';try{clearRendered();const r=await fetch('/spatial/site-context',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({site_lat:s.lat,site_lon:s.lon,state:s.state,radius_m:800})});const data=await r.json();if(!r.ok)throw Error(data.detail?.message||data.detail||r.status);contextData=data;const live=data.layers.filter(x=>x.status==='LIVE_QUERY').length;const hits=data.signals.filter(x=>x.status==='SOURCE_CONTEXT_HIT').length;$('sc-status').textContent=`${live}/${data.layers.length} layers returned geometry · ${hits} source-context hits · ${data.query.parallel?'parallel query':''} · ${data.radius_m}m radius`;renderRows();renderSignals();data.layers.filter(x=>DEFAULT_VISIBLE.has(x.id)&&x.status==='LIVE_QUERY').forEach(x=>renderLayer(x,true));window.dispatchEvent(new CustomEvent('urbion:spatial-context',{detail:data}));}catch(e){$('sc-status').textContent='Spatial query unavailable — evidence gap disclosed; no geometry fabricated.';console.warn('URBION spatial context',e)}finally{if(b){b.disabled=false;b.textContent='QUERY SITE'}}}
function boot(){captureMap();inject();if(map()&&!window.__URBION_SPATIAL_CONTEXT_AUTO){window.__URBION_SPATIAL_CONTEXT_AUTO=true;setTimeout(query,900)}}
window.addEventListener('urbion:site-change',()=>setTimeout(query,250));window.addEventListener('urbion:analysis',()=>setTimeout(query,250));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,350));else setTimeout(boot,350);setTimeout(boot,1200);setTimeout(boot,2200);
})();