/* URBION HORIZON — live station + judge presentation owner.
   Presentation-only layer on the canonical V5 workspace. */
(()=>{
'use strict';
if(window.__URBION_STATION_MAP_OWNER_V5__)return;
window.__URBION_STATION_MAP_OWNER_V5__=true;
const $=id=>document.getElementById(id);
function mapObj(){try{return (typeof map!=='undefined'&&map)||window.__URBION_MAP__||window.__URBION_FCC_MAP__||null}catch(_){return null}}
function packet(){return window.URBION_LAST?.canonical_evidence_packet||window.URBION_LAST?.copilot?.canonical_evidence_packet||window.URBION_LAST?.deterministic_packet?.canonical_evidence_packet||null}
function cachedStations(){const p=packet();return p?.evidence?.stations||window.URBION_LAST?.live_station_evidence||null}
function esc(s){return String(s??'').replace(/[&<>\\\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;'}[m]||m))}
function structuralLocation(){for(const [id,label] of [['district','Select District'],['pbt','Select PBT'],['mukim','Select Mukim']]){const el=$(id);if(!el||el.tagName==='SELECT')continue;const s=document.createElement('select');for(const attr of ['id','name','class','required','disabled','autocomplete','aria-label'])if(el.hasAttribute(attr))s.setAttribute(attr,el.getAttribute(attr));s.className=el.className||'select';const value=String(el.value||'').trim();s.innerHTML=`<option value=\"\">${esc(label)}</option>`+(value?`<option value=\"${esc(value)}\">${esc(value)}</option>`:'');if(value)s.value=value;el.replaceWith(s)}}
function style(){if($('urbionStationMapStyle'))return;const s=document.createElement('style');s.id='urbionStationMapStyle';s.textContent='.urbion-station-btn{width:100%;margin-top:6px;padding:7px 9px;border:1px solid rgba(47,225,233,.22);background:rgba(47,225,233,.05);border-radius:8px;text-align:left;font-size:6.5px}.urbion-station-btn.on{border-color:rgba(72,223,170,.5);color:var(--good)}.urbion-present-btn{margin-top:7px;width:100%;padding:8px 9px;border:1px solid rgba(47,225,233,.35);background:linear-gradient(90deg,rgba(88,232,196,.08),rgba(47,225,233,.08));border-radius:8px;font-size:7px;font-weight:800;letter-spacing:.06em}.urbion-present-mode .left,.urbion-present-mode .right{display:none!important}.urbion-present-mode .layout{grid-template-columns:minmax(0,1fr)}.urbion-present-mode .center{padding:14px}.urbion-present-mode .mapwrap{border-radius:16px}.urbion-present-mode .bottom{height:170px}.urbion-present-mode .brand{min-width:250px}';document.head.appendChild(s)}
function popup(item,domain){const parts=[];if(domain==='JPS RAINFALL'){const reading=item.rainfall_1h_mm??item.daily_rainfall_mm??null;parts.push(reading==null?'No reading':`${esc(reading)} mm`)}else if(domain==='MYEQMS WATER'){if(item.ph!=null)parts.push(`pH ${esc(item.ph)}`);if(item.turbidity_ntu!=null)parts.push(`Turbidity ${esc(item.turbidity_ntu)} NTU`);if(item.conductivity_us_cm!=null)parts.push(`Conductivity ${esc(item.conductivity_us_cm)} µS/cm`)}else{const reading=item.reading??item.api??null;parts.push(reading==null?'No reading':`${esc(reading)} ${esc(item.unit||'')}`)}return `<b>${esc(item.name||item.station_id||'Station')}</b><br>${esc(domain)} · ${parts.join(' · ')}<br>${item.distance_m!=null?esc(Math.round(item.distance_m)+' m from site'):''}<br><small>SOURCE_CONTEXT · ${esc(item.last_updated||item.last_updated_rainfall||item.observed_at||'time not supplied')}</small>`}
let layer=null;
async function loadStations(){const cached=cachedStations();if(cached)return cached;const lat=Number($('site_lat')?.value),lon=Number($('site_lon')?.value),state=String($('state')?.value||'Melaka');if(!Number.isFinite(lat)||!Number.isFinite(lon))throw Error('Site coordinates unavailable');const r=await fetch(`/mobility/stations?site_lat=${encodeURIComponent(lat)}&site_lon=${encodeURIComponent(lon)}&state=${encodeURIComponent(state)}&limit=10`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.detail||`HTTP ${r.status}`);return d}
function toggleMarkers(data,on){const m=mapObj();if(!m||typeof L==='undefined')throw Error('Map engine unavailable');if(layer){try{m.removeLayer(layer)}catch(_){}layer=null}if(!on)return;layer=L.layerGroup();const feeds=[['JPS RAINFALL',data?.jps_rainfall?.stations||[]],['MYEQMS WATER',data?.eqmp_water?.stations||[]],['AIR QUALITY',data?.air_quality?.stations||[]]];for(const [domain,items] of feeds)for(const item of items){const lat=Number(item.latitude??item.lat),lon=Number(item.longitude??item.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const marker=L.circleMarker([lat,lon],{radius:6,weight:2,fillOpacity:.8});marker.bindPopup(popup(item,domain));marker.addTo(layer)}layer.addTo(m)}
function stationCount(data){return(data?.jps_rainfall?.stations||[]).length+(data?.eqmp_water?.stations||[]).length+(data?.air_quality?.stations||[]).length}
function mountStation(){style();const root=document.querySelector('.right');if(!root)return false;if($('urbionStationMapCard'))return true;const card=document.createElement('section');card.id='urbionStationMapCard';card.className='card';card.innerHTML='<div class="cardhead"><h3>MAP · LIVE STATIONS</h3><span class="tiny">OBSERVATION</span></div><div class="tiny">JPS rainfall · MyEQMS water stations · DOE air-quality stations when source data is available.</div><button type="button" class="urbion-station-btn" id="urbionStationToggle">SHOW STATIONS ON MAP</button><div class="tiny" id="urbionStationStatus" style="margin-top:5px">OFF · no station markers rendered</div>';root.appendChild(card);$('urbionStationToggle').addEventListener('click',async()=>{const b=$('urbionStationToggle'),st=$('urbionStationStatus');const on=b.dataset.on==='1';if(on){toggleMarkers(null,false);b.dataset.on='0';b.textContent='SHOW STATIONS ON MAP';b.classList.remove('on');st.textContent='OFF · no station markers rendered';return}b.disabled=true;st.textContent='LOADING · canonical/live station coordinates';try{const d=await loadStations();toggleMarkers(d,true);b.dataset.on='1';b.textContent='HIDE STATIONS FROM MAP';b.classList.add('on');const total=stationCount(d);const eqmp=(d?.eqmp_water?.stations||[]).length;st.textContent=total?`ON · ${total} source-backed station markers · MyEQMS ${eqmp}`:'ON · no station geometry returned';}catch(e){st.textContent='UNAVAILABLE · '+e.message}finally{b.disabled=false}});return true}
function judgeCss(){if($('urbionJudgeStyle'))return;const s=document.createElement('style');s.id='urbionJudgeStyle';s.textContent='.urbion-judge-card{border:1px solid var(--line);border-radius:10px;background:linear-gradient(145deg,rgba(7,29,41,.96),rgba(3,15,22,.98));padding:10px;margin-bottom:8px;box-shadow:0 10px 30px rgba(0,0,0,.18)}.light .urbion-judge-card{background:#fff}.urbion-judge-card .jhead{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.urbion-judge-card .jtitle{font-size:8px;letter-spacing:.08em;font-weight:900}.urbion-judge-card .jmeta{font-size:6px;color:var(--muted)}.urbion-judge-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.urbion-judge-chip{border:1px solid var(--line);border-radius:8px;padding:7px;background:rgba(255,255,255,.018)}.urbion-judge-chip b{display:block;font:800 10px Space Grotesk;margin-bottom:2px}.urbion-judge-chip span{display:block;font-size:5.9px;color:var(--muted);line-height:1.35}.urbion-judge-strip{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.urbion-judge-pill{padding:4px 6px;border:1px solid var(--line);border-radius:999px;font-size:5.8px;color:var(--muted)}.urbion-judge-pill.good{color:var(--good);border-color:rgba(72,223,170,.3)}.urbion-judge-pill.warn{color:var(--warn);border-color:rgba(255,203,93,.28)}.urbion-judge-why{margin-top:7px;padding:7px 8px;border-left:2px solid var(--cyan);background:rgba(47,225,233,.035);font-size:6.3px;line-height:1.45;color:#b9ccd3}.light .urbion-judge-why{color:#5d727d}';document.head.appendChild(s)}
function reviewCount(p){const r=p?.review_gaps??p?.review_required??p?.assessment?.review_gaps??[];if(Array.isArray(r))return r.length;const n=Number(r);return Number.isFinite(n)?n:0}
function evidenceCount(p){const e=p?.evidence||{};let n=0;const walk=x=>{if(!x||typeof x!=='object')return;if(x.evidence_state||x.source||x.provenance)n++;Object.values(x).forEach(v=>walk(v))};walk(e);return n}
function inferSite(p){return p?.site?.name||p?.site?.site_name||p?.assessment?.project_site_name||p?.inputs?.project_site_name||'Planning Case'}
function inferUse(p){return p?.assessment?.development_type||p?.assessment?.land_use||p?.site_analysis?.current_land_use||p?.inputs?.development_type||'Development proposal'}
function presentationButton(card){if($('urbionPresentBtn'))return;const b=document.createElement('button');b.type='button';b.id='urbionPresentBtn';b.className='urbion-present-btn';b.textContent='ENTER PRESENTATION MODE';b.addEventListener('click',()=>{const active=document.body.classList.toggle('urbion-present-mode');b.textContent=active?'EXIT PRESENTATION MODE':'ENTER PRESENTATION MODE';setTimeout(()=>{try{mapObj()?.invalidateSize(true)}catch(_){}} ,120)});card.appendChild(b);const key=e=>{if(e.key==='Escape'&&document.body.classList.contains('urbion-present-mode')){document.body.classList.remove('urbion-present-mode');b.textContent='ENTER PRESENTATION MODE';setTimeout(()=>{try{mapObj()?.invalidateSize(true)}catch(_){}} ,120)}};if(!window.__URBION_PRESENT_KEY__)window.addEventListener('keydown',key);window.__URBION_PRESENT_KEY__=true}
function renderJudge(){const right=document.querySelector('.right');if(!right)return;judgeCss();let card=$('urbionJudgeCard');if(!card){card=document.createElement('section');card.id='urbionJudgeCard';card.className='urbion-judge-card';right.prepend(card)}const p=packet();const gaps=reviewCount(p);const site=inferSite(p);const use=inferUse(p);const states=Object.values(p?.evidence_states||{});const source=states.filter(x=>String(x).toUpperCase()==='SOURCE_CONTEXT').length;const verified=states.filter(x=>String(x).toUpperCase()==='VERIFIED').length;const decision=p?(gaps===0?'READY FOR PLANNER REVIEW':'REVIEW REQUIRED'):'PRE-RUN';const dtext=p?(gaps===0?'No unresolved review gaps in packet':`${gaps} review gap${gaps===1?'':'s'} must be checked before handoff`):'Complete the case and run analysis';card.innerHTML=`<div class="jhead"><span class="jtitle">JUDGE SNAPSHOT</span><span class="jmeta">CANONICAL V5 · READ-ONLY</span></div><div class="urbion-judge-grid"><div class="urbion-judge-chip"><b>${esc(site)}</b><span>${esc(use)}</span></div><div class="urbion-judge-chip"><b>${p?'PACKET READY':'PRE-RUN'}</b><span>${p?esc(p.version||'PHASE1.2'):'Run site analysis to populate evidence'}</span></div><div class="urbion-judge-chip"><b>${gaps}</b><span>review gap${gaps===1?'':'s'} tracked in canonical packet</span></div><div class="urbion-judge-chip"><b>${evidenceCount(p)}</b><span>evidence items surfaced from canonical payload</span></div></div><div class="urbion-judge-strip"><span class="urbion-judge-pill ${p?'good':'warn'}">BASELINE ${p?'ACTIVE':'WAITING'}</span><span class="urbion-judge-pill ${p?'good':'warn'}">WHAT-IF ${p?'AVAILABLE':'AFTER ANALYSIS'}</span><span class="urbion-judge-pill ${gaps?'warn':p?'good':'warn'}">${esc(decision)}</span><span class="urbion-judge-pill ${source?'good':'warn'}">SOURCE CONTEXT ${source}</span><span class="urbion-judge-pill ${verified?'good':'warn'}">VERIFIED ${verified}</span></div><div class="urbion-judge-why"><b>WHY THIS MATTERS</b> · <span>${esc(dtext)}. AI narrative explains the packet only; deterministic planning evidence remains the source of truth and statutory verification is NOT_CLAIMED.</span></div>`;presentationButton(card)}
function boot(){structuralLocation();window.addEventListener('urbion:analysis-ready',()=>setTimeout(renderJudge,0),{passive:true});let n=0;const t=setInterval(()=>{renderJudge();if(mountStation()||++n>=300){if(window.__URBION_JUDGE_OWNER_V1__!==true)window.__URBION_JUDGE_OWNER_V1__=true;if(n>=300)clearInterval(t)}},100);renderJudge()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();