/* URBION HORIZON — P3 judge-facing decision story owner.
   Presentation-only view over the canonical evidence packet. It never scores,
   ranks, approves, or invents planning evidence. */
(()=>{'use strict';
if(window.__URBION_DECISION_STORY_OWNER_V1__)return;
window.__URBION_DECISION_STORY_OWNER_V1__=true;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]||m));
function packet(){return window.URBION_LAST?.canonical_evidence_packet||window.URBION_LAST?.copilot?.canonical_evidence_packet||window.URBION_LAST?.deterministic_packet?.canonical_evidence_packet||null}
function arr(x){return Array.isArray(x)?x:[]}
function statusClass(s){const t=String(s||'').toUpperCase();return t.includes('NON')?'bad':t.includes('REVIEW')||t.includes('VERIFY')?'warn':'ok'}
function pickRules(p){return arr(p?.assessment?.compliance_results).length?arr(p.assessment.compliance_results):arr(p?.assessment?.retrieved_rules)}
function pickScenarios(p){const s=p?.what_if||p?.evidence?.what_if||p?.scenario_intelligence||p?.assessment?.scenario_intelligence||{};return {items:arr(s.ranked_scenarios).length?arr(s.ranked_scenarios):arr(s.scenarios),best:s.best_candidate||s.preferred_scenario||s.recommended_scenario||null}}
function pickLive(p){const e=p?.evidence||{};const out=[];for(const [domain,key] of [['JPS rainfall','jps_rainfall'],['MyEQMS water','eqmp_water'],['Air quality','air_quality']]){const block=p?.evidence?.stations?.[key]||e?.environment?.[key]||p?.live_station_evidence?.[key];if(block)out.push({domain,state:String(block.evidence_state||block.status||'SOURCE_CONTEXT'),timestamp:block.last_updated||block.observed_at||block.last_updated_rainfall||'time not supplied'})}return out}
function render(){const root=document.querySelector('.right');if(!root)return;let card=$('urbionDecisionStoryCard');if(!card){card=document.createElement('section');card.id='urbionDecisionStoryCard';card.className='card';root.appendChild(card)}const p=packet();if(!p){card.innerHTML='<div class="cardhead"><h3>DECISION STORY</h3><span class="tiny">WAITING FOR ANALYSIS</span></div><div class="tiny">Run the canonical assessment to build the evidence-backed decision story.</div>';return}const a=p.assessment||{};const rules=pickRules(p).slice(0,4);const scenarios=pickScenarios(p);const best=scenarios.best;const gaps=arr(p.review_gaps);const live=pickLive(p);const handoff=gaps.length?'REVIEW REQUIRED':'READY FOR PLANNER REVIEW';const actions=gaps.slice(0,2);const ruleHtml=rules.length?rules.map(r=>`<div class="ds-row"><b>${esc(r.rule_id||r.parameter||r.name||'Planning control')}</b><span>${esc(r.source||r.source_document||'Planning source')} → ${esc(r.proposed_value??r.value??'—')} → <em class="tag ${statusClass(r.status)}">${esc(r.status||'REQUIRES REVIEW')}</em></span><small>${esc(r.reason||r.why||'Review against the applicable planning control.')}</small></div>`).join(''):'<div class="tiny">No rule records surfaced in the canonical packet.</div>';const scHtml=scenarios.items.slice(0,3).map(s=>`<div class="ds-row"><b>${esc(s.name||s.id||'Scenario')}</b><span>${esc(s.status||s.final_status||'REVIEW')} · ${esc(s.decision_delta??'no delta supplied')}</span></div>`).join('')||'<div class="tiny">No scenario comparison executed yet.</div>';const liveHtml=live.length?live.map(x=>`<span class="tag ${statusClass(x.state)}">${esc(x.domain)} · ${esc(x.state)}</span>`).join(' '):'<span class="tag warn">LIVE SOURCE CONTEXT</span>';card.innerHTML=`<div class="cardhead"><h3>DECISION STORY</h3><span class="tiny">CANONICAL PACKET · READ-ONLY</span></div><div class="finding"><b>${esc(a.final_status||'REQUIRES REVIEW')} · ${esc(a.classification||'PLANNING CASE')}</b><p>Baseline is the canonical assessment. ${best?`Preferred scenario signal: ${esc(typeof best==='object'?(best.name||best.id||'candidate'):best)}.`:'No preferred scenario is claimed yet.'}</p><small>STATUTORY VERIFICATION · ${esc(p.statutory_verification||'NOT_CLAIMED')}</small></div><div class="ds-title">RULE → VALUE → RESULT → WHY</div>${ruleHtml}<div class="ds-title">BASELINE → OPTIONS</div>${scHtml}<div class="ds-title">LIVE EVIDENCE</div><div class="ds-live">${liveHtml}</div><div class="finding"><b>${handoff}</b><p>${actions.length?actions.map(esc).join('<br>'):'No disclosed review blockers in the canonical packet.'}</p><small>DECISION AUTHORITY · ${esc(p.decision_authority||'NONE')} · PLANNER REVIEW ONLY</small></div>`}
function css(){if($('urbionDecisionStoryStyle'))return;const s=document.createElement('style');s.id='urbionDecisionStoryStyle';s.textContent='.ds-title{margin-top:8px;padding-top:7px;border-top:1px solid rgba(45,85,100,.18);font-size:6px;letter-spacing:.08em;color:var(--cyan);font-weight:900}.ds-row{padding:6px 0;border-bottom:1px solid rgba(45,85,100,.15)}.ds-row b{display:block;font-size:6.8px}.ds-row span,.ds-row small{display:block;font-size:5.9px;color:var(--muted);line-height:1.4}.ds-row em{font-style:normal}.ds-live{line-height:1.8}.ds-live .tag{display:inline-block;margin-right:3px}';document.head.appendChild(s)}
function boot(){css();render();window.addEventListener('urbion:analysis-ready',render,{passive:true});setInterval(()=>{if(packet())render()},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();