(()=>{
'use strict';
if(window.__URBION_GAP_CLOSURE__)return;
window.__URBION_GAP_CLOSURE__=true;

const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const read=id=>String($('#fcc-'+id)?.value||'').trim();
const lang=()=>localStorage.getItem('urbion-lang')||'en';
const tx=(en,bm)=>lang()==='bm'?bm:en;
const getUnified=()=>window.__URBION_UNIFIED_STATE||{};
const asObj=v=>v&&typeof v==='object'?v:{};
const asArr=v=>Array.isArray(v)?v:[];

function casePayload(){
 const s=getUnified();
 return {
   project_name:read('project_name'),lat:read('lat'),lon:read('lon'),site_lat:read('lat'),site_lon:read('lon'),
   state:read('state'),pbt:read('pbt'),district:read('district'),lot:read('lot'),lot_no:read('lot'),project_reference:read('project_reference'),
   landuse:read('landuse'),category:read('category'),activity:read('activity'),development:read('development'),ratio:read('ratio'),plot_ratio:read('ratio'),
   todlat:read('todlat'),todlon:read('todlon'),tod_lat:read('todlat'),tod_lon:read('todlon'),development_type:read('development'),development_class:read('category'),
   precinct:read('district'),land_use_type:read('landuse'),unified_state:s
 };
}
function upsertStyle(){
 if($('#urbion-gap-style'))return;
 const st=document.createElement('style');st.id='urbion-gap-style';st.textContent=`
 #urbion-gap-closure{margin:0 16px 18px;display:grid;grid-template-columns:1.1fr 1fr 1fr;gap:12px;position:relative;z-index:5}
 .gap-card{border:1px solid rgba(112,225,207,.18);background:linear-gradient(145deg,rgba(13,31,43,.96),rgba(8,20,31,.96));border-radius:14px;padding:14px;box-shadow:0 12px 30px rgba(0,0,0,.18)}
 body.fcc-light .gap-card{background:#fff;border-color:#d9e8ec;box-shadow:0 8px 24px rgba(12,40,56,.08)}
 .gap-kicker{font:700 10px/1 Inter,system-ui,sans-serif;letter-spacing:.12em;text-transform:uppercase;color:#55dec1}
 .gap-card h3{margin:7px 0 4px;font-size:16px}.gap-card p{margin:0 0 10px;font-size:11px;line-height:1.45;opacity:.72}
 .gap-actions{display:flex;flex-wrap:wrap;gap:7px}.gap-btn{appearance:none;border:1px solid rgba(83,221,195,.28);background:rgba(27,194,173,.08);color:inherit;border-radius:9px;padding:7px 9px;font:700 10px/1 Inter,system-ui,sans-serif;cursor:pointer}.gap-btn:hover,.gap-btn:focus-visible{border-color:#53ddc3;outline:none}.gap-result{margin-top:10px;font-size:10px;line-height:1.45;max-height:170px;overflow:auto}
 #urbion-completion-surface{margin:0 16px 24px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;position:relative;z-index:5}
 .completion-card{border:1px solid rgba(112,225,207,.16);background:rgba(9,24,35,.88);border-radius:12px;padding:13px;min-height:132px}.completion-card h4{margin:6px 0;font-size:13px}.completion-card p{margin:0;opacity:.68;font-size:10px;line-height:1.45}.completion-metric{font-size:24px;font-weight:800;letter-spacing:-.03em}.completion-meta{margin-top:6px;font-size:9px;opacity:.55;line-height:1.4}.completion-state{margin-top:8px;font-size:9px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.completion-actions{grid-column:1/-1;display:flex;justify-content:flex-end;gap:7px}
 body.fcc-light .completion-card{background:#fff;border-color:#d9e8ec}.completion-card[data-state="ready"] .completion-state{color:#53ddc3}.completion-card[data-state="review"] .completion-state{color:#f3c86b}.completion-card[data-state="gap"] .completion-state{color:#f28b82}
 @media(max-width:1200px){#urbion-completion-surface{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:1100px){#urbion-gap-closure{grid-template-columns:1fr}#urbion-completion-surface{grid-template-columns:1fr}}`;
 document.head.appendChild(st);
}
function insertSurface(){
 const root=$('#urbion-final-command-centre');if(!root||$('#urbion-gap-closure'))return false;
 const wrap=document.createElement('section');wrap.id='urbion-gap-closure';
 wrap.innerHTML=`
 <article class="gap-card"><div class="gap-kicker">01 · ${esc(tx('INTELLIGENCE','KECERDASAN'))}</div><h3>${esc(tx('Explain This Case','Terangkan Kes Ini'))}</h3><p>${esc(tx('AI-backed explanation using the existing assessment/case evidence chain. Planner support only — not statutory approval.','Penjelasan berasaskan AI menggunakan rantaian bukti/penilaian sedia ada. Sokongan perancang sahaja — bukan kelulusan statutori.'))}</p><div class="gap-actions"><button class="gap-btn" id="gap-ai">${esc(tx('AI EXPLAIN','TERANGKAN DENGAN AI'))}</button><button class="gap-btn" id="gap-stations">${esc(tx('STATION / MOBILITY','STESEN / MOBILITI'))}</button></div><div class="gap-result" id="gap-ai-result">${esc(tx('Ready when a case is defined.','Sedia selepas kes ditakrifkan.'))}</div></article>
 <article class="gap-card"><div class="gap-kicker">02 · ${esc(tx('JUDGE VIEW','PANDANGAN JURI'))}</div><h3>${esc(tx('90-Second Decision Story','Cerita Keputusan 90 Saat'))}</h3><p>${esc(tx('Dedicated judge surface linked to the existing judge-mode contract.','Paparan khas juri yang dipautkan kepada kontrak judge-mode sedia ada.'))}</p><div class="gap-actions"><button class="gap-btn" id="gap-judge">${esc(tx('OPEN JUDGE VIEW','BUKA PAPARAN JURI'))}</button></div><div class="gap-result" id="gap-judge-result">${esc(tx('Evidence → Score → Why → Decision → Action','Bukti → Skor → Sebab → Keputusan → Tindakan'))}</div></article>
 <article class="gap-card"><div class="gap-kicker">03 · ${esc(tx('PACKAGE','PAKEJ KES'))}</div><h3>${esc(tx('Unified Case Package','Pakej Kes Bersepadu'))}</h3><p>${esc(tx('Export the complete orchestration state and explicit authority boundary for review/audit.','Eksport keseluruhan keadaan orkestrasi dan sempadan kuasa secara jelas untuk semakan/audit.'))}</p><div class="gap-actions"><button class="gap-btn" id="gap-export">${esc(tx('EXPORT UNIFIED PACKAGE','EKSPORT PAKEJ BERSEPADU'))}</button><button class="gap-btn" id="gap-cascade">${esc(tx('REFRESH CASCADE','SEGARKAN RANTAIAN INPUT'))}</button></div><div class="gap-result" id="gap-package-result">${esc(tx('Package ready for export after analysis.','Pakej sedia dieksport selepas analisis.'))}</div></article>`;
 const tabs=$('#fcc-tabs',root)||$('.fcc-tabs',root);
 if(tabs?.parentElement)tabs.parentElement.insertAdjacentElement('afterend',wrap);else(root.querySelector('.fcc-main')||root).prepend(wrap);
 return true;
}
function insertCompletionSurface(){
 const root=$('#urbion-final-command-centre');if(!root||$('#urbion-completion-surface'))return false;
 const wrap=document.createElement('section');wrap.id='urbion-completion-surface';
 wrap.innerHTML=`
 <article class="completion-card" id="completion-policy"><div class="gap-kicker">04 · ${esc(tx('POLICY GRAPH','GRAF POLISI'))}</div><h4>${esc(tx('Planning Policy & Guidelines','Polisi & Garis Panduan Perancangan'))}</h4><div class="completion-metric" id="completion-policy-metric">—</div><p id="completion-policy-copy">${esc(tx('Policy nodes and relationships are shown from the current case state.','Nod dan hubungan polisi dipaparkan berdasarkan keadaan kes semasa.'))}</p><div class="completion-meta" id="completion-policy-meta"></div><div class="completion-state" id="completion-policy-state">${esc(tx('WAITING FOR CASE','MENUNGGU KES'))}</div></article>
 <article class="completion-card" id="completion-km"><div class="gap-kicker">05 · ${esc(tx('KM / OSC','KM / OSC'))}</div><h4>${esc(tx('Approval Readiness','Kesediaan Kebenaran Merancang'))}</h4><div class="completion-metric" id="completion-km-metric">—</div><p id="completion-km-copy">${esc(tx('Readiness, authority actions and review gaps from the existing KM chain.','Kesediaan, tindakan pihak berkuasa dan jurang semakan daripada rantaian KM sedia ada.'))}</p><div class="completion-meta" id="completion-km-meta"></div><div class="completion-state" id="completion-km-state">${esc(tx('WAITING FOR ANALYSIS','MENUNGGU ANALISIS'))}</div></article>
 <article class="completion-card" id="completion-lcp"><div class="gap-kicker">06 · ${esc(tx('LCP / EVIDENCE','LCP / BUKTI'))}</div><h4>${esc(tx('Evidence Completeness','Kelengkapan Bukti'))}</h4><div class="completion-metric" id="completion-lcp-metric">—</div><p id="completion-lcp-copy">${esc(tx('Evidence gaps and LCP intelligence are summarised for planner review.','Jurang bukti dan kecerdasan LCP diringkaskan untuk semakan perancang.'))}</p><div class="completion-meta" id="completion-lcp-meta"></div><div class="completion-state" id="completion-lcp-state">${esc(tx('WAITING FOR ANALYSIS','MENUNGGU ANALISIS'))}</div></article>
 <article class="completion-card" id="completion-mobility"><div class="gap-kicker">07 · ${esc(tx('NETWORK / MOBILITY','RANGKAIAN / MOBILITI'))}</div><h4>${esc(tx('Site Connectivity','Ketersambungan Tapak'))}</h4><div class="completion-metric" id="completion-mobility-metric">—</div><p id="completion-mobility-copy">${esc(tx('Spatial network context and station intelligence remain explicit about data availability.','Konteks rangkaian spatial dan kecerdasan stesen kekal jelas tentang ketersediaan data.'))}</p><div class="completion-meta" id="completion-mobility-meta"></div><div class="completion-state" id="completion-mobility-state">${esc(tx('REVIEW REQUIRED','PERLU SEMAKAN'))}</div></article>
 <div class="completion-actions"><button class="gap-btn" id="completion-refresh">${esc(tx('SYNC INTELLIGENCE','SEGERAK KECERDASAN'))}</button><button class="gap-btn" id="completion-run">${esc(tx('RUN DECISION ANALYSIS','JALANKAN ANALISIS KEPUTUSAN'))}</button></div>`;
 const anchor=$('#urbion-gap-closure');if(anchor)anchor.insertAdjacentElement('afterend',wrap);else(root.querySelector('.fcc-main')||root).appendChild(wrap);return true;
}
function setResult(id,text){const e=$('#'+id);if(e)e.textContent=text}
async function aiExplain(){
 const p=casePayload();setResult('gap-ai-result',tx('Running AI explanation…','Menjalankan penjelasan AI…'));
 try{const assessment={site_lat:p.site_lat,site_lon:p.site_lon,tod_lat:p.tod_lat,tod_lon:p.tod_lon,plot_ratio:p.plot_ratio,precinct:p.precinct,development_type:p.development_type,development_class:p.development_class,state:p.state,district:p.district,pbt:p.pbt,lot_no:p.lot_no,project_reference:p.project_reference};const res=await fetch('/copilot/run',{method:'POST',headers:{'content-type':'application/json','cache-control':'no-cache'},body:JSON.stringify({assessment})});const data=await res.json();if(!res.ok)throw new Error(data?.detail?.message||data?.detail||'AI endpoint unavailable');const insights=[];const spatial=asObj(data.spatial);const assess=data.assessment||data.assessments||{};const rec=data.recommendations||data.recommendation||{};if(asObj(spatial.network_access).distance_m!=null)insights.push(`${tx('Network context','Konteks rangkaian')}: ${Number(spatial.network_access.distance_m).toFixed(0)} m`);if(Object.keys(asObj(assess)).length)insights.push(JSON.stringify(assess).slice(0,700));if(Object.keys(asObj(rec)).length)insights.push(JSON.stringify(rec).slice(0,700));if(!insights.length)insights.push(JSON.stringify(data).slice(0,1200));setResult('gap-ai-result',insights.join(' · '));syncCompletion(data)}catch(err){setResult('gap-ai-result',tx(`AI explain unavailable: ${err.message}`,`Penjelasan AI tidak tersedia: ${err.message}`));syncCompletion()}}
async function stationExplain(){const lat=read('lat'),lon=read('lon'),state=read('state');if(!lat||!lon){setResult('gap-ai-result',tx('Enter site coordinates first.','Masukkan koordinat tapak dahulu.'));return}setResult('gap-ai-result',tx('Loading live station intelligence…','Memuatkan kecerdasan stesen langsung…'));try{const res=await fetch(`/station-intelligence?site_lat=${encodeURIComponent(lat)}&site_lon=${encodeURIComponent(lon)}&state=${encodeURIComponent(state)}`,{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data?.detail?.message||'Station endpoint unavailable');const n=asObj(data.nearest),lcp=asObj(data.lcp_snapshot),gaps=asArr(data.review_gaps);setResult('gap-ai-result',`${tx('Nearest','Terdekat')}: ${n.name||n.station_name||'—'} · ${n.distance_m!=null?Number(n.distance_m).toFixed(0)+' m':'—'} · ${tx('LCP','LCP')}: ${JSON.stringify(lcp).slice(0,500)} · ${tx('Review gaps','Jurang semakan')}: ${JSON.stringify(gaps).slice(0,500)}`);syncCompletion({station:data})}catch(err){setResult('gap-ai-result',tx(`Station intelligence unavailable: ${err.message}`,`Kecerdasan stesen tidak tersedia: ${err.message}`));syncCompletion()}}
async function judgeView(){setResult('gap-judge-result',tx('Loading judge story…','Memuatkan cerita juri…'));try{const res=await fetch('/judge-mode',{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data?.detail||'Judge endpoint unavailable');const text=[`v${data.version}`,`${data.scenario_count} scenarios`,data.decision_boundary,data.statutory_verification].filter(Boolean).join(' · ');setResult('gap-judge-result',`${text} · ${tx('Open full judge surface','Buka paparan juri penuh')}: /judge-mode`)}catch(err){setResult('gap-judge-result',tx(`Judge view unavailable: ${err.message}`,`Paparan juri tidak tersedia: ${err.message}`))}}
function fullPackage(){const s=getUnified(),p=casePayload(),pkg={schema:'urbion-horizon-unified-case-package',schema_version:'1.0.0',release:'MASTER-132',engine:'PHASE-E.8',frontend_release:'MASTER-331',exported_at:new Date().toISOString(),case:p,assessment:s.assessment??null,spatial_context:s.spatial??null,evidence:{spatial_summary:s.spatialSummary??null,layers:s.spatial?.layers??[],lot:s.lot??null},policy_guideline:s.km?.policy_guideline??s.assessment?.policy_guideline??null,policy_graph:s.km?.policy_graph??null,recommendations:s.assessment?.recommendations??s.lcp?.recommendations??null,agency_intelligence:s.km?.agency_intelligence??s.km?.agencies??null,km_readiness:s.km??null,what_if:s.whatIf??null,decision:s.decision??null,lcp_intelligence:s.lcp??null,evidence_gaps:(s.lcp?.evidence_gaps??s.assessment?.evidence_gaps??s.spatial?.evidence_gaps??[]),authority_boundary:{planner_decision_support_only:true,statutory_verification:'NOT_CLAIMED',cadastral_authority:'JUPEM / relevant PBT verification',source_context_is_not_statutory_verification:true},next_authority_action:s.decision?.next_authority_action??s.km?.next_authority_action??'Confirm current PBT/OSC requirements and statutory verification before submission.'};const blob=new Blob([JSON.stringify(pkg,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='urbion-horizon-unified-case-package.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setResult('gap-package-result',tx('Unified package exported.','Pakej bersepadu telah dieksport.'))}
const cascade={Residential:{categories:['New Development','Redevelopment','Infill Development','Urban Regeneration','Subdivision / Consolidation'],activities:['Housing'],proposals:['Residential Development','Urban Regeneration / Infill']},Commercial:{categories:['New Development','Redevelopment','Infill Development','Urban Regeneration','Change of Use'],activities:['Retail / Commercial','Office'],proposals:['Commercial Development','TOD Development / Mixed Use','Urban Regeneration / Infill']},'Mixed Use':{categories:['New Development','Redevelopment','Infill Development','Urban Regeneration'],activities:['Mixed Activity','Retail / Commercial','Office','Housing','Hospitality / Tourism'],proposals:['TOD Development / Mixed Use','Urban Regeneration / Infill']},Institutional:{categories:['New Development','Redevelopment','Change of Use'],activities:['Institution / Education'],proposals:['Institutional Development']},'Recreation / Tourism':{categories:['New Development','Redevelopment','Infill Development','Urban Regeneration'],activities:['Hospitality / Tourism','Recreation'],proposals:['Recreation / Tourism','TOD Development / Mixed Use']},Industrial:{categories:['New Development','Redevelopment','Infill Development','Subdivision / Consolidation'],activities:['Industrial / Logistics'],proposals:['Commercial Development']},'Transport / Infrastructure':{categories:['New Development','Redevelopment','Infrastructure / Transport'],activities:['Recreation','Mixed Activity'],proposals:['Infrastructure / Mobility']},'Open Space / Green':{categories:['New Development','Redevelopment','Change of Use'],activities:['Recreation'],proposals:['Recreation / Tourism']},Agriculture:{categories:['New Development','Change of Use','Subdivision / Consolidation'],activities:['Mixed Activity'],proposals:['Infrastructure / Mobility']}};
function options(sel,items,keep){const cur=sel.value;sel.innerHTML=`<option value="">${sel.id.includes('category')?'Select category':sel.id.includes('activity')?'Select activity':'Select proposal'}</option>`+items.map(x=>`<option>${esc(x)}</option>`).join('');if(keep&&items.includes(cur))sel.value=cur}
function applyCascade(){const cfg=cascade[read('landuse')],c=$('#fcc-category'),a=$('#fcc-activity'),d=$('#fcc-development');if(!cfg||!c||!a||!d)return;options(c,cfg.categories,true);options(a,cfg.activities,true);options(d,cfg.proposals,true)}
function metricValue(v,fallback='—'){return v==null||v===''?fallback:String(v)}
function setCardState(card,state,label){card?.setAttribute('data-state',state);const e=card?.querySelector('.completion-state');if(e)e.textContent=label}
function syncCompletion(extra){
 const s=getUnified();const assessment=asObj(s.assessment),km=asObj(s.km),lcp=asObj(s.lcp),spatial=asObj(s.spatial);const decision=asObj(s.decision);const policy=asObj(km.policy_graph||assessment.policy_graph);const nodes=asArr(policy.nodes),edges=asArr(policy.edges);const policyGuide=km.policy_guideline??assessment.policy_guideline;const policyMetric=(nodes.length||edges.length)?`${nodes.length}/${edges.length}`:(policyGuide?'LINKED':'—');
 $('#completion-policy-metric')&&(($('#completion-policy-metric').textContent=policyMetric));$('#completion-policy-meta')&&(($('#completion-policy-meta').textContent=policyGuide?tx('Guideline context available','Konteks garis panduan tersedia'):tx('Awaiting policy context','Menunggu konteks polisi')));setCardState($('#completion-policy'),policyGuide||nodes.length?'ready':'review',policyGuide||nodes.length?tx('CONNECTED','DISAMBUNG'):tx('REVIEW','SEMAK'));
 const kmRead=km.readiness_score??km.score??assessment.km_readiness_score;const agencies=asArr(km.agency_intelligence||km.agencies);const kmMetric=kmRead!=null?`${Math.round(Number(kmRead))}%`:agencies.length?`${agencies.length}`:'—';$('#completion-km-metric')&&($('#completion-km-metric').textContent=kmMetric);$('#completion-km-meta')&&($('#completion-km-meta').textContent=km.next_authority_action||decision.next_authority_action||tx('Authority action pending','Tindakan pihak berkuasa menunggu'));setCardState($('#completion-km'),kmRead!=null||agencies.length?'ready':'review',kmRead!=null?tx('TRACKED','DIJEJAK'):tx('REVIEW','SEMAK'));
 const gaps=asArr(lcp.evidence_gaps||assessment.evidence_gaps||spatial.evidence_gaps);const lcpScore=lcp.completeness_score??lcp.evidence_completeness??assessment.evidence_completeness;const lcpMetric=lcpScore!=null?`${Math.round(Number(lcpScore))}%`:(gaps.length?`${gaps.length} gaps`:'—');$('#completion-lcp-metric')&&($('#completion-lcp-metric').textContent=lcpMetric);$('#completion-lcp-meta')&&($('#completion-lcp-meta').textContent=gaps.length?`${gaps.length} ${tx('review gaps','jurang semakan')}`:tx('No recorded evidence gap','Tiada jurang bukti direkodkan'));setCardState($('#completion-lcp'),lcpScore!=null&&Number(lcpScore)>=75?'ready':gaps.length?'gap':'review',lcpScore!=null&&Number(lcpScore)>=75?tx('READY FOR REVIEW','SEDIA UNTUK SEMAKAN'):gaps.length?tx('EVIDENCE GAP','JURANG BUKTI'):tx('REVIEW','SEMAK'));
 const network=asObj(spatial.network_access);const station=asObj((extra||{}).station||s.station);const nearest=asObj(station.nearest);const dist=network.distance_m??station.distance_m??nearest.distance_m;const mobilityMetric=dist!=null?`${Math.round(Number(dist))} m`:(read('todlat')&&read('todlon')?'TOD SET':'—');$('#completion-mobility-metric')&&($('#completion-mobility-metric').textContent=mobilityMetric);$('#completion-mobility-meta')&&($('#completion-mobility-meta').textContent=nearest.name||nearest.station_name||network.status||tx('Live station adapter review','Semakan adapter stesen langsung'));setCardState($('#completion-mobility'),dist!=null?'ready':'review',dist!=null?tx('SPATIAL CONTEXT','KONTEKS SPATIAL'):tx('REVIEW REQUIRED','PERLU SEMAKAN'));
}
function bind(){
 const lu=$('#fcc-landuse');if(lu&&!lu.dataset.gapCascade){lu.dataset.gapCascade='1';lu.addEventListener('change',()=>{applyCascade();window.dispatchEvent(new CustomEvent('urbion:inputs-change',{detail:{inputs:casePayload()}}));syncCompletion()});applyCascade()}
 $('#gap-ai')?.addEventListener('click',aiExplain);$('#gap-stations')?.addEventListener('click',stationExplain);$('#gap-judge')?.addEventListener('click',judgeView);$('#gap-export')?.addEventListener('click',fullPackage);$('#gap-cascade')?.addEventListener('click',()=>{applyCascade();setResult('gap-package-result',tx('Input cascade refreshed from Land Use Type.','Rantaian input disegarkan berdasarkan Jenis Guna Tanah.'));syncCompletion()});
 $('#completion-refresh')?.addEventListener('click',()=>syncCompletion());
 $('#completion-run')?.addEventListener('click',()=>{$('#fcc-run')?.click();setTimeout(()=>syncCompletion(),350)});
 window.addEventListener('urbion:inputs-change',()=>syncCompletion());
 syncCompletion();
}
function boot(){upsertStyle();if(insertSurface()&&insertCompletionSurface())bind();else setTimeout(()=>{if(insertSurface()&&insertCompletionSurface())bind()},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
