(()=>{
'use strict';
if(window.__URBION_VISUAL_OVERHAUL)return;window.__URBION_VISUAL_OVERHAUL=true;
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=`
:root{--uo-bg:#06131c;--uo-panel:#0b1c27;--uo-panel2:#0e2430;--uo-line:#234455;--uo-text:#edf8fb;--uo-muted:#89a5b4;--uo-accent:#43e5bd;--uo-cyan:#18cce5;--uo-warn:#ffc857;--uo-danger:#ff6877;--uo-shadow:0 18px 55px rgba(0,0,0,.28)}
body.uo-clean .header{height:76px;padding:0 24px;background:rgba(5,16,25,.96);backdrop-filter:blur(18px)}
body.uo-clean .header .logo{background:none;width:188px;height:52px;border-radius:0;display:block;background-image:url('/urbion_logo_dark.svg');background-size:contain;background-repeat:no-repeat;background-position:left center;color:transparent}
body.urbion-light.uo-clean .header .logo{background-image:url('/urbion_logo_light.svg')}
body.uo-clean .header .brand{gap:0}.uo-brand-sub{display:none}
body.uo-clean .sidebar{background:linear-gradient(180deg,#071721,#08141d);padding:18px 16px}
body.uo-clean .main{padding:18px 20px 34px}
body.uo-clean .nav{gap:6px;margin-bottom:12px}.uo-clean .nav button{border-radius:999px;padding:8px 13px;background:#081923}.uo-clean .nav button.active{box-shadow:0 0 0 3px rgba(67,229,189,.08)}
#urbion-workstation-v2,#urbion-decision-os{display:none!important}
#uo-statusbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0 0 12px;padding:9px 12px;border:1px solid var(--uo-line);border-radius:12px;background:linear-gradient(90deg,rgba(67,229,189,.08),rgba(24,204,229,.04));font-size:8px;color:var(--uo-muted)}#uo-statusbar .uo-live{display:flex;align-items:center;gap:7px;color:var(--uo-accent);font-weight:900;letter-spacing:.08em}.uo-dot{width:7px;height:7px;border-radius:50%;background:var(--uo-accent);box-shadow:0 0 12px var(--uo-accent)}#uo-statusbar button{border:1px solid var(--uo-line);border-radius:999px;background:#07151e;color:var(--uo-text);padding:6px 9px;font-size:7px;font-weight:900;cursor:pointer}
#spatial-studio{margin-top:12px!important;border-radius:18px!important;border-color:#315467!important;background:linear-gradient(145deg,#081822,#06121a)!important;box-shadow:var(--uo-shadow)!important}
#spatial-studio .ss-head{padding:15px 16px!important}.ss-eyebrow{font-size:7px!important}.ss-head h2{font-size:20px!important}.ss-head p{font-size:8px!important;max-width:760px}.ss-actions button{border-radius:999px!important;padding:8px 11px!important}.ss-actions button:first-child{box-shadow:0 0 0 3px rgba(67,229,189,.08)}
#spatial-studio .ss-grid{grid-template-columns:minmax(0,1fr) 310px!important}.ss-map{height:560px!important;position:relative}.ss-panel{max-height:560px!important;padding:12px!important}.ss-section{padding-bottom:11px!important;margin-bottom:11px!important}.ss-section>b{font-size:7px!important;color:#7fa0af!important}.ss-layer{border-radius:9px!important;background:#07151e!important}.ss-prov{background:#07151e!important}
#uo-map-hud{position:absolute;left:12px;top:12px;z-index:800;display:flex;gap:6px;flex-wrap:wrap;max-width:calc(100% - 24px);pointer-events:none}.uo-hud-chip{padding:7px 9px;border:1px solid rgba(67,229,189,.28);border-radius:999px;background:rgba(5,18,27,.86);backdrop-filter:blur(10px);color:#dff6f2;font:800 7px Inter;letter-spacing:.04em;box-shadow:0 8px 25px rgba(0,0,0,.18)}
#uo-layer-dock{position:absolute;right:12px;top:12px;z-index:801;width:min(250px,calc(100% - 24px));border:1px solid rgba(36,68,85,.95);border-radius:12px;background:rgba(5,18,27,.92);backdrop-filter:blur(14px);box-shadow:0 12px 32px rgba(0,0,0,.24);overflow:hidden}.uo-dock-head{padding:9px 10px;border-bottom:1px solid #234455;display:flex;justify-content:space-between;align-items:center}.uo-dock-head b{font-size:8px;letter-spacing:.08em}.uo-dock-head button{border:0;background:transparent;color:#89a5b4;font-weight:900;cursor:pointer}.uo-dock-body{padding:8px;display:grid;gap:5px}.uo-layer-row{display:grid;grid-template-columns:auto 1fr auto;gap:7px;align-items:center;padding:7px 8px;border:1px solid #1d3848;border-radius:8px;background:#07151e;color:#dcecf0;font-size:7px}.uo-layer-row input{accent-color:var(--uo-accent)}.uo-layer-row small{color:#7592a2;text-align:right}.uo-layer-row.is-active{border-color:rgba(67,229,189,.42);background:rgba(67,229,189,.07)}
#uo-evidence-strip{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:12px}.uo-proof{padding:10px;border:1px solid var(--uo-line);border-radius:11px;background:#07151e}.uo-proof small{display:block;color:#7592a2;font-size:6px;letter-spacing:.1em;font-weight:900}.uo-proof b{display:block;margin-top:4px;font:700 13px 'Space Grotesk'}.uo-proof span{display:block;margin-top:3px;color:#8fa9b5;font-size:7px;line-height:1.4}.uo-proof.good{border-color:rgba(67,229,189,.3)}.uo-proof.warn{border-color:rgba(255,200,87,.3)}
#uo-focus-bar{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.uo-focus{padding:7px 9px;border:1px solid #254858;border-radius:999px;background:#071720;color:#9eb7c2;font-size:7px;font-weight:900;cursor:pointer}.uo-focus.active{background:rgba(67,229,189,.1);border-color:rgba(67,229,189,.5);color:#67e9c6}
.leaflet-container .uo-site-pin,.leaflet-container .uo-tod-pin{display:grid;place-items:center;width:34px;height:34px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);border:2px solid #fff;box-shadow:0 5px 16px rgba(0,0,0,.35)}.uo-site-pin i,.uo-tod-pin i{display:block;width:11px;height:11px;border-radius:50%;background:#fff}.uo-site-pin{background:linear-gradient(135deg,#18cce5,#43e5bd)}.uo-tod-pin{background:linear-gradient(135deg,#ffc857,#ff8f5a)}.uo-pin-label{font:900 8px Inter;letter-spacing:.03em}
.uo-ring-label{padding:4px 6px;border:1px solid rgba(67,229,189,.35);border-radius:999px;background:rgba(5,18,27,.9);color:#d9f8f0;font:800 7px Inter;box-shadow:0 5px 15px rgba(0,0,0,.2)}
@media(max-width:900px){#spatial-studio .ss-grid{grid-template-columns:1fr!important}.ss-panel{max-height:none!important}.ss-map{height:470px!important}#uo-evidence-strip{grid-template-columns:repeat(2,1fr)}}
@media(max-width:600px){body.uo-clean .header .logo{width:155px}#uo-map-hud{right:12px}#uo-layer-dock{top:54px;width:calc(100% - 24px)}#uo-evidence-strip{grid-template-columns:1fr 1fr}.uo-proof b{font-size:11px}}
`;
const st=document.createElement('style');st.id='urbion-visual-overhaul-style';st.textContent=css;document.head.appendChild(st);
function waitFor(fn,tries=80){if(fn())return; if(tries>0)setTimeout(()=>waitFor(fn,tries-1),100)}
function addStatus(){if($('uo-statusbar'))return;const nav=$('nav');if(!nav)return;const el=document.createElement('div');el.id='uo-statusbar';el.innerHTML='<div class="uo-live"><i class="uo-dot"></i> LIVE PLANNING EVIDENCE <span style="opacity:.5">·</span> deterministic core online</div><button id="uo-density">COMPACT UI</button>';nav.insertAdjacentElement('afterend',el);$('uo-density').onclick=()=>document.body.classList.toggle('uo-compact')}
function cleanBrand(){document.body.classList.add('uo-clean');const brand=document.querySelector('.brand');if(brand){const old=brand.querySelector('strong');if(old)old.setAttribute('aria-label','URBION HORIZON');}}
function category(x){const s=((x.name||x.id||'')+' '+(x.type||'')).toLowerCase();if(/zoning|zon|land use|guna tanah|committed|density|plot/.test(s))return'ZONING / LAND USE';if(/flood|water|river|drain|environment|eco|green|forest|ksas|slope|contour/.test(s))return'ENVIRONMENT';if(/road|transport|rail|transit|bus|network|mobility/.test(s))return'MOBILITY';return'SPATIAL CONTEXT'}
function sourceStatus(x){return String(x?.status||x?.evidence_status||x?.source_status||'SOURCE CONTEXT').toUpperCase()}
function addIcon(className){return L.divIcon({className:'',html:`<div class="${className}"><i></i></div>`,iconSize:[34,34],iconAnchor:[17,34],popupAnchor:[0,-30]})}
function setupMap(){const map=$('ss-map');if(!map||!window.L||map.__uoReady)return false;const leaflet=map._leaflet_map_instance||map.__leaflet_map;if(!leaflet)return false;map.__uoReady=true;const m=leaflet;
 const s=()=>({lat:parseFloat($('lat')?.value),lon:parseFloat($('lon')?.value),todlat:parseFloat($('todlat')?.value),todlon:parseFloat($('todlon')?.value)});
 const hav=(a,b,c,d)=>{const R=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,z=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(z))};
 const layers={};
 const site=L.marker([s().lat,s().lon],{icon:addIcon('uo-site-pin'),zIndexOffset:900}).addTo(m).bindTooltip('<span class="uo-pin-label">SCREENING SITE</span>',{permanent:false,direction:'top'}).bindPopup('<b>URBION SCREENING SITE</b><br>🟡 User-provided / map-selected input');
 const tod=L.marker([s().todlat,s().todlon],{icon:addIcon('uo-tod-pin'),zIndexOffset:850}).addTo(m).bindTooltip('<span class="uo-pin-label">TOD REFERENCE</span>',{permanent:false,direction:'top'}).bindPopup('<b>TOD REFERENCE</b><br>Reference point used for screening distance.');
 const ringSpecs=[[400,'400 m catchment',.06],[800,'800 m catchment',.035],[1000,'1 km context',.018],[1500,'1.5 km context',.012]];
 ringSpecs.forEach(([r,label,fill],i)=>{const c=L.circle([s().lat,s().lon],{radius:r,color:i<2?'#43e5bd':'#18cce5',weight:i<2?2:1,opacity:.65,fillOpacity:fill,interactive:false}).addTo(m);layers['ring'+r]=c;L.marker([s().lat,s().lon],{icon:L.divIcon({className:'',html:`<span class="uo-ring-label">${label}</span>`,iconSize:[90,20],iconAnchor:[45,10]}),interactive:false}).addTo(m).setZIndexOffset(300-i);});
 const link=L.polyline([[s().lat,s().lon],[s().todlat,s().todlon]],{color:'#ffc857',weight:3,dashArray:'8 7',opacity:.85}).addTo(m);layers.link=link;
 function sync(){const v=s();if(![v.lat,v.lon,v.todlat,v.todlon].every(Number.isFinite))return;site.setLatLng([v.lat,v.lon]);tod.setLatLng([v.todlat,v.todlon]);ringSpecs.forEach(([r])=>layers['ring'+r].setLatLng([v.lat,v.lon]));link.setLatLngs([[v.lat,v.lon],[v.todlat,v.todlon]]);const d=hav(v.lat,v.lon,v.todlat,v.todlon);const hud=$('uo-map-hud');if(hud)hud.querySelector('[data-metric="distance"]').textContent=(d<1000?Math.round(d)+' m':(d/1000).toFixed(2)+' km');}
 const host=document.createElement('div');host.id='uo-map-hud';host.innerHTML='<span class="uo-hud-chip">SITE <b>ACTIVE</b></span><span class="uo-hud-chip">TOD DISTANCE <b data-metric="distance">—</b></span><span class="uo-hud-chip">4 CATCHMENT RINGS</span>';map.appendChild(host);
 const dock=document.createElement('div');dock.id='uo-layer-dock';dock.innerHTML='<div class="uo-dock-head"><b>MAP EVIDENCE OVERLAYS</b><button type="button" id="uo-dock-toggle">−</button></div><div class="uo-dock-body" id="uo-dock-body"><label class="uo-layer-row is-active"><input type="checkbox" data-ring="400" checked><span>400 m screening catchment</span><small>CALC</small></label><label class="uo-layer-row is-active"><input type="checkbox" data-ring="800" checked><span>800 m screening catchment</span><small>CALC</small></label><label class="uo-layer-row is-active"><input type="checkbox" data-ring="1000" checked><span>1 km context ring</span><small>CALC</small></label><label class="uo-layer-row is-active"><input type="checkbox" data-ring="1500" checked><span>1.5 km context ring</span><small>CALC</small></label><label class="uo-layer-row is-active"><input type="checkbox" data-link checked><span>Site → TOD relationship</span><small>CALC</small></label><div id="uo-source-layer-list"></div></div>';map.appendChild(dock);
 $('uo-dock-toggle').onclick=()=>{$('uo-dock-body').style.display=$('uo-dock-body').style.display==='none'?'grid':'none';$('uo-dock-toggle').textContent=$('uo-dock-body').style.display==='none'?'+':'−'};
 dock.querySelectorAll('input[data-ring]').forEach(cb=>cb.onchange=()=>{const r=cb.dataset.ring;const l=layers['ring'+r];if(l)(cb.checked?m.addLayer(l):m.removeLayer(l));cb.closest('label').classList.toggle('is-active',cb.checked)});
 dock.querySelector('input[data-link]').onchange=e=>{e.target.checked?m.addLayer(link):m.removeLayer(link);e.target.closest('label').classList.toggle('is-active',e.target.checked)};
 sync();m.on('click',()=>setTimeout(sync,50));
 loadSourceLayers(m,dock);return true}
async function loadSourceLayers(m,dock){try{const state=encodeURIComponent($('state')?.value||'Melaka');const r=await fetch('/map/layers?state='+state,{cache:'no-store'});if(!r.ok)throw Error(r.status);const data=await r.json();const list=(data.layers||[]).filter(x=>['GEOSERVER_WMS','TILE','ARCGIS_MAP'].includes(x.type));const host=$('uo-source-layer-list');if(!host)return;const groups={};list.forEach(x=>{const g=category(x);(groups[g]??=[]).push(x)});host.innerHTML=Object.entries(groups).map(([g,items])=>`<div style="margin-top:8px;color:#6f8c9c;font-size:6px;font-weight:900;letter-spacing:.12em">${esc(g)}</div>`+items.map((x,i)=>`<label class="uo-layer-row"><input type="checkbox" data-src="${esc(x.id)}"><span>${esc(x.name||x.id)}</span><small>${esc(sourceStatus(x))}</small></label>`).join('')).join('')||'<div style="color:#7894a3;font-size:7px;padding:5px">No declared visual source layers available.</div>';
 const stateLayers=new Map();list.forEach(x=>{const cb=host.querySelector(`input[data-src="${CSS.escape(x.id)}"]`);if(!cb)return;cb.onchange=()=>{let layer=stateLayers.get(x.id);if(!cb.checked){if(layer)m.removeLayer(layer);cb.closest('label').classList.remove('is-active');return}if(!layer){if(x.type==='GEOSERVER_WMS'&&x.url&&x.layers)layer=L.tileLayer.wms(x.url,{layers:x.layers,transparent:true,format:'image/png',version:'1.1.1',opacity:.68});else if(x.type==='TILE'&&x.url)layer=L.tileLayer(x.url,{opacity:.68});else if(x.type==='ARCGIS_MAP'&&x.url)layer=L.tileLayer(x.url.replace(/\/MapServer.*$/,'/MapServer/tile/{z}/{y}/{x}'),{opacity:.68});if(layer)stateLayers.set(x.id,layer)}if(layer){layer.addTo(m);cb.closest('label').classList.add('is-active')}};
 });
 }catch(e){const host=$('uo-source-layer-list');if(host)host.innerHTML='<div style="color:#ffc857;font-size:7px;padding:5px">Source catalogue unavailable. Calculated screening overlays remain active.</div>'}}
function addEvidenceStrip(){if($('uo-evidence-strip'))return;const studio=$('spatial-studio');if(!studio)return;const strip=document.createElement('div');strip.id='uo-evidence-strip';strip.innerHTML='<div class="uo-proof good"><small>SCREENING SITE</small><b>PINNED</b><span>User/map-selected coordinate</span></div><div class="uo-proof good"><small>TOD RELATION</small><b>VISIBLE</b><span>Reference point + relationship line</span></div><div class="uo-proof good"><small>CATCHMENTS</small><b>400 · 800 m</b><span>Plus 1 km and 1.5 km context rings</span></div><div class="uo-proof"><small>SOURCE LAYERS</small><b>TOGGLE</b><span>Zoning, land use, environment & mobility when declared</span></div><div class="uo-proof warn"><small>BOUNDARY</small><b>REVIEW</b><span>Visual evidence ≠ statutory confirmation</span></div>';studio.insertAdjacentElement('afterend',strip)}
function compactOtherPanels(){const candidates=['#intel-upgrade','#urbion-decision-intelligence','#decision-intelligence'];candidates.forEach(sel=>{const el=document.querySelector(sel);if(el){el.style.maxHeight='240px';el.style.overflow='auto'}})}
function boot(){addStatus();cleanBrand();compactOtherPanels();waitFor(()=>setupMap());waitFor(()=>{addEvidenceStrip();return !!$('uo-evidence-strip')});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();