(()=>{
'use strict';
if(window.__URBION_DECISION_OS_UI)return;window.__URBION_DECISION_OS_UI=true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=`#urbion-decision-os{position:fixed;right:18px;top:18px;z-index:9997;width:min(390px,calc(100vw - 36px));padding:12px;border:1px solid rgba(24,204,229,.28);border-radius:14px;background:rgba(7,19,31,.92);backdrop-filter:blur(16px);box-shadow:0 16px 45px rgba(0,0,0,.28);font:10px Inter,system-ui,sans-serif;color:#eaf5f7}#urbion-decision-os .do-head{display:flex;justify-content:space-between;gap:8px;align-items:center}.do-k{font-size:7px;font-weight:900;letter-spacing:.15em;color:#18cce5}.do-title{font:700 14px 'Space Grotesk',Inter,sans-serif}.do-gate{margin-top:9px;padding:9px;border-radius:10px;background:#0a1722;border:1px solid #274657}.do-gate b{font-size:11px}.do-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:7px}.do-metrics div{padding:7px;background:#091722;border:1px solid #203343;border-radius:8px}.do-metrics span{display:block;color:#7f98a8;font-size:7px}.do-metrics strong{display:block;margin-top:2px}.do-block{margin-top:8px;color:#ffd37a;font-size:8px;line-height:1.45}.do-note{margin-top:8px;color:#7890a3;font-size:7px;line-height:1.45}#urbion-decision-os button{border:1px solid #31516a;background:#0b1b28;color:#eaf5f7;border-radius:8px;padding:6px 8px;font:900 8px Inter;cursor:pointer}@media(max-width:600px){#urbion-decision-os{right:8px;top:8px;width:calc(100vw - 16px)}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const el=document.createElement('aside');el.id='urbion-decision-os';el.innerHTML='<div class="do-head"><div><div class="do-k">SIGMA · DECISION OS</div><div class="do-title">Evidence-gated planner review</div></div><button id="do-run">GATE</button></div><div id="do-gate" class="do-gate">Awaiting deterministic packet</div><div id="do-metrics" class="do-metrics"><div><span>QUALITY</span><strong>—</strong></div><div><span>COVERAGE</span><strong>—</strong></div><div><span>VERIFIED</span><strong>—</strong></div></div><div id="do-block" class="do-block"></div><div class="do-note">Decision OS is planner decision support only. It does not infer statutory approval or replace authority review.</div></aside>';
document.body.appendChild(el);
function payload(){let raw=sessionStorage.getItem('urbion_assessment_inputs');try{if(raw)return JSON.parse(raw)}catch(e){}return{site_lat:2.285,site_lon:102.196,tod_lat:2.286,tod_lon:102.197,plot_ratio:4.5,precinct:'Terminal Sg. Udang',development_type:'TOD Development / Mixed Use',development_class:'Mixed Use',state:'Melaka',district:'Melaka Tengah',pbt:'Majlis Bandaraya Melaka Bersejarah',lot_no:'11213'}}
async function run(){const b=document.getElementById('do-run');b.disabled=true;b.textContent='…';try{const r=await fetch('/intelligence/decision-os',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assessment_inputs:payload()})});const d=await r.json();if(!r.ok)throw Error(d.detail?.message||d.detail||r.status);const x=d.decision_os||{};document.getElementById('do-gate').innerHTML='<b>'+esc(x.gate||'UNKNOWN')+'</b><br><span style="opacity:.7">Status: '+esc(x.decision_status)+'</span>';const e=x.evidence||{};document.getElementById('do-metrics').innerHTML='<div><span>QUALITY</span><strong>'+esc(e.score??'—')+'</strong></div><div><span>COVERAGE</span><strong>'+esc(e.coverage??'—')+'</strong></div><div><span>VERIFIED</span><strong>'+esc(e.verified_ratio??'—')+'</strong></div>';document.getElementById('do-block').innerHTML=(x.blockers||[]).map(v=>'• '+esc(v)).join('<br>')||'No active gate blockers.'}catch(e){document.getElementById('do-gate').innerHTML='<b>GATE FAILED</b><br>'+esc(e.message)}finally{b.disabled=false;b.textContent='GATE'}}
document.getElementById('do-run').onclick=run;
})();