(()=>{
'use strict';
if(window.__URBION_VISUAL_SYSTEM_V1__)return;
window.__URBION_VISUAL_SYSTEM_V1__=true;
const css=`
:root{--vh-bg:#031019;--vh-bg2:#061b29;--vh-panel:#071c2a;--vh-panel2:#092435;--vh-line:rgba(79,204,220,.20);--vh-strong:rgba(71,224,214,.45);--vh-text:#effcff;--vh-body:#b9cbd3;--vh-muted:#76929f;--vh-cyan:#39d9e8;--vh-mint:#57e2c0;--vh-blue:#6aaaff;--vh-amber:#ffc568}
body.horizon-ui{background:radial-gradient(950px 560px at 76% -4%,rgba(38,174,216,.16),transparent 62%),radial-gradient(780px 560px at 10% 92%,rgba(57,218,187,.09),transparent 58%),linear-gradient(180deg,#020a12 0%,#041622 48%,#020a12 100%)!important;color:var(--vh-text)!important}
body.horizon-ui #urbion-championship-shell{padding-bottom:38px!important;background:transparent!important}
body.horizon-ui #urbion-championship-shell:before{opacity:.22!important;background-size:28px 28px,56px 56px,56px 56px!important}
body.horizon-ui .topbar{height:74px!important;padding:0 26px!important;background:rgba(3,13,21,.91)!important;border-bottom-color:rgba(78,204,220,.16)!important}
body.horizon-ui .identity img{width:184px!important;max-height:42px!important}
body.horizon-ui .identity strong{font-size:15px!important}.identity small{font-size:8px!important}.institution{font-size:9px!important}
body.horizon-ui .main-nav{height:54px!important;padding:0 22px!important;gap:5px!important;background:rgba(4,18,28,.86)!important;border-bottom-color:rgba(78,204,220,.14)!important}
body.horizon-ui .nav-link{height:38px!important;padding:0 12px!important;font-size:9px!important;border-radius:10px!important}.nav-link span{font-size:9px!important}
body.horizon-ui .utility{font-size:8px!important;padding:8px 10px!important}
body.horizon-ui .app-shell{max-width:1680px!important;padding:0 24px 30px!important}
body.horizon-ui .workspace-head{padding:24px 0 18px!important;min-height:112px!important}
body.horizon-ui .workspace-head .eyebrow{font-size:10px!important;letter-spacing:.19em!important}
body.horizon-ui .workspace-head h1{font-size:clamp(40px,3.25vw,56px)!important;line-height:1.04!important;letter-spacing:-.052em!important;margin:6px 0 10px!important}
body.horizon-ui .workspace-head p{font-size:12px!important;color:#90aab5!important}
body.horizon-ui .workspace-actions .primary{min-width:220px!important;min-height:46px!important;padding:12px 16px!important;font-size:12px!important}
body.horizon-ui .workstation{grid-template-columns:minmax(315px,350px) minmax(0,1fr) minmax(370px,410px)!important;gap:16px!important;align-items:start!important;position:relative!important}
body.horizon-ui .case-panel,body.horizon-ui .map-panel-canonical,body.horizon-ui .intel-head,body.horizon-ui .intel-card{border-radius:18px!important}
body.horizon-ui .case-panel{height:calc(100vh - 202px)!important;max-height:930px!important;min-height:680px!important;background:linear-gradient(145deg,rgba(8,29,43,.98),rgba(3,13,22,.99))!important;border-color:rgba(79,205,218,.24)!important;box-shadow:0 22px 60px rgba(0,0,0,.30)!important}
body.horizon-ui .panel-title{padding:19px 18px!important}.panel-title h2{font-size:18px!important}.panel-title p{font-size:10px!important;line-height:1.5!important}
body.horizon-ui .case-body{padding:10px 12px!important}.case-body summary{font-size:8px!important;padding:9px 4px!important}.field{margin:8px 4px!important}.field>span{font-size:7px!important}.field input,.field select{height:39px!important;font-size:10px!important;padding:9px 10px!important;border-radius:9px!important}
body.horizon-ui .map-panel-canonical{background:linear-gradient(145deg,#071c2b,#03111c)!important;border-color:rgba(75,210,224,.30)!important;box-shadow:0 26px 70px rgba(0,0,0,.37)!important;overflow:hidden!important}
body.horizon-ui .map-toolbar{min-height:78px!important;padding:14px 16px!important}.map-toolbar .eyebrow{font-size:10px!important}.map-toolbar h2{font-size:17px!important;line-height:1.2!important}.base-tab{font-size:9px!important;padding:9px 11px!important;border-radius:9px!important}
body.horizon-ui .map-stage{height:min(68vh,700px)!important;min-height:560px!important;background:#06131d!important}.map-search{top:14px!important;right:14px!important;width:310px!important}.map-search input{font-size:10px!important;padding:11px!important}.map-controls{top:78px!important;left:14px!important}.map-controls button{width:36px!important;height:36px!important;border-radius:9px!important}
body.horizon-ui .intel-panel{gap:11px!important;padding:0!important;overflow:auto!important;max-height:calc(100vh - 202px)!important}.intel-head{padding:18px 16px!important;background:linear-gradient(145deg,rgba(10,34,49,.98),rgba(4,15,24,.99))!important;border-color:rgba(74,211,221,.25)!important}.intel-head .eyebrow{font-size:10px!important}.intel-head h2{font-size:22px!important;line-height:1.18!important}.case-code{font-size:8px!important}
body.horizon-ui .intel-card{padding:16px!important;background:linear-gradient(145deg,rgba(8,26,39,.97),rgba(3,14,23,.99))!important;border-color:rgba(76,193,209,.18)!important;box-shadow:0 14px 32px rgba(0,0,0,.22)!important}.intel-card .eyebrow{font-size:9px!important;letter-spacing:.14em!important}.card-row>b{font-size:21px!important}
body.horizon-ui .readiness-main{grid-template-columns:110px 1fr!important;gap:15px!important}.readiness-main strong{font-size:60px!important;line-height:.92!important}.readiness-main b{font-size:13px!important}.readiness-main p{font-size:10px!important;line-height:1.55!important}
body.horizon-ui .metrics{margin-top:11px!important}.metrics div{padding:9px 0!important}.metrics span{font-size:9px!important}.metrics b{font-size:9px!important}
body.horizon-ui .site-summary{margin:9px 0!important}.site-summary b{font-size:20px!important}.site-summary span{font-size:10px!important}.link-btn{font-size:9px!important}.mini-stats{gap:7px!important}.mini-stats span{padding:9px!important}.mini-stats b{font-size:14px!important}.mini-stats small{font-size:7px!important}
body.horizon-ui .signals div{padding:9px 0!important;font-size:10px!important}.signals b{font-size:8px!important}.next-card h3{font-size:19px!important}.next-card p{font-size:10px!important}.next-card button{font-size:9px!important;padding:10px!important}.tool-grid button{font-size:8px!important;padding:10px!important}.tool-result{font-size:9px!important;max-height:100px!important}
body.horizon-ui .workbench{margin-top:16px!important}.workbench-nav{padding:6px!important;border-radius:12px!important}.workbench-nav button{font-size:9px!important;padding:9px 13px!important}.analysis-card{padding:17px!important;border-radius:16px!important}.analysis-card h2{font-size:22px!important}.analysis-card h3{font-size:15px!important}.analysis-card p{font-size:10px!important}.metric-box b{font-size:19px!important}.scenario strong{font-size:30px!important}.scenario p{font-size:9px!important}.footer{font-size:8px!important;margin-top:18px!important}
/* The old detached metric ribbon competes with the primary workflow; keep information inside the workbench. */
body.horizon-ui .horizon-metrics{display:none!important}
/* Definitive layer drawer: one scroll owner, non-scrolling groups. */
body.horizon-ui #cs-layer-drawer{top:12px!important;right:12px!important;bottom:12px!important;width:min(365px,42%)!important;height:auto!important;max-height:none!important;display:none!important;overflow-y:auto!important;overflow-x:hidden!important;padding:11px!important;border-radius:17px!important;background:rgba(2,14,23,.98)!important;border-color:rgba(84,218,228,.44)!important;box-shadow:0 30px 80px rgba(0,0,0,.58)!important;z-index:7000!important;scrollbar-width:thin!important;scrollbar-color:rgba(84,218,228,.56) transparent!important}
body.horizon-ui #cs-layer-drawer.open,body.horizon-ui #cs-layer-drawer:not(.horizon-closed)[aria-hidden=false]{display:flex!important;flex-direction:column!important}
body.horizon-ui #cs-layer-drawer::-webkit-scrollbar{width:7px!important}.cs-layer-drawer::-webkit-scrollbar-thumb{background:rgba(84,218,228,.45)!important;border-radius:99px!important}
body.horizon-ui #cs-layer-drawer .layers-head,body.horizon-ui #cs-layer-drawer .layer-status-key{flex:0 0 auto!important;position:sticky!important;top:0!important;z-index:4!important;background:rgba(2,14,23,.98)!important}
body.horizon-ui #cs-layer-drawer .layer-status-key{top:48px!important;padding-bottom:8px!important}
body.horizon-ui #cs-layer-drawer .layer-group{flex:0 0 auto!important;height:auto!important;max-height:none!important;overflow:visible!important;margin:4px 0!important;border:1px solid rgba(79,177,197,.17)!important;border-radius:11px!important;background:rgba(6,25,37,.72)!important}
body.horizon-ui #cs-layer-drawer .group-toggle{min-height:40px!important;padding:9px 11px!important;font-size:9px!important}.group-body{display:block!important;overflow:visible!important;height:auto!important;max-height:none!important}
body.horizon-ui #cs-layer-drawer .fcc-layer-row{min-height:45px!important;padding:8px 9px!important;margin:2px 4px!important;grid-template-columns:19px minmax(0,1fr) 54px!important;gap:8px!important;border-radius:9px!important}.fcc-layer-row span{font-size:10px!important;line-height:1.25!important}.fcc-layer-row span small{font-size:8px!important}.fcc-layer-row input[type=checkbox]{width:17px!important;height:17px!important}.layer-opacity{width:54px!important;height:16px!important}.legend-inline{font-size:8px!important;gap:10px!important;padding:11px 3px 3px!important}
body.horizon-ui .workspace-head,.workstation,.workbench{position:relative}.workspace-head:after{content:"01 CASE   →   02 SPATIAL EVIDENCE   →   03 ASSESS   →   04 WHAT-IF   →   05 DECIDE   →   06 OUTPUT";display:block;margin-top:12px;color:#53717e;font:800 8px/1.2 Inter,sans-serif;letter-spacing:.09em;white-space:nowrap;opacity:.82}
@media(max-width:1340px){body.horizon-ui .workstation{grid-template-columns:minmax(285px,315px) minmax(0,1fr) minmax(330px,360px)!important}.institution{display:none!important}}
@media(max-width:1120px){body.horizon-ui .workstation{grid-template-columns:1fr!important}.case-panel,.intel-panel{height:auto!important;max-height:none!important}.map-stage{height:600px!important}.intel-panel{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important}.intel-head{grid-column:1/-1}.tool-card{grid-column:1/-1}}
@media(max-width:760px){body.horizon-ui .app-shell{padding:0 12px 22px!important}.workspace-head{display:block!important}.workspace-head:after{white-space:normal!important;line-height:1.5!important}.workspace-actions{margin-top:12px!important}.workspace-head h1{font-size:clamp(34px,9vw,48px)!important}.workstation{display:block!important}.case-panel,.map-panel-canonical,.intel-panel{margin-bottom:12px!important}.intel-panel{display:block!important;max-height:none!important}.map-stage{height:540px!important;min-height:0!important}.map-search{width:calc(100% - 28px)!important}.map-tabs{flex-wrap:wrap!important}.base-tab{font-size:8px!important}.fcc-layer-drawer{left:10px!important;right:10px!important;top:auto!important;bottom:10px!important;width:auto!important;height:min(64%,440px)!important;max-height:440px!important}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;
const st=document.createElement('style');st.id='urbion-visual-system-v1';st.textContent=css;document.head.appendChild(st);
function normalize(){const d=document.querySelector('#cs-layer-drawer');if(!d)return;d.style.overflowY='auto';d.style.overflowX='hidden';d.querySelectorAll('.layer-group').forEach(g=>{g.style.maxHeight='none';g.style.height='auto';g.style.overflow='visible'});d.querySelectorAll('.group-body').forEach(g=>{g.style.maxHeight='none';g.style.height='auto';g.style.overflow='visible'});}
normalize();new MutationObserver(normalize).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','aria-hidden']});
})();
