(()=>{
  if(location.pathname!=='/' && !location.pathname.endsWith('/index.html') && !location.pathname.endsWith('/championship.html')) return;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const byText=(needle)=>[...document.querySelectorAll('#ss-layers .ss-layer')].filter(x=>x.textContent.toUpperCase().includes(needle));
  function style(){if(document.getElementById('ss-upgrade-style'))return;const s=document.createElement('style');s.id='ss-upgrade-style';s.textContent='.ss-focus{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:8px}.ss-focus button{border:1px solid #17303e;border-radius:7px;background:#07131c;color:#b8cad5;padding:7px 5px;font:900 7px Inter;cursor:pointer}.ss-focus button:hover{border-color:var(--a);color:var(--text)}.ss-evidencebar{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:8px;padding:8px;border:1px solid #17303e;border-radius:7px;background:#07131c;font-size:7px;color:#8299a8}.ss-evidencebar b{color:#d8e6ec}.ss-copycoord{border:1px solid #17303e;border-radius:6px;background:#07131c;color:#9ec0cc;padding:4px 6px;font:800 6px Inter;cursor:pointer}@media(max-width:600px){.ss-focus{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
  function setGroup(mode){const all=[...document.querySelectorAll('#ss-layers input[data-i]')];all.forEach(cb=>{const row=cb.closest('.ss-layer');const t=(row?.textContent||'').toUpperCase();let on=false;if(mode==='ALL')on=true;else if(mode==='OFF')on=false;else if(mode==='PLANNING')on=/I-PLAN|RFN/.test(t);else if(mode==='RISK')on=/FLOOD|DISASTER|FAULT|QUARRY|SEISMIC|GEOHAZARD/.test(t);else if(mode==='ENVIRONMENT')on=/KSAS|ECOLOG|CFS|HERITAGE|AFFORDABLE|TOPO|GROUNDWATER|LITHOLOGY|MINERAL|GEOHERITAGE/.test(t);if(cb.checked!==on){cb.checked=on;cb.dispatchEvent(new Event('change',{bubbles:true}))}})}
  function inject(){const panel=document.querySelector('#spatial-studio .ss-panel');if(!panel||document.getElementById('ss-upgrade'))return;style();const sec=document.createElement('div');sec.id='ss-upgrade';sec.className='ss-section';sec.innerHTML='<b>MAP FOCUS</b><div class="ss-focus"><button data-mode="PLANNING">PLANNING</button><button data-mode="RISK">RISK</button><button data-mode="ENVIRONMENT">ENVIRONMENT</button><button data-mode="ALL">ALL</button></div><div class="ss-evidencebar"><span><b id="ss-active-count">0</b> active visual layers · source context only</span><button id="ss-copy-coord" class="ss-copycoord">COPY COORDINATES</button></div>';panel.insertBefore(sec,panel.querySelector('.ss-note'));sec.querySelectorAll('button[data-mode]').forEach(b=>b.onclick=()=>setGroup(b.dataset.mode));document.getElementById('ss-copy-coord').onclick=()=>{const c=document.getElementById('ss-coords')?.textContent||'';navigator.clipboard?.writeText(c);document.getElementById('ss-copy-coord').textContent='COPIED';setTimeout(()=>document.getElementById('ss-copy-coord').textContent='COPY COORDINATES',1000)};updateCount();new MutationObserver(updateCount).observe(document.getElementById('ss-layers'),{childList:true,subtree:true,attributes:true,attributeFilter:['checked']})}
  function updateCount(){const n=document.querySelectorAll('#ss-layers input[data-i]:checked').length;const el=document.getElementById('ss-active-count');if(el)el.textContent=n}
  function boot(){inject();updateCount();setTimeout(()=>inject(),500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
