/* MASTER-267 championship workflow upgrade: planner-facing evidence, impact, what-if and action surfaces. */
(function(){
'use strict';
const API=location.origin;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=`
#uc-upgrade{margin:12px 0;border:1px solid #29445f;border-radius:20px;background:#08131eee;color:#eff8ff;font-family:Inter,system-ui,sans-serif;overflow:hidden}
#uc-upgrade *{box-sizing:border-box}.ux-head{padding:16px 18px;border-bottom:1px solid #203343;display:flex;justify-content:space-between;gap:12px;align-items:center}.ux-kicker{font-size:8px;font-weight:900;letter-spacing:.18em;color:#5ee7c2;text-transform:uppercase}.ux-title{margin:5px 0 0;font:600 21px 'Space Grotesk',Inter}.ux-live{font-size:8px;color:#7890a3;text-align:right}.ux-live b{color:#5ee7c2}.ux-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:12px}.ux-card{border:1px solid #203343;border-radius:13px;background:#ffffff03;padding:12px}.ux-card h4{margin:0 0 8px;font:600 13px 'Space Grotesk'}.ux-card p{margin:0;color:#8ea4b5;font-size:8px;line-height:1.55}.ux-pill{display:inline-block;margin-top:9px;padding:4px 7px;border-radius:99px;font:900 7px Inter;letter-spacing:.05em;background:#5ee7c212;color:#5ee7c2}.ux-pill.warn{background:#ffc85712;color:#ffc857}.ux-pill.bad{background:#ff687712;color:#ff6877}.ux-wide{grid-column:span 2}.ux-list{display:grid;gap:6px}.ux-row{display:flex;justify-content:space-between;gap:8px;padding:8px;border:1px solid #203343;border-radius:8px;font-size:8px}.ux-row span:last-child{color:#5ee7c2;font-weight:800}.ux-action{display:flex;flex-wrap:wrap;gap:6px;margin-top:9px}.ux-btn{border:1px solid #29445f;background:#07121c;color:#eff8ff;border-radius:8px;padding:7px 9px;font:900 7px Inter;cursor:pointer;text-decoration:none}.ux-btn:hover{border-color:#5ee7c2}.ux-btn.primary{background:#5ee7c2;color:#031017;border-color:#5ee7c2}.ux-bar{height:7px;border-radius:99px;background:#0a1b28;overflow:hidden;margin-top:6px}.ux-fill{height:100%;background:linear-gradient(90deg,#5ee7c2,#6aa9ff);border-radius:99px}.ux-compare{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.ux-scenario{padding:10px;border:1px solid #203343;border-radius:10px}.ux-scenario strong{display:block;font-size:10px}.ux-scenario small{display:block;color:#7890a3;font-size:7px;margin-top:3px}.ux-delta{font:700 16px 'Space Grotesk';margin-top:8px}.ux-note{margin-top:10px;padding:9px;border:1px dashed #29445f;border-radius:9px;color:#7890a3;font-size:7px;line-height:1.5}.ux-footer{padding:10px 14px;border-top:1px solid #203343;color:#71889a;font-size:7px}@media(max-width:1000px){.ux-grid{grid-template-columns:1fr 1fr}.ux-wide{grid-column:span 2}.ux-compare{grid-template-columns:1fr}}@media(max-width:650px){.ux-grid{grid-template-columns:1fr}.ux-wide{grid-column:span 1}.ux-head{align-items:flex-start;flex-direction:column}.ux-live{text-align:left}}
`;
function style(){if(document.getElementById('uc-upgrade-style'))return;const s=document.createElement('style');s.id='uc-upgrade-style';s.textContent=css;document.head.appendChild(s)}
function q(id){return document.getElementById(id)}
async function json(path,opts){const r=await fetch(API+path,opts);if(!r.ok)throw Error(path+' '+r.status);return r.json()}
function inputs(){const g=id=>q(id);return{site_lat:+g('uc-lat').value,site_lon:+g('uc-lon').value,tod_lat:+g('uc-todlat').value,tod_lon:+g('uc-todlon').value,plot_ratio:+g('uc-ratio').value,precinct:g('uc-precinct').value,development_type:g('uc-devtype').value,development_class:g('uc-devclass').value,state:g('uc-state').value,district:g('uc-district').value,pbt:g('uc-pbt').value,lot_no:g('uc-lot').value,building_height:g('uc-height').value?+g('uc-height').value:null,perimeter_planting:g('uc-plant').value?+g('uc-plant').value:null,landscaped_pedestrian_walkway:g('uc-walk').value?+g('uc-walk').value:null,shop_frontage_verified:g('uc-shop').value==='true',shop_office_verified:g('uc-office').value==='true'}}
function statusClass(s){s=String(s||'').toUpperCase();return s.includes('NON')?'bad':s.includes('REVIEW')||s.includes('RISK')?'warn':''}
function build(){if(q('uc-upgrade')||!q('urbion-championship'))return;const el=document.createElement('section');el.id='uc-upgrade';el.innerHTML=`<div class="ux-head"><div><div class="ux-kicker">MASTER-267 · Championship workflow</div><div class="ux-title">Planner Action Board</div></div><div class="ux-live"><b>LIVE WORKFLOW</b><br>SITE → GIS → POLICY → IMPACT → WHAT-IF → DECISION → LCP</div></div><div class="ux-grid"><div class="ux-card"><h4>01 · Site Intelligence</h4><p id="ux-site">Waiting for site analysis.</p><span id="ux-site-pill" class="ux-pill">READY</span></div><div class="ux-card"><h4>02 · Spatial Evidence</h4><p id="ux-spatial">Waiting for GIS context.</p><span id="ux-spatial-pill" class="ux-pill">SOURCE CONTEXT</span></div><div class="ux-card"><h4>03 · Environment</h4><p id="ux-env">Flood · KSAS · slope · geology · ecology</p><span class="ux-pill">SCREEN</span></div><div class="ux-card"><h4>04 · Policy & Agencies</h4><p id="ux-policy">Applicable rule and technical pathway will appear after assessment.</p><span id="ux-policy-pill" class="ux-pill">PLANNER REVIEW</span></div><div class="ux-card ux-wide"><h4>Development Impact</h4><div class="ux-list" id="ux-impact"><div class="ux-row"><span>Run URBION Analysis first</span><span>—</span></div></div></div><div class="ux-card ux-wide"><h4>Evidence & Review Gaps</h4><div class="ux-list" id="ux-evidence"><div class="ux-row"><span>Evidence state</span><span>UNVERIFIED</span></div></div><div class="ux-action"><a class="ux-btn" href="/decision-center">OPEN DECISION CENTER ↗</a><a class="ux-btn" href="/what-if">OPEN WHAT-IF ↗</a><a class="ux-btn" href="/judge-mode">OPEN JUDGE MODE ↗</a><a class="ux-btn" href="/judge-mode" target="_blank">PRESENTATION VIEW ↗</a></div></div><div class="ux-card ux-wide"><h4>What-If Decision Lens</h4><div class="ux-compare" id="ux-compare"><div class="ux-scenario"><strong>BASELINE</strong><small>Awaiting assessment</small><div class="ux-delta">—</div></div><div class="ux-scenario"><strong>SCENARIO A</strong><small>Adjust proposal parameters in What-If</small><div class="ux-delta">—</div></div><div class="ux-scenario"><strong>SCENARIO B</strong><small>Compare alternative intensity / controls</small><div class="ux-delta">—</div></div></div><div class="ux-note">The comparison surface is decision support: it highlights directional change and review needs. It does not replace statutory assessment or approval.</div></div><div class="ux-card"><h4>Decision Boundary</h4><p id="ux-boundary">PLANNER DECISION SUPPORT ONLY</p><span class="ux-pill warn">NOT STATUTORY APPROVAL</span></div><div class="ux-card"><h4>LCP Handoff</h4><p>Consolidate assessment, spatial intelligence, impact, policy, recommendations, What-If and review gaps into the planner-facing LCP intelligence layer.</p><span class="ux-pill">READY FOR REVIEW</span></div></div><div class="ux-footer">URBION HORIZON · Explainable planning intelligence · Human-in-the-loop</div>`;q('urbion-championship').after(el)}
function render(a){if(!a)return;const s=a.final_status||'REQUIRES REVIEW',c=a.decision_confidence||{},site=a.site||{},sa=a.site_analysis||{},ei=a.evidence_intelligence||{};q('ux-site').textContent=`${site.state||'—'} · ${site.district||'—'} · ${site.pbt||'—'} · ${site.lot_no||'Lot not specified'}`;q('ux-site-pill').textContent=s; q('ux-site-pill').className='ux-pill '+statusClass(s);const sc=a.classification||'—';q('ux-spatial').textContent=`${sc} · ${Number(a.tod_distance_m||0).toFixed(0)} m from TOD node · ${a.development_class||'—'}`;const cov=a.policy_coverage||{};q('ux-policy').textContent=`${a.retrieved_rules?.length||0} rule(s) retrieved · policy coverage ${typeof cov==='object'?(cov.status||cov.coverage||'available'):'available'} · agencies: JPS / JKR / TNB / IWK / PBT`;q('ux-policy-pill').textContent=s.includes('COMPLY')?'POLICY TRACE':'REVIEW REQUIRED';const score=sa.suitability_score??(sa.suitability||{}).score??'—';q('ux-impact').innerHTML=[['Suitability',score==='—'?'—':`${score}/100`],['Final decision',s],['Confidence',c.band||'—'],['Recommendation',a.recommendation?.headline||a.recommendation||'Planner review']].map(x=>`<div class="ux-row"><span>${esc(x[0])}</span><span>${esc(x[1])}</span></div>`).join('');const es=a.evidence_state||{};const gaps=a.review_gaps||sa.review_gaps||[];q('ux-evidence').innerHTML=[['Site coordinates',es.site_coordinates||'USER_PROVIDED'],['TOD distance',es.tod_distance||'CALCULATED'],['Planning rules',es.planning_rules||'SOURCE_CONTEXT'],['Final decision',es.final_decision||'CALCULATED'],['Statutory verification',es.statutory_verification||'NOT_CLAIMED'],['Review gaps',Array.isArray(gaps)?gaps.length:'—']].map(x=>`<div class="ux-row"><span>${esc(x[0])}</span><span>${esc(x[1])}</span></div>`).join('');q('ux-boundary').textContent=a.decision_boundary||'INTEGRATED_LCP_PLANNING_SUPPORT';q('ux-env').textContent=ei?.summary||'Flood · KSAS · slope · geohazard · groundwater · ecology · hydrology screened through available source context.'}
async function wire(){const b=q('urbion-championship');if(!b)return;try{await new Promise(r=>setTimeout(r,350));const a=window.__urbionAssessment;if(a)render(a);const analyse=q('uc-analyse');if(analyse){analyse.addEventListener('click',()=>setTimeout(async()=>{try{const a=await json('/assess',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(inputs())});window.__urbionAssessment=a;render(a)}catch(e){q('ux-site').textContent='Assessment error: '+e.message}},500))}}catch(e){}}
style();build();wire();window.addEventListener('load',wire);
})();
