/* MASTER-283: public spatial intelligence + source-aligned planning classification. */
(()=>{
'use strict';
if(window.__URBION_PUBLIC_SPATIAL_V283__)return;
window.__URBION_PUBLIC_SPATIAL_V283__=1;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(u,o)=>{const r=await fetch(u,o);if(!r.ok)throw Error(u+' · '+r.status);return r.json()};
const p=()=>({site_lat:+($('dash-lat')?.value||2.285),site_lon:+($('dash-lon')?.value||102.196),state:$('dash-state')?.value||'Melaka'});
const ARCGIS={
 fault:'https://mygems.jmg.gov.my/server/rest/services/GeologiAsas/Major_Fault/FeatureServer/5/query',
 lithology:'https://mygems.jmg.gov.my/server/rest/services/Demarcation/Litology_by_Negeri/FeatureServer/22/query',
 school:'https://scharms.planmalaysia.gov.my/arcgis/rest/services/SCHARMS/MobileLayer/MapServer/28/query',
 health:'https://scharms.planmalaysia.gov.my/arcgis/rest/services/SCHARMS/MobileLayer/MapServer/26/query',
 transport:'https://scharms.planmalaysia.gov.my/arcgis/rest/services/SCHARMS/MobileLayer/MapServer/32/query'
};
const state={map:null,layers:{},busy:false};
const css=document.createElement('style');css.textContent=`.v283-shell{border:1px solid #244452;border-radius:14px;background:#07131b;padding:14px;margin-top:10px}.v283-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v283-kicker{font-size:8px;letter-spacing:.14em;color:#67e8b7;font-weight:900}.v283-title{font-size:17px;font-weight:900;margin-top:3px}.v283-muted{font-size:9px;color:#78919d;line-height:1.5}.v283-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.v283-card{border:1px solid #203b46;border-radius:10px;padding:10px;background:#081820}.v283-card b{display:block;color:#eaf7f4;font-size:10px}.v283-card small{display:block;color:#78919d;line-height:1.45;margin-top:4px}.v283-status{font-size:8px;font-weight:900;letter-spacing:.08em;margin-top:7px;display:inline-block}.v283-ok{color:#67e8b7}.v283-warn{color:#ffd27a}.v283-bad{color:#ff8292}.v283-btn{border:1px solid #284654;background:#0a1a22;color:#edf7f5;border-radius:8px;padding:8px 10px;font:800 9px Inter;cursor:pointer;margin:5px 5px 0 0}.v283-btn.active{border-color:#67e8b7;color:#67e8b7}.v283-table{width:100%;border-collapse:collapse;font-size:9px;margin-top:8px}.v283-table th,.v283-table td{padding:7px;border-bottom:1px solid #19313b;text-align:left;vertical-align:top}.v283-table th{color:#67e8b7}.v283-select{width:100%;margin-top:6px;background:#07131b;color:#edf7f5;border:1px solid #294653;border-radius:8px;padding:8px;font:700 9px Inter}.v283-result{margin-top:9px;max-height:330px;overflow:auto}.v283-chip{display:inline-block;border:1px solid #294653;border-radius:999px;padding:4px 7px;margin:3px;color:#a8c0c8;font-size:8px}.v283-note{margin-top:8px;padding:8px;border-left:2px solid #67e8b7;background:#091b23;color:#91aab3;font-size:8px;line-height:1.5}@media(max-width:900px){.v283-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.v283-grid{grid-template-columns:1fr}.v283-head{display:block}}`;
document.head.appendChild(css);
function arcParams(lat,lon){return new URLSearchParams({where:'1=1',geometry:lon+','+lat,geometryType:'esriGeometryPoint',inSR:'4326',spatialRel:'esriSpatialRelIntersects',distance:'5000',units:'esriSRUnit_Meter',outFields:'*',returnGeometry:'true',outSR:'4326',f:'json'});}
async function arcQuery(url,lat,lon){const r=await fetch(url+'?'+arcParams(lat,lon));if(!r.ok)throw Error('ArcGIS '+r.status);const x=await r.json();if(x.error)throw Error(x.error.message||'ArcGIS query failed');return x}
function featureCollection(x){const fs=x.features||[];return{type:'FeatureCollection',features:fs.map(f=>{const g=f.geometry||{};let geom=null;if(g.x!=null&&g.y!=null)geom={type:'Point',coordinates:[g.x,g.y]};else if(g.paths)geom={type:'MultiLineString',coordinates:g.paths};else if(g.rings)geom={type:'MultiPolygon',coordinates:[g.rings]};return{type:'Feature',properties:f.attributes||{},geometry:geom}}).filter(f=>f.geometry)} }
function featureLabel(props,fallback){const keys=['nama','NAME','Name','HOR','AGE','Type','jenis','kod_kmdhn','kod_kmdhn'];for(const k of keys)if(props&&props[k]!=null&&String(props[k]).trim())return String(props[k]);return fallback}
function ensureMap(){state.map=window.__URBION_V277_MAP__||state.map;return state.map}
function draw(k,fc){const m=ensureMap();if(!m||!window.L)return false;if(state.layers[k])m.removeLayer(state.layers[k]);state.layers[k]=L.geoJSON(fc,{pointToLayer:(f,latlng)=>L.circleMarker(latlng,{radius:6,weight:2,fillOpacity:.8}),style:()=>({weight:2,fillOpacity:.18}),onEachFeature:(f,l)=>{l.bindPopup('<b>'+esc(featureLabel(f.properties,k))+'</b><br><small>'+esc(JSON.stringify(f.properties).slice(0,900))+'</small>')}});state.layers[k].addTo(m);return true}
async function toggle(k,btn){const m=ensureMap();if(!m){btn.textContent='MAP NOT READY';return}if(state.layers[k]){m.removeLayer(state.layers[k]);delete state.layers[k];btn.classList.remove('active');btn.textContent='OFF';return}btn.textContent='LOADING…';try{const q=p(),x=await arcQuery(ARCGIS[k],q.site_lat,q.site_lon),fc=featureCollection(x);if(!draw(k,fc))throw Error('Map library not ready');btn.textContent=(x.features||[]).length?'ON · '+x.features.length:'ON · 0';btn.classList.add('active');setResult(k,x)}catch(e){btn.textContent='ERROR';btn.classList.remove('active');setResult(k,{error:e.message})}}
function setResult(k,x){const o=$('v283-spatial-result');if(!o)return;if(x.error){o.innerHTML='<span class="v283-bad">'+esc(k)+' failed · '+esc(x.error)+'</span>';return}const fs=x.features||[];o.innerHTML='<b>'+esc(k.toUpperCase())+'</b> · '+fs.length+' feature(s) within 5 km'+(fs.length?'<table class="v283-table"><thead><tr><th>Feature</th><th>Key attributes</th></tr></thead><tbody>'+fs.slice(0,12).map(f=>'<tr><td>'+esc(featureLabel(f.attributes,k))+'</td><td>'+esc(JSON.stringify(f.attributes).slice(0,700))+'</td></tr>').join('')+'</tbody></table>':'<div class="v283-muted">No returned feature within the query radius.</div>')}
function addClassification(){const host=document.querySelector('#uhd-gis .v276-grid');if(!host||$('v283-class'))return;const c=document.createElement('div');c.id='v283-class';c.className='v276-card full v283-shell';c.innerHTML='<div class="v283-head"><div><div class="v283-kicker">PLANNING CLASSIFICATION</div><div class="v283-title">Guna Tanah → Aktiviti → Kategori</div><div class="v283-muted">Source-aligned planning helper. Options shown here are a curated UI subset; authoritative classifications remain the source plan / i-PLAN result.</div></div><span id="v283-class-state" class="v283-status v283-warn">READY</span></div><div class="v283-grid"><div class="v283-card"><b>Guna Tanah Semasa</b><select id="v283-land" class="v283-select"><option>Perumahan</option><option>Komersil</option><option>Industri</option><option>Institusi dan Kemudahan Masyarakat</option><option>Tanah Lapang dan Rekreasi</option><option>Pengangkutan dan Lalulintas</option><option>Infrastruktur dan Utiliti</option><option>Pertanian</option><option>Hutan</option><option>Badan Air</option><option>Pantai</option></select></div><div class="v283-card"><b>Aktiviti</b><select id="v283-activity" class="v283-select"></select></div><div class="v283-card"><b>Kategori</b><select id="v283-category" class="v283-select"></select></div></div><div id="v283-class-note" class="v283-note">Select a land-use class to filter source-aligned activity examples, then select a category. This helper does not replace the authoritative lot result.</div></div>';host.appendChild(c);
const map={
'Perumahan':[['Rumah Pekerja',['Rumah Pekerja']],['Teres',['Teres']],['Berkembar',['Berkembar']],['Bangunan Sesebuah',['Bangunan Sesebuah']],['Pembangunan Penggunaan Bercampur',['Pembangunan Penggunaan Bercampur']],['Kegunaan Khusus',['Kegunaan Khusus']]],
'Komersil':[['Kedai',['Kedai']],['Rumah Kedai',['Rumah Kedai']],['Kedai Pejabat',['Kedai Pejabat']]],
'Industri':[['Industri Umum',['Kilang / Gudang']],['Industri Khas',['Kegunaan Khusus']]],
'Institusi dan Kemudahan Masyarakat':[['Pendidikan',['Sekolah / Institusi Pendidikan']],['Kesihatan',['Hospital / Klinik']],['Keselamatan',['Polis / Bomba']]],
'Tanah Lapang dan Rekreasi':[['Rekreasi',['Taman / Sukan / Padang']]],
'Pengangkutan dan Lalulintas':[['Terminal / Stesen',['Bas / Rel / Teksi / Jeti']]],
'Infrastruktur dan Utiliti':[['Utiliti',['Infrastruktur / Utiliti']]],
'Pertanian':[['Pertanian',['Tanaman / Ternakan']]],'Hutan':[['Hutan',['Hutan']]],'Badan Air':[['Badan Air',['Sungai / Tasik / Empangan']]],'Pantai':[['Pantai',['Pantai / Pesisir']]]};
function fill(){const land=$('v283-land'),a=$('v283-activity'),cat=$('v283-category');if(!land||!a||!cat)return;const rows=map[land.value]||[];a.innerHTML=rows.map(r=>'<option value="'+esc(r[0])+'">'+esc(r[0])+'</option>').join('');cat.innerHTML=(rows[0]?.[1]||[]).map(v=>'<option>'+esc(v)+'</option>').join('');$('v283-class-state').textContent='FILTERED';$('v283-class-state').className='v283-status v283-ok'}land.onchange=fill;a.onchange=()=>{const r=(map[land.value]||[]).find(x=>x[0]===a.value);cat.innerHTML=(r?.[1]||[]).map(v=>'<option>'+esc(v)+'</option>').join('')};fill()}
function addSpatial(){const host=document.querySelector('#uhd-gis .v276-grid');if(!host||$('v283-spatial'))return;const c=document.createElement('div');c.id='v283-spatial';c.className='v276-card full v283-shell';c.innerHTML='<div class="v283-head"><div><div class="v283-kicker">PUBLIC SPATIAL INTELLIGENCE</div><div class="v283-title">JMG + SCHARMS / i-PLAN Results</div><div class="v283-muted">Live public feature queries around the active site. Query radius: 5 km. Results remain source-context evidence, not statutory approval.</div></div><span id="v283-live" class="v283-status v283-warn">READY</span></div><div><button class="v283-btn" data-v283="fault">Major Fault</button><button class="v283-btn" data-v283="lithology">Lithology · Melaka</button><button class="v283-btn" data-v283="school">Education</button><button class="v283-btn" data-v283="health">Health</button><button class="v283-btn" data-v283="transport">Transport</button><button class="v283-btn" id="v283-run">RUN SITE INTELLIGENCE</button></div><div id="v283-spatial-result" class="v283-card v283-result">Ready. Click a layer or run the complete site intelligence check.</div><div class="v283-note">Sources: JMG MyGEMS public FeatureServer; PLANMalaysia/SCHARMS public FeatureServer. The current site coordinate is taken from the URBION dashboard inputs.</div></div>';host.appendChild(c);c.querySelectorAll('[data-v283]').forEach(b=>b.onclick=()=>toggle(b.dataset.v283,b));$('v283-run').onclick=runAll}
async function runAll(){if(state.busy)return;state.busy=true;const live=$('v283-live'),o=$('v283-spatial-result');if(live)live.textContent='RUNNING…';if(o)o.textContent='Querying public spatial sources in parallel…';const q=p();const jobs=Object.entries(ARCGIS).map(([k,u])=>[k,arcQuery(u,q.site_lat,q.site_lon)]);const rs=await Promise.allSettled(jobs.map(x=>x[1]));let rows='';rs.forEach((r,i)=>{const k=jobs[i][0];const n=r.status==='fulfilled'?(r.value.features||[]).length:0;rows+='<tr><td>'+esc(k)+'</td><td class="'+(r.status==='fulfilled'?'v283-ok':'v283-bad')+'">'+(r.status==='fulfilled'?'RESPONDED':'FAILED')+'</td><td>'+n+'</td></tr>';if(r.status==='fulfilled')draw(k,featureCollection(r.value))});try{const j=await api('/station-intelligence?site_lat='+q.site_lat+'&site_lon='+q.site_lon+'&state='+encodeURIComponent(q.state));rows+='<tr><td>JPS station intelligence</td><td class="v283-ok">RESPONDED</td><td>LIVE CONTEXT</td></tr>';rows+='<tr><td>i-PLAN context</td><td class="v283-ok">RESPONDED</td><td>PLANNING CONTEXT</td></tr>';window.__URBION_PUBLIC_SPATIAL_RESULT_V283__={spatial:Object.fromEntries(rs.map((r,i)=>[jobs[i][0],r.status==='fulfilled'?r.value:null])),jps:j};}catch(e){rows+='<tr><td>JPS station intelligence</td><td class="v283-bad">FAILED</td><td>'+esc(e.message)+'</td></tr>'}if(o)o.innerHTML='<table class="v283-table"><thead><tr><th>Source</th><th>Status</th><th>Result</th></tr></thead><tbody>'+rows+'</tbody></table><div class="v283-note">Site-linked result bundle is retained in the browser session for downstream evidence UI. No statutory approval is inferred.</div>';if(live){live.textContent='COMPLETE';live.className='v283-status v283-ok'}state.busy=false}
function boot(){addClassification();addSpatial();setTimeout(()=>{ensureMap()},700)}
setTimeout(boot,500);setTimeout(boot,1500);new MutationObserver(boot).observe(document.body,{childList:true,subtree:true});
})();
