"""Canonical validation cases and compact evidence cards for URBION HORIZON.

These cases are deterministic demonstration fixtures. They provide a stable
bridge between the validation chapter of the report and the live prototype:
case definitions are fixed here, while all result values are generated by the
same assessment/coplaning engines used by the application.
"""
from __future__ import annotations

from typing import Any

from urbion_demo_scenarios import get_demo_scenario

VALIDATION_CASES = (
    {
        "id": "TC-01",
        "scenario_id": "TOD-COMPLY",
        "title": "GIS Spatial Proximity",
        "purpose": "Validate GIS feature proximity and TOD spatial classification.",
        "focus": "GIS & Spatial Validation",
    },
    {
        "id": "TC-02",
        "scenario_id": "SHOP-FAIL",
        "title": "Planning Rule & Compliance",
        "purpose": "Validate retrieval of planning controls and rule-based compliance review.",
        "focus": "Rule Retrieval & Compliance",
    },
    {
        "id": "TC-03",
        "scenario_id": "TOD-COMPLY",
        "title": "End-to-End Assessment",
        "purpose": "Demonstrate the integrated assessment, spatial, evidence, decision and scenario workflow.",
        "focus": "End-to-End Assessment",
        "variants": [
            {"id": "LOWER-DENSITY", "name": "Lower Density", "overrides": {"plot_ratio": 3.0}},
            {"id": "HIGHER-DENSITY", "name": "Higher Density", "overrides": {"plot_ratio": 6.0}},
        ],
    },
)


def validation_cases() -> list[dict[str, Any]]:
    """Return immutable-source copies suitable for API responses."""
    return [dict(item, variants=[dict(v, overrides=dict(v.get("overrides", {}))) for v in item.get("variants", [])]) for item in VALIDATION_CASES]


def get_validation_case(case_id: str) -> dict[str, Any] | None:
    return next((item for item in validation_cases() if item["id"] == case_id), None)


def _compact_assessment(result: dict[str, Any]) -> dict[str, Any]:
    site = result.get("site", {}) or {}
    evidence = result.get("evidence_state", {}) or {}
    return {
        "status": result.get("final_status"),
        "recommendation": result.get("recommendation"),
        "decision_confidence": result.get("decision_confidence"),
        "site": {"latitude": site.get("latitude"), "longitude": site.get("longitude"), "pbt": site.get("pbt"), "lot_no": site.get("lot_no")},
        "tod": {"distance_m": result.get("tod_distance_m"), "classification": result.get("classification")},
        "rules": {"retrieved_count": len(result.get("retrieved_rules", []) or []), "applicability_count": len(result.get("applicability_results", []) or []), "compliance_count": len(result.get("compliance_results", []) or [])},
        "evidence_state": evidence,
        "decision_trace": result.get("decision_trace", []),
    }


def _compact_copilot(packet: dict[str, Any]) -> dict[str, Any]:
    decision = packet.get("decision", {}) or {}
    knowledge = packet.get("knowledge", {}) or {}
    impact = packet.get("impact", {}) or {}
    scenario = packet.get("scenario_intelligence", {}) or {}
    return {
        "mode": packet.get("mode"),
        "assessment": _compact_assessment(packet.get("assessment", {}) or {}),
        "knowledge": {"retrieval_count": knowledge.get("retrieval_count"), "evidence_state": knowledge.get("evidence_state"), "review_gaps": knowledge.get("review_gaps", [])},
        "impact": {"status": impact.get("status"), "evidence_state": impact.get("evidence_state"), "signal_count": impact.get("signal_count"), "domains": impact.get("domains")},
        "scenario": {"status": scenario.get("status"), "count": scenario.get("count"), "ranked_scenarios": scenario.get("ranked_scenarios", []), "best_candidate": scenario.get("best_candidate")},
        "decision": {"status": decision.get("decision", {}).get("status"), "confidence": decision.get("decision", {}).get("confidence"), "next_actions": decision.get("next_actions", [])},
        "guardrails": {"decision_authority": packet.get("decision_authority"), "statutory_verification": packet.get("statutory_verification")},
    }


def run_validation_case(case_id: str, assess_fn, copilot_fn) -> dict[str, Any] | None:
    """Execute a canonical case through the production engines and return a report-ready card."""
    case = get_validation_case(case_id)
    if not case:
        return None
    scenario = get_demo_scenario(case["scenario_id"])
    if not scenario:
        raise ValueError(f"Missing demo scenario: {case['scenario_id']}")
    inputs = dict(scenario["inputs"])
    if case_id == "TC-03":
        result = copilot_fn(inputs, variants=case.get("variants"))
        evidence_card = _compact_copilot(result)
    else:
        result = assess_fn(inputs)
        evidence_card = _compact_assessment(result)
    return {"case": {"id": case["id"], "title": case["title"], "purpose": case["purpose"], "focus": case["focus"], "scenario_id": case["scenario_id"]}, "evidence_card": evidence_card, "result": result}
