(()=>{
'use strict';
if(window.__URBION_PREMIUM_V6__)return;
window.__URBION_PREMIUM_V6__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const root=()=>$('#urbion-championship-shell');
const lang=()=>localStorage.getItem('urbion-lang')==='bm'?'bm':'en';
const copy={en:{case:'PLANNING CASE',caseSub:'Define the site, governance, land use and proposal before analysis.',layers:'MAP LAYERS',layersSub:'Turn planning evidence on or off directly on the map.',about:'ABOUT URBION',sources:'DATA SOURCES',status:'SYSTEM STATUS',run:'RUN ANALYSIS',newCase:'NEW CASE',active:'ACTIVE',visible:'VISIBLE',source:'SOURCE',development:'Development / Proposal',selectDevelopment:'Select development / proposal',sourceBound:'SOURCE-BOUND',browser:'Browser map connection'},bm:{case:'KES PERANCANGAN',caseSub:'Takrif tapak, tadbir urus, guna tanah dan cadangan sebelum analisis.',layers:'LAPISAN PETA',layersSub:'Hidup atau matikan bukti perancangan terus pada peta.',about:'TENTANG URBION',sources:'SUMBER DATA',status:'STATUS SISTEM',run:'JALANKAN ANALISIS',newCase:'KES BAHARU',active:'AKTIF',visible:'DIPAPARKAN',source:'SUMBER',development:'Pembangunan / Cadangan',selectDevelopment:'Pilih pembangunan / cadangan',sourceBound:'TERIKAT SUMBER',browser:'Sambungan peta pelayar'}};
const t=()=>copy[lang()];
const developmentOptions=['New Development','Redevelopment','Extension / Addition','Change of Use','Subdivision','Land Consolidation','Mixed-Use Development','Temporary Use'];
function syncTheme(){const light=document.body.classList.contains('cs-light');document.body.classList.toggle('fcc-light',light);const b=$('#cs-theme');if(b){b.textContent=light?'DARK':'LIGHT';b.title=light?'Switch to dark mode':'Switch to light mode';b.setAttribute('aria-label',b.title)}}
function syncLanguageButton(){const b=$('#cs-lang');if(!b)return;b.textContent=lang()==='bm'?'EN':'BM';b.title=lang()==='bm'?'Switch to English':'Tukar ke Bahasa Melayu';b.setAttribute('aria-label',b.title)}
function populateDevelopment(){const e=$('#cs-development');if(!e)return;const old=e.value;e.innerHTML='<option value="">'+t().selectDevelopment+'</option>'+developmentOptions.map(v=>`<option value="${v}">${v}</option>`).join('');if(old)e.value=old;const label=$$('#urbion-championship-shell label').find(x=>(x.childNodes[0]?.textContent||'').trim().startsWith('Development / Proposal'));if(label&&label.childNodes[0])label.childNodes[0].textContent=t().development+' ';e.addEventListener('input',()=>window.__URBION_PREMIUM_V6_SYNC__?.(),{once:false});e.addEventListener('change',()=>window.__URBION_PREMIUM_V6_SYNC__?.(),{once:false})}
function moveCaseBuilder(){const r=root(),d=$('#cs-drawer'),i=$('.intelligence',r);if(!r||!d||!i)return;if(d.parentElement!==i){i.appendChild(d)}d.classList.add('persistent-case');$('#cs-close')?.setAttribute('aria-hidden','true');$('#cs-close')?.setAttribute('tabindex','-1');setTimeout(()=>window.__URBION_FCC_MAP__?.invalidateSize?.(),100)}
function decorateLayerRail(){const d=$('#cs-layer-drawer');if(!d||d.dataset.premiumV6)return;d.dataset.premiumV6='1';d.classList.add('persistent-layers');const labels=$$('label',d);labels.forEach((row,idx)=>{row.classList.add('fcc-layer-row');const input=$('input',row);const small=$('small',row);const txt=(small?.textContent||'').trim()||'MAP';row.dataset.group=txt;row.dataset.index=idx+1;input?.setAttribute('aria-label',(row.textContent||'').trim());row.addEventListener('mouseenter',()=>row.classList.add('hover'));row.addEventListener('mouseleave',()=>row.classList.remove('hover'))});const head=document.createElement('div');head.className='premium-layer-head';head.innerHTML=`<div><b>${t().layers}</b><small>${t().layersSub}</small></div><strong id="premium-layer-count">0</strong>`;d.prepend(head);const foot=document.createElement('div');foot.className='premium-layer-foot';foot.innerHTML='<span>●</span><small>i-Plan WMS · Source-labeled evidence</small>';d.appendChild(foot);updateLayerCount()}
function updateLayerCount(){const d=$('#cs-layer-drawer'),c=$('#premium-layer-count');if(!d||!c)return;c.textContent=$$('input[data-layer]:checked,input[type="checkbox"]:checked',d).length}
function addInfoStrip(){const r=root();if(!r||$('#premium-info-strip'))return;const tabs=$('.analysis',r)||$('#cs-analysis',r);if(!tabs)return;const strip=document.createElement('section');strip.id='premium-info-strip';strip.className='premium-info-strip';strip.innerHTML=`<article><span>${t().about}</span><b>URBION HORIZON</b><small>Planner decision-support workspace connecting spatial context, evidence and explainable decisions.</small></article><article><span>${t().sources}</span><b>i-Plan · JUPEM · JPS · MyEQMS · MyGEMS</b><small>Live availability varies by configured service and source response.</small></article><article><span>${t().status}</span><b><i class="status-dot"></i> RUNTIME ONLINE</b><small>${t().sourceBound} · ${t().browser}</small></article>`;tabs.insertAdjacentElement('afterend',strip)}
function styleLayerCategories(){const d=$('#cs-layer-drawer');if(!d)return;$$('.fcc-layer-row',d).forEach(row=>{const g=(row.dataset.group||'').toLowerCase();row.style.setProperty('--layer-accent',g.includes('risk')?'#ffb86b':g.includes('ecology')?'#6fe3b5':g.includes('heritage')?'#d19af8':g.includes('housing')?'#6dc9ff':g.includes('terrain')?'#b0c1cc':'#63deda')})}
function setupBaseMap(){const m=window.__URBION_FCC_MAP__;if(!m||!window.L||m.__premiumV6Base)return;m.__premiumV6Base=true;window.__URBION_PREMIUM_BASES__=window.__URBION_PREMIUM_BASES__||{};const B=window.__URBION_PREMIUM_BASES__;B.street=B.street||L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'});B.light=B.light||L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:20,attribution:'© OpenStreetMap © CARTO'});B.dark=B.dark||L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:20,attribution:'© OpenStreetMap © CARTO'});B.sat=B.sat||L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'© Esri'});B.terrain=B.terrain||L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'});const set=k=>{Object.values(B).forEach(x=>{if(m.hasLayer(x))m.removeLayer(x)});B[k].addTo(m);$$('[data-base]',r()).forEach(x=>x.classList.toggle('active',x.dataset.base===k));window.__URBION_FCC_BASE_TILE__=B[k];m.invalidateSize()};$$('[data-base]',r()).forEach(b=>{if(b.dataset.boundV6)return;b.dataset.boundV6='1';b.onclick=e=>set(e.currentTarget.dataset.base)});B.street.addTo(m);set('street')}
function mapLayerDirect(id,on){const m=window.__URBION_FCC_MAP__;if(!m||!window.L)return;window.__URBION_WMS__=window.__URBION_WMS__||{};const code=({Johor:'01',Kedah:'02',Kelantan:'03',Melaka:'04','Negeri Sembilan':'05',Pahang:'06','Pulau Pinang':'07',Perak:'08',Perlis:'09',Selangor:'10',Terengganu:'11',Sabah:'12',Sarawak:'13','Wilayah Persekutuan':'14',Labuan:'15',Putrajaya:'16'}[$('#cs-state')?.value]||'04');const names={'iplan-current':`iplan:gunatanah_semasa_${code}`,'iplan-zoning':`iplan:gunatanah_zoning_${code}`,'iplan-committed':`iplan:gunatanah_komited_${code}`,'iplan-rfn':'iplan:rfn','iplan-flood':'iplan:banjir','iplan-disaster-risk':'iplan:risiko_bencana','iplan-ksas':'iplan:ksas','iplan-cfs':'iplan:cfs','iplan-ecology':'iplan:rangkaian_ekologi','iplan-heritage':'iplan:warisan','iplan-affordable-housing':'iplan:rumah_mampu_milik','iplan-topography':'iplan:topo'};const old=window.__URBION_WMS__[id];if(old&&m.hasLayer(old))m.removeLayer(old);if(!on){delete window.__URBION_WMS__[id];updateLayerCount();return}const name=names[id];if(!name)return;const layer=L.tileLayer.wms('https://iplan.planmalaysia.gov.my/geoserver/iplan/wms',{layers:name,format:'image/png',transparent:true,version:'1.1.1',opacity:id==='iplan-current'?.72:.66,attribution:'PLANMalaysia · i-Plan'});layer.addTo(m);window.__URBION_WMS__[id]=layer;updateLayerCount()}
function bindLayers(){const d=$('#cs-layer-drawer');if(!d||d.dataset.v6change)return;d.dataset.v6change='1';d.addEventListener('change',e=>{const i=e.target;if(!(i instanceof HTMLInputElement)||!i.matches('[data-layer]'))return;mapLayerDirect(i.dataset.layer,i.checked);const row=i.closest('.fcc-layer-row');row?.classList.toggle('is-on',i.checked);updateLayerCount()})}
function normalizeLayerMarkup(){const d=$('#cs-layer-drawer');if(!d)return;$$('label',d).forEach(row=>{const i=$('input',row);if(!i||!i.dataset.layer)return;row.classList.add('fcc-layer-row');row.dataset.layerId=i.dataset.layer});styleLayerCategories()}
function enhanceTabs(){const r=root(),bar=$('.tabs',r);if(!bar)return;bar.classList.add('premium-tabs');$$('button',bar).forEach((b,i)=>{b.dataset.tabIndex=i+1;b.title=(b.textContent||'').trim();b.setAttribute('aria-label',b.title)})}
function polishControls(){const r=root();if(!r)return;$$('button',r).forEach(b=>{if(!b.title&&(b.textContent||'').trim())b.title=(b.textContent||'').trim()});$('#cs-theme')?.classList.add('premium-icon-control');$('#cs-lang')?.classList.add('premium-lang-control');$('#cs-run')?.classList.add('premium-run-control');$('#cs-next')?.classList.add('premium-run-control');$('#cs-reset')?.classList.add('premium-secondary-control');$('#cs-save')?.classList.add('premium-run-control');const status=$('#cs-status');if(status&&status.textContent==='Complete the planning case before analysis.')status.textContent=lang()==='bm'?'Lengkapkan kes perancangan sebelum analisis.':'Complete the planning case before analysis.'}
function keepCaseVisible(){const d=$('#cs-drawer');if(d&&!d.classList.contains('persistent-case'))d.classList.add('persistent-case')}
function sync(){window.__URBION_PREMIUM_V6_SYNC__=()=>{try{$('#cs-ready')&&($('#cs-ready').textContent=(function(){const ids=['project_name','lat','lon','state','pbt','district','landuse','category','activity','development','ratio'];const n=ids.filter(id=>String($('#cs-'+id)?.value||'').trim()).length;return Math.round(n/ids.length*100)+'%'})()}catch{}};window.__URBION_PREMIUM_V6_SYNC__()}
function refresh(){moveCaseBuilder();normalizeLayerMarkup();decorateLayerRail();bindLayers();enhanceTabs();polishControls();syncTheme();syncLanguageButton();populateDevelopment();addInfoStrip();setupBaseMap();keepCaseVisible();setTimeout(()=>{window.__URBION_FCC_MAP__?.invalidateSize?.();updateLayerCount()},150)}
function observe(){const r=root();if(!r||r.__v6obs)return;r.__v6obs=true;const mo=new MutationObserver(()=>{moveCaseBuilder();normalizeLayerMarkup();styleLayerCategories();keepCaseVisible();syncTheme()});mo.observe(r,{childList:true,subtree:true});}
function boot(){const r=root();if(!r)return setTimeout(boot,120);refresh();observe();setTimeout(refresh,500);setTimeout(refresh,1500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();