/* URBION HORIZON — canonical workspace function layer. Source: PLANMalaysia Manual GIS Rancangan Pemajuan Versi 3 (2025). */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const api=location.origin;
const GT={
'Perumahan':{
'Perumahan Strata':['Rumah Berbilang Tingkat','Penginapan Pekerja','Rumah Bandar (Townhouse)','Sesebuah','Berkembar','Teres','Kluster','Pondok Pengawal'],
'Perumahan Bukan Strata':['Sesebuah','Berkembar','Teres','Kluster','Kuarters Kerajaan: Rumah Bertanah','Kuarters Kerajaan: Rumah Berbilang Tingkat','Penginapan Pekerja','Perumahan Bukan Strata Lain'],
'Kampung':['Kampung Tersusun','Petempatan Tanah Rancangan FELDA/FELCRA/RISDA','Kampung Baru','Kampung Tradisional','Kampung Nelayan','Kampung Atas Air/Kampung Bagan','Kampung Orang Asli','Petempatan Estet/Perumahan Ladang','Perumahan Kampung Lain'],
'Setinggan':['Setinggan']},
'Komersial':{
'Teres':['Kedai','Rumah Kedai','Kedai Pejabat','Pejabat'],
'Berkembar':['Kedai','Rumah Kedai','Kedai Pejabat','Pejabat'],
'Bangunan Sesebuah':['Kedai','Rumah Kedai','Kedai Pejabat','Pejabat','Hypermarket','Pasaraya (Supermarket/Superstore/Departmental Store)','Kompleks Perniagaan','Hotel/Kemudahan Penginapan','Restoran','Arked/Bazar','Gerai Statik/Medan Selera','Pasar Borong','Pasar Basah/Pasar Kering','Stesen Minyak','Institusi Kewangan','Pusat Hiburan','Pusat Penjagaan Kesihatan','Pusat Pameran/Showroom','Pusat Konvensyen (MICE - meeting, incentive, convention, exhibition)','Pejabat Pos/Perkhidmatan Penghantaran/Kurier','Kawasan Rehat dan Rawat (R&R)/Hentian Sebelah','Unit Kosong/Tidak Beroperasi Komersial'],
'Pembangunan Penggunaan Bercampur Menegak':['Komersial - Perumahan','Komersial - Industri','Pembangunan Penggunaan Bercampur Lain'],
'Kegunaan Khusus Komersial':['Pendidikan swasta','Kesihatan swasta','Kemudahan swasta','Sukan dan Rekreasi swasta','Perkuburan swasta / Taman Peringatan','Pusat Jagaan swasta','Tempat Letak Kenderaan Swasta','Rumah Persatuan/Pertubuhan Swasta','Tapak bazar','Asrama','Penginapan Pekerja','Pangsapuri Perkhidmatan','Pusat Penyelidikan dan Pembangunan Swasta (R&D)','Pusat Data (Data Centre)','Nursery (tapak semaian dan penjualan anak pokok/bunga-bungaan)','Sekolah Memandu','Pejabat Kerajaan/Pentadbiran','Kilang Tanaman (Plant Factory)','Lain-lain Kegunaan Khusus Komersial']},
'Industri':{
'Bukan Taman Perindustrian':['Aeroangkasa','Alat Pengukuran Saintifik','Automotif/Jentera/Kelengkapan Kenderaan','Barangan Kitar Semula','Bengkel/Depo Kenderaan','Gudang (Warehouse)','Industri Tenaga Boleh Baharu','Kayu dan Perabot','Kelengkapan Farmaseutikal/Perubatan/Kosmetik/Optikal','Kertas/Percetakan dan Penerbitan','Kimia/Produk Kimia','Komputer, Elektrik dan Elektronik','Kulit/Produk Kulit','Logam/Fabrikasi Logam','Makanan dan Minuman','Perusahaan Kecil dan Sederhana (PKS)/Industri Desa','Produk Getah','Produk Mineral/Galian Bukan Logam','Produk Petroleum','Produk Plastik','Tekstil dan Pakaian','Tembakau/Produk Tembakau','Unit Kosong/Tidak Beroperasi','Industri Lain'],
'Taman Perindustrian':['Aeroangkasa','Alat Pengukuran Saintifik','Automotif/Jentera/Kelengkapan Kenderaan','Barangan Kitar Semula','Bengkel/Depo Kenderaan','Gudang (Warehouse)','Industri Tenaga Boleh Baharu','Kayu dan Perabot','Kelengkapan Farmaseutikal/Perubatan/Kosmetik/Optikal','Kertas/Percetakan dan Penerbitan','Kimia/Produk Kimia','Komputer, Elektrik dan Elektronik','Kulit/Produk Kulit','Logam/Fabrikasi Logam','Makanan dan Minuman','Perusahaan Kecil dan Sederhana (PKS)/Industri Desa','Produk Getah','Produk Mineral/Galian Bukan Logam','Produk Petroleum','Produk Plastik','Tekstil dan Pakaian','Tembakau/Produk Tembakau','Unit Kosong/Tidak Beroperasi','Industri Lain'],
'Perlombongan':['Perlombongan','Kuari'],
'Kegunaan Khusus Industri':['Pusat/Kemudahan Pelancar Satelit','Kilang Tanaman (Plant Factory)','Ladang Solar','Penginapan Pekerja','Pusat Data (Data Centre)','Pusat Pameran/Showroom','Pusat Penyelidikan dan Pembangunan (R&D)','Pusat Penyembelihan','Lain-lain Kegunaan Khusus Industri']},
'Institusi dan Kemudahan Masyarakat':{
'Pendidikan':['Asrama','Institut Pengajian Tinggi/Kolej/Politeknik/Maktab/Institut Perguruan','Kolej Vokasional/Pusat Latihan Teknikal dan Vokasional','Kompleks Sekolah Wawasan','Maahad Tahfiz','Maktab Rendah Sains Mara (MRSM)','Sekolah Berasrama Penuh','Sekolah Bersepadu/Model Khas','Sekolah Jenis Kebangsaan Cina (SJKC)','Sekolah Jenis Kebangsaan Tamil (SJKT)','Sekolah Menengah Agama','Sekolah Menengah Kebangsaan','Sekolah Pendidikan Khas','Sekolah Rendah Agama','Sekolah Rendah Kebangsaan','Tadika/Pra Sekolah','Tabika','Taska','Kemudahan Pendidikan Lain'],
'Kesihatan':['Hospital','Hospital Pakar','Klinik Kesihatan/Poliklinik','Klinik Desa','Klinik Ibu dan Anak','Klinik Komuniti','Klinik Gigi','Kemudahan Kesihatan Lain'],
'Keagamaan':['Masjid','Surau','Tokong','Kuil','Gereja','Gurdwara','Wat','Kemudahan Keagamaan Lain'],
'Perkuburan':['Perkuburan Islam','Perkuburan Buddha/Tao','Perkuburan Hindu','Perkuburan Kristian','Krematorium/Dewan Pengurusan Mayat','Kolumbarium','Perkuburan Lain'],
'Keselamatan':['Angkatan Pertahanan Awam Malaysia','Balai Bomba dan Penyelamat','Balai Polis','Balai Polis Komuniti/Pondok Polis','Cure & Care Vocational Centre (CCVC)','Depoh Tahanan Imigresen/Khas','Ibu Pejabat Jabatan Bomba dan Penyelamat','Ibu Pejabat Polis Daerah (IPD)','Ibu Pejabat Polis Kontijen (IPK)','Kem Tentera','Kem/Markas Pasukan Gerakan Am (PGA)','Padang Lapar Sasar','Pangkalan/Markas/Depoh Polis Marin','Penjara/Pusat Tahanan Sementara','Pusat Latihan Tentera/Polis/Bomba/Rela/APM/Kastam/KPDNKK/JPJ','Keselamatan Lain'],
'Rumah Kebajikan':['Rumah Anak Yatim','Pusat Pemulihan Akhlak','Pusat Transit Gelandangan','Rumah Orang Kelainan Upaya','Rumah Warga Emas','Rumah Kebajikan Lain'],
'Kegunaan Kerajaan/Badan Berkanun':['Badan Berkanun','Galeri/Memorial','Institut Latihan','Istana','Mahkamah','Muzium','Pejabat Kerajaan/Agensi Kerajaan','Pejabat Penghulu','Stesen Kaji Cuaca','Kegunaan Kerajaan/Badan Berkanun Lain'],
'Kemudahan Awam':['Balai Raya/Pusat Komuniti','Dewan Orang Ramai','Dewan Serbaguna Awam','Perpustakaan','Tandas Awam','Kemudahan Awam lain'],
'Rumah Persatuan/Pertubuhan':['Rumah Persatuan/Pertubuhan','Bomba Sukarela']},
'Tanah Lapang dan Rekreasi':{
'Tanah Lapang':['Taman Persekutuan/Taman Wilayah','Taman Bandaran','Taman Tempatan','Taman Kejiranan','Padang Permainan','Lot Permainan','Tanah Lapang Lain'],
'Kemudahan Sukan dan Rekreasi':['Stadium','Kompleks Sukan','Kompleks Renang','Kemudahan Sukan dan Rekreasi Lain'],
'Kawasan Hijau':['Zon Penampan','Kawasan Hijau']},
'Tanah Pembangunan':{'Tanah Untuk Pembangunan':['Tapak Projek dalam Pembinaan','Tapak Infill','Tapak Brownfield'],'Tanah Belum Dibangunkan':['Semak Samun/Belukar/Tanah Terbiar']},
'Pengangkutan':{'Pengangkutan Darat':['Depoh Bas','Depoh Keretapi/Rel','Depoh Lori/Jentera Berat','Landasan Keretapi/Rel','Pelabuhan Darat','Tempat Letak Kenderaan','Terminal Pengangkutan Bersepadu','Terminal/Stesen Bas','Terminal/Stesen Keretapi/Rel','Terminal/Stesen Teksi','Pengangkutan Darat Lain'],'Pengangkutan Air':['Jeti','Marina','Pelabuhan Laut','Stesen Pemindahan Kargo','Terminal Feri/Bot','Pengangkutan Air Lain'],'Pengangkutan Udara':['Lapangan Terbang','Terminal Kargo','Lapangan Terbang Kecil (Airstrip)','Pengangkutan Udara Lain'],'Jalan':['Lebuhraya','Jalan Persekutuan','Jalan Negeri','Jalan Bandaran','Jalan Lain']},
'Infrastruktur dan Utiliti':{
'Bekalan Elektrik':['Laluan Rentis 500 kv','Laluan 275 kv','Laluan Rentis 132 kv','Laluan Rentis 32 kv','Laluan Rentis 22 kv','Loji Janakuasa Elektrik','Loji Janakuasa Hidro','Pencawang Masuk Utama (PMU)','Pencawang Pembahagi Utama (PPU)','Pencawang Elektrik (PE)','Loji Janakuasa Arang Batu','Loji Janakuasa Kincir Angin','Loji Janakuasa Solar','Bekalan Elektrik Lain'],
'Bekalan Gas/Petroleum':['City Gates','Laluan Paip Gas (PGU I, PGU II, PGU III)','Stesen Pengagihan Gas','Bekalan Gas/Petroleum lain'],
'Bekalan Air':['Loji Rawatan Air','Paip Pengairan Air Antara Negara/Negeri/Daerah','Rumah Pam Bekalan Air','Takat Pengambilan Air','Tangki Air','Bekalan Air Lain'],
'Pengairan dan Perparitan':['Benteng Pemecah Ombak','Kolam Takungan','Rangkaian Sistem Perparitan/Monsun Drain','Saliran Pertanian','Stesen Pam','Tali Air dan Jalan','Pengairan dan Perparitan Lain'],
'Telekomunikasi':['Satelit Bumi','Bangunan Ibu Sawat','IT Hub','Menara Pemancar Telekomunikasi','Menara Radar/Antena','Rizab Telekomunikasi','Stesen Bukit','Stesen Radio','Stesen Radio Selular','Stesen VSAT','Telekomunikasi Lain'],
'Pengurusan Sisa Pepejal':['Pusat Rawatan Sisa Pepejal','Pusat Pemindahan Sisa Pepejal','Loji Rawatan Termal (Incinerator)','Tapak Pelupusan Sisa Pepejal Sanitari','Tapak Pusat Pengumpulan/Pemindahan','Pusat Kitar Semula','Tapak Pelupusan Sisa Pepejal Bukan Sanitari','Tapak Pelupusan Sisa Pepejal Bersepadu','Tapak Pelupusan Sisa Pepejal Yang Telah Ditutup','Pelupusan Sisa Pepejal Lain'],
'Pelupusan Sisa Berjadual':['Pusat Pengurusan Bahan Kimia/Berbahaya','Pusat Pengurusan Sisa Klinikal','Pusat Pengurusan Sisa Radioaktif','Buangan Terjadual Lain'],
'Pembetungan':['Kolam Oksidasi','Loji Rawatan Kumbahan','Stesen Pam Rangkaian','Pembetungan Lain'],'Empangan':['Struktur Empangan'],'Laluan Kemudahan Utiliti':['Rizab Utiliti Bersepadu']},
'Pertanian':{'Tanaman Makanan':['Buah-buahan','Padi','Sayur-sayuran','Tanaman Makanan Lain'],'Komoditi':['Getah','Kelapa','Kelapa Sawit','Koko','Komoditi Lain'],'Tanaman Lain':['Bunga-bungaan','Rempah Ratus/Herba','Teh','Tembakau','Tanaman Lain'],'Pertanian Campuran':['Campuran Tanaman Makanan-Penternakan','Campuran Tanaman Makanan-Penternakan-Perikanan','Tanaman Makanan Campuran','Pertanian Campuran Lain'],'Penternakan':['Ayam','Babi','Burung','Itik/Angsa','Kambing/Biri-biri','Lembu/Kerbau','Padang Ragut','Penternakan Campuran','Penternakan Lain'],'Perikanan/Akuakultur':['Ikan','Kolam Pancing','Penternakan Ikan Hiasan','Udang','Akuakultur Lain'],'Tanah Tidak Diusahakan':['Dibersihkan Untuk Pertanian','Semak Samun/Belukar/Tanah Terbiar Pertanian']},
'Hutan':{'Hutan Simpanan Kekal':['Hutan Darat','Hutan Paya Gambut','Hutan Paya Laut'],'Bukan Hutan Simpanan Kekal':['Cadangan HSK','Taman Negara/Taman Negeri/Rizab Hidupan Liar','Hutan Tanah Kerajaan','Kawasan Berhutan/Tanah Bermilik']},
'Badan Air':{'Badan Air Semula Jadi':['Sungai','Tasik','Paya/Tanah Bencah','Lagun','Laut','Badan Air Semula Jadi Lain'],'Badan Air Buatan':['Lombong/Bekas Lombong','Tasik','Tasik Empangan','Badan Air Buatan Lain'],'Kegunaan Khusus Badan Air':['Solar Terapung (Floating Solar)','Lain-lain Kegunaan Khusus Badan Air']},
'Pantai':{'Pantai Semula Jadi':['Pantai Berpasir','Pantai Berbatu','Pantai Berlumpur','Pantai Semula Jadi Lain'],'Pantai Buatan':['Kawasan Tambak','Pantai Buatan Lain']}
};
const state={layers:{},basemap:null,labels:null,rings:{}};
function opts(sel,arr,placeholder){sel.innerHTML=(placeholder?`<option value="">${placeholder}</option>`:'')+arr.map(v=>`<option value="${String(v).replaceAll('"','&quot;')}">${v}</option>`).join('')}
function setupLandUse(){const a=$('landuse1'),b=$('landuse2'),c=$('landuse3');if(!a||!b||!c)return;opts(a,Object.keys(GT));a.insertAdjacentHTML('beforebegin','<div id="gtnBadge" style="font-size:6px;color:var(--mint);margin:-3px 0 5px;letter-spacing:.06em">PLANMalaysia · Manual GIS Rancangan Pemajuan Versi 3 (2025) · 12 GT1 / 55 GT2 / 381 GT3</div>');const sync1=()=>{const x=GT[a.value]||{};opts(b,Object.keys(x),'Pilih Guna Tanah 2');opts(c,[],'Pilih Aktiviti Guna Tanah 3')};const sync2=()=>{const x=GT[a.value]?.[b.value]||[];opts(c,x,'Pilih Aktiviti Guna Tanah 3')};a.addEventListener('change',sync1);b.addEventListener('change',sync2);sync1();}
function getMap(){try{return map}catch(_){return null}}
function setBase(mode){const m=getMap();if(!m||!window.L)return;Object.values(state.baseLayers||{}).forEach(x=>m.removeLayer(x));if(state.labels)m.removeLayer(state.labels);if(mode==='sat'||mode==='hybrid'){state.basemap=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Esri'}).addTo(m);if(mode==='hybrid'){state.labels=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,opacity:.85,attribution:'Esri'}).addTo(m)}}else{state.basemap=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(m)}document.querySelectorAll('[data-base]').forEach(x=>x.classList.toggle('active',x.dataset.base===mode));$('mapStatus').textContent=(mode==='street'?'MAP':'')+(mode==='sat'?'SATELLITE':'')+(mode==='hybrid'?'HYBRID':'')+' · LIVE';m.invalidateSize(true)}
function moveSite(lat,lon){const m=getMap();if(!m)return;try{setSite(lat,lon)}catch(_){$('site_lat').value=lat.toFixed(6);$('site_lon').value=lon.toFixed(6);if(marker)marker.setLatLng([lat,lon]);if(r400)r400.setLatLng([lat,lon]);if(r800)r800.setLatLng([lat,lon]);if(state.rings.r1000)state.rings.r1000.setLatLng([lat,lon]);}if($('coords'))$('coords').textContent=`${lat.toFixed(6)}, ${lon.toFixed(6)}`}
function ensureRings(){const m=getMap();if(!m||!window.L)return;const lat=+$('site_lat').value||2.285,lon=+$('site_lon').value||102.196;if(!state.rings.r1000)state.rings.r1000=L.circle([lat,lon],{radius:1000,color:'#8b7cff',fillOpacity:.025,weight:1,dashArray:'5 6'}).addTo(m);else state.rings.r1000.setLatLng([lat,lon]);if(r400)r400.setRadius(400);if(r800)r800.setRadius(800);}
async function loadLayers(){const m=getMap();if(!m||!window.L)return;const list=$('layerList');if(!list)return;list.innerHTML='<div class="tiny">Loading official map catalogue…</div>';try{const r=await fetch(api+'/map/layers?state='+encodeURIComponent(($('state')?.value)||'Melaka'));if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();const layers=(d.layers||[]).filter(x=>x.id!=='osm');const groups={};layers.forEach(x=>(groups[x.group||'OTHER']??=[]).push(x));list.innerHTML=Object.entries(groups).map(([g,arr])=>`<div class="lg">${g}</div>`+arr.map(x=>`<div class="layerrow"><input type="checkbox" data-final-layer="${x.id}"><span>${x.name||x.id}<small>${x.source||x.type||''}</small></span><small data-layer-state="${x.id}">OFF</small></div>`).join('')).join('')||'<div class="tiny">No browser-renderable layers returned.</div>';layers.forEach(x=>{const cb=list.querySelector(`[data-final-layer="${x.id}"]`);if(!cb)return;cb.addEventListener('change',()=>toggleLayer(x,cb.checked));});}catch(e){list.innerHTML=`<div class="tiny" style="color:var(--bad)">Layer catalogue error · ${e.message}</div>`}}
function toggleLayer(x,on){const m=getMap();if(!m||!window.L)return;const s=document.querySelector(`[data-layer-state="${x.id}"]`);try{if(on){let layer;if(x.type==='GEOSERVER_WMS'){if(!x.layers)throw new Error('WMS layer name missing');layer=L.tileLayer.wms(x.url,{layers:x.layers,format:'image/png',transparent:true,version:'1.1.1',opacity:.72});}else if(x.type==='TILE'){layer=L.tileLayer(x.url,{maxZoom:19,opacity:.78,attribution:x.name||'Source'});}else if(x.type==='ARCGIS_MAP'){layer=L.tileLayer(x.url.replace(/\/$/,'')+'/tile/{z}/{y}/{x}',{maxZoom:19,opacity:.74,attribution:x.name||'ArcGIS'});}else{on=false;if(s)s.textContent='PORTAL';const u=x.url||'#';const a=document.createElement('a');a.href=u;a.target='_blank';a.rel='noopener';a.textContent='OPEN SOURCE';a.style='display:block;font-size:6px;color:var(--cyan);margin:3px 0';s?.parentElement?.appendChild(a);return}layer.addTo(m);state.layers[x.id]=layer;if(s)s.textContent='ON';toast(`${x.name||x.id} · map layer ON`);}else{if(state.layers[x.id]){m.removeLayer(state.layers[x.id]);delete state.layers[x.id]}if(s)s.textContent='OFF';}}catch(e){if(s)s.textContent='ERROR';toast(`Layer failed: ${x.name||x.id} · ${e.message}`,false)}}
function refreshMap(){const m=getMap();if(!m)return;ensureRings();setTimeout(()=>m.invalidateSize(true),60);setTimeout(()=>m.invalidateSize(true),300);}
function payload(){const g=(id)=>$(id)?.value||null;return{site_lat:+g('site_lat'),site_lon:+g('site_lon'),tod_lat:+g('tod_lat')||null,tod_lon:+g('tod_lon')||null,plot_ratio:+g('plot_ratio')||4.5,development_type:g('development_type'),development_class:g('development_class'),state:g('state'),district:g('district'),pbt:g('pbt'),lot_no:g('lot_no'),building_height:+g('building_height')||null,landuse1:g('landuse1'),landuse2:g('landuse2'),landuse3:g('landuse3'),units:+g('units')||null,gfa:+g('gfa')||null,precinct:g('precinct'),perimeter_planting:null,landscaped_pedestrian_walkway:null,shop_frontage_verified:false,shop_office_verified:false}}
function setReadiness(r){const rules=r.compliance_results||[];const gaps=r.review_gaps||[];const score=Math.max(0,Math.min(100,Math.round(r.decision_confidence?.score??r.readiness?.score??r.site_analysis?.suitability_score??0)));if($('readyPct'))$('readyPct').textContent=score+'%';if($('ring'))$('ring').style.background=`conic-gradient(var(--mint) 0 ${score}%,#183a47 ${score}% 100%)`;if($('readyLabel'))$('readyLabel').textContent=r.final_status||'REQUIRES REVIEW';['d1','d2','d3','d4'].forEach((id,i)=>{const el=$(id);if(el)el.className='dot '+(i<2?'on':i===2?(gaps.length?'warn':'on'):(r.environment_intelligence?'on':'warn'))});if($('mRules'))$('mRules').textContent=rules.length;if($('mSources'))$('mSources').textContent=(r.evidence_summary?.counts?Object.values(r.evidence_summary.counts).reduce((a,b)=>a+b,0):'—');}
function renderIntelligence(r){const status=r.final_status||r.assessment?.final_status||'REQUIRES REVIEW';const rules=r.compliance_results||r.assessment?.compliance_results||[];const li=r.lcp_intelligence||r.lcp||{};const gids=r.guideline_intelligence?.guidelines||li.guideline_intelligence?.guidelines||[];const gaps=r.review_gaps||li.review_gaps||[];const spatial=r.spatial_intelligence||r.spatial||{};const env=r.environment_intelligence||{};setReadiness(r);if($('findings'))$('findings').innerHTML=((spatial.metrics||[]).slice(0,4).map(x=>`<div class="finding"><b>${x.label||x.name||'Spatial signal'}</b><p>${x.value??x.message??'Source context available'}</p><small>${x.evidence||'SOURCE_CONTEXT'}</small></div>`).join('')||`<div class="finding"><b>${status}</b><p>Assessment returned. Review the disclosed evidence chain and gaps.</p><small>URBION</small></div>`);if($('rules'))$('rules').innerHTML=[...rules.slice(0,8).map(x=>{const st=x.status||'REQUIRES REVIEW';const cls=st.includes('NON')?'bad':st.includes('REVIEW')?'warn':'ok';return`<div class="rule"><b>${x.parameter||x.rule_id||'Planning control'} <span class="tag ${cls}">${st}</span></b><span>Proposed: ${x.proposed_value??x.value??'—'} · Requirement: ${x.requirement??'—'}<br>${x.reason||x.why||''}<br><i>${x.source||x.source_document||'RT / planning source'}</i></span></div>`}),gids.length?`<div class="rule"><b>Relevant GP / GPP</b><span>${gids.slice(0,4).map(g=>`${g.title||g.name||'Guideline'} · ${g.status||g.applicability||'CANDIDATE_REVIEW'} · ${g.source||'PLANMalaysia'}`).join('<br>')}</span></div>`:''].join('')||'<div class="rule"><b>RT / GP</b><span>No returned controls.</span></div>';if($('complianceDock'))$('complianceDock').innerHTML=`<div class="mini"><span>RT MBMB</span><span class="tag ${rules.length?'ok':'warn'}">${rules.length||0} RULES</span></div><div class="mini"><span>GP/GPP candidates</span><span class="tag ${gids.length?'ok':'warn'}">${gids.length}</span></div><div class="mini"><span>Evidence gaps</span><span class="tag ${gaps.length?'warn':'ok'}">${gaps.length}</span></div>`;if($('siteDock'))$('siteDock').innerHTML=`<div class="mini"><span>Case status</span><span class="tag ${status==='COMPLY'?'ok':'warn'}">${status}</span></div><div class="mini"><span>Spatial signals</span><span>${(spatial.metrics||[]).length}</span></div><div class="mini"><span>Environment</span><span>${env.summary?.domain_count??'—'} domains</span></div><div class="mini"><span>Next planner action</span><span>${gaps[0]||'Verify source applicability'}</span></div>`;}
async function analyse(){try{$('run').disabled=true;$('run').textContent='⟳ ANALYSING…';const res=await fetch(api+'/workstation/analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assessment:payload(),development_inputs:payload(),spatial_inputs:{site_lat:payload().site_lat,site_lon:payload().site_lon}})});const d=await res.json();if(!res.ok)throw new Error(d.detail||'Assessment failed');window.URBION_LAST=d;renderIntelligence(d);toast('Assessment complete');}catch(e){toast(e.message,false)}finally{$('run').disabled=false;$('run').textContent='▶ RUN SITE ANALYSIS'}}
async function whatif(){if(!window.URBION_LAST){toast('Run analysis first',false);return}openModal('WHAT-IF SCENARIO',`<div class="grid2"><div class="resultbox"><h4>BASELINE</h4><p>Plot ratio <b>${$('plot_ratio').value}</b><br>Height <b>${$('building_height').value||'—'}</b></p></div><div class="resultbox"><h4>SCENARIO</h4><input id="wfRatio" class="field" value="${$('plot_ratio').value}"><input id="wfHeight" class="field" value="${$('building_height').value||8}" style="margin-top:6px"><button id="wfRun" class="primary" style="margin-top:8px">COMPARE</button></div></div>`);$('wfRun').onclick=async()=>{const b=payload();const v={id:'SCENARIO-A',name:'Scenario A',overrides:{plot_ratio:+$('wfRatio').value||b.plot_ratio,building_height:+$('wfHeight').value||b.building_height}};const rr=await fetch(api+'/what-if',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseline:b,variants:[v]})});const d=await rr.json();openModal('WHAT-IF RESULT',`<div class="resultbox"><h4>BASELINE vs SCENARIO</h4><p>Baseline: ${d.baseline_status||d.baseline?.status||'—'}<br>Best candidate: ${d.best_candidate||'—'}</p><p>${(d.scenarios||d.ranked_scenarios||[]).map(s=>`${s.name||s.id}: ${s.status||s.final_status||'REVIEW'} · ${s.decision_delta??''}`).join('<br>')}</p><small>Scenario comparison is decision support only.</small></div>`)}}
async function decision(){const b=payload();try{const rr=await fetch(api+'/decision-center',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assessment:b})});const d=await rr.json();openModal('DECISION SUPPORT',`<div class="statusbig">${d.status||d.recommendation||'REVIEW REQUIRED'}</div><div class="grid2"><div class="resultbox"><h4>RATIONALE</h4><p>${d.rationale||d.reason||d.explanation||'Review returned evidence and controls.'}</p></div><div class="resultbox"><h4>PLANNER ACTION</h4><p>${(d.next_actions||d.actions||['Verify adopted plan and authority requirements']).join('<br>')}</p></div></div><small>Planning decision support only · no statutory approval claim.</small>`) }catch(e){toast(e.message,false)}}
function output(){if(!window.URBION_LAST){toast('Run analysis first',false);return}const r=window.URBION_LAST;const rules=r.compliance_results||[];const gids=r.guideline_intelligence?.guidelines||r.lcp_intelligence?.guideline_intelligence?.guidelines||[];const gaps=r.review_gaps||[];openModal('PLANNER-READY OUTPUT',`<div class="grid2"><div class="resultbox"><h4>CASE</h4><p>${$('project').value}<br>${$('state').value} · ${$('district').value}<br>${$('landuse1').value} → ${$('landuse2').value} → ${$('landuse3').value}</p></div><div class="resultbox"><h4>STATUS</h4><div class="statusbig">${r.final_status||'REQUIRES REVIEW'}</div></div><div class="resultbox"><h4>RT / GP</h4><p>${rules.slice(0,5).map(x=>`${x.parameter||x.rule_id}: ${x.status}`).join('<br>')||'—'}<br>GP/GPP: ${gids.length} candidate(s)</p></div><div class="resultbox"><h4>EVIDENCE GAPS</h4><p>${gaps.slice(0,7).join('<br>')||'No disclosed gaps'}</p></div></div><div class="buttons" style="margin-top:9px"><button id="outPrint" class="primary">PRINT / PDF</button></div>`);$('outPrint').onclick=()=>window.print()}
function openModal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').classList.add('show')}
function wire(){setupLandUse();document.querySelectorAll('[data-base]').forEach(b=>b.addEventListener('click',()=>setBase(b.dataset.base)));$('layerBtn')?.addEventListener('click',e=>{e.stopImmediatePropagation();$('layers').classList.toggle('open')},true);$('run')?.addEventListener('click',analyse);$('whatifBtn')?.addEventListener('click',whatif);$('decisionBtn')?.addEventListener('click',decision);$('outputBtn')?.addEventListener('click',output);$('generateOutput')?.addEventListener('click',output);$('printBtn')?.addEventListener('click',()=>window.print());$('closeModal')?.addEventListener('click',()=>$('modal').classList.remove('show'));document.querySelectorAll('.sec .sechead button').forEach(b=>b.addEventListener('click',()=>b.parentElement.parentElement.classList.toggle('collapsed')));$('useMap')?.addEventListener('click',()=>toast('Click the map to select a site'));$('locate')?.addEventListener('click',()=>{const m=getMap();if(m)moveSite(+$('site_lat').value,+$('site_lon').value)});document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.mode==='whatif')whatif();else if(b.dataset.mode==='decision')decision();else if(b.dataset.mode==='output')output()}));window.addEventListener('resize',refreshMap);setTimeout(()=>{refreshMap();loadLayers();document.querySelectorAll('[data-base]').length&&setBase('street')},250);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
window.URBION_FINAL={GT,loadLayers,analyse,whatif,decision,output,setBase,refreshMap};
})();
