(()=>{'use strict';
if(window.__URBION_UX_V3)return;window.__URBION_UX_V3=true;
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PBT={
'Johor':['Majlis Bandaraya Johor Bahru','Majlis Bandaraya Iskandar Puteri','Majlis Bandaraya Pasir Gudang','Majlis Perbandaran Batu Pahat','Majlis Perbandaran Kluang','Majlis Perbandaran Kulai','Majlis Perbandaran Muar','Majlis Perbandaran Segamat','Majlis Daerah Kota Tinggi','Majlis Daerah Mersing','Majlis Daerah Pontian','Majlis Daerah Tangkak'],
'Kedah':['Majlis Bandaraya Alor Setar','Majlis Perbandaran Sungai Petani','Majlis Perbandaran Kulim','Majlis Perbandaran Langkawi Bandaraya Pelancongan','Majlis Perbandaran Kubang Pasu','Majlis Daerah Baling','Majlis Daerah Yan','Majlis Daerah Pendang','Majlis Daerah Sik'],
'Kelantan':['Majlis Bandaraya Kota Bharu','Majlis Perbandaran Pengkalan Chepa','Majlis Daerah Bachok','Majlis Daerah Gua Musang','Majlis Daerah Jeli','Majlis Daerah Kuala Krai','Majlis Daerah Machang','Majlis Daerah Pasir Mas','Majlis Daerah Pasir Puteh','Majlis Daerah Tanah Merah','Majlis Daerah Tumpat'],
'Melaka':['Majlis Bandaraya Melaka Bersejarah','Majlis Perbandaran Alor Gajah','Majlis Perbandaran Jasin','Majlis Perbandaran Hang Tuah Jaya'],
'Negeri Sembilan':['Majlis Bandaraya Seremban','Majlis Perbandaran Port Dickson','Majlis Perbandaran Jempol','Majlis Daerah Jelebu','Majlis Daerah Kuala Pilah','Majlis Daerah Rembau','Majlis Daerah Tampin'],
'Pahang':['Majlis Bandaraya Kuantan','Majlis Perbandaran Bentong','Majlis Perbandaran Pekan','Majlis Perbandaran Temerloh','Majlis Daerah Bera','Majlis Daerah Cameron Highlands','Majlis Daerah Jerantut','Majlis Daerah Lipis','Majlis Daerah Maran','Majlis Daerah Raub','Majlis Daerah Rompin'],
'Perak':['Majlis Bandaraya Ipoh','Majlis Perbandaran Kuala Kangsar','Majlis Perbandaran Manjung','Majlis Perbandaran Taiping','Majlis Perbandaran Teluk Intan','Majlis Daerah Batang Padang','Majlis Daerah Gerik','Majlis Daerah Kerian','Majlis Daerah Lenggong','Majlis Daerah Perak Tengah','Majlis Daerah Selama','Majlis Daerah Tanjong Malim'],
'Perlis':['Majlis Perbandaran Kangar'],
'Pulau Pinang':['Majlis Bandaraya Pulau Pinang','Majlis Bandaraya Seberang Perai'],
'Sabah':['Dewan Bandaraya Kota Kinabalu','Majlis Perbandaran Sandakan','Majlis Perbandaran Tawau','Majlis Daerah Beaufort','Majlis Daerah Beluran','Majlis Daerah Keningau','Majlis Daerah Kota Belud','Majlis Daerah Kota Marudu','Majlis Daerah Kuala Penyu','Majlis Daerah Kunak','Majlis Daerah Lahad Datu','Majlis Daerah Papar','Majlis Daerah Penampang','Majlis Daerah Putatan','Majlis Daerah Ranau','Majlis Daerah Semporna','Majlis Daerah Sipitang','Majlis Daerah Tambunan','Majlis Daerah Tenom','Majlis Daerah Tuaran'],
'Sarawak':['Kuching South City Council','Kuching North City Commission','Miri City Council','Sibu Municipal Council','Bintulu Development Authority','Samarahan Municipal Council','Sri Aman District Council','Sarikei District Council','Kapit District Council','Limbang District Council','Mukah District Council','Betong District Council'],
'Selangor':['Majlis Bandaraya Shah Alam','Majlis Bandaraya Petaling Jaya','Majlis Bandaraya Subang Jaya','Majlis Bandaraya Diraja Klang','Majlis Perbandaran Ampang Jaya','Majlis Perbandaran Kajang','Majlis Perbandaran Kuala Langat','Majlis Perbandaran Kuala Selangor','Majlis Perbandaran Selayang','Majlis Perbandaran Sepang','Majlis Daerah Hulu Selangor','Majlis Daerah Sabak Bernam'],
'Terengganu':['Majlis Bandaraya Kuala Terengganu','Majlis Perbandaran Dungun','Majlis Perbandaran Kemaman','Majlis Daerah Besut','Majlis Daerah Hulu Terengganu','Majlis Daerah Marang','Majlis Daerah Setiu'],
'W.P. Kuala Lumpur':['Dewan Bandaraya Kuala Lumpur'],'W.P. Putrajaya':['Perbadanan Putrajaya'],'W.P. Labuan':['Perbadanan Labuan']};
const LAND={'Perumahan':['Rumah Sesebuah','Rumah Berkembar','Rumah Teres','Pangsapuri / Kondominium','Perumahan Berstrata','Perumahan Penjawat / Pekerja'],'Komersial':['Kedai / Rumah Kedai','Kedai Pejabat','Pusat Perniagaan','Kompleks Membeli-belah','Hotel / Penginapan','Pusat Makanan & Minuman','Perkhidmatan Profesional','Pasar / Pasar Raya'],'Industri':['Industri Ringan','Industri Sederhana','Industri Berat','Gudang / Logistik','Industri Berasaskan Makanan','Industri Kitar Semula'],'Institusi & Kemudahan Masyarakat':['Pendidikan','Kesihatan','Keagamaan','Keselamatan','Kerajaan / Pentadbiran','Kebajikan','Perkuburan','Kemudahan Awam'],'Tanah Lapang & Rekreasi':['Taman Awam','Padang Sukan','Rekreasi Komersial','Taman Tema','Laluan Rekreasi','Ruang Awam / Dataran'],'Pengangkutan & Lalulintas':['Jalan Raya','Terminal / Hab Pengangkutan','Stesen Transit','Tempat Letak Kereta','Depot / Logistik Pengangkutan'],'Infrastruktur & Utiliti':['Bekalan Air','Elektrik','Telekomunikasi','Loji Rawatan','Sistem Saliran','Kemudahan Sisa Pepejal'],'Pertanian':['Tanaman Makanan','Ladang','Hortikultur','Agro-Pelancongan','Ternakan','Akuakultur'],'Hutan':['Hutan Simpan','Hutan Perlindungan','Hutan Rekreasi','Koridor Ekologi'],'Badan Air':['Sungai','Tasik','Takungan','Kolam','Wetland'],'Pantai':['Pantai Awam','Pesisir Rekreasi','Pesisir Pelancongan','Zon Perlindungan Pantai']};
const DEV={'Perumahan':['Pembangunan Perumahan Baharu','Perumahan Semula','Perumahan Berstrata','Pembangunan Transit-Oriented'],'Komersial':['Pembangunan Komersial Baharu','Redevelopment Komersial','Mixed Commercial','Transit-Oriented Commercial'],'Industri':['Pembangunan Industri Baharu','Pengembangan Industri','Industrial Park','Logistics / Distribution Hub'],'Institusi & Kemudahan Masyarakat':['Pembangunan Kemudahan Baharu','Naik Taraf Kemudahan','Redevelopment Institusi'],'Tanah Lapang & Rekreasi':['Taman & Ruang Awam','Kemudahan Sukan','Rekreasi Komersial','Pelancongan Rekreasi'],'Pengangkutan & Lalulintas':['Transit-Oriented Development','Hab Pengangkutan','Jaringan Jalan','Park & Ride'],'Infrastruktur & Utiliti':['Kemudahan Utiliti Baharu','Naik Taraf Infrastruktur','Smart Utility'],'Pertanian':['Agro-Pelancongan','Pengukuhan Pertanian','Pertanian Bandar','Agro-Industrial'],'Hutan':['Pemuliharaan','Rekreasi Berimpak Rendah','Pemulihan Ekologi'],'Badan Air':['Pemulihan Sungai / Tasik','Rekreasi Air','Perlindungan Tadahan'],'Pantai':['Pelancongan Pesisir','Pemulihan Pantai','Rekreasi Pesisir','Perlindungan Pantai']};
const states=Object.keys(PBT);
function options(el,items,selected){if(!el)return;el.innerHTML=items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(selected&&items.includes(selected))el.value=selected}
function addField(id,label,after){let el=$(id);if(el)return el;const w=document.createElement('div');w.className='ux-field';w.innerHTML=`<div class="label">${label}</div><select id="${id}" class="select"></select>`;after.insertAdjacentElement('afterend',w);return w.querySelector('select')}
function setupPlanningControls(){const state=$('state'),pbt=$('pbt'),dev=$('devtype'),side=state?.closest('.sidebar');if(!state||!pbt||!side)return;const selected=state.value&&PBT[state.value]?state.value:'Melaka';options(state,states,selected);function pbtFor(s){options(pbt,PBT[s]||[],s==='Melaka'?'Majlis Bandaraya Melaka Bersejarah':undefined)}const land=addField('landuse','Land use category',dev?.closest('.label')?.previousElementSibling||dev);const activity=addField('activity','Land use activity',land.closest('.ux-field'));const proposal=addField('development','Development / proposal type',activity.closest('.ux-field'));options(land,Object.keys(LAND),'Perumahan');function syncLand(){const l=land.value;options(activity,LAND[l]||[],(LAND[l]||[])[0]);options(proposal,DEV[l]||[],(DEV[l]||[])[0]);const mapped=(l==='Pengangkutan & Lalulintas'?'TOD Development / Mixed Use':l==='Komersial'?'Commercial Development':l==='Perumahan'?'Residential Development':l==='Institusi & Kemudahan Masyarakat'?'Institutional Development':l==='Tanah Lapang & Rekreasi'?'Recreation / Tourism':'Mixed Use');if(dev&&[...dev.options].some(o=>o.value===mapped))dev.value=mapped}state.onchange=()=>{pbtFor(state.value);window.dispatchEvent(new CustomEvent('urbion:state-change',{detail:{state:state.value}}));window.dispatchEvent(new CustomEvent('urbion:reload-map-layers'))};land.onchange=syncLand;pbtFor(selected);syncLand();const copy=side.querySelector('.side-copy');if(copy)copy.innerHTML='Start with the case. Then move left-to-right: <b>Map & Evidence</b> → <b>Scenarios</b> → <b>Decision</b>.'}
function cleanFloating(){['urbion-workstation-v2','urbion-decision-os'].forEach(id=>$(id)?.remove())}
function setupNav(){const n=$('nav');if(!n)return;const names={command:'01 · START / CASE',evidence:'02 · MAP / EVIDENCE',scenarios:'03 · WHAT-IF',decision:'04 · DECISION / LCP',judge:'05 · JUDGE VIEW'};n.querySelectorAll('button[data-view]').forEach(b=>{b.textContent=names[b.dataset.view]||b.textContent});let g=$('ux-guide');if(!g){g=document.createElement('div');g.id='ux-guide';g.innerHTML='<span class="ux-step active">01</span><b>Define case</b><i>→</i><span class="ux-step">02</span><b>Inspect evidence</b><i>→</i><span class="ux-step">03</span><b>Test options</b><i>→</i><span class="ux-step">04</span><b>Decide & explain</b>';n.insertAdjacentElement('afterend',g)}}
function mapInstance(){const n=$('ss-map');return n?.__urbionMap||(window.__URBION_MAPS||[]).find(x=>x?.getContainer?.()===n)}
async function bindOpacity(){const map=mapInstance();if(!map)return;let catalog=window.__URBION_LAYER_CATALOG;if(!catalog){try{const r=await fetch('/map/layers?state='+encodeURIComponent($('state')?.value||'Melaka'),{cache:'no-store'});catalog=(await r.json()).layers||[];window.__URBION_LAYER_CATALOG=catalog}catch{return}}document.querySelectorAll('#uo-layer-dock input[type="range"]').forEach(sl=>{if(sl.dataset.uxBound)return;const cb=sl.closest('.uo-layer-row')?.querySelector('input[data-evidence]');const id=cb?.dataset?.evidence;if(!id)return;sl.dataset.uxBound='1';sl.addEventListener('input',()=>{const v=parseFloat(sl.value);map.eachLayer(l=>{if(l._urbionEvidenceId===id)l.setOpacity?.(v);if(l._urbionLayerId===id)l.setOpacity?.(v)})})});document.querySelectorAll('#ss-layers input.ss-opacity').forEach(sl=>{if(sl.dataset.uxBound)return;const row=sl.closest('.ss-layer'),idx=Number(row?.querySelector('input[type="checkbox"]')?.dataset?.i),id=catalog.filter(x=>['GEOSERVER_WMS','TILE','ARCGIS_MAP'].includes(x.type))[idx]?.id;if(!id)return;sl.dataset.uxBound='1';sl.addEventListener('input',()=>map.eachLayer(l=>{if(l._urbionLayerId===id)l.setOpacity?.(parseFloat(sl.value))}))})}
function hideLegacyControls(){const p=$('ss-layers')?.closest('.ss-section');if(p)p.style.display='none'}
function css(){if($('ux-v3-style'))return;const s=document.createElement('style');s.id='ux-v3-style';s.textContent=`#ux-guide{display:flex;align-items:center;gap:8px;padding:9px 12px;margin:-4px 0 14px;border:1px solid var(--line);border-radius:10px;background:#081722;color:#8da5b6;font-size:8px}#ux-guide b{font-size:8px;color:#b9cbd4}.ux-step{display:grid;place-items:center;width:20px;height:20px;border:1px solid #2a4658;border-radius:50%;font-size:7px;font-weight:900}.ux-step.active{background:var(--a);border-color:var(--a);color:#061018}#ux-guide i{font-style:normal;color:#3e5a69}.sidebar{padding:20px 18px}.sidebar .side-title{font-size:17px}.sidebar .label{margin-top:14px}.sidebar .input,.sidebar .select{height:40px;font-size:11px;border-radius:9px}.sidebar .run{height:42px;font-size:9px}.sidebar .reset{height:36px}.nav{gap:6px}.nav button{padding:9px 12px;border-radius:999px;font-size:8px}.nav button[data-view="judge"]{margin-left:auto}.ss-map{height:580px!important}.ss-panel{max-height:580px!important}#urbion-workstation-v2,#urbion-decision-os{display:none!important}.ux-field{margin:0}@media(max-width:900px){#ux-guide{overflow:auto;white-space:nowrap}.ss-map{height:500px!important}.ss-panel{max-height:none!important}.nav button[data-view="judge"]{margin-left:0}}`;document.head.appendChild(s)}
function observe(){const mo=new MutationObserver(()=>{cleanFloating();setupPlanningControls();setupNav();bindOpacity()});mo.observe(document.body,{childList:true,subtree:true});setInterval(()=>{cleanFloating();bindOpacity()},1000)}
function boot(){css();cleanFloating();setupPlanningControls();setupNav();bindOpacity();observe()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();