/* URBION HORIZON — canonical live mobility/station presentation owner. */
(()=>{
'use strict';
if(window.__URBION_STATION_MAP_OWNER_V10__)return;
window.__URBION_STATION_MAP_OWNER_V10__=true;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function mapObj(){try{return(typeof map!=='undefined'&&map)||window.__URBION_MAP__||window.__URBION_FCC_MAP__||null}catch(_){return null}}
function packet(){return window.URBION_LAST?.canonical_evidence_packet||window.URBION_LAST?.copilot?.canonical_evidence_packet||window.URBION_LAST?.deterministic_packet?.canonical_evidence_packet||null}
function cachedStations(){const p=packet();return p?.evidence?.stations||window.URBION_LAST?.live_station_evidence||null}
function toast(message,ok=true){const t=$('toast');if(!t)return;t.textContent=message;t.style.display='block';t.style.color=ok?'var(--good)':'var(--bad)';clearTimeout(window.__urbionStationToast);window.__urbionStationToast=setTimeout(()=>t.style.display='none',2200)}
function style(){if($('urbionStationMapStyle'))return;const s=document.createElement('style');s.id='urbionStationMapStyle';s.textContent='.urbion-station-btn{width:100%;margin-top:6px;padding:7px 9px;border:1px solid rgba(47,225,233,.22);background:rgba(47,225,233,.05);border-radius:8px;text-align:left;font-size:6.5px}.urbion-station-btn.on{border-color:rgba(72,223,170,.5);color:var(--good)}.urbion-live-row{display:flex;align-items:flex-start;gap:7px;padding:7px 2px;border-bottom:1px solid rgba(45,85,100,.18);font-size:7px}.urbion-live-row input{accent-color:var(--cyan);margin-top:2px}.urbion-live-row span{flex:1}.urbion-live-row small{font-size:5.5px;color:var(--muted);text-align:right}.urbion-live-note{font-size:5.8px;color:var(--muted);line-height:1.4;margin-top:5px}.urbion-present-btn{margin-top:7px;width:100%;padding:8px 9px;border:1px solid rgba(47,225,233,.35);background:linear-gradient(90deg,rgba(88,232,196,.08),rgba(47,225,233,.08));border-radius:8px;font-size:7px;font-weight:800;letter-spacing:.06em}.urbion-present-mode .left,.urbion-present-mode .right{display:none!important}.urbion-present-mode .layout{grid-template-columns:minmax(0,1fr)}.urbion-present-mode .center{padding:14px}.urbion-present-mode .mapwrap{border-radius:16px}.urbion-present-mode .bottom{height:170px}.urbion-km-card{border:1px solid var(--line);border-radius:10px;background:linear-gradient(145deg,rgba(7,29,41,.96),rgba(3,15,22,.98));padding:10px;margin-bottom:8px}.light .urbion-km-card{background:#fff}.ukm-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.ukm-title{font-size:8px;font-weight:900;letter-spacing:.07em}.ukm-sub{font-size:5.8px;color:var(--muted)}.ukm-status{margin-top:8px;font:800 11px Space Grotesk}.ukm-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:7px}.ukm-chip{border:1px solid var(--line);border-radius:8px;padding:7px}.ukm-chip b{display:block;font-size:7px}.ukm-chip span{display:block;font-size:5.8px;color:var(--muted);margin-top:2px;line-height:1.35}.ukm-list{margin-top:7px}.ukm-row{padding:5px 0;border-bottom:1px solid rgba(45,85,100,.15);font-size:5.8px;color:var(--muted)}.ukm-pill{display:inline-block;padding:3px 5px;border:1px solid var(--line);border-radius:999px;font-size:5.4px;margin:2px 3px 0 0}.ukm-good{color:var(--good);border-color:rgba(72,223,170,.3)}.ukm-warn{color:var(--warn);border-color:rgba(255,203,93,.3)}.ukm-note{margin-top:7px;padding:7px 8px;border-left:2px solid var(--cyan);background:rgba(47,225,233,.035);font-size:5.8px;line-height:1.45;color:#b9ccd3}.light .ukm-note{color:#5d727d}';document.head.appendChild(s)}
function popup(item,domain){let metric='No live reading';if(domain==='JPS RAINFALL'){const v=item.rainfall_1h_mm??item.daily_rainfall_mm;if(v!=null)metric=`${esc(v)} mm`; }else if(domain==='MYEQMS WATER'){const parts=[];if(item.ph!=null)parts.push(`pH ${esc(item.ph)}`);if(item.turbidity_ntu!=null)parts.push(`Turbidity ${esc(item.turbidity_ntu)} NTU`);if(item.conductivity_us_cm!=null)parts.push(`Conductivity ${esc(item.conductivity_us_cm)} µS/cm`);if(parts.length)metric=parts.join(' · ');}else{const v=item.aqi??item.api??item.reading;if(v!=null)metric=`${esc(v)} ${esc(item.unit||'')}`;}return `<b>${esc(item.name||item.station_id||'Station')}</b><br>${esc(domain)} · ${metric}<br>${item.distance_m!=null?esc(Math.round(item.distance_m)+' m from site'):''}<br><small>SOURCE_CONTEXT · ${esc(item.last_updated||item.last_updated_rainfall||item.observed_at||'time not supplied')}</small>`}
let layerGroups={};
async function loadStations(){const cached=cachedStations();if(cached)return cached;const lat=Number($('site_lat')?.value),lon=Number($('site_lon')?.value),state=String($('state')?.value||'Melaka');if(!Number.isFinite(lat)||!Number.isFinite(lon))throw Error('Site coordinates unavailable');const r=await fetch(`/mobility/stations?site_lat=${encodeURIComponent(lat)}&site_lon=${encodeURIComponent(lon)}&state=${encodeURIComponent(state)}&limit=10`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.detail||`HTTP ${r.status}`);return d}
function itemsFor(data,domain){return domain==='JPS RAINFALL'?(data?.jps_rainfall?.stations||[]):domain==='MYEQMS WATER'?(data?.eqmp_water?.stations||[]):(data?.air_quality?.stations||[])}
function toggleMarkers(data,domain,on){const m=mapObj();if(!m||typeof L==='undefined')throw Error('Map engine unavailable');if(layerGroups[domain]){try{m.removeLayer(layerGroups[domain])}catch(_){}delete layerGroups[domain]}if(!on)return;const group=L.layerGroup();itemsFor(data,domain).forEach(item=>{const lat=Number(item.latitude??item.lat),lon=Number(item.longitude??item.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;const marker=L.circleMarker([lat,lon],{radius:6,weight:2,fillOpacity:.82});marker.bindPopup(popup(item,domain));marker.addTo(group)});group.addTo(m);layerGroups[domain]=group}
function total(data){return ['JPS RAINFALL','MYEQMS WATER','AIR QUALITY'].reduce((n,d)=>n+itemsFor(data,d).length,0)}
function addDrawerRows(){const host=$('layers');if(!host||$('urbionLiveLayerGroup'))return;const section=document.createElement('div');section.id='urbionLiveLayerGroup';section.innerHTML='<div class="lg">LIVE OBSERVATION</div><label class="urbion-live-row"><input type="checkbox" data-live-layer="JPS RAINFALL"><span>JPS Rainfall Stations</span><small>JPS</small></label><label class="urbion-live-row"><input type="checkbox" data-live-layer="MYEQMS WATER"><span>MyEQMS / EQMP Water Stations</span><small>JAS</small></label><label class="urbion-live-row"><input type="checkbox" data-live-layer="AIR QUALITY"><span>Air Quality Stations</span><small>APIMS</small></label><div class="urbion-live-note">Observation context only. APIMS values/markers appear only when an authorised/public JSON endpoint is configured; no air-quality index is fabricated.</div>';host.appendChild(section);section.querySelectorAll('[data-live-layer]').forEach(cb=>cb.addEventListener('change',async()=>{cb.disabled=true;try{const data=await loadStations();toggleMarkers(data,cb.dataset.liveLayer,cb.checked);const n=itemsFor(data,cb.dataset.liveLayer).length;cb.closest('label').querySelector('small').textContent=cb.checked?`${n} LIVE`:(cb.dataset.liveLayer==='MYEQMS WATER'?'JAS':cb.dataset.liveLayer==='JPS RAINFALL'?'JPS':'APIMS')}catch(e){cb.checked=false;toast('Station layer unavailable',false)}finally{cb.disabled=false}}))}
function mountStationCard(){const root=document.querySelector('.right');if(!root||$('urbionStationMapCard'))return;const card=document.createElement('section');card.id='urbionStationMapCard';card.className='card';card.innerHTML='<div class="cardhead"><h3>MAP · LIVE STATIONS</h3><span class="tiny">OBSERVATION</span></div><div class="tiny">JPS rainfall · MyEQMS water · DOE air-quality stations when source data is available.</div><button type="button" class="urbion-station-btn" id="urbionStationToggle">SHOW ALL STATIONS ON MAP</button><div class="tiny" id="urbionStationStatus" style="margin-top:5px">OFF · no station markers</div>';root.appendChild(card);$('urbionStationToggle').addEventListener('click',async()=>{const b=$('urbionStationToggle'),st=$('urbionStationStatus'),on=b.dataset.on==='1';if(on){Object.keys(layerGroups).forEach(k=>toggleMarkers(null,k,false));b.dataset.on='0';b.textContent='SHOW ALL STATIONS ON MAP';b.classList.remove('on');st.textContent='OFF · no station markers';document.querySelectorAll('[data-live-layer]').forEach(x=>x.checked=false);return}b.disabled=true;st.textContent='LOADING · canonical/live station coordinates';try{const d=await loadStations();['JPS RAINFALL','MYEQMS WATER','AIR QUALITY'].forEach(k=>toggleMarkers(d,k,true));b.dataset.on='1';b.textContent='HIDE ALL STATIONS FROM MAP';b.classList.add('on');st.textContent=`ON · ${total(d)} source-backed station markers`;document.querySelectorAll('[data-live-layer]').forEach(x=>x.checked=true)}catch(e){st.textContent='UNAVAILABLE · '+e.message}finally{b.disabled=false}})}
function renderJudge(){const right=document.querySelector('.right');if(!right)return;let card=$('urbionJudgeCard');if(!card){card=document.createElement('section');card.id='urbionJudgeCard';card.className='card';right.prepend(card)}const p=packet(),gaps=Array.isArray(p?.review_gaps)?p.review_gaps.length:0;const states=Object.values(p?.evidence_states||{});const source=states.filter(x=>String(x).toUpperCase()==='SOURCE_CONTEXT').length;const verified=states.filter(x=>String(x).toUpperCase()==='VERIFIED').length;const statusText=p?(gaps===0?'READY FOR PLANNER REVIEW':'REVIEW REQUIRED'): 'PRE-RUN';card.innerHTML=`<div class="cardhead"><h3>JUDGE SNAPSHOT</h3><span class="tiny">CANONICAL V5 · READ-ONLY</span></div><div class="tiny">${p?'PACKET READY':'PRE-RUN'} · ${gaps} review gap${gaps===1?'':'s'}</div><div class="tiny" style="margin-top:5px"><b>${esc(statusText)}</b> · BASELINE ${p?'ACTIVE':'WAITING'} · WHAT-IF ${p?'AVAILABLE':'AFTER ANALYSIS'} · SOURCE CONTEXT ${source} · VERIFIED ${verified}</div>`;presentationButton(card);window.__URBION_JUDGE_OWNER_V1__=true;window.__URBION_JUDGE_OWNER_V2__=true}
function presentationButton(card){if($('urbionPresentBtn'))return;const b=document.createElement('button');b.type='button';b.id='urbionPresentBtn';b.className='urbion-present-btn';b.textContent='ENTER PRESENTATION MODE';b.onclick=()=>{const active=document.body.classList.toggle('urbion-present-mode');b.textContent=active?'EXIT PRESENTATION MODE':'ENTER PRESENTATION MODE';setTimeout(()=>{try{mapObj()?.invalidateSize(true)}catch(_){ }},120)};card.appendChild(b);if(!window.__URBION_PRESENT_KEY__){window.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('urbion-present-mode')){document.body.classList.remove('urbion-present-mode');b.textContent='ENTER PRESENTATION MODE';try{mapObj()?.invalidateSize(true)}catch(_){}}});window.__URBION_PRESENT_KEY__=true}}
function renderKmOsc(){const right=document.querySelector('.right');if(!right)return;let card=$('urbionKmOscCard');if(!card){card=document.createElement('section');card.id='urbionKmOscCard';card.className='urbion-km-card';right.appendChild(card)}const r=window.URBION_LAST?.km_readiness||window.URBION_LAST?.handoff?.km_readiness||window.URBION_LAST?.planner_handoff?.km_readiness;if(!r){card.innerHTML='<div class="ukm-head"><span class="ukm-title">KM / OSC READINESS</span><span class="ukm-sub">WAITING FOR ANALYSIS</span></div><div class="ukm-note">Complete canonical analysis to surface workflow readiness.</div>';window.__URBION_KM_OSC_OWNER_V1__=true;window.__URBION_KM_OSC_OWNER_V2__=true;return}
const checklist=Array.isArray(r.checklist)?r.checklist:(Array.isArray(r.items)?r.items:[]);
const derivedDocs=Array.isArray(r.missing_documents)?r.missing_documents:(Array.isArray(r.core_document_check?.missing)?r.core_document_check.missing:[]);
const blockers=Array.isArray(r.blockers)?r.blockers:[];
const derivedRows=checklist.length?checklist:[
  ...(r.core_document_check? [{label:'Core submission evidence',status:String(r.core_document_check.state||'INCOMPLETE')}]:[]),
  ...(r.technical_review? [{label:'Technical review',status:Object.values(r.technical_review).filter(Boolean).join(' · ')||'REVIEW'}]:[])
];
const category=String(r.km_category||r.readiness_label||'').trim();
const review=String(r.readiness||'').toUpperCase()==='REQUIRES_REVIEW'||String(r.status||'').toUpperCase()==='REVIEW'||String(r.readiness_label||'').toUpperCase()==='REVIEW REQUIRED';
const readinessLabel=review?`REVIEW REQUIRED${category?` · ${category}`:''}`:(r.readiness_label||category||r.readiness||r.status||'REVIEW REQUIRED');
const status=String(r.status||'').trim()||((review)?'REVIEW':'READY');
const readyCount=checklist.filter(x=>String(x.status).toUpperCase()==='READY').length;
const boundary=r.decision_boundary||'KM/OSC readiness support only; URBION does not grant or predict statutory approval.';
card.innerHTML=`<div class="ukm-head"><span class="ukm-title">KM / OSC READINESS</span><span class="ukm-sub">${esc(status)}</span></div><div class="ukm-status">${esc(readinessLabel)}</div><div class="ukm-grid"><div class="ukm-chip"><b>${readyCount}</b><span>READY CHECKS</span></div><div class="ukm-chip"><b>${derivedDocs.length}</b><span>MISSING DOCUMENTS</span></div></div><div class="ukm-list">${derivedRows.slice(0,6).map(x=>`<div class="ukm-row">${esc(x.label||x.item||x.name||'Requirement')} · <span class="ukm-pill ${String(x.status).toUpperCase().includes('READY')?'ukm-good':'ukm-warn'}">${esc(x.status||'REVIEW')}</span></div>`).join('')||'<div class="ukm-row">Readiness checklist will populate after analysis.</div>'}</div>${blockers.length?`<div class="ukm-note"><b>BLOCKERS:</b> ${esc(blockers.slice(0,5).join(' · '))}</div>`:''}${derivedDocs.length?`<div class="ukm-note"><b>DOCUMENTS:</b> ${esc(derivedDocs.slice(0,5).join(' · '))}</div>`:''}<div class="ukm-note"><b>BOUNDARY:</b> NOT APPROVAL · STATUTORY APPROVAL IS NOT DETERMINED BY URBION. ${esc(boundary)}</div>${r.workflow_basis?`<div class="ukm-note"><b>WORKFLOW:</b> ${esc(r.workflow_basis)}</div>`:''}`;
window.__URBION_KM_OSC_OWNER_V1__=true;window.__URBION_KM_OSC_OWNER_V2__=true}
function structuralLocation(){for(const [id,label] of [['district','Select District'],['pbt','Select PBT'],['mukim','Select Mukim']]){const el=$(id);if(!el||el.tagName==='SELECT')continue;const s=document.createElement('select');for(const attr of ['id','name','class','required','disabled','autocomplete','aria-label'])if(el.hasAttribute(attr))s.setAttribute(attr,el.getAttribute(attr));s.className=el.className||'select';const value=String(el.value||'').trim();s.innerHTML=`<option value="">${esc(label)}</option>`+(value?`<option value="${esc(value)}">${esc(value)}</option>`:'');if(value)s.value=value;el.replaceWith(s)}}
function refreshFromState(){try{renderKmOsc()}catch(e){window.__URBION_KM_OSC_RENDER_ERROR__=String(e?.message||e)}}
function boot(){style();structuralLocation();window.__URBION_JUDGE_OWNER_V1__=true;window.__URBION_JUDGE_OWNER_V2__=true;window.__URBION_KM_OSC_OWNER_V1__=true;window.__URBION_KM_OSC_OWNER_V2__=true;window.addEventListener('urbion:assessment-ready',refreshFromState);window.addEventListener('urbion:analysis-complete',refreshFromState);let n=0;const t=setInterval(()=>{mountStationCard();renderJudge();renderKmOsc();addDrawerRows();if(++n>=220)clearInterval(t)},100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();