/* URBION HORIZON — explainable decision intelligence + bounded planner copilot + validation lab. */
(function(){
  'use strict';
  function esc(v){return String(v==null?'—':v).replace(/[&<>\"]/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'})[c]||c;});}
  function input(id,fallback){var e=document.getElementById(id);return e&&e.value!==''?e.value:fallback;}
  function validationButton(){
    if(document.getElementById('urbion-validation-open'))return;
    var b=document.createElement('button');b.id='urbion-validation-open';b.textContent='VALIDATION LAB';
    b.style.cssText='position:fixed;right:18px;bottom:18px;z-index:1301;border:1px solid #35e2b0;background:#0b2029;color:#dffbf4;border-radius:999px;padding:10px 14px;font:900 10px Inter;letter-spacing:.04em;cursor:pointer;box-shadow:0 12px 35px #0008';
    b.onclick=showValidationLab;document.body.appendChild(b);
  }
  async function showValidationLab(){
    var panel=document.getElementById('urbion-validation-lab');
    if(!panel){
      panel=document.createElement('section');panel.id='urbion-validation-lab';
      panel.style.cssText='position:fixed;right:18px;bottom:62px;z-index:1302;width:min(470px,calc(100vw - 36px));max-height:65vh;overflow:auto;background:#08141ff2;border:1px solid #31566a;border-radius:16px;padding:14px;color:#eff8ff;font:12px Inter,system-ui;box-shadow:0 18px 60px #0009';
      panel.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center"><strong>VALIDATION LAB · CHAPTER 5</strong><button id="urbion-validation-close" style="background:none;border:0;color:#9eb5c7;font-size:18px">×</button></div><div id="urbion-validation-body" style="margin-top:8px;color:#b9cbd7">Loading…</div>';
      document.body.appendChild(panel);document.getElementById('urbion-validation-close').onclick=function(){panel.style.display='none';};
    }
    panel.style.display='block';var body=document.getElementById('urbion-validation-body');body.innerHTML='Loading canonical cases…';
    try{
      var r=await fetch('/validation/cases');if(!r.ok)throw Error('HTTP '+r.status);var data=await r.json();
      body.innerHTML=(data.cases||[]).map(function(c){return '<div style="border-top:1px solid #203443;padding:10px 0"><b>'+esc(c.id)+' · '+esc(c.title)+'</b><div style="margin:4px 0;color:#9eb5c7">'+esc(c.purpose)+'</div><button data-vcase="'+esc(c.id)+'" style="border:1px solid #35e2b0;background:#102a31;color:#dffbf4;border-radius:8px;padding:7px 10px;font:800 10px Inter;cursor:pointer">RUN CASE</button><div id="vresult-'+esc(c.id)+'" style="margin-top:6px"></div></div>';}).join('');
      Array.prototype.forEach.call(body.querySelectorAll('[data-vcase]'),function(btn){btn.onclick=function(){runValidation(btn.getAttribute('data-vcase'));};});
    }catch(e){body.innerHTML='<span style="color:#ff8292">Validation Lab unavailable · '+esc(e.message)+'</span>';}
  }
  async function runValidation(id){
    var out=document.getElementById('vresult-'+id);if(!out)return;out.innerHTML='<span style="color:#9eb5c7">Executing production workflow…</span>';
    try{
      var r=await fetch('/validation/run/'+encodeURIComponent(id),{method:'POST'});if(!r.ok)throw Error('HTTP '+r.status);var x=await r.json(),e=x.evidence_card||{},a=e.assessment||e,s=a.status||e.status||'REVIEW_REQUIRED',rules=(a.rules||{}).retrieved_count,d=(a.tod||{}).distance_m,sc=(e.scenario||{}).count;
      out.innerHTML='<div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><div><small>STATUS</small><br><b>'+esc(s)+'</b></div><div><small>RULES</small><br><b>'+esc(rules==null?'—':rules)+'</b></div><div><small>TOD</small><br><b>'+esc(d==null?'—':Math.round(d)+' m')+'</b></div><div><small>SCENARIOS</small><br><b>'+esc(sc==null?'—':sc)+'</b></div></div><div style="margin-top:7px;color:#7ee6c7">✓ Generated by production engine · decision-support only</div>';
    }catch(e){out.innerHTML='<span style="color:#ff8292">Case failed · '+esc(e.message)+'</span>';}
  }
  function mount(){
    if(document.getElementById('urbion-di-panel')){validationButton();return;}
    var panel=document.createElement('section');panel.id='urbion-di-panel';panel.style.cssText='position:fixed;left:18px;bottom:18px;z-index:1300;width:min(440px,calc(100vw - 36px));max-height:60vh;overflow:auto;background:#09131deF;border:1px solid #294052;border-radius:16px;padding:14px;color:#eff8ff;font:12px Inter,system-ui;box-shadow:0 18px 60px #0008;display:none;';
    panel.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center"><strong>URBION AI COPILOT</strong><button id="urbion-di-close" style="background:none;border:0;color:#9eb5c7;font-size:18px">×</button></div><div id="urbion-di-body" style="margin-top:10px;color:#b9cbd7">Run an assessment to generate evidence-weighted priorities.</div><button id="urbion-copilot-run" style="margin-top:10px;width:100%;border:1px solid #35e2b0;background:#35e2b0;color:#061018;border-radius:8px;padding:9px;font:900 10px Inter;cursor:pointer">RUN PLANNER COPILOT</button>';
    document.body.appendChild(panel);document.getElementById('urbion-di-close').onclick=function(){panel.style.display='none';};
    document.getElementById('urbion-copilot-run').onclick=async function(){
      var body=document.getElementById('urbion-di-body');body.innerHTML='<b>Running bounded planner copilot…</b><div style="margin-top:6px;color:#8299aa">Assessment → spatial → knowledge → impact → agents → decision → evidence ledger</div>';
      var payload={site_lat:+input('dash-lat',2.285),site_lon:+input('dash-lon',102.196),tod_lat:+input('dash-todlat',2.286),tod_lon:+input('dash-todlon',102.197),plot_ratio:+input('dash-ratio',4.5),development_type:input('dash-dev','TOD Development / Mixed Use'),development_class:'Mixed Use',state:input('dash-state','Melaka'),district:'Melaka Tengah',pbt:'Majlis Bandaraya Melaka Bersejarah',lot_no:input('dash-lot','')};
      try{var r=await fetch('/copilot/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error('HTTP '+r.status);var x=await r.json(),d=x.decision||{},k=x.knowledge||{},i=x.impact||{},a=x.agents||{},l=x.evidence_ledger||{};body.innerHTML='<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0"><div><small>DECISION</small><br><b>'+esc(d.status||d.decision_status)+'</b></div><div><small>AGENT MODE</small><br><b>'+esc(a.mode)+'</b></div><div><small>POLICY HITS</small><br><b>'+esc(k.retrieval_count)+'</b></div><div><small>IMPACT</small><br><b>'+esc(i.status)+'</b></div><div><small>EVIDENCE ITEMS</small><br><b>'+esc(l.total_items)+'</b></div><div><small>REVIEW ITEMS</small><br><b>'+esc(l.review_required_items)+'</b></div></div><div style="font-weight:800;margin:8px 0">NEXT ACTIONS</div>'+(x.next_actions||[]).map(function(v,n){return '<div style="padding:7px 0;border-top:1px solid #203443"><b>'+(n+1)+'.</b> '+esc(v)+'</div>';}).join('')+'<div style="margin-top:10px;font-size:10px;color:#8299aa">BOUNDED COPILOT · DECISION-SUPPORT ONLY · STATUTORY VERIFICATION NOT CLAIMED</div>';validationButton();}catch(e){body.innerHTML='<div style="color:#ff8292">Copilot failed · '+esc(e.message)+'</div><div style="margin-top:8px;color:#8299aa">Check site inputs and rerun.</div>';}
    };
    window.urbionDecisionIntelligence=function(payload){panel.style.display='block';var body=document.getElementById('urbion-di-body');body.innerHTML='<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0"><div><small>STATUS</small><br><b>'+esc(payload.decision_intelligence&&payload.decision_intelligence.decision_status)+'</b></div><div><small>CONFIDENCE</small><br><b>'+esc(payload.decision_intelligence&&payload.decision_intelligence.confidence&&payload.decision_intelligence.confidence.band)+'</b></div></div>';var actions=(payload.decision_intelligence&&payload.decision_intelligence.priority_actions)||[];body.innerHTML+='<div style="font-weight:800;margin:8px 0">PRIORITY ACTIONS</div>'+(actions.length?actions.map(function(a){return '<div style="padding:8px 0;border-top:1px solid #203443"><b>'+esc(a.priority)+' · '+esc(a.rule_id)+'</b><br><span style="color:#b9cbd7">'+esc(a.reason)+'</span></div>';}).join(''):'<div style="padding:8px 0">No mapped priority actions.</div>');body.innerHTML+='<div style="margin-top:10px;font-size:10px;color:#8299aa">DECISION-SUPPORT ONLY · STATUTORY VERIFICATION NOT CLAIMED</div>';validationButton();};
    validationButton();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
