/* URBION HORIZON — canonical workspace control owner.
   This layer runs after the legacy/runtime helpers have initialized, then
   removes competing listeners from the controls it owns and binds exactly
   one handler per control. It deliberately reuses the inline workspace
   analysis/map functions instead of introducing another planning engine. */
(()=>{
'use strict';
if(window.__URBION_CANONICAL_UI_V1__) return;
window.__URBION_CANONICAL_UI_V1__=true;
const $=id=>document.getElementById(id);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const waitFor=async(pred,tries=120,delay=100)=>{for(let i=0;i<tries;i++){try{if(pred())return true}catch(_){}await sleep(delay)}return false};
const clone=(el)=>{if(!el||!el.parentNode)return null;const c=el.cloneNode(true);el.parentNode.replaceChild(c,el);return c};
const toast=(message,ok=true)=>{const t=$('toast');if(!t)return;t.textContent=message;t.style.display='block';t.style.color=ok?'var(--good)':'var(--bad)';clearTimeout(window.__urbionCanonicalToast);window.__urbionCanonicalToast=setTimeout(()=>{t.style.display='none'},2600)};
const esc=s=>String(s??'').replace(/[&<>\\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[m]));
function mapObj(){try{return typeof map!=='undefined'&&map?map:null}catch(_){return null}}
function baseSwitch(kind){const m=mapObj();if(!m||typeof baseLayers==='undefined'||!baseLayers[kind]){toast('Map engine is not ready',false);return}for(const k of Object.keys(baseLayers)){try{if(m.hasLayer(baseLayers[k]))m.removeLayer(baseLayers[k])}catch(_){} }baseLayers[kind].addTo(m);document.querySelectorAll('[data-base]').forEach(b=>b.classList.toggle('active',b.dataset.base===kind));if($('mapStatus'))$('mapStatus').textContent=(kind==='street'?'MAP':kind==='sat'?'SATELLITE':'HYBRID')+' · LIVE';m.invalidateSize(true)}
function syncSite(lat,lon,zoom=14){lat=Number(lat);lon=Number(lon);const m=mapObj();if(!Number.isFinite(lat)||!Number.isFinite(lon)||!m)return;try{if(typeof setSite==='function')setSite(lat,lon,zoom);else{if($('site_lat'))$('site_lat').value=lat.toFixed(6);if($('site_lon'))$('site_lon').value=lon.toFixed(6);if(typeof marker!=='undefined'&&marker)marker.setLatLng([lat,lon]);[typeof r400!=='undefined'?r400:null,typeof r800!=='undefined'?r800:null,typeof r1000!=='undefined'?r1000:null].forEach(x=>x?.setLatLng([lat,lon]));m.setView([lat,lon],zoom)}if($('coords'))$('coords').textContent=`${lat.toFixed(6)}, ${lon.toFixed(6)}`;updateCaseReadiness()}catch(e){toast('Location update failed: '+e.message,false)}}
async function runAnalysisCanonical(){const run=$('run');if(!run)return;if(!caseIsReady()){updateCaseReadiness();toast('Complete the required planning case fields before analysis',false);return}run.disabled=true;const old=run.textContent;run.textContent='⟳ ANALYSING…';try{if(window.URBION_FINAL?.analyse)await window.URBION_FINAL.analyse();else if(typeof runAnalysis==='function')await runAnalysis();else throw Error('Canonical analysis function is unavailable');await waitFor(()=>!!window.URBION_LAST,80,100);if(!window.URBION_LAST)throw Error('Analysis returned no result');const input=typeof getInputs==='function'?getInputs():null;if(input){try{const res=await fetch('/copilot/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assessment:input})});const d=await res.json();if(res.ok){const ex=d.explanation||{};const text=typeof ex==='string'?ex:(ex.text||ex.explanation||'No narrative returned.');const provider=typeof ex==='object'?(ex.provider||'LLM'):'LLM';const status=typeof ex==='object'?(ex.status||'READY'):'READY';window.URBION_AI_LAST={provider,status,text,evidence_ledger:d.evidence_ledger||{},source:'bounded_copilot_explain'};if($('findings')){$('findings').querySelector('#aiSynthesisCard')?.remove();const card=document.createElement('div');card.className='finding';card.id='aiSynthesisCard';card.innerHTML=`<b>AI PLANNING SYNTHESIS</b><p>${esc(text)}</p><small>${esc(provider)} · ${esc(status)} · DETERMINISTIC PACKET REMAINS SOURCE OF TRUTH</small>`;$('findings').appendChild(card)}if($('evidenceHealth')){$('evidenceHealth').querySelector('#aiEvidenceCard')?.remove();const card=document.createElement('div');card.className='finding';card.id='aiEvidenceCard';card.innerHTML=`<b>AI / COPILOT</b><p>Planner narrative generated from the deterministic planning packet and evidence ledger.</p><small>${esc(provider)} · ${esc(status)} · NO STATUTORY AUTHORITY</small>`;$('evidenceHealth').appendChild(card)}}}catch(e){window.URBION_AI_LAST={provider:'fallback',status:'UNAVAILABLE',text:String(e.message||e)};toast('Deterministic analysis completed; AI narrative unavailable',false)}}toast('URBION analysis completed')}catch(e){toast(String(e.message||e),false)}finally{run.disabled=!caseIsReady();run.textContent=old==='⟳ ANALYSING…'?'▶ RUN SITE ANALYSIS':old}}
function openCore(kind){if(kind==='evidence'&&typeof evidenceModal==='function')return evidenceModal();if(kind==='whatif'&&typeof whatIfModal==='function'){const result=whatIfModal();const title=$('modalTitle');if(title&&title.textContent.trim()==='WHAT-IF STUDIO')title.textContent='WHAT-IF SCENARIO';return result}if(kind==='decision'&&typeof decisionModal==='function')return decisionModal();if(kind==='output'&&typeof outputModal==='function')return outputModal();toast('Core function unavailable',false)}
function bindSearch(input){if(!input)return;const holder=input.parentElement;holder.style.position='relative';let box=$('canonicalSearchResults');if(!box){box=document.createElement('div');box.id='canonicalSearchResults';box.style.cssText='position:absolute;left:0;right:0;top:39px;z-index:1200;display:none;max-height:240px;overflow:auto;background:#061820;border:1px solid var(--line);border-radius:9px;padding:6px';holder.appendChild(box)}let timer=0;const query=async q=>{if(q.length<3){box.style.display='none';return}try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=6&q='+encodeURIComponent(q),{headers:{Accept:'application/json'}});if(!r.ok)throw Error('HTTP '+r.status);const items=await r.json();box.innerHTML=items.length?items.map((x,i)=>`<button type="button" data-search-i="${i}" style="display:block;width:100%;text-align:left;background:transparent;border:0;color:inherit;padding:8px;font-size:8px;border-bottom:1px solid rgba(45,85,100,.18)">${esc(x.display_name)}</button>`).join(''):'<div style="padding:8px;font-size:8px;color:var(--muted)">No location found</div>';box.style.display='block';box.querySelectorAll('[data-search-i]').forEach(btn=>btn.onclick=()=>{const x=items[Number(btn.dataset.searchI)];syncSite(+x.lat,+x.lon,14);input.value=x.display_name;box.style.display='none';toast('Location selected')})}catch(e){box.innerHTML='<div style="padding:8px;font-size:8px;color:var(--bad)">Location search unavailable</div>';box.style.display='block'}};input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>query(input.value.trim()),350)});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();query(input.value.trim())}});document.addEventListener('click',e=>{if(!holder.contains(e.target))box.style.display='none'})}
function claim(selector,bind){const el=document.querySelector(selector);if(!el)return null;const c=clone(el);bind(c);return c}
const GEO_URL='https://raw.githubusercontent.com/open-admin-data/malaysia-administrative-divisions/main/data/hierarchy.json';
let GEO_CACHE=null;
function labelControl(label){const needle=label.toLowerCase();for(const row of document.querySelectorAll('.sec .row')){const lab=row.querySelector('.lab');if(lab&&lab.textContent.toLowerCase().includes(needle))return row.querySelector('input,select,textarea')}return null}
function replaceWithSelect(control){if(!control)return null;if(control.tagName==='SELECT')return control;const select=document.createElement('select');for(const attr of ['id','name','class','required','disabled','autocomplete','aria-label'])if(control.hasAttribute(attr))select.setAttribute(attr,control.getAttribute(attr));select.className=control.className||'select';select.value=control.value||'';control.parentNode.replaceChild(select,control);return select}
async function loadGeography(){if(GEO_CACHE)return GEO_CACHE;try{const r=await fetch(GEO_URL,{cache:'force-cache',headers:{Accept:'application/json'}});if(!r.ok)throw Error('HTTP '+r.status);const payload=await r.json();GEO_CACHE=payload.data||[];return GEO_CACHE}catch(e){GEO_CACHE=[];return GEO_CACHE}}
function setOptions(select,items,placeholder='Select') {if(!select)return;const current=select.value;select.innerHTML=`<option value="">${esc(placeholder)}</option>`+items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(current&&items.includes(current))select.value=current}
function ensureCanonicalPbt(){const pbt=replaceWithSelect(labelControl('local authority'));if(!pbt)return null;pbt.dataset.pbtStructuralOwned='1';pbt.dataset.pbtCanonicalControl='1';return pbt}
async function enhanceLocationHierarchy(){let state=replaceWithSelect(labelControl('state'));let district=replaceWithSelect(labelControl('district'));let mukim=replaceWithSelect(labelControl('mukim'));ensureCanonicalPbt();if(!state||!district||!mukim)return;state.dataset.geoOwned='1';district.dataset.geoOwned='1';mukim.dataset.geoOwned='1';const currentState=state.value||'Melaka';const tree=await loadGeography();if(!tree.length){setOptions(state,['Johor','Kedah','Kelantan','Melaka','Negeri Sembilan','Pahang','Perak','Perlis','Pulau Pinang','Sabah','Sarawak','Selangor','Terengganu','W.P. Kuala Lumpur','W.P. Labuan','W.P. Putrajaya'],'Select State');toast('Administrative data source unavailable; using full state fallback',false)}else{const names=tree.map(x=>x.name?.local||x.name?.en).filter(Boolean);setOptions(state,names,'Select State')}const findState=()=>tree.find(x=>(x.name?.local||x.name?.en)===state.value)||(tree.find(x=>(x.name?.en||'').toLowerCase()===state.value.toLowerCase()));const refreshDistricts=()=>{const node=findState();const districts=(node?.district||[]).map(x=>x.name?.local||x.name?.en).filter(Boolean);setOptions(district,districts,'Select District');setOptions(mukim,[],'Select Mukim')};const refreshMukim=()=>{const node=findState();const d=(node?.district||[]).find(x=>(x.name?.local||x.name?.en)===district.value);const items=(d?.mukim||[]).map(x=>x.name?.local||x.name?.en).filter(Boolean);setOptions(mukim,items,'Select Mukim');updateCaseReadiness()};state.addEventListener('change',()=>{refreshDistricts();updateCaseReadiness()},{once:false});district.addEventListener('change',()=>{refreshMukim();updateCaseReadiness()},{once:false});if(!state.value)state.value=currentState;state.dispatchEvent(new Event('change',{bubbles:true}));if(district.value)refreshMukim();updateCaseReadiness()}
function compactPlanningCase(){let style=$('urbionCaseCompactStyle');if(!style){style=document.createElement('style');style.id='urbionCaseCompactStyle';style.textContent='.leftscroll .sec{height:auto!important;min-height:0!important}.leftscroll .sec .body{height:auto!important;min-height:0!important;max-height:none!important}.leftscroll .sec .row:last-child{margin-bottom:0}.leftscroll{scrollbar-gutter:stable}.urbion-readiness-inline{border:1px solid rgba(47,225,233,.18);background:rgba(4,24,33,.76);border-radius:9px;padding:7px 8px;margin:0 0 7px}.urbion-readiness-inline .rh{display:flex;justify-content:space-between;align-items:center;font-size:7px;letter-spacing:.07em}.urbion-readiness-inline .rp{color:var(--cyan);font:800 11px Space Grotesk,system-ui,sans-serif}.urbion-readiness-inline .track{height:4px;margin-top:5px;border-radius:999px;background:#12303d;overflow:hidden}.urbion-readiness-inline .fill{height:100%;width:0;background:linear-gradient(90deg,var(--mint),var(--cyan));transition:width .2s ease}.urbion-readiness-inline .note{display:block;margin-top:4px;font-size:5.8px;color:var(--muted)}';document.head.appendChild(style)}for(const sec of document.querySelectorAll('.leftscroll .sec')){sec.style.height='auto';sec.style.minHeight='0';const body=sec.querySelector('.body');if(body){body.style.height='auto';body.style.minHeight='0';body.style.maxHeight='none'}}const head=document.querySelector('.casehead');if(head&&!$('caseReadinessInline')){const box=document.createElement('div');box.id='caseReadinessInline';box.className='urbion-readiness-inline';box.innerHTML='<div class="rh"><span>CASE COMPLETION</span><b class="rp" id="caseReadinessPct">0%</b></div><div class="track"><div class="fill" id="caseReadinessFill"></div></div><span class="note" id="caseReadinessNote">Complete required case fields before running analysis.</span></div>';head.parentNode.insertBefore(box,head.nextSibling)}}
function requiredCaseControls(){return [labelControl('project / site name'),labelControl('state'),labelControl('district'),labelControl('local authority'),$('site_lat')||labelControl('latitude'),$('site_lon')||labelControl('longitude'),labelControl('development type'),labelControl('development class'),$('landuse1'),$('landuse2'),$('landuse3')].filter(Boolean)}
function caseIsReady(){const controls=requiredCaseControls();return controls.length>=11&&controls.every(c=>String(c.value||'').trim()!=='')}
function updateCaseReadiness(){const controls=requiredCaseControls();const filled=controls.filter(c=>String(c.value||'').trim()!=='').length;const pct=controls.length?Math.round(filled/controls.length*100):0;const ready=controls.length>=11&&filled===controls.length;const pctEl=$('caseReadinessPct'),fill=$('caseReadinessFill'),note=$('caseReadinessNote'),run=$('run'),ring=document.querySelector('.ring'),ringPct=document.querySelector('.ring b'),readyLabel=$('readyLabel');if(pctEl)pctEl.textContent=pct+'%';if(fill)fill.style.width=pct+'%';if(note)note.textContent=ready?'READY TO ANALYSE':'Complete required fields to unlock analysis.';if(ring){ring.style.background=`conic-gradient(var(--mint) 0 ${pct}%,#183a47 ${pct}% 100%)`;if(ringPct)ringPct.textContent=pct+'%'}if(readyLabel)readyLabel.textContent=ready?'READY':'PRE-RUN';if(run&&!run.matches(':active'))run.disabled=!ready;return {pct,ready}}
function wireReadinessListeners(){for(const c of requiredCaseControls()){if(c.dataset.readinessWired)continue;c.dataset.readinessWired='1';c.addEventListener('input',updateCaseReadiness);c.addEventListener('change',updateCaseReadiness)}updateCaseReadiness()}
async function boot(){const core=await waitFor(()=>window.URBION_FINAL&&typeof window.URBION_FINAL.analyse==='function'&&typeof window.URBION_LAYER_MANAGER!=='undefined'&&typeof L!=='undefined'&&mapObj(),120,100);if(!core)return console.warn('URBION canonical UI: core timeout');await sleep(500);window.URBION_FINAL.loadLayers=()=>window.URBION_LAYER_MANAGER?.refresh?.();window.URBION_FINAL.refreshMap=()=>{try{mapObj()?.invalidateSize(true)}catch(_){} };
// One owner for land-use cascading.
['landuse1','landuse2','landuse3'].forEach(id=>$(id)&&clone($(id)));
if(typeof taxonomy!=='undefined'){const a=$('landuse1'),b=$('landuse2'),c=$('landuse3');const fill=(s,arr,p)=>{s.innerHTML=(p?`<option value="">${esc(p)}</option>`:'')+arr.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')};if(a&&b&&c){fill(a,Object.keys(taxonomy).filter(x=>x.toLowerCase()!=='perdagangan'));const s2=()=>{fill(b,Object.keys(taxonomy[a.value]||{}),'Pilih Guna Tanah 2');fill(c,[],'Pilih Aktiviti Guna Tanah 3');updateCaseReadiness()};const s3=()=>{fill(c,(taxonomy[a.value]||{})[b.value]||[],'Pilih Aktiviti Guna Tanah 3');updateCaseReadiness()};a.addEventListener('change',s2);b.addEventListener('change',s3);s2()}}
// Section accordions: exactly one listener per header.
document.querySelectorAll('.sec .sechead button').forEach(b=>{const c=clone(b);c.addEventListener('click',()=>c.parentElement.parentElement.classList.toggle('collapsed'))});
// Map controls.
document.querySelectorAll('[data-base]').forEach(b=>{const c=clone(b);c.addEventListener('click',()=>baseSwitch(c.dataset.base))});
// Layer drawer: canonical capture-phase owner. This prevents late runtime listeners from double-toggling the drawer.
claim('#layerBtn',b=>b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const layers=$('layers');layers?.classList.toggle('open');void window.URBION_LAYER_MANAGER?.refresh?.()},{capture:true}));
claim('#run',()=>{});const run=$('run');run?.addEventListener('click',()=>void runAnalysisCanonical());
[['#evidenceBtn','evidence'],['#whatifBtn','whatif'],['#decisionBtn','decision'],['#outputBtn','output'],['#generateOutput','output']].forEach(([s,k])=>claim(s,b=>b.addEventListener('click',()=>openCore(k))));
claim('#printBtn',b=>b.addEventListener('click',()=>window.print()));
claim('#closeModal',b=>b.addEventListener('click',()=>$('#modal')?.classList.remove('show')));
claim('#useMap',b=>b.addEventListener('click',()=>toast('Click the map to choose the site')));
claim('#locate',b=>b.addEventListener('click',()=>syncSite(+$('site_lat').value,+$('site_lon').value,14)));
[['#ring400','#context400','r400'],['#ring800','#context800','r800'],['#ring1000','#context1000','r1000']].forEach(([b,c,r])=>{claim(c,x=>x.addEventListener('change',e=>{const o=window[r];if(o&&mapObj())e.target.checked?o.addTo(mapObj()):o.removeFrom(mapObj())}));claim(b,x=>x.addEventListener('click',()=>{const q=$(c);if(q){q.checked=!q.checked;q.dispatchEvent(new Event('change'))}}))});
claim('#roadCtx',b=>b.addEventListener('change',e=>{const m=mapObj();if(!m||typeof L==='undefined')return;if(!window.__URBION_CANON_ROAD)L&& (window.__URBION_CANON_ROAD=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{opacity:.42,maxZoom:19,attribution:'© OpenStreetMap'}));if(e.target.checked)window.__URBION_CANON_ROAD?.addTo(m);else if(window.__URBION_CANON_ROAD&&m.hasLayer(window.__URBION_CANON_ROAD))m.removeLayer(window.__URBION_CANON_ROAD)}));
claim('#roadCtxMap',b=>b.addEventListener('change',e=>{$('roadCtx').checked=e.target.checked;$('roadCtx').dispatchEvent(new Event('change'))}));
const search=claim('#search',bindSearch);
// Menu owner.
document.querySelectorAll('.nav button').forEach(btn=>{const c=clone(btn);c.addEventListener('click',()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));c.classList.add('active');openCore(c.dataset.mode==='evidence'?'evidence':c.dataset.mode==='whatif'?'whatif':c.dataset.mode==='decision'?'decision':c.dataset.mode==='output'?'output':null)})});
// Existing runtime utilities are already deliberately isolated and retained.
await waitFor(()=>!!$('runtimeTools'),50,100);['#runtimeAbout','#runtimeHelp','#runtimeSources','#runtimeStatus','#runtimeFullscreen','#runtimeReset'].forEach(s=>{const el=$(s);if(el)el.setAttribute('data-canonical-runtime','1')});
compactPlanningCase();
await enhanceLocationHierarchy();
wireReadinessListeners();
setTimeout(()=>window.URBION_LAYER_MANAGER?.refresh?.(),300);
console.info('URBION CANONICAL UI OWNER READY');
}
boot().catch(e=>console.error('URBION canonical UI boot failed',e));
})();