(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const makeBtn=(id,text)=>{const b=document.createElement('button');b.id=id;b.className='tool';b.textContent=text;return b};
  function openInfo(title,html){const modal=$('modal');if(!modal)return;$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.add('show')}
  function injectUtilities(){
    const top=document.querySelector('.top');if(!top||document.getElementById('finalTools'))return;
    const box=document.createElement('div');box.id='finalTools';box.style.cssText='display:flex;align-items:center;gap:4px;flex-wrap:nowrap';
    const about=makeBtn('aboutBtn','ABOUT'),help=makeBtn('helpBtn','HELP'),sources=makeBtn('sourcesBtn','SOURCES'),status=makeBtn('systemBtn','STATUS'),fs=makeBtn('fsBtn','FULLSCREEN'),reset=makeBtn('resetBtn','RESET');
    [about,help,sources,status,fs,reset].forEach(x=>box.appendChild(x));
    const anchor=$('themeBtn');if(anchor&&anchor.parentNode)anchor.parentNode.insertBefore(box,anchor.nextSibling);else top.appendChild(box);
    about.onclick=()=>location.href='/about';
    help.onclick=()=>openInfo('URBION HORIZON — HELP','<div class="grid2"><div class="resultbox"><h4>1 · DEFINE CASE</h4><p>Isi lokasi, pembangunan dan hierarki Guna Tanah 1 → 2 → 3.</p></div><div class="resultbox"><h4>2 · SELECT SITE</h4><p>Klik peta atau gunakan koordinat untuk menetapkan tapak.</p></div><div class="resultbox"><h4>3 · ANALYSE</h4><p>Run Site Analysis untuk spatial evidence, RT/GP, evidence health dan decision support.</p></div><div class="resultbox"><h4>4 · WHAT-IF</h4><p>Bandingkan baseline dengan scenario melalui enjin /what-if.</p></div><div class="resultbox"><h4>5 · OUTPUT</h4><p>Semak planner-ready output dan gunakan Print / PDF.</p></div><div class="resultbox"><h4>BOUNDARY</h4><p>URBION ialah decision-support. Tiada kelulusan statutori atau verifikasi kadaster dituntut.</p></div></div>');
    sources.onclick=()=>openInfo('DATA SOURCES','<div class="resultbox"><h4>OFFICIAL / PRIMARY</h4><p>PLANMalaysia i-Plan · Sistem Maklumat Gunatanah Perancangan Bersepadu<br>Official i-Plan GeoServer / WMS layers<br>RT / RS / RFN / guidelines are treated as source context and must be verified for currency/applicability.</p></div><div style="height:8px"></div><div class="resultbox"><h4>BASEMAP</h4><p>OpenStreetMap · Esri World Imagery</p></div><div style="height:8px"></div><div class="resultbox"><h4>EVIDENCE BOUNDARY</h4><p>Live source context is not automatic statutory verification.</p></div>');
    status.onclick=async()=>{const checks=[['Health','/health'],['Metadata','/metadata'],['Map layer catalogue','/map/layers?state=Melaka']];let html='';for(const [n,u] of checks){try{const r=await fetch(u,{cache:'no-store'});html+=`<div class="mini"><span>${n}</span><span class="tag ${r.ok?'ok':'bad'}">${r.ok?'ONLINE':'ERROR '+r.status}</span></div>`}catch(e){html+=`<div class="mini"><span>${n}</span><span class="tag bad">ERROR</span></div>`}}openInfo('SYSTEM STATUS',html+'<div class="finding"><b>Canonical presentation</b><p>/workspace is served through the isolated public presentation entrypoint.</p></div>')};
    fs.onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(e){openInfo('FULLSCREEN','<p>Browser fullscreen is unavailable in this context.</p>')}};
    reset.onclick=()=>{if(confirm('Reset planning case and return to the default workspace state?'))location.reload()};
  }
  function attachRoadContext(){const cb=$('roadCtx');if(!cb||cb.dataset.finalWired)return;cb.dataset.finalWired='1';cb.addEventListener('change',()=>{if(!window.map||!window.L)return;window.__urbionRoad=window.__urbionRoad||L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{opacity:.48,maxZoom:19,attribution:'© OpenStreetMap'});if(cb.checked){window.__urbionRoad.addTo(window.map);$('layerState').textContent='Road / transit context ON · OpenStreetMap overlay'}else{window.map.removeLayer(window.__urbionRoad);$('layerState').textContent='Road / transit context OFF'}})}
  function attachSearch(){const s=$('search');if(!s||s.dataset.finalWired)return;s.dataset.finalWired='1';let timer;const holder=s.parentNode;holder.style.position='relative';const results=document.createElement('div');results.id='searchResults';results.style.cssText='position:absolute;left:0;right:0;top:38px;z-index:1200;display:none;max-height:220px;overflow:auto;background:#061820;border:1px solid var(--line);border-radius:9px;padding:6px';holder.appendChild(results);async function query(q){if(q.length<3){results.style.display='none';return}try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&q='+encodeURIComponent(q),{headers:{'Accept':'application/json'}});const d=await r.json();results.innerHTML=d.length?d.map((x,i)=>`<button data-ri="${i}" style="display:block;width:100%;text-align:left;background:transparent;border:0;color:inherit;padding:7px;font-size:8px;border-bottom:1px solid rgba(45,85,100,.18)">${x.display_name}</button>`).join(''):'<div style="padding:7px;font-size:8px;color:#8aa">No location found</div>';results.style.display='block';results.querySelectorAll('[data-ri]').forEach(b=>b.onclick=()=>{const x=d[+b.dataset.ri];if(typeof window.setSite==='function')window.setSite(+x.lat,+x.lon,15);s.value=x.display_name;results.style.display='none'})}catch(e){results.innerHTML='<div style="padding:7px;font-size:8px;color:#f88">Search unavailable</div>';results.style.display='block'}}s.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>query(s.value.trim()),350)});document.addEventListener('click',e=>{if(!holder.contains(e.target))results.style.display='none'})}
  function init(){injectUtilities();attachRoadContext();attachSearch();setTimeout(()=>{if(window.map&&window.L)window.map.invalidateSize(true)},250)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
