(()=>{
  if(location.pathname!=='/' && !location.pathname.endsWith('/index.html') && !location.pathname.endsWith('/championship.html')) return;
  function style(){if(document.getElementById('ss-upgrade-style'))return;const s=document.createElement('style');s.id='ss-upgrade-style';s.textContent='.ss-focus{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin-top:8px}.ss-focus button{border:1px solid #17303e;border-radius:7px;background:#07131c;color:#b8cad5;padding:7px 5px;font:900 7px Inter;cursor:pointer}.ss-focus button:hover{border-color:var(--a);color:var(--text)}.ss-evidencebar{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:8px;padding:8px;border:1px solid #17303e;border-radius:7px;background:#07131c;font-size:7px;color:#8299a8}.ss-evidencebar b{color:#d8e6ec}.ss-copycoord{border:1px solid #17303e;border-radius:6px;background:#07131c;color:#9ec0cc;padding:4px 6px;font:800 6px Inter;cursor:pointer}.ss-evidence{margin-top:7px;border:1px solid #17303e;border-radius:8px;background:#07131c;padding:8px}.ss-evidence summary{cursor:pointer;color:#b8cad5;font:900 7px Inter;letter-spacing:.06em}.ss-evgrid{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:7px}.ss-evitem{padding:6px;border:1px solid #203343;border-radius:6px}.ss-evitem b{display:block;font-size:7px;color:#d8e6ec}.ss-evitem span{display:block;margin-top:2px;font-size:6px;color:#8299a8}@media(max-width:600px){.ss-focus{grid-template-columns:1fr 1fr}.ss-evgrid{grid-template-columns:1fr}}';document.head.appendChild(s)}
  function setGroup(mode){const all=[...document.querySelectorAll('#ss-layers input[data-i]')];all.forEach(cb=>{const row=cb.closest('.ss-layer');const t=(row?.textContent||'').toUpperCase();let on=false;if(mode==='ALL')on=true;else if(mode==='OFF')on=false;else if(mode==='PLANNING')on=/I-PLAN|RFN/.test(t);else if(mode==='RISK')on=/FLOOD|DISASTER|FAULT|QUARRY|SEISMIC|GEOHAZARD/.test(t);else if(mode==='ENVIRONMENT')on=/KSAS|ECOLOG|CFS|HERITAGE|AFFORDABLE|TOPO|GROUNDWATER|LITHOLOGY|MINERAL|GEOHERITAGE/.test(t);if(cb.checked!==on){cb.checked=on;cb.dispatchEvent(new Event('change',{bubbles:true}))}});updateCount()}
  function updateCount(){const n=document.querySelectorAll('#ss-layers input[data-i]:checked').length;const el=document.getElementById('ss-active-count');if(el)el.textContent=n}
  function bindLive(){const layerRoot=document.getElementById('ss-layers');if(!layerRoot||layerRoot.dataset.urbionLiveBound==='1')return;layerRoot.dataset.urbionLiveBound='1';layerRoot.addEventListener('change',e=>{if(e.target?.matches('input[data-i]'))updateCount()});layerRoot.addEventListener('input',e=>{if(e.target?.matches('input[data-i]'))updateCount()});new MutationObserver(updateCount).observe(layerRoot,{childList:true,subtree:true})}
  function renderEvidence(data){const box=document.getElementById('ss-evidence');if(!box)return;const site=data?.site||{},state=data?.evidence_state||{},rules=Array.isArray(data?.retrieved_rules)?data.retrieved_rules.length:0;const status=data?.final_status||'REQUIRES REVIEW';const tod=data?.tod_distance_m;const fmt=v=>v==null?'—':(typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:0}):String(v));box.innerHTML='<details open><summary>EVIDENCE SNAPSHOT · CURRENT ANALYSIS</summary><div class="ss-evgrid"><div class="ss-evitem"><b>COORDINATES</b><span>'+fmt(site.latitude)+', '+fmt(site.longitude)+' · '+(state.site_coordinates||'USER_PROVIDED')+'</span></div><div class="ss-evitem"><b>TOD DISTANCE</b><span>'+fmt(tod)+' m · '+(state.tod_distance||'CALCULATED')+'</span></div><div class="ss-evitem"><b>PLANNING RULES</b><span>'+fmt(rules)+' retrieved · '+(state.planning_rules||'UNVERIFIED')+'</span></div><div class="ss-evitem"><b>DECISION</b><span>'+status+' · '+(state.final_decision||'CALCULATED')+'</span></div></div></details>'}
  function inject(){const panel=document.querySelector('#spatial-studio .ss-panel');if(!panel||document.getElementById('ss-upgrade')){bindLive();updateCount();return}style();const sec=document.createElement('div');sec.id='ss-upgrade';sec.className='ss-section';sec.innerHTML='<b>MAP FOCUS</b><div class="ss-focus"><button data-mode="PLANNING">PLANNING</button><button data-mode="RISK">RISK</button><button data-mode="ENVIRONMENT">ENVIRONMENT</button><button data-mode="ALL">ALL</button><button data-mode="OFF">OFF</button></div><div class="ss-evidencebar"><span><b id="ss-active-count">0</b> active visual layers · source context only</span><button id="ss-copy-coord" class="ss-copycoord">COPY COORDINATES</button></div><div id="ss-evidence" class="ss-evidence"></div>';panel.insertBefore(sec,panel.querySelector('.ss-note'));sec.querySelectorAll('button[data-mode]').forEach(b=>b.onclick=()=>setGroup(b.dataset.mode));document.getElementById('ss-copy-coord').onclick=()=>{const c=document.getElementById('ss-coords')?.textContent||'';if(navigator.clipboard)navigator.clipboard.writeText(c);document.getElementById('ss-copy-coord').textContent='COPIED';setTimeout(()=>document.getElementById('ss-copy-coord').textContent='COPY COORDINATES',1000)};bindLive();updateCount();renderEvidence(window.__urbionAssessment)}
  function boot(){inject();setTimeout(()=>inject(),500);setTimeout(()=>{bindLive();updateCount();renderEvidence(window.__urbionAssessment)},1200)}
  window.addEventListener('urbion:analysis',e=>renderEvidence(e.detail));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();